#+TITLE: 读书简介
#+DESCRIPTION: 读书简介
#+TAGS: 读书
#+CATEGORIES: 人
#+DATE: <2019-08-19 05:29:19>

* 读书简介
** 简介
   #+begin_verse
   拿一本书看，并记牢书中的内容。
   看报，看小说这种无需记忆的不在此范围。
   #+end_verse
   #+HTML: <!-- more -->

   #+begin_quote
   #+begin_verse
   因为世界是一个关联的网，所以书一般也是一张网，如果缺少某一科目的书籍，那可能对世界的那一块还不熟悉，还没出书。
   脑子也要有一张世界的网，但现代科学表明这张网最好是视觉化，形象化的，那样容易记忆，所以看书时最好形象化书中的内容。
   #+end_verse
   #+end_quote
     #+BEGIN_EXPORT html
     {% pullquote mindmap mindmap-md %}
     - 书和脑子
      - 书
         - 天书
         - 地书
         - 人书
           - 男人书
           - 女人书
         - 动物书
         - 物理书
         - .....书
      - 脑子 
         - 书中东西的备份
     {% endpullquote %}
     #+END_EXPORT   

** 细
   孔子说，学习要经常复习。
   
   #+begin_verse
   胡适之的读书四到： 眼到，口到，心到，手到
   
   具体的解释为： 
   眼到: 就是别看错，看书要仔细。( 别把 1 看成 3 就好了，现在都识字的)
   口到: 读书要背
   心到: 读懂，理解，读心里去
   手到: 要多做笔记，摘要

   简单来说就是 ：观察，记忆，理解，归纳，反思 (特抽象，不好记忆，可以记为 读书要用到人的五官和四肢(哈哈，有点多了))
   #+end_verse

*** PQRS 应试策略  
    另一种学习方法，好记的 *PQRST*
    #+begin_verse
    预览(preview):学生大概了解将要考试的内容及要点
    问题(question):学生发掘温习中所发现的问题并制定问题
    阅读(read):在温习资料中找出问题的答案
    总结(summary):总结所有温习的要点
    测试(test):学生测试在"问题"部分制定的问题
    #+end_verse

*** 记忆 
    艾宾浩斯遗忘曲线：讲你看的书的内容，其遗忘程度是一条双曲线，所以你一般要在几个遗忘点温习一下。
    
    | 第一个记忆周期 | 5 分钟  |
    | 第二个记忆周期 | 30 分钟 |
    | 第三个记忆周期 | 12 小时 |
    | 第四个记忆周期 | 1 天    |
    | 第五个记忆周期 | 2 天    |
    | 第六个记忆周期 | 4 天    |
    | 第七个记忆周期 | 7 天    |
    | 第八个记忆周期 | 15 天   |

    #+begin_verse
   规避错误：1.要系统学习，不要今天学这明天学那。
   2.学习不能速成
    #+end_verse
   
*** 思维，思考
    思考也要用到脑的材料啦，一般是要用到想象力， 形象化，还要认真，仔细，查资料。
    
*** 学习时间管理(目标)
    番茄工作法 或 蕃茄时钟 
*** 道
    阳明先生说，为善去恶是格物 。就是你懂道理了，别人也懂道理了(但别人懂的道理是错误的理论)，这时你修正他的理论，是为格物。
** 博
   博，就是构建一个知识网络。
   这个网，因为脑子的记忆元素[fn:1]像酒精一样会散发，所以要经常翻翻自己做的笔记。

   #+begin_quote
   胡适之： 为学当如埃及塔，要能博大要能高。
   #+end_quote

** TODO (这个人的记忆原件还待查些资料到哪里了)
** 个人拙见
   我看书，常常看到看不懂的书，这时我就看不下去了，因为不理解。
   
   #+begin_verse
   这时，我的看法是，把那个东西当成一个生活中很简单的东西，比如枕头。枕头，我们可以拿来塞啊，挤啊，拉啊，容易变形。
   这时，我们在想一想我们不理解的东西，是否拥有枕头一样的特点，又有哪些区别，来比较思维，可能会促进理解。
   #+end_verse
   
   #+begin_quote
   如上想法是我觉得现在人们创造了很多抽象的概念，那些概念脱离人很远，人不熟悉，所以用身边的东西比拟会形象的多，容易记忆又便于引申。
   #+end_quote
* 学习   
  #+begin_verse
  学、思、习、行的总称
  读书是学习的一种方式，上学，看视频都是。 
  #+end_verse
 
** 有效学习的条件
*** 内部条件
    #+begin_verse
    适当的知识准备
    主动加工的心理倾向
    明确的学习目标
    #+end_verse
    
*** 外部条件
    #+begin_verse
    奖励与回馈
    反复练习
    #+end_verse
* Footnotes

[fn:1] 待查资料 
