#+TITLE: 物理简介
#+DESCRIPTION: 物理简介
#+TAGS[]: 物理
#+CATEGORIES[]: 科普
#+DATE: 2020-02-21T06:20:02+08:00
#+url: /post/physics

物理是研究东西属性，或者东西之间属性的知识。

# more
* 基础物理
** 接触力 (运动) 

   东西在世界上有两种状态，一种是在动，一种是不动(静止) 。牛顿说啊，其实世界上的东西本来有一个初始状态的，要么静止，要么恒速运动，为啥动动停停是因为受到了力的作用。
   
   比如我们是站在地球而不是飘在地球上，是因为受到了地球的吸力(引力)。那为什么我吸不动你呢，牛顿解释说是因为吸力跟质量有关的。
  
   接触力的分类如果细分的话会很多，其实就两类，动力和阻力。
  
   对于日常的接触力，我们怎么来算我们受了多少力呢，可以用求力公式 *F = Ma*  ，指的是力跟东西质量和运动增量有关(力是矢量，所以运动方向不一样，力也不一样，注意保持方向一致)。 
   #+begin_quote
   坐公交或者乘电梯就感到了
   #+end_quote
   #+begin_quote
   引力虽然不是接触力，但太普遍了，拿来做例子挺多的。
  #+begin_export type
  #+end_export 
 接触力我们身边很直观，比如买一斤的菜我们只要用一斤的力提着，如果我们力用大了，菜就网上飞了。 
   #+end_quote
  
   万有引力，牛顿只说东西都有吸力存在，但不知道吸力是怎么产生的。然后吸力跟东西的质量和距离有关。
   
   还有一个要知道的是 *量的守恒* ，这里是 *动量守恒* 。(用矢量算术的技术来计算)
   #+begin_quote
   什么动量守恒，能量守恒都是东西内部的一些属性的算术表达。
   #+end_quote
*** 惯性参考系和加速参考系 
    在加速参考系中，东西的运动受到的力就复杂了。
    
** 光学
** 热学
** 电磁学 (小东西)
   这里讲一小小东西，电。
*** 静电 (静止的电荷)
    电荷，有正电荷和负电荷，正电荷与正电荷相互排斥，正电荷与负电荷相互吸引。
    #+begin_quote
    因为电荷存在于原子级别，我们趋向于认为所有东西都有电荷的属性(除了光)。
    #+end_quote
    
** 原子物理学
* 近代物理   
** 理论力学
** 电动力学
** 量子力学
** 统计力学

