#+TITLE: 【置顶】人生意义
#+TAGS[]:  人生
#+CATEGORIES[]: 生活
#+DATE: 2019-11-22T06:55:56+08:00
#+PUBLISHDATE: 2019-11-22T06:55:56+08:00
#+DRAFT: nil
#+WEIGHT: 1

关于人生的意义，一百个人有一百个人的想法。这里仅说自己的狭隘理解。
# more

* 什么是人
  人是一个智能体，跟非智能体本质的差别是人能思维，能智能的行为，而我们的行为，会对周围的世界产生影响。  
 
** 人的结构
   人的形状就像中文汉字“大”差不多的形状，有一个大脑，是智能中心，然后有两个手，用来改变东西，两个脚，用来改变位置。 
  
   智能的大脑由思维，记忆，感觉，运动，感情，自律，身体协调等不同脑块构成，每个脑块都有不同的功能。 
  
   人的每次行为，差不多就是人用接收器官（主要是眼睛）接收身边的东西，用脑进行理解并思考，然后给出一个行为指令，然后用输出器官（主要是手和嘴）进行输出。
  
   #+begin_quote
   所以人的大脑最重要，大脑没了，人就是植物人瘫痪了
   #+end_quote
   
   #+begin_quote
   因为现代心理学有一种潜意识的说法，就是说我们平时做的很多事情都是习惯性的，经过的是大脑的潜意识思维部分，这从我们做一些自觉的事情时，能明显感受到。相当于性格决定做事风格。那么，如果我们要改变做事风格，就要多进行意识思考，多多练习，就改变风格了。
   #+end_quote
** 大脑
*** 意识   
    大脑能对我们看到，听到，或想象中的东西能够进行图像化渲染，使东西更直观 
*** 思维
    - 思维是我们对感受到的东西进行 *行为加工* 的现象
    - 要想加工好，需要专注东西
    - 反复加工
    - 进行测试
 
      思维方法 
    - 沉浸式思维
*** 情绪(喜怒哀乐)
    情绪是我们对东西的感受，与人对东西的往期经历有关，对未知的东西，我们会像灵长类动物一样产生好奇，然后打开潘多拉魔盒。
    
    #+begin_quote
    这里的潘多拉仅仅指人有好奇心
    #+end_quote
   
*** 想象
    想象是对不同的东西进行行为加工，好像跟思维差不多么！
*** 缺陷
    - 5 分钟没氧气就要死翘翘
    - 用脑过度或睡眠不好会影响脑的活力
    - 人累也影响用脑

*** 清醒训练
    - 大脑工作时间长了，或者刚起床，还没初始化，就可以用点清醒训练
    - 冥想 并 呼吸控制（腹式呼吸） (几分钟就好)
    - 5 分钟感受大自然(出去走走)
    - 闭眼，以手扶腮
    - 折纸 （做手工）
    - 实在不行就好好休息

      #+begin_quote
     简单的多动动似乎更能使人清醒，呼吸更急促，为大脑提供提供氧气 
      #+end_quote
* 人生意义
 本子活着的意义就是给人写字，书活着的意义就是给人传授知识。人活着的意义是什么？因为人是智能体，所以，人活着的意义在于他给自己的定位，是想成为本子呢？还是成为书！ 
  
 虽定位不同，但下面这几件事是每个人都要思考的。
** 寿命
   人命很短，人很脆弱，所以人活着只能做自己想到的很少一部分的事情，要做就抓紧了。
     
** 关系
   对人最重要的关系是  
   - 父母   
   - 妻女   
   - 朋友
** 事业   
   - 人生规划
** 健康
   - 既然小肚子变大了，为什么不做仰卧起坐
   - 既然坐姿不好，含胸驼背，为什么不昂首挺胸
   - 既然眼睛不好，为什么不少看手机
** 知识
   - 知识的整理比知识的阅览更重要
   - 泛泛浏览信息有害

     
