#+TITLE: 人与哲学
#+TAGS:  人,哲学
#+DESCRIPTION: 人，哲学
#+CATEGORIES: 人
#+DATE: <2019-06-01 16:25:02>
* 哲学
** 物质简介
   #+begin_verse
   东西就是物质，这里用更 *口语化*的“东西”替换。 
   东西的表象很多，有肉眼看到与看不到的（细菌），还有我们未知的东西（银河系外）
   #+end_verse
   
  #+HTML: <!-- more -->
*** 关联 
    #+begin_verse
    东西与东西之间是有关联的。我们学习知识，学一个东西，然后引申出其他东西，就是因为东西的关联性。
    我们要引申出别的关系，就要开动思维。有些书，如果你直接看，书里讲了关联的东西，没有了思维活动，并不能清晰理解东西的本质。
    所以你进行关联的思维，就形成了自我的判断能力，就能判断是否受到欺骗。现在网络上假的东西很多的哦!
    #+end_verse
    
    #+begin_verse
    比如有这么一个问题，怎么把弯管矫直？我们会进行事物的关联思维。
    弯管 --》 铁 --》直尺 --》人 --》榔头 。。。越来越接近解决方案
    如果不进行延伸，一直把重心放在弯管上，就不能找到解决问题的答案。
    #+end_verse
*** 静止
    #+begin_verse
    东西如果不和其它东西接触，就不会改变。比如杯子，不跟石头接触，就不会摔坏。
    还有就是人，不跟别人接触，整天宅在家里，心智就不能发展强大。
    #+end_verse
*** 变化
    东西有了接触，就会发生变化，我们就说东西是变化的。也就是东西之间有了关联，才导致变化。
*** 细分
    #+begin_verse
    大东西的特点我们都知道，由小东西构成的。
    但小到量子体系呢？这个特点就不太了解了。还需研究
    #+end_verse
    
* 人 
** 简介 
   #+begin_verse
   跟无机物比，人有感知。 人的感知是造成人如此复杂的原因。
   跟其他动物比，人有更发达的大脑，能进行复杂的计算和抽象思维。
   #+end_verse
#+HTML: <!-- more -->

** 生理特性
*** 代谢
**** 分解代谢
**** 合成代谢
*** 神经网络
    神经元、细胞、触点等组成网络，用于产生生物的意识，帮助生物进行思考和行动。
* 人类社会
** 分类  
*** 前工业化
    前工业化社会中，食物的产生是主要的经济活动，过程中伴随着人力及动物力的投入。
    前工业化社会又可以依其技术水准以及产生食物的方式来分类：狩猎采集社会、畜牧社
    会、园艺型社会（horticultural society）、农业社会、及封建社会。
*** 工业化 
    工业化社会在商品制造上大幅依赖利用燃料作为动力的机器。产生了比以前更大的剩余
    资本主义的特点是自由市场的开放竞争，而生产设备工具是私有的。
*** 后工业社会
    #+begin_verse
    后工业社会不是以制造商品为主的社会，而是以资讯、服务及高科技为主的社会
    服务产业包括政府、研究、教育、医疗、业务、法律及银行等。
    #+end_verse

** 生产活动 [ 协作分工,生产出了商品 ] 
   #+begin_verse
   体力工作者  [ 以体力为主,浅层脑力 ]
   脑力工作者
   #+end_verse
   #+begin_quote
   人本来是自给自足，但后来发现分工后产量高了，就进行了分工，出现了不同的行业。此时人已经不生产自用了，就进入了市场交换。
   #+end_quote
   #+begin_quote
   动力是为了生存
   #+end_quote
   
** 商业活动 [ 商品交换 ]
   #+begin_verse
   一般是货币与商品的交换，因为货币便于存放。
   现在都快数字货币了，连造纸的支出都不用了。
   #+end_verse
   #+begin_quote
   商业活动产生了各种垄断，欺骗，残酷竞争。此时需要有一种约束。
   #+end_quote
   #+begin_quote
   动力是为了生存和享受。
   #+end_quote
 
** 行为规范 [ 相对自由, 相对拘谨 ]
   #+begin_verse
   道德规范 
   法律规范 
   #+end_verse
   
   #+begin_quote
   保持人类系统相对稳定。
   #+end_quote
   
** 生殖繁衍 [ 婚姻形式 ]
*** 亲情关系
    #+begin_verse
    夫妻关系
    子女关系
    父母关系
    祖辈亲戚
    #+end_verse
*** 非亲情
    动物可能会没这么亲密的约束,人估计都是有亲属性的。
