#+TITLE: 哲学
#+TAGS: 哲学 , 人
#+DESCRIPTION: 有道理的观点 
#+CATEGORIES: 人
#+DATE: <2019-06-01 16:25:02>

* 哲学 
  对 *未解决问题* 的理性的 *思考* ， *推理* 。
  #+HTML: <!-- more -->
 
** 存在 
** 价值
** 心灵
* 人 
** 简介 
   #+begin_verse
   人类有比其他动物更发达的大脑，能进行复杂的计算和抽象思维。(心)  
   人类是社会性的 (网)
   人类起源: 普遍认为人类及所有的动物都是演化而来的。(少部分神创论)
   #+end_verse

** 生理特性
*** 代谢
**** 分解代谢
**** 合成代谢
*** 神经网络
    神经元、细胞、触点等组成网络，用于产生生物的意识，帮助生物进行思考和行动。
* 人类社会
** 分类  
*** 前工业化
    前工业化社会中，食物的产生是主要的经济活动，过程中伴随着人力及动物力的投入。
    前工业化社会又可以依其技术水准以及产生食物的方式来分类：狩猎采集社会、畜牧社
    会、园艺型社会（horticultural society）、农业社会、及封建社会。
*** 工业化 
    工业化社会在商品制造上大幅依赖利用燃料作为动力的机器。产生了比以前更大的剩余
    资本主义的特点是自由市场的开放竞争，而生产设备工具是私有的。
*** 后工业社会
    #+begin_verse
    后工业社会不是以制造商品为主的社会，而是以资讯、服务及高科技为主的社会
    服务产业包括政府、研究、教育、医疗、业务、法律及银行等。
    #+end_verse

** 生产活动 [ 协作分工,生产出了商品 ] 
   #+begin_verse
   体力工作者  [ 以体力为主,浅层脑力 ]
   脑力工作者
   #+end_verse
   #+begin_quote
   人本来是自给自足，但后来发现分工后产量高了，就进行了分工，出现了不同的行业。此时人已经不生产自用了，就进入了市场交换。
   #+end_quote
   #+begin_quote
   动力是为了生存
   #+end_quote
   
** 商业活动 [ 商品交换 ]
   #+begin_verse
   一般是货币与商品的交换，因为货币便于存放。
   现在都快数字货币了，连造纸的支出都不用了。
   #+end_verse
   #+begin_quote
   商业活动产生了各种垄断，欺骗，残酷竞争。此时需要有一种约束。
   #+end_quote
   #+begin_quote
   动力是为了生存和享受。
   #+end_quote
 
** 行为规范 [ 相对自由, 相对拘谨 ]
   #+begin_verse
   道德规范 
   法律规范 
   #+end_verse
   
   #+begin_quote
   保持人类系统相对稳定。
   #+end_quote
   
** 生殖繁衍 [ 婚姻形式 ]
*** 亲情关系
    #+begin_verse
    夫妻关系
    子女关系
    父母关系
    祖辈亲戚
    #+end_verse
*** 非亲情
    动物可能会没这么亲密的约束,人估计都是有亲属性的。
