#+TITLE: 人与哲学
#+TAGS[]:  哲学
#+DESCRIPTION: 人，哲学
#+CATEGORIES[]: 生活
#+DATE: 2019-11-22T06:55:56+08:00
#+PUBLISHDATE: 2019-11-22T06:55:56+08:00
#+DRAFT: nil


哲学，有智慧的学问，理解起来有道理观念。
# more
  
* 哲学
** 物质简介
   东西就是物质，这里用更 *口语化* 的“ *东西* ”替换。   
*** 关联 
    东西一般不会遗世独立的，一般东西与东西之间是有关联的。有些东西，我们不知道，
    暂时跟我们人类没有关联，但它一定跟其它东西有某种关联，如果某天人类发现了它，
    那就又增加了一条与人类的关联。
    
    有些东西，并不是直接和另一个东西相关联，而是中间隔了好多关联的东西，这个叫间接关联。
*** 静止
    #+begin_verse
    东西如果不和其它东西关联，就不会改变。比如杯子，不跟石头接触，就不会摔坏。
    还有就是人，不跟别人接触，整天宅在家里，心智就不能发展强大。
    #+end_verse
*** 变化
    东西与东西之间如果有了 *接触* 的关联，东西就会发生某种变化，我们就说东西是变
    化的。
*** 细分
    #+begin_verse
    大东西的特点我们都知道，由小东西构成的。
    但小到量子体系呢？这个特点就不太了解了。还需研究
    #+end_verse
*** 聚合
    有些东西就像一个胶水一样，会把其它东西聚合成一个大的集体。
** 时间
   我们的印象是时间是一直往前走的。
* 人 
** 简介 
   跟无机物比，人有感知。 人的感知是造成人如此复杂的原因。
   跟其他动物比，人有更发达的大脑，神经网络，能进行复杂的计算和抽象思维。

   人脑中的“ *东西* ”，我们的念想，估计是液态，因为是比固体的东西更容易变化，导致我们人的外在行为的 *易变*。
** 生产活动 [ 与吃用关联 ] 
   为了生存
** 商业活动 [ 与吃用关联 ]
   一般是货币与商品的交换，因为货币便于存放。
   现在都快数字货币了，连造纸的支出都不用了。
   #+begin_quote
   商业活动产生了各种垄断，欺骗，残酷竞争。此时需要有一种约束。
   #+end_quote
 
** 行为规范 [ 与生存关联 ]
   道德规范 和 法律规范 
   #+begin_quote
   保持人类系统相对稳定。
   #+end_quote
   
** 生殖繁衍 [ 与生存关联 ]
*** 亲情关系
    - 夫妻关系
    - 子女关系
    - 父母关系
    - 祖辈亲戚
*** 非亲情
    动物可能会没这么亲密的约束,人估计都是有亲属性的。
