#+TITLE: 设计简介
#+DESCRIPTION: 设计简介 
#+TAGS: 设计
#+CATEGORIES: 人
#+DATE: <2019-07-18 20:45:49>

* 设计
** 简介 
   所谓设计，即“设想和计划，设想是目的，计划是过程安排”，通常是指有目标和计划的创作行为及活动。
   
   #+HTML: <!-- more -->
   #+begin_verse
   *人类* 在生存繁衍的过程中，创造了许多 *人造物* 。
   虽然起先可能是凭着 *经验*, 但在 *美学追求* 的驱动下，造出的东西往往趋于 *美观* 。
   说明有些 *人类* 追求美感，他们是最早的设计师。 
   #+end_verse

   #+begin_verse
   我们身边的东西，大多都是精美设计的结果。
   一个东西刚产生之时，往往注重是否能用，随后才慢慢向好用靠拢，是设计师几代人的辛劳。
   #+end_verse
   
   #+begin_quote
   #+begin_verse
   你看那些人工智能，天天设计我们，给我们推送我们喜欢的东西，使我们得不到批评。
   还有计算机，刚出来就一大傻子似的，又大又笨。
   编程语言，制造机器指令的设计师缺乏美感，然后后来的开发者构建了框架，可直接拿来用了，但还需发展。。(但相对传统的东西很智能了)
   #+end_verse
   #+end_quote

   设计好之后，要好好 *体验* ，用心感受。能促进设计的兴趣。
** 大自然设计师
   #+begin_verse
   我觉得我们的人类文明是一步一步设计而来的。
   自宇宙诞生以后，宇宙的发展都是宇宙中的存在物一步一步有意无意的"设计" 而成。
   我们的地球，是地球自身与周边的环境共同设计的结果。
   #+end_verse
   #+begin_quote
   #+begin_verse
   我们人，大自然设计的挺好的，能蹦能跳，还设计了 *基因* 模式，使人能直接通过 *基因* 信息 *拷贝* 而不用重新一个个地制作。
   当然还有缺陷，就是不能飞，但现在，不用大自然设计，我们人类自己就设计了很多飞行器了
   #+end_verse
   #+end_quote

** 设计方式
   大自然的设计要慢一点，因为大自然不会思考。所以设计最好用脑。
   
*** 通用设计方式
    构思
    #+begin_verse
    笔
    纸
    参考资料(或网络搜索)
    大脑思维
    #+end_verse
   
    然后通过创造的实物体验使用

