* 计算机体系结构
** 发展阶段
*** 第一阶段 自己开发自己用
    60年代中期以前，是计算机系统发展的早期时代。在这个时期通用硬件已经相当普遍，软
    件却是为每个具体应用而专门编写的，大多数人认为软件开发是无需预先计划的事情。这
    时的软件实际上就是规模较小的程序，程序的编写者和使用者往往是同一个(或同一组)人。
    由于规模小，程序编写起来相当容易，也没有什么系统化的方法，对软件开发工作更没有
    进行任何管理。这种个体化的软件环境，使得软件设计往往只是在人们头脑中隐含进行的
    一个模糊过程，除了程序清单之外，根本没有其他文档资料保存下来。
*** 第二阶段 还是个人开发为主
    从60年代中期到70年代中期，是计算机系统发展的第二代。在这10年中计算机技术有了很
    大进步。多道程序、多用户系统引入了人机交互的新概念，开创了计算机应用的新境界，
    使硬件和软件的配合上了一个新的层次。实时系统能够从多个信息源收集、分析和转换数
    据，从而使得进程控制能以毫秒而不是分钟来进行。在线存储技术的进步导致了第一代数
    据库管理系统的出现。计算机系统发展的第二代的一个重要特征是出现了“软件作坊”，
    广泛使用产品软件。但是，“软件作坊”基本上仍然沿用早期形成的个体化软件开发方法。
    随着计算机应用的日益普及，软件数量急剧膨胀。在程序运行时发现的错误必须设法改正；
    用户有了新的需求时必须相应地修改程序；硬件或操作系统更新时，通常需要修改程序以
    适应新的环境。上述种种软件维护工作，以令人吃惊的比例耗费资源。更严重的是，许多
    程序的个体化特性使得它们最终成为不可维护的。“软件危机”就这样开始出现了。1968
    年北大西洋公约组织的计算机科学家在联邦德国召开国际会议，讨论软件危机课题，在这
    次会议上正式提出并使用了“软件工程”这个名词，一门新兴的工程学科就此诞生了。
*** 第三阶段 个人微机出现，个人应用还是很少
    计算机系统发展的第三代从20世纪70年代中期开始，并且跨越了整整10年。在这10年中计
    算机技术又有了很大进步。分布式系统极大地增加亍计算机系统的复杂性，局域网、广域
    网、宽带数字通信以及对“即时”数据访问需求的增加，都对软件开发者提出了更高的要
    求。但是，在这个时期软件仍然主要在工业界和学术界应用，个人应用还很少。这个时期
    的主要特点是出现了微处理器，而且微处理器获得了广泛应用。以微处理器为核心的“智
    能”产品随处可见，当然，最重要的智能产品是个人计算机。在不到10年的时间里，个人
    计算机已经成为大众化的商品。
*** 第四阶段 微机流行，手机流行，软件技术很快发展
    在计算机系统发展的第四代已经不再看重单台计算机和程序，人们感受到的是硬件和软件
    的综合效果。由复杂操作系统控制的强大的桌面机及局域网和广域网，与先进的应用软件
    相配合，已经成为当前的主流。计算机体系结构已迅速地从集中的主机环境转变成分布的
    客户机/服务器(或浏览器/服务器)环境。世界范围的信息网为人们进行广泛交流和资源的
    充分共享提供了条件。软件产业在世界经济中已经占有举足轻重的地位。随着时代的前进，
    新的技术也不断地涌现出来。面向对象技术已经在许多领域迅速地取代了传统的软件开发
    方法。
** 分类 
*** 冯*诺依曼体系 一维
    CPU(处理器)和内存, 中断控制器
**** 内存 (指令与数据) 
     内存属性相同，没有存储类型, 便宜
***** 寻址方式 (Intel）
****** 立即寻址，寄存器寻址(与地址无关） 
****** 直接寻址（地址)
****** 间接寻址（地址)
       变址寻址
       基址寻址
**** CPU组成
     程序计数器
     指令解码器
     数据总线
     通用寄存器
     算术逻辑单元
**** CPU指令
**** 中断控制器 (接受外部事件)
*** 分布式 多维
