* cmd
有关某个命令的详细信息，请键入 HELP 命令名
ASSOC          显示或修改文件扩展名关联。
ATTRIB         显示或更改文件属性。
BREAK          设置或清除扩展式 CTRL+C 检查。
BCDEDIT        设置启动数据库中的属性以控制启动加载。
CACLS          显示或修改文件的访问控制列表(ACL)。
CALL           从另一个批处理程序调用这一个。
CD             显示当前目录的名称或将其更改。
CHCP           显示或设置活动代码页数。
CHDIR          显示当前目录的名称或将其更改。
CHKDSK         检查磁盘并显示状态报告。
CHKNTFS        显示或修改启动时间磁盘检查。
CLS            清除屏幕。
CMD            打开另一个 Windows 命令解释程序窗口。
COLOR          设置默认控制台前景和背景颜色。
COMP           比较两个或两套文件的内容。
COMPACT        显示或更改 NTFS 分区上文件的压缩。
CONVERT        将 FAT 卷转换成 NTFS。您不能转换当前驱动器。
COPY           将至少一个文件复制到另一个位置。
DATE           显示或设置日期。
DEL            删除至少一个文件。
DIR            显示一个目录中的文件和子目录。
DISKCOMP       比较两个软盘的内容。
DISKCOPY       将一个软盘的内容复制到另一个软盘。
DISKPART       显示或配置磁盘分区属性。
DOSKEY         编辑命令行、调用 Windows 命令并创建宏。
DRIVERQUERY    显示当前设备驱动程序状态和属性。
ECHO           显示消息，或将命令回显打开或关上。
ENDLOCAL       结束批文件中环境更改的本地化。
ERASE          删除一个或多个文件。
EXIT           退出 CMD.EXE 程序(命令解释程序)。
FC             比较两个文件或两个文件集并显示它们之间的不同。
FIND           在一个或多个文件中搜索一个文本字符串。
FINDSTR        在多个文件中搜索字符串。
FOR            为一套文件中的每个文件运行一个指定的命令。
FORMAT         格式化磁盘，以便跟 Windows 使用。
FSUTIL         显示或配置文件系统的属性。
FTYPE          显示或修改用在文件扩展名关联的文件类型。
GOTO           将 Windows 命令解释程序指向批处理程序
               中某个带标签的行。
GPRESULT       显示机器或用户的组策略信息。
GRAFTABL       启用 Windows 在图形模式显示扩展字符集。
HELP           提供 Windows 命令的帮助信息。
ICACLS         显示、修改、备份或还原文件和
 目录的 ACL。
IF             在批处理程序中执行有条件的处理过程。
LABEL          创建、更改或删除磁盘的卷标。
MD             创建一个目录。
MKDIR          创建一个目录。
MKLINK         创建符号链接和硬链接
MODE           配置系统设备。
MORE           逐屏显示输出。
MOVE           将一个或多个文件从一个目录移动到另一个目录。
OPENFILES      显示远程用户为了文件共享而打开的文件。
PATH           为可执行文件显示或设置搜索路径。
PAUSE          停止批处理文件的处理并显示信息。
POPD           还原由 PUSHD 保存的当前目录上一次的值。
PRINT          打印一个文本文件。
PROMPT         改变 Windows 命令提示。
PUSHD          保存当前目录，然后对其进行更改。
RD             删除目录。
RECOVER        从损坏的磁盘中恢复可读取的信息。
REM            记录批处理文件或 CONFIG.SYS 中的注释。
REN            重新命名文件。
RENAME         重新命名文件。
REPLACE        替换文件。
RMDIR          删除目录。
ROBOCOPY       复制文件和目录树的高级实用程序
SET            显示、设置或删除 Windows 环境变量。
SETLOCAL       开始用批文件改变环境的本地化。
SC             显示或配置服务(后台处理)。
SCHTASKS       安排命令和程序在一部计算机上按计划运行。
SHIFT          调整批处理文件中可替换参数的位置。
SHUTDOWN       让机器在本地或远程正确关闭。
SORT           将输入排序。
START          打开单独视窗运行指定程序或命令。
SUBST          将驱动器号与路径关联。
SYSTEMINFO     显示机器的具体的属性和配置。
TASKLIST       显示包括服务的所有当前运行的任务。
TASKKILL       终止正在运行的进程或应用程序。
TIME           显示或设置系统时间。
TITLE          设置 CMD.EXE 会话的窗口标题。
TREE           以图形显示启动器或路径的目录结构。
TYPE           显示文本文件的内容。
VER            显示 Windows 的版本。
VERIFY         告诉 Windows 验证文件是否正确写入磁盘。
VOL            显示磁盘卷标和序列号。
XCOPY          复制文件和目录树。
WMIC           在交互命令外壳里显示 WMI 信息。
* 复制
  C:\WINDOWS\system32\xcopy Z:\b-b-car.com D:\b-b-car.combak /y /e 
(y:\替换时不需确认， 

* right
  set mmdd=%date:~0,4%%date:~5,2%%date:~8,2% 
  C:\WINDOWS\system32\xcopy  D:\test D:\testbak\%mmdd% /e/I/d/h/r/y
  



  C:\WINDOWS\system32\xcopy Z:\b-b-car.com D:\b-b-car.combak%mmdd% /d /y /e 
  set mmdd=%date:~0,4%   //年
echo %date:~5,2%  //月
echo %date:~8,2%  //日期
 %date:\~5,2%%date:\~8,2% 
set name=%date:~-3%  

(d:\目录 f:\文件 y:\替换时不需确认，e:\复制所有文件) 
set mmdd=%date:\~0,4%%date:\~5,2%%date:\~8,2%
* 重要数据必须备份！其重要性不必多说，先讲一个小故事。
博主所在的公司是一个小公司，项目源码都在SVN服务器上，忽然有一天，服务器中毒，文件被破坏，导致SVN代码库文件夹丢失，后来经过多方整合才从各开发人员的机器上确认了各项目的最新源码的副本，就是因为没有做好备份，才带来了不必要的麻烦。
故事将完了，那就来说一下怎么利用批处理命令和任务计划来实现文件夹的定时备份。
首先，新建一个文本文档，改名为备份SVN.bat

粘贴以下内容：

[plain] view plain copy
@echo off  
echo 本批处理为Ls_man原创  
echo 更多精彩博文请访问 http://blog.csdn.net/ls_man  
echo 或登陆求知域官网 http://www.qqextra.com  
color 0b & cls  
echo 设置要备份的文件夹...  
set "pbuf=D:\VisualSVN_Repositories"  
echo 设置备份文件存放文件夹...  
set "tbuf=G:\Backup_VisualSVN_Repositories"  
  
echo 初始化压缩程序设置...  
cd \  
C:  
cd C:\Program Files\WinRAR  
set yes=ok  
echo 压缩程序在C:\Program Files\WinRAR\WinRAR.exe  
  
echo 设置备份文件名(以星期几命名，即备份文件只保存最近一周)...  
set name=%date%  
set name=%name:~-3%  
set name=svn_backup_%name%  
  
echo 是否存在同名文件，若存在则删除同名文件...  
if exist %tbuf%\%name%.rar del %tbuf%\%name%.rar  
  
echo 开始执行压缩备份...  
rar a -r -ed -esh %tbuf%\%name%.rar %pbuf%\*.*  
echo 备份完毕！  

由于要备份的文件夹和存放备份的文件夹及WinRaR的安装路径可能不同，根据实际情况修改即可。
下一步就是添加任务计划，打开控制面板-任务计划-添加任务计划，设置每天执行备份.bat，最好在晚上执行如凌晨1点。
