* emacs 
** 选项
  +<行号>：启动emacs编辑器，并将光标移动到制定行号的行；
  -q：启动emacs编辑器，而不加载初始化文件；
  -u<用户>：启动emacs编辑器时，加载指定用户的初始化文件；
  -t<文件>：启动emacs编辑器时，把指定的文件作为中端，不适用标准输入（stdin）与标准输出（stdout）；
  -f<函数>：执行指定lisp（广泛应用于人工智能领域的编程语言）函数；
  -l<lisp代码文件>：加载指定的lisp代码文件；
  -batch：以批处理模式运行emacs编辑器。
  --DEBUG-init
** 调试任务
   gdb –annotate=3 test
   无论上面的那种情况，都出现了一个现象：程序的输出不能显示，只有在程序退出的时候才显示出来。无论上面的那种情况，都出现了一个现象：程序的输出不能显示，
   只有在程序退出的时候才显示出来。无论上面的那种情况，都出现了一个现象：程序的输出不能显示，只有在程序退出的时候才显示出来。
   gdb-many-windows 切换单窗格/多窗格模式
   gdb-restore-windows 恢复窗格布局	
** 功能
   screen menu bar/echo area/mode line
   text edit(许多文本，位置属性，单词，行数，列数，数组）transposed(交换)/upcase/lowercase/
   mode SGML/HTML/PICTURE/compilation/sql/java/perl/emacs-lisp/Lisp interaction/auto save/auto-fill/ISO accents(重音）
   copy/yank 堆栈结构 abc
   sort行 列
   search and replace (regular expression) vi中也是默认正则, 文件中搜索　grep
   spell-check ispell/flyspell-mode ispell-change-directory
   buffers read-only
   Word Abbreviation (global-abbrev-table)
   (text-mode-abbrev-table) (setq-default abbrev-mode t) (read-abbrev-file "~/.abbrev_defs") (setq save-abbrevs t)
   macro
   format
   comment
   frame
   latex
   window windmove-left /right /down/up
   markdown
   diff
   dired
   Comparing Files compare-windows(高亮不同）
   print lpr
   calendar diary
   holiday
   bookmark
   browse browse-url-of-buffer
   shell(setq shell-file-name "/bin/zsh") .emacs_shell-name (shell初始化文件）
   language etags etags *.[ch]
   debug next-error
   as work environment
   custom(tool-bar/menu-bar/
   模式属性　(add-hook 'text-mode-hook 'turn-on-auto-fill)
   按键属性　(define-key global-map "\C-x\C-u" 'undo)
   输入法切换 `c-\' (toggle-input-method')
  : lisp
  : package
  : version control(vc-next-action/vc-diff/vc-print-log/vc-cnacel-version)
  : Unicode coding-system
  (setq buffer-file-coding-system 'utf-8)  默认buffer编码是utf-8,(写文件)
  (prefer-coding-system 'utf-8)   指定文件编码,此时buffer新建和读取
  (setq read-quoted-char-radix 16) insert-quoted-char 
  : info
  : browser
  : help system/key/variable/mode
  : bug
  ^                Matches the beginning of a line.
  $                Matches the end of a line.
  .                Matches any single character (like ? in filenames).
  .*               Matches any group of zero or more characters 
  \<               Matches the beginning of a word.
  \>               Matches the end of a word.
  []               Matches any character specified within the brackets; for example, [a-z]
  \{n,m\}          表示它前面的单个字符重新的次数
  \s, \S           \S matches any character except whitespace.
  \d, \D           Matches any single digit, 0-9; \D matches any character but a digit.
  \w, \W           Matches any "word" character (upper- and lowercase letters, digits, and the