* emacs （黑板） 
** 环境变量 (配置)
*** 命令所在位置
    getenv
*** 设置环境
    #+BEGIN_SRC elisp
      (setenv "PATH"
        (concat
         "C:/Program Files (x86)/Notepad++" ";"
         (getenv "PATH")
        )
      )
    #+END_SRC
** 界面 黑板
** 黑板文字编辑 (黑板擦)
** 扩展(黑板辅助)
*** 加载
    list-packages
*** 配置 
    require <sysbol name>
    load load-path
    autoload
    `autoload`告诉emacs某个地方有一个定义好的函数，并且告诉emacs，先别加载，只要记住在调用这个函数时去哪里寻找它的定义即可
*** 包管理器 elpa(Emacs package system)
    安装一个插件后，elpa会自动在插件所在目录下生成一个autoloads文件。这个文档本意是方便你调用插件的。比如，你可以在`init.el`中加入`(load 某某插件-autoloads)`来加载该插件
    如果你希望用`require`的方式来加载插件，并且还希望`require`这个autoloads文件，会出现一个问题。autoloads的结尾并没有`(provide '某某插件-autoloads)`，所以`require`一定会报错。而且这样做也没什么意义。因为你的目的在于将插件本身的名字放到features列表中，而不是“插件名-autoloads”。所以，请`load`而不是`require`autoloads文件
    当然，你也可以直接加载插件的主脚本，比如`(require 'auto-complete)`而不是`(load 'auto-complete-autoloads)`。不过，这样做有两个坏处。第一，有些插件可能会指导elpa在生成autoloads文件时加入一些配置代码。在这种情形下，有可能你通过`load`这个autoloads文件能成功初始化插件，而直接`load`或者`require`插件的主脚本则不能。第二，autoloads由`autoload`函数构成，`autoload`的好处如前所述，可以轻便化emacs的启动
*** load-path 很重要的变量（用来找到包）
*** 服务 程序调用程序     
    调用编辑程序, 由环境变量 EDITOR 控制, 如果 是 emacs 会开启一个新进程，就不能共享缓存，命令历史和其他信息
    那么，把emacs 设置层 edit server,因为服务是一直开着的，监视edit请求
    方法：1. 在emacs 中 server-start, 或放在init file中
    2.用 --daemon 作为启动emacs 的参数
    
    先要开服务
    然后调用emacs客户端形式emacsclient -c 创建一个新的frame  (tells a running Emacs to visit a file)
    
    也能创建多个不同名字的emacs 服务
    先设置服务名
    For example, M-x set-variable <RET> server-name <RET> "foo" <RET> sets the server name to ‘foo’. The emacsclient program can specify a server by name, using the ‘-s’ option (see emacsclient Options).
    
    TCP Emacs server: Listening to a TCP socket.
    Invoking emacsclient: Connecting to the Emacs server.
    emacsclient Options: Emacs client startup options.
    [1] Some programs use a different environment variable; for example, to make TeX use ‘emacsclient’, set the TEXEDIT environment variable to ‘emacsclient +%d %s’.
* 扩展
** WriteRoom
   开启WriteRoom后即进入全屏模式,默认黑色界面,绿色字体也许会给你带来创作的灵感.
   我也更喜欢这种模式的码字.没有图片,没有格式,只专注地将所要表达的文字给记录下来.
   你不必分心,需要时仅仅将鼠标移向屏幕顶端即可显示无处不在的系统导航栏;
   移向底部显示当前你所码入的字数.
* emacs
