* java lsp
** Server jdtls: status:starting exited with status exit. Do you want to restart it
   1.Delete workspace `lsp-java-workspace-dir`
   2.Delete server installation from `lsp-java-server-install-dir`
   3.Evaluating `lsp-java--ls-command` will give you the command that is used for starting JDT LS - you could then start it outside of emacs
* ntfs 执行权限
  fstab 配置
  UUID=0005D5040006FBE9   /media/d        ntfs-3g defaults,locale=zh_CN.UTF-8     0       0
* ubuntu 释放 cache 内存
写了个简单的脚本：

#!/bin/bash                                                                                                                                                                                                 

sync && echo 1 | sudo tee /proc/sys/vm/drop_caches
sync && echo 2 | sudo tee /proc/sys/vm/drop_caches
sync && echo 3 | sudo tee /proc/sys/vm/drop_caches
然后加到 crontab 里，每小时执行一次，定时释放 cache。。。 
几天以后，发现脚本没有起作用。。。每次查看内存使用情况，发现 cache 并没有释放。。。该死机还是死机。。。 
想了想，/proc/sys/vm/drop_caches 这个路径，普通账号应该是没有权限去操作的。。。 
果断将这个脚本添加到 root 的 crontab 里，每小时跑一次。发现起作用了。。。 
距上次强制重启已经两周，完美解决。。
* linux
** 忘记密码
   3 秒之内要按一下回车，出现如下界面
   然后输入 e
   在 第二行最后边输入 single，有一个空格。具体方法为按向下尖头移动到第二行，按"e"进入编辑模式
   在后边加上 single 回车
   最后按"b"启动，启动后就进入了单用户模式了
   此时已经进入到单用户模式了，你可以更改 root 密码了。更密码的命令为 passwd
** .profile 配置文件会在图形界面开始或登录系统后执行一遍,而单独的 .zshrc .bashrc 配置文件会在开 shell 后又单独执行一遍.
* CGI 服务器调用脚本语言
* 终端下使用 lantern 代理
  1，在 linux 上安装蓝灯（lantern），只能在浏览器上访问外网，不能在终端下访问外网，
 
  2，在本地终端命令行下访问外网：

       export http_proxy=http://127.0.0.1:42428
       export https_proxy=https://127.0.0.1:42428
       
       # 127.0.0.1:40695
      用 curl google.com 测试下，不会出现连接被拒绝的情况
      也可以将 这两行命令写入到  ~/.bashrc 文件中，这样就不用每次打开一个窗口，都要 export 一下


3，在服务器端下命令行下访问外网
     服务器可以利用本地机器访问外网，不过，这两个网络要在同一个局域网中
     
     在本地终端下 
     cd  ~/.lantern
     vi  settings.yaml
     修改 addr: 127.0.0.1:X  为  addr:本地机器 ip:X

     在服务器端下：
     export  http_proxy=http://本地机器 ip:X
     export  https_proxy=http://本地机器 ip:X
* 客户机如何使用宿主机 lantern 代理上网
  ip route show
  # 查看 route
  http_proxy="http://10.0.2.2:50067"
  # virtualbox 默认路由 10.0.2.2
  # lantern 端口 50067
* google 翻译
  就 Google 翻译，可以改用 http://translate.google.cn  ，这个网址在大陆一直都
  可以访问，且如果用 google-translate  的话，可以用以下的命令把 .com 改成 .cn:
  #+begin_src lisp
    (eval-after-load 'google-translate-core
      '(setq google-translate-base-url "http://translate.google.cn/translate_a/single"
             google-translate-listen-url "http://translate.google.cn/translate_tts"))

    (eval-after-load 'google-translate-tk
      '(setq google-translate--tkk-url "http://translate.google.cn/"))
#+end_src
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to proxy
  git config --global http.proxy http://proxy.server.com:8080
  git config --global https.proxy https://proxy.server.com:8080
* 站立办公，脚跟疼 [ 体重，鞋子,重心移向前脚掌,边运动边工作,深蹲,拉伸臀部 ]
* ABI [应用二进制接口,]
  两程序模块间的接口；通常其中一个程序模块会是库或操作系统所提供的服务，而另一边的
  模块则是用户所运行的程序。

一个 ABI 定义了机器代码如何访问数据结构与运算程序，此处所定义的界面相当低级并且
相依于硬件。而类似概念的 API 则在源代码定义这些，则较为高端，并不直接相依于硬件，
通常会是人类可阅读的代码。一个 ABI 常见的样貌即是调用约定：数据怎么成为计算程序
的输入或者从中得到输出；x86 的调用约定即是一个 ABI 的例子。
* 根
  高等植物茎干下部长在土里的部分，主要功能是把植物固定在土地上，吸收土壤里的水分
  和养料，有的还能储藏养料。
* 写公式 在 LibreOffice Writer 中用公式编辑器写,所见即所得
* 关于写文档，是很有必要重新写一遍的，但是写两遍三遍就没必要了
* 关于框架，是为了我们不要重复的写两遍三遍，重复造轮子没有必要，轮子造一遍，会了就好了，然后可以深入轮子，造的更优化
* 统计一个文件中特定字符的个数,统计单词(其实是统计有多少个分隔符号) 
  统计一个文件中某个字符串的个数，其实就是在在一块沙地里面找石头，有的人看到石头
以后，在上面做个标记（grep），然后记住自己做了多少个标记；有的人看到石头以后，把
它挖了（tr），最后统计自己挖了多少石头；有的人看到石头以后，把它跳过去（awk），


然后统计自己跳了多少次。这是我用的的文件

grep 方法,-c 一行只会统计一个,-o 输出匹配到的东西
grep -o 'WORD' <file> | wc -l
* 死机
  进入虚拟终端
  通常是 ~Ctrl Alt  [F2..]~,切换 tty,用 top 查看程序，然后 pkill,kill
  注销桌面系统 sudo pkill Xorg 或者 sudo restart lightdm
  
  如果切换 tty 失败，则尝试 ssh 登录此电脑

  重启图形界面，方法是<Ctrl><Alt><backspace>
  
  重启计算机 <Ctrl><Alt><Delete>
  
  系统维护的用户空间通信管道保持畅通,busier 反过来,busy 的比较级
  reisub 强制方法
  按住 Alt+SysRq，再依次按下 reisub 几个键,就会重启
  
  unRaw 将键盘控制从 X Server 那里抢回来
  tErminate 给所有进程发送 SIGTERM 信号，让他们自己解决善后
  kIll 给所有进程发送 SIGKILL 信号，强制他们马上关闭
  Sync 将所有数据同步至磁盘
  Unmount 将所有分区挂载为只读模式
  reBoot 重启
* 什么时候会用到 kindle,当你想看书，而没有电脑的时候，最好选择 kindle 
* 看新闻是一种解压，那还有什么方法解压呢？[ 用来限制玩机 ]
  列出来吧:
 1. 深呼吸
    1. 十次(Power 10) 
         先吸气 4 秒，将注意力专注于焦虑及压力的心情上，再呼气 6 秒，专注于放松的感觉，同时将它释放，连续呼吸 10 次。
    2. 心情振奋
          先回忆一下生命中最美好的两个时刻，在吸气的时侯，将注意力集中于开心与爱的感受中。呼气时，释放负面感受。这样的方法可将负面心情与吸气时的正面心情相配合，可以转移心脏节拍、改善心情。
    3. 心情转移
       这个方法分三个步骤，共有五次呼吸，每次呼吸持续 4 秒吸气，5秒呼气。

       第一步，呼吸两次，呼吸时，专注于你的消极情绪，并让它们随着呼气消散；
       第二次，呼吸两次，呼吸时，清除所有杂念，只专注于呼气与吸气；
       最后一次呼吸，拥抱你心中的爱，不管是你的家人还是朋友，放开那些负面情绪。
 2. 听音乐
    优美的音乐让人心旷神怡，要听慢曲调哦，让人放松。听音乐也要认真哦。
 3. 看鲜艳的色彩
   美丽的摄影，绘画
 4. 到户外走走，呼吸下新空气
 5. 手部按摩 5 分钟的手部按摩有助于降低压力
 6. 跟动物相处 
    在网路上看一些有关于动物的趣味短片，也可以达到类似效果。
 7. 花草茶
    花草茶是一种很棒的纾压剂，可试试柠檬香蜂草、西番莲花、啤酒花、洋甘菊、猫薄荷等等。
 8. 坐摇椅
 9. 调整体态
 10. 拥抱一下
* 环游世界  买一张[ 环游世界的机票 ], 住就住在  [ 青年旅社 ]
* 总访客量 121 SCHEDULED: <2019-06-03 一>
