#+TITLE: 使用 Hexo 搭建博客 
#+DATE: 2019-05-31 20:36:03
#+DESCRIPTION: Hexo 是一个快速、简洁且高效的博客框架。Hexo 使用 Markdown（或其他渲染引擎）解析文章 。
#+CATEGORIES: 软件使用 
#+KEYWORDS: Hexo

* Hexo [ 博客框架 ]
** 什么是 Hexo？
   Hexo 是一个快速、简洁且高效的博客框架。Hexo 使用 Markdown（或其他渲染引擎）解析文章，在几秒内，即可利用靓丽的主题生成静态网页。
   #+HTML: <!-- more -->
** 安装 [ 先决条件是本机已安装了 node.js 和 git ]
   #+begin_src shell
     $ npm install hexo-cli -g
   #+end_src
** 使用方法 
   安装好了，就可以学习怎么使用这套工具了
*** 1. 创建博客,创建一个自己的博客
    #+begin_src shell
    $ hexo init blog
    $ cd blog
    #+end_src
   
    会生成一个 ~blog~ 目录，里面是你的整个博客项目了
    
*** 2. 写一篇博客文
    #+begin_src shell
    $ hexo new "Hello Hexo"
    #+end_src
    
    会在默认的 source/_post 目录下创建一个 ~Hello Hexo.md~ 文件，
    然后你就可以写自己的博文了，这里要学一些 ~markdown~ 排版的语法哦 ！
    
*** 3. 生成静态页面
    #+begin_src shell
    $ hexo generate
    #+end_src
    
    hexo 程序在做一系列解析渲染的工作了
*** 4. 开启服务
    
    #+begin_src shell
    $ hexo server
    #+end_src
    
    开启你的服务端通道，你就可以在浏览器客户端用 ~http://localhost:4000/~ 地址访问了。
*** 5. 发布到 github 仓库
    
    #+begin_src shell 
    $ hexo deploy
    #+end_src
    
    上传到远程服务器后，就可以在任何终端访问啦
    
*** 6. 清除缓存文件
    #+begin_src shell
    $ hexo clean
    #+end_src

    清除缓存文件 (db.json) 和已生成的静态文件 (public)。

*** 7. 组合命令 
    命令的缩略写法 
   #+begin_src shell
   $ hexo s -g #生成并本地预览
   $ hexo d -g #生成并上传
   #+end_src
   
** 配置    
   基本配置就不说了，官网文档写的很好，我都是照抄的。
*** 如何上传到 github
     + 首先，ssh key 肯定要配置好。
     + 其次，配置_config.yml 中有关发布 (deploy) 的部分：
       #+BEGIN_SRC yaml 
           deploy:
             type: git
             repository: git@github.com:liuxianan/liuxianan.github.io.git
             branch: master
       #+END_SRC
     + 然后，_还需要安装一个插件：
       #+begin_src shell
         $ npm install hexo-deployer-git --save
       #+end_src
     + 发布
       #+begin_src shell 
         $ hexo deploy
       #+end_src

** Front-matter [ 就是博客页面顶上的一段，没测 ]
*** 设置页面分类 
    #+begin_src yaml 
        categories:
        - Sports
        - Baseball
          #+end_src

    Hexo 不支持指定多个同级分类,会使分类 Baseball 成为 Sports 的子分类 ,只支持子分类哦,因此，有必要为您的文章选择尽可能准确的分类。 
    
*** 设置页面标签

    #+begin_src yaml
      tags:
      - Injury
      - Fight
      - Shocking
    #+end_src

    或者 
#+begin_src yaml
  tags: [label, label, label]
#+end_src

** 文章备份
  我的博客页 不在 ~_post~ 文件夹下，所有我把要发表的文章创建了一个 ~软链接~ 。我用到的文章会保持修改 ，确保不落后太久。
😏
