* Javascript 
  /home/wuming/git/lang/javascript/javascript-tutorial/docs/async/general.md
** 对象
*** 东西
    数字，文字
*** 新建对象
   名字：值（类型）
 #+BEGIN_SRC json
 {
       "firstName": "John",
       "lastName": "Smith",
       "sex": "male",
       "age": 25,
       "address": 
       {
           "streetAddress": "21 2nd Street",
           "city": "New York",
           "state": "NY",
           "postalCode": "10021"
       },
       "phoneNumber": 
       [
           {
             "type": "home",
             "number": "212 555-1234"
           },
           {
             "type": "fax",
             "number": "646 555-4567"
           }
       ]
   }
 [
 {
      "text":"This is the text","color":"dark_red","bold":"true","strikethough":"true","clickEvent":
           {"action":"open_url","value":"zh.wikipedia.org"},
      "hoverEvent":
           {"action":"show_text","value":
                {"extra":"something"}
           }
 },
 {
      "translate":"item.dirt.name","color":"blue","italic":"true"
 }
 ]

 #+END_SRC
*** 东西起名字(变量) 
    var a=东西;
** 行为
*** 起名字
    #+begin_src javascript
      function doAdd(a,b) {
          return a + b;
      }
    #+end_src
*** 匿名函数
    #+begin_src javascript

      var doEcho = function() {
          console.log('你好');
      }
    #+end_src
*** 纯动作
    #+begin_src javascript

      function addLater(a,b,callback) {
          setTimeout(function() {
              var sum = a+b;
              callback(sum);
          },1000);
      }
    #+end_src
** 可视对象行为（事件)
   行为绑定 document.getElementById("btnTest").onclick=thisTest; //给 button 的 onclick 事件注册一个函数
   
   - 行为类型
     - 页面或图像对象 载入行为 onload 和 onUnload 
     - 表单对象 onFocus, onBlur 和 onChange
     - 鼠标对象 onMouseOver 和 onMouseOut
     - 提交对象 onSubmit 
** 错误对象捕捉 
*** Try...Catch 
    #+BEGIN_SRC js
      try
      {
          //在此运行代码
      }
      catch(err)
      {
          //在此处理错误
      }
    #+END_SRC
    #+BEGIN_SRC html
      <html>
        <head>
          <script type="text/javascript">
            var txt=""
            function message()
            {
            try
            {
            adddlert("Welcome guest!")
            }
            catch(err)
            {
            txt="此页面存在一个错误。\n\n"
            txt+="错误描述: " + err.description + "\n\n"
            txt+="点击 OK 继续。\n\n"
            alert(txt)
            }
            }
          </script>
        </head>

        <body>
          <input type="button" value="View message" onclick="message()" />
        </body>
      </html>
      #+END_SRC
** 对象库
*** Date 对象
    #+BEGIN_SRC js
      日期 Date() getTime() setFullYear() toUTString getDay()
      new Date() // 当前日期和时间
      new Date(milliseconds) //返回从 1970 年 1 月 1 日至今的毫秒数
      new Date(dateString)
      new Date(year, month, day, hours, minutes, seconds, milliseconds)

      milliseconds 毫秒（0-999）1 秒=1000 毫秒
      var today = new Date()
      var d1 = new Date("October 13, 1975 11:13:00")
      var d2 = new Date(79,5,24)
      var d3 = new Date(79,5,24,11,33,0)
      设置日期
      var myDate=new Date();
      myDate.setFullYear(2010,0,14);

      设置日期为 5 天后
      var myDate=new Date();
      myDate.setDate(myDate.getDate()+5);
      getTime 获取毫秒时间
    #+END_SRC
*** Math
    abs 绝对值
    E 自然对数
    LN2 2 的自然对数
    PI 圆周率
    Math.SQRT2 2 的平方根
    sqrt 平方根
    pow(x, y) x 的 y 次方
    max
    min
    ceil 上
    floor 下
    round 四舍五入
*** 对象与字符串转换
    对象字符串化   var strify = JSON.stringify(arr);
    字符串对象话  var arrParse = JSON.parse(strify);
*** 字符正则查找
    #+BEGIN_SRC js
      var s="helo world";
      var i=s.search(/wo/i);
      i: 不区分大小写
    #+END_SRC
*** 对象数列 Array
    数组创建
    var arr1 = new Array(); //创建一个空数组
    var arr2 = new Array(20); // 创建一个包含 20 项的数组
    var arr3 = new Array("lily","lucy","Tom"); // 创建一个包含 3 个字符串的数组
    创建数组的第二种基本方式是使用数组字面量表示法：

    var arr4 = []; //创建一个空数组
    var arr5 = [20]; // 创建一个包含 1 项的数组
    var arr6 = ["lily","lucy","Tom"]; // 创建一个包含 3 个字符串的数组
    在读取和设置数组的值时，要使用方括号并提供相应值的基于 0 的数字索引：

    var arr6 = ["lily","lucy","Tom"]; // 创建一个包含 3 个字符串的数组
    alert(arr6[0]); //lily
    arr6[1] = "mary"; //修改第二项为 mary
    arr6[3] = "sean"; //增加第四项为 sean
    JavaScript 中数组的 length 属性是可以修改的，看下面的示例：

    var arr = ["lily","lucy","Tom"]; // 创建一个包含 3 个字符串的数组
    arr[arr.length] = "sean"; //在下标为 3 处（也就是数组尾部）添加一项"sean"
    arr.length = arr.length-1; //将数组的最后一项删除
    如果需要判断一个对象是不是数组对象，在 ECMAScript 5 之前，我们可以通过 instanceof Array 去判断，但是 instanceof 操作符的问题在于，它假定只有一个全局执行环境。如果网页中包含多个框架，那实际上就存在两个以上不同的全局执行环境，从而存在两个以上不同版本的 Array 构造函数。如果你从一个框架向另一个框架传入一个数组，那么传入的数组与在第二个框架中原生创建的数组分别具有各自不同的构造函数。

    ECMAScript 5 新增了 Array.isArray()方法。这个方法的目的是最终确定某个值到底是不是数组，而不管它是在哪个全局执行环境中创建的。

    数组方法

    下面开始介绍数组的方法，数组的方法有数组原型方法，也有从 object 对象继承来的方法，这里我们只介绍数组的原型方法，数组原型方法主要有以下这些：

    join()
    push()和 pop()
    shift() 和 unshift()
    sort()
    reverse()
    concat()
    slice()
    splice()
    indexOf()和 lastIndexOf() （ES5 新增）
    forEach() （ES5 新增）
    map() （ES5 新增）
    filter() （ES5 新增）
    every() （ES5 新增）
    some() （ES5 新增）
    reduce()和 reduceRight() （ES5 新增）
    针对 ES5 新增的方法浏览器支持情况：

    Opera 11+ 
    Firefox 3.6+ 
    Safari 5+ 
    Chrome 8+ 
    Internet Explorer 9+

    对于支持的浏览器版本，可以通过 Array 原型扩展来实现。下面详细介绍一下各个方法的基本功能。

    1、join()

    join(separator): 将数组的元素组起一个字符串，以 separator 为分隔符，省略的话则用默认用逗号为分隔符，该方法只接收一个参数：即分隔符。

    var arr = [1,2,3];
    console.log(arr.join()); // 1,2,3
    console.log(arr.join("-")); // 1-2-3
    console.log(arr); // [1, 2, 3]（原数组不变）
    通过 join()方法可以实现重复字符串，只需传入字符串以及重复的次数，就能返回重复后的字符串，函数如下：

    function repeatString(str, n) {
    return new Array(n + 1).join(str);
    }
    console.log(repeatString("abc", 3)); // abcabcabc
    console.log(repeatString("Hi", 5)); // HiHiHiHiHi
    2、push()和 pop()

    push(): 可以接收任意数量的参数，把它们逐个添加到数组末尾，并返回修改后数组的长度。 
    pop()：数组末尾移除最后一项，减少数组的 length 值，然后返回移除的项。

    var arr = ["Lily","lucy","Tom"];
    var count = arr.push("Jack","Sean");
    console.log(count); // 5
    console.log(arr); // ["Lily", "lucy", "Tom", "Jack", "Sean"]
    var item = arr.pop();
    console.log(item); // Sean
    console.log(arr); // ["Lily", "lucy", "Tom", "Jack"]
    3、shift() 和 unshift()

    shift()：删除原数组第一项，并返回删除元素的值；如果数组为空则返回 undefined。 
    unshift:将参数添加到原数组开头，并返回数组的长度 。

    这组方法和上面的 push()和 pop()方法正好对应，一个是操作数组的开头，一个是操作数组的结尾。

    var arr = ["Lily","lucy","Tom"];
    var count = arr.unshift("Jack","Sean");
    console.log(count); // 5
    console.log(arr); //["Jack", "Sean", "Lily", "lucy", "Tom"]
    var item = arr.shift();
    console.log(item); // Jack
    console.log(arr); // ["Sean", "Lily", "lucy", "Tom"]
    4、sort()

    sort()：按升序排列数组项——即最小的值位于最前面，最大的值排在最后面。

    在排序时，sort()方法会调用每个数组项的 toString()转型方法，然后比较得到的字符串，以确定如何排序。即使数组中的每一项都是数值，sort()方法比较的也是字符串，因此会出现以下的这种情况：

    var arr1 = ["a", "d", "c", "b"];
    console.log(arr1.sort()); // ["a", "b", "c", "d"]
    arr2 = [13, 24, 51, 3];
    console.log(arr2.sort()); // [13, 24, 3, 51]
    console.log(arr2); // [13, 24, 3, 51](元数组被改变)
    为了解决上述问题，sort()方法可以接收一个比较函数作为参数，以便我们指定哪个值位于哪个值的前面。比较函数接收两个参数，如果第一个参数应该位于第二个之前则返回一个负数，如果两个参数相等则返回 0，如果第一个参数应该位于第二个之后则返回一个正数。以下就是一个简单的比较函数：

    function compare(value1, value2) {
    if (value1 < value2) {
    return -1;
    } else if (value1 > value2) {
    return 1;
    } else {
    return 0;
    }
    }
    arr2 = [13, 24, 51, 3];
    console.log(arr2.sort(compare)); // [3, 13, 24, 51]
    如果需要通过比较函数产生降序排序的结果，只要交换比较函数返回的值即可：

    function compare(value1, value2) {
    if (value1 < value2) {
    return 1;
    } else if (value1 > value2) {
    return -1;
    } else {
    return 0;
    }
    }
    arr2 = [13, 24, 51, 3];
    console.log(arr2.sort(compare)); // [51, 24, 13, 3]

    5、reverse()

    reverse()：反转数组项的顺序。

    var arr = [13, 24, 51, 3];
    console.log(arr.reverse()); //[3, 51, 24, 13]
    console.log(arr); //[3, 51, 24, 13](原数组改变)
    6、concat()

    concat() ：将参数添加到原数组中。这个方法会先创建当前数组一个副本，然后将接收到的参数添加到这个副本的末尾，最后返回新构建的数组。在没有给 concat()方法传递参数的情况下，它只是复制当前数组并返回副本。

    var arr = [1,3,5,7];
    var arrCopy = arr.concat(9,[11,13]);
    console.log(arrCopy); //[1, 3, 5, 7, 9, 11, 13]
    console.log(arr); // [1, 3, 5, 7](原数组未被修改)
    从上面测试结果可以发现：传入的不是数组，则直接把参数添加到数组后面，如果传入的是数组，则将数组中的各个项添加到数组中。但是如果传入的是一个二维数组呢？

    var arrCopy2 = arr.concat([9,[11,13]]);
    console.log(arrCopy2); //[1, 3, 5, 7, 9, Array[2]]
    console.log(arrCopy2[5]); //[11, 13]
    上述代码中，arrCopy2 数组的第五项是一个包含两项的数组，也就是说 concat 方法只能将传入数组中的每一项添加到数组中，如果传入数组中有些项是数组，那么也会把这一数组项当作一项添加到 arrCopy2 中。

    7、slice()

    slice()：返回从原数组中指定开始下标到结束下标之间的项组成的新数组。slice()方法可以接受一或两个参数，即要返回项的起始和结束位置。在只有一个参数的情况下，slice()方法返回从该参数指定位置开始到当前数组末尾的所有项。如果有两个参数，该方法返回起始和结束位置之间的项——但不包括结束位置的项。

    var arr = [1,3,5,7,9,11];
    var arrCopy = arr.slice(1);
    var arrCopy2 = arr.slice(1,4);
    var arrCopy3 = arr.slice(1,-2);
    var arrCopy4 = arr.slice(-4,-1);
    console.log(arr); //[1, 3, 5, 7, 9, 11](原数组没变)
    console.log(arrCopy); //[3, 5, 7, 9, 11]
    console.log(arrCopy2); //[3, 5, 7]
    console.log(arrCopy3); //[3, 5, 7]
    console.log(arrCopy4); //[5, 7, 9]
    arrCopy 只设置了一个参数，也就是起始下标为 1，所以返回的数组为下标 1（包括下标 1）开始到数组最后。 
    arrCopy2 设置了两个参数，返回起始下标（包括 1）开始到终止下标（不包括 4）的子数组。 
    arrCopy3 设置了两个参数，终止下标为负数，当出现负数时，将负数加上数组长度的值（6）来替换该位置的数，因此就是从 1 开始到 4（不包括）的子数组。 
    arrCopy4 中两个参数都是负数，所以都加上数组长度 6 转换成正数，因此相当于 slice(2,5)。

    8、splice()

    splice()：很强大的数组方法，它有很多种用法，可以实现删除、插入和替换。

    删除：可以删除任意数量的项，只需指定 2 个参数：要删除的第一项的位置和要删除的项数。例如，splice(0,2)会删除数组中的前两项。
    插入：可以向指定位置插入任意数量的项，只需提供 3 个参数：起始位置、0（要删除的项数）和要插入的项。例如，splice(2,0,4,6)会从当前数组的位置 2 开始插入 4 和 6。
    替换：可以向指定位置插入任意数量的项，且同时删除任意数量的项，只需指定 3 个参数：起始位置、要删除的项数和要插入的任意数量的项。插入的项数不必与删除的项数相等。例如，splice (2,1,4,6)会删除当前数组位置 2 的项，然后再从位置 2 开始插入 4 和 6。
    splice()方法始终都会返回一个数组，该数组中包含从原始数组中删除的项，如果没有删除任何项，则返回一个空数组。

    var arr = [1,3,5,7,9,11];
    var arrRemoved = arr.splice(0,2);
    console.log(arr); //[5, 7, 9, 11]
    console.log(arrRemoved); //[1, 3]
    var arrRemoved2 = arr.splice(2,0,4,6);
    console.log(arr); // [5, 7, 4, 6, 9, 11]
    console.log(arrRemoved2); // []
    var arrRemoved3 = arr.splice(1,1,2,4);
    console.log(arr); // [5, 2, 4, 4, 6, 9, 11]
    console.log(arrRemoved3); //[7]
    9、indexOf()和 lastIndexOf()

    indexOf()：接收两个参数：要查找的项和（可选的）表示查找起点位置的索引。其中， 从数组的开头（位置 0）开始向后查找。 
    lastIndexOf：接收两个参数：要查找的项和（可选的）表示查找起点位置的索引。其中， 从数组的末尾开始向前查找。

    这两个方法都返回要查找的项在数组中的位置，或者在没找到的情况下返回1。在比较第一个参数与数组中的每一项时，会使用全等操作符。

    var arr = [1,3,5,7,7,5,3,1];
    console.log(arr.indexOf(5)); //2
    console.log(arr.lastIndexOf(5)); //5
    console.log(arr.indexOf(5,2)); //2
    console.log(arr.lastIndexOf(5,4)); //2
    console.log(arr.indexOf("5")); //-1
    10、forEach()

    forEach()：对数组进行遍历循环，对数组中的每一项运行给定函数。这个方法没有返回值。参数都是 function 类型，默认有传参，参数分别为：遍历的数组内容；第对应的数组索引，数组本身。

    var arr = [1, 2, 3, 4, 5];
    arr.forEach(function(x, index, a){
    console.log(x + '|' + index + '|' + (a === arr));
    });
    // 输出为：
    // 1|0|true
    // 2|1|true
    // 3|2|true
    // 4|3|true
    // 5|4|true
    11、map()

    map()：指“映射”，对数组中的每一项运行给定函数，返回每次函数调用的结果组成的数组。

    下面代码利用 map 方法实现数组中每个数求平方。

    var arr = [1, 2, 3, 4, 5];
    var arr2 = arr.map(function(item){
    return item*item;
    });
    console.log(arr2); //[1, 4, 9, 16, 25]
    12、filter()

    filter()：“过滤”功能，数组中的每一项运行给定函数，返回满足过滤条件组成的数组。

    var arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
    var arr2 = arr.filter(function(x, index) {
    return index % 3 === 0 || x >= 8;
    }); 
    console.log(arr2); //[1, 4, 7, 8, 9, 10]
    13、every()

    every()：判断数组中每一项都是否满足条件，只有所有项都满足条件，才会返回 true。

    var arr = [1, 2, 3, 4, 5];
    var arr2 = arr.every(function(x) {
    return x < 10;
    }); 
    console.log(arr2); //true
    var arr3 = arr.every(function(x) {
    return x < 3;
    }); 
    console.log(arr3); // false
    14、some()

    some()：判断数组中是否存在满足条件的项，只要有一项满足条件，就会返回 true。

    var arr = [1, 2, 3, 4, 5];
    var arr2 = arr.some(function(x) {
    return x < 3;
    }); 
    console.log(arr2); //true
    var arr3 = arr.some(function(x) {
    return x < 1;
    }); 
    console.log(arr3); // false
    15、reduce()和 reduceRight()

    这两个方法都会实现迭代数组的所有项，然后构建一个最终返回的值。reduce()方法从数组的第一项开始，逐个遍历到最后。而 reduceRight()则从数组的最后一项开始，向前遍历到第一项。

    这两个方法都接收两个参数：一个在每一项上调用的函数和（可选的）作为归并基础的初始值。

    传给 reduce()和 reduceRight()的函数接收 4 个参数：前一个值、当前值、项的索引和数组对象。这个函数返回的任何值都会作为第一个参数自动传给下一项。第一次迭代发生在数组的第二项上，因此第一个参数是数组的第一项，第二个参数就是数组的第二项。

    下面代码用 reduce()实现数组求和，数组一开始加了一个初始值 10。

    var values = [1,2,3,4,5];
    var sum = values.reduceRight(function(prev, cur, index, array){
    return prev + cur;
    },10);
    console.log(sum); //25
*** 时钟对象
    执行一次 setTimeout
    重复执行 setInterval
    #+BEGIN_SRC html 
      <html>
        <head>
          <meta http-equiv="Content-Type" content="text/html; charset=gb2312" />
          <title>无标题文档</title>
          <script language="JavaScript" type="text/javascript">
            var str = "这个是测试用的范例文字";
            var seq = 0;
            var second=1000; //间隔时间 1 秒钟
            function scroll() {
            msg = str.substring(0, seq+1);
            document.getElementByIdx_x_x('word').innerHTML = msg;
            seq++;
            if (seq >= str.length) seq = 0;
            }
          </script>
        </head>
        <body onload="setInterval('scroll()',second)">
          <div id="word"></div><br/><br/>
        </body>
      </html>
      <p>页面上显示时钟：</p>
      <p id="demo"></p>
      <button onclick="myStopFunction()">停止时钟</button>
      <script>
        var myVar=setInterval(function(){myTimer()},1000);
        function myTimer(){
        var d=new Date();
        var t=d.toLocaleTimeString();
        document.getElementById("demo").innerHTML=t;
        }
        function myStopFunction(){
        clearInterval(myVar);
        }
      </script>


    #+END_SRC
** 对象的模板 类 最新 ES6 语法
*** ES5 模拟类  
    #+begin_src javascript
      function PersonES5(p) {
          this.age = p.age;
          this.name = p.name;
          this.sex = p.sex;
      }

      PersonES5.prototype.showInfo = function() {
          console.log(this);
      };

      var person = new PersonES5({
          age:18,
          name:'tom',
          sex:'boy'
      });

      person.showInfo();
 #+end_src
*** ES6
    #+begin_src js
      class PersonES6 {
          constructor(p) {
              this.age = p.age;
              this.name = p.name;
              this.sex = p.sex;
          }
          showInfo() {
              console.log(this);
          }
      }


      var person = new PersonES6({
          age:18,
          name:'tom',
          sex:'boy'
      });

      person.showInfo();
    #+end_src
* javascript 语言
** Global objects
*** 基本对象值 
 数字，字符串，小数
  Infinity
  NaN
  undefined
  null literal
  globalThis
 
*** 基本功能
  eval()
  isFinite()
  isNaN()
  parseFloat()
  parseInt()
  decodeURI()
  decodeURIComponent()
  encodeURI()
  encodeURIComponent()
  escape() 
  unescape() 
 
*** 基本对象 Fundamental objects
  Object
  Function  new Function('a','b','return a+b');
  Boolean
  Symbol
  Error
  EvalError
  InternalError
  RangeError
  ReferenceError
  SyntaxError
  TypeError
  URIError

*** Numbers and dates
  Number
  Math
  Date

***  Text processing
  These objects represent strings and support manipulating them.

  String
  RegExp

***  Indexed collections
  These objects represent collections of data which are ordered by an index
  value. This includes (typed) arrays and array-like constructs.

  Array
  Int8Array
  Uint8Array
  Uint8ClampedArray
  Int16Array
  Uint16Array
  Int32Array
  Uint32Array
  Float32Array
  Float64Array

***  Keyed collections
  These objects represent collections which use keys; these contain elements
  which are iterable in the order of insertion.

  Map
  Set
  WeakMap
  WeakSet

***  Structured data
  These objects represent and interact with structured data buffers and data
  coded using JavaScript Object Notation (JSON).

  ArrayBuffer
  SharedArrayBuffer 
  Atomics 
  DataView
  JSON

***  Control abstraction objects
  Promise
  Generator
  GeneratorFunction
  AsyncFunction 

***  Reflection
  Reflect
  Proxy

*** Internationalization
  Additions to the ECMAScript core for language-sensitive functionalities.

  Intl
  Intl.Collator
  Intl.DateTimeFormat
  Intl.ListFormat
  Intl.NumberFormat
  Intl.PluralRules
  Intl.RelativeTimeFormat

*** WebAssembly
  WebAssembly
  WebAssembly.Module
  WebAssembly.Instance
  WebAssembly.Memory
  WebAssembly.Table
  WebAssembly.CompileError
  WebAssembly.LinkError
  WebAssembly.RuntimeError

*** Other
  arguments

** Statements
  This chapter documents all the JavaScript statements and declarations.

  For an alphabetical listing see the sidebar on the left.

*** Control flow
  Block
  A block statement is used to group zero or more statements. The block is delimited by a pair of curly brackets.
  break
  Terminates the current loop, switch, or label statement and transfers program control to the statement following the terminated statement.
  continue
  Terminates execution of the statements in the current iteration of the current or labeled loop, and continues execution of the loop with the next iteration.
  Empty
  An empty statement is used to provide no statement, although the JavaScript syntax would expect one.
  if...else
  Executes a statement if a specified condition is true. If the condition is false, another statement can be executed.
  switch
  Evaluates an expression, matching the expression's value to a case clause, and executes statements associated with that case.
  throw
  Throws a user-defined exception.
  try...catch
  Marks a block of statements to try, and specifies a response, should an exception be thrown.
 
*** Declarations
  var
  Declares a variable, optionally initializing it to a value.
  let
  Declares a block scope local variable, optionally initializing it to a value.
  const
  Declares a read-only named constant.
 
*** Functions and classes
  function
  Declares a function with the specified parameters.
  function*
  Generator Functions enable writing iterators more easily.
  async function
  Declares an async function with the specified parameters.
  return
  Specifies the value to be returned by a function.
  class
  Declares a class.
 
*** Iterations
  do...while
  Creates a loop that executes a specified statement until the test condition evaluates to false. The condition is evaluated after executing the statement, resulting in the specified statement executing at least once.
  for
  Creates a loop that consists of three optional expressions, enclosed in parentheses and separated by semicolons, followed by a statement executed in the loop.
    for each...in
  Iterates a specified variable over all values of object's properties. For each distinct property, a specified statement is executed.
  for...in
  Iterates over the enumerable properties of an object, in arbitrary order. For each distinct property, statements can be executed.
  for...of
  Iterates over iterable objects (including arrays, array-like objects, iterators and generators), invoking a custom iteration hook with statements to be executed for the value of each distinct property.
  for await...of
  Iterates over async iterable objects, array-like objects, iterators and generators, invoking a custom iteration hook with statements to be executed for the value of each distinct property.
  while
  Creates a loop that executes a specified statement as long as the test condition evaluates to true. The condition is evaluated before executing the statement.
 
*** Others
  debugger
  Invokes any available debugging functionality. If no debugging functionality is available, this statement has no effect.
  export
  Used to export functions to make them available for imports in external modules, and other scripts.
  import
  Used to import functions exported from an external module, another script.
  import.meta
  A meta-property exposing context-specific metadata to a JavaScript module.
  label
  Provides a statement with an identifier that you can refer to using a break or continue statement.
   with
  Extends the scope chain for a statement.
 
** Expressions and operators
  This chapter documents all the JavaScript expressions and operators. 

  For an alphabetical listing see the sidebar on the left.

 
*** Primary expressions
   Basic keywords and general expressions in JavaScript.

   this
   The this keyword refers to a special property of an execution context.
   function
   The function keyword defines a function expression.
   class
   The class keyword defines a class expression.
   function*
   The function* keyword defines a generator function expression.
   yield
   Pause and resume a generator function.
   yield*
   Delegate to another generator function or iterable object.
   async function
   The async function defines an async function expression.
   await
   Pause and resume an async function and wait for the promise's resolution/rejection.
   []
   Array initializer/literal syntax.
   {}
   Object initializer/literal syntax.
   /ab+c/i
   Regular expression literal syntax.
   ( )
   Grouping operator.
  
*** Left-hand-side expressions
   Left values are the destination of an assignment.

   Property accessors
   Member operators provide access to a property or method of an object
   (object.property and object["property"]).
   new
   The new operator creates an instance of a constructor.
   new.target
   In constructors, new.target refers to the constructor that was invoked by new.
   super
   The super keyword calls the parent constructor.
   ...obj
   Spread syntax allows an expression to be expanded in places where multiple arguments (for function calls) or multiple elements (for array literals) are expected.
  
*** Increment and decrement
   Postfix/prefix increment and postfix/prefix decrement operators.

   A++
   Postfix increment operator.
   A--
   Postfix decrement operator.
   ++A
   Prefix increment operator.
   --A
   Prefix decrement operator.
  
*** Unary operators
   A unary operation is operation with only one operand.

   delete
   The delete operator deletes a property from an object.
   void
   The void operator discards an expression's return value.
   typeof
   The typeof operator determines the type of a given object.
   +
   The unary plus operator converts its operand to Number type.
   -
   The unary negation operator converts its operand to Number type and then negates it.
   ~
   Bitwise NOT operator.
   !
   Logical NOT operator.
  
*** Arithmetic operators
   Arithmetic operators take numerical values (either literals or variables) as their operands and return a single numerical value.

   +
   Addition operator.
   -
   Subtraction operator.
   /
   Division operator.
   *
   Multiplication operator.
   %
   Remainder operator.
   **
   Exponentiation operator.
  
*** Relational operators
   A comparison operator compares its operands and returns a Boolean value based on whether the comparison is true.

   in
   The in operator determines whether an object has a given property.
   instanceof
   The instanceof operator determines whether an object is an instance of another object.
   <
   Less than operator.
   >
   Greater than operator.
   <=
   Less than or equal operator.
   >=
   Greater than or equal operator.
   Note: => is not an operator, but the notation for Arrow functions.

  
*** Equality operators
   The result of evaluating an equality operator is always of type Boolean based on whether the comparison is true.

   ==
   Equality operator.
   !=
   Inequality operator.
   ===
   Identity operator.
   !==
   Nonidentity operator.
  
*** Bitwise shift operators
   Operations to shift all bits of the operand.

   <<
   Bitwise left shift operator.
   >>
   Bitwise right shift operator.
   >>>
   Bitwise unsigned right shift operator.
  
*** Binary bitwise operators
   Bitwise operators treat their operands as a set of 32 bits (zeros and ones) and return standard JavaScript numerical values.

   &
   Bitwise AND.
   |
   Bitwise OR.
   ^
   Bitwise XOR.
  
*** Binary logical operators
   Logical operators are typically used with boolean (logical) values, and when they are, they return a boolean value.

   &&
   Logical AND.
   ||
   Logical OR.
  
*** Conditional (ternary) operator
   (condition ? ifTrue : ifFalse)
   The conditional operator returns one of two values based on the logical value of the condition.

*** Assignment operators
   An assignment operator assigns a value to its left operand based on the value of its right operand.

   =
   Assignment operator.
   *=
   Multiplication assignment.
   /=
   Division assignment.
   %=
   Remainder assignment.
   +=
   Addition assignment.
   -=
   Subtraction assignment
   <<=
   Left shift assignment.
   >>=
   Right shift assignment.
   >>>=
   Unsigned right shift assignment.
   &=
   Bitwise AND assignment.
   ^=
   Bitwise XOR assignment.
   |=
   Bitwise OR assignment.
   [a, b] = [1, 2]
   {a, b} = {a:1, b:2}
   Destructuring assignment allows you to assign the properties of an array or object to variables using syntax that looks similar to array or object literals.
* DOM (js 解析的对象)
  处理可扩展标志语言的标准编程接口
*** window 对象
**** 对象状态处理
    | 窗口是否已被关闭               | closed      |
    | 文档显示区高度                 | innerHeight |
    | 文档显示区宽度                 | innerwidth  |
    | 设置或返回框架数量             | length      |
    | 设置或返回窗口的名称           | name        |
    | 返回窗口的外部高度           | outerheight |
    | 返回窗口的外部宽度           | outerwidth  |
    | 返回父窗口                   | parent      |
    | 返回对当前窗口的引用           | self        |
    | 设置窗口状态栏的文本           | status      |
    | 返回最顶层的先辈窗口           | top         |
    | 窗口的左上角在屏幕上的的 y 坐标 | screenY     |
**** 对象操作
   | 显示带有一段消息和一个确认按钮的警告框           | alert             |
   | 把键盘焦点从顶层窗口移开                         | blur              |
   | 取消由 setInterval() 设置的 timeout              | clearInterval     |
   | 取消由 setTimeout() 方法设置的 timeout           | clearTimeout      |
   | 关闭浏览器窗口                                   | close             |
   | 显示带有一段消息以及确认按钮和取消按钮的对话框   | confirm           |
   | 创建一个 pop-up 窗口                             | createPopup       |
   | 把键盘焦点给予一个窗口                           | focus             |
   | 可相对窗口的当前坐标把它移动指定的像素           | moveBy            |
   | 把窗口的左上角移动到一个指定的坐标               | moveTo            |
   | 打开一个新的浏览器窗口或查找一个已命名的窗口     | open(link,'blank) |
   | 访问打开的原窗口                                 | opener            |
   | 打印当前窗口的内容(打印机）                      | print             |
   | 显示可提示用户输入的对话框                       | prompt            |
   | 按照指定的像素调整窗口的大小                     | resizeBy          |
   | 把窗口的大小调整到指定的宽度和高度               | resizeTo          |
   | 按照指定的像素值来滚动内容                       | scrollBy          |
   | 把内容滚动到指定的坐标                           | scrollTo          |
   | 按照指定的周期（以毫秒计）来调用函数或计算表达式 | setInterval       |
   | 在指定的毫秒数后调用函数或计算表达式             | setTimeout        |
*** 浏览器 navigator
**** 属性
     | 代码名                | appCodeName     |
     | 次级版本              | appMinorVersion |
     | 名称                  | appName         |
     | 平台和版本信息        | appVersion      |
     | 语言                   | browserLanguage |
     | 是否启用 cookie     | cookieEnabled   |
     | CPU 等级             | cpuClass        |
     | 是否处于脱机模式       | onLine          |
     | 操作系统               | platform        |
     | 默认语言               | systemLanguage  |
     |                        | language        |
     | user-agent 头部的值    | userAgent       |
     | 返回 OS 的自然语言设置 | userLanguage    |
**** 方法
     javaEnabled() 	      规定浏览器是否启用 Java
     taintEnabled() 	    规定浏览器是否启用数据污点 (data tainting)
*** 屏幕 screen
**** 状态
     availHeight 	     返回显示屏幕的高度 (除 Windows 任务栏之外)
     availWidth 	     返回显示屏幕的宽度 (除 Windows 任务栏之外) 
     bufferDepth 	     设置或返回在 off-screen bitmap buffer 中调色板的比特深度
     colorDepth 	     返回目标设备或缓冲器上的调色板的比特深度
     deviceYDPI 	     返回显示屏幕的每英寸垂直点数 
     height 	         返回显示屏幕的高度 
     pixelDepth 	     返回显示屏幕的颜色分辨率（比特每像素）
     width 	           返回显示器屏幕的宽度 
*** history
**** 属性
     length            返回浏览器历史列表中的 URL 数量
**** 方法
     back() 	          加载 history 列表中的前一个 URL 	
     forward() 	        加载 history 列表中的下一个 URL 
     go() 	            加载 history 列表中的某个具体页面 [Num|URL] e: -1 前一个页面	
*** location 地址
**** 属性
     hash 	            设置或返回从井号 (#) 开始的 URL（锚）
     host 	            设置或返回主机名和当前 URL 的端口号 
     hostname 	        设置或返回当前 URL 的主机名 
     href 	            设置或返回完整的 URL
     pathname 	        设置或返回当前 URL 的路径部分 
     port 	            设置或返回当前 URL 的端口号
     protocol 	        设置或返回当前 URL 的协议 
     search           	设置或返回从问号 (?) 开始的 URL（查询部分）
**** 方法
     assign() 	        加载新的文档
     reload() 	        重新加载当前文档
     replace() 	        用新的文档替换当前文档 
*** document  
**** 属性
     body    	          提供对 <body> 元素的直接访问对于定义了框架集的文档，该属性引用最外层的 <frameset> 	  	  	  	 
     cookie 	          设置或返回与当前文档有关的所有 cookie
     domain 	          返回当前文档的域名 	
     lastModified 	    返回文档被最后修改的日期和时间 该值来自于 Last-Modified HTTP 头部，它是由 Web 服务器发送的可选项	
     referrer 	        返回载入当前文档的文档的 URL
     title 	            返回当前文档的标题 
     URL 	              返回当前文档的 URL 
**** 方法
     close() 	             关闭用 document.open() 方法打开的输出流，并显示选定的数据 
     getElementById() 	   返回对拥有指定 id 的第一个对象的引用
     getElementsByName()   返回带有指定名称的对象集合 	
     getElementsByTagName()返回带有指定标签名的对象集合
     getElementsByClassName()返回带有指定 class 的对象集合
     open() 	             打开一个流，以收集来自任何 document.write() 或 document.writeln() 方法的输出
     write()    	         向文档写 HTML 表达式 或 JavaScript 代码 
     writeln() 	           等同于 write() 方法，不同的是在每个表达式之后写一个换行符 
*** Style
    element.style.属性=属性值 
**** 属性
***** 背景
      background 	          在一行中设置所有的背景属性 
      backgroundAttachment 	设置背景图像是否固定或随页面滚动 
      backgroundColor 	    设置元素的背景颜色 
      backgroundImage 	    设置元素的背景图像 
      backgroundPosition 	  设置背景图像的起始位置 
      backgroundPositionX 	设置 backgroundPosition 属性的 X 坐标 
      backgroundPositionY 	设置 backgroundPosition 属性的 Y 坐标 
      backgroundRepeat 	    设置是否及如何重复背景图像
***** 边框和边距
      border             	在一行设置四个边框的所有属性 	
      borderBottom  	    在一行设置底边框的所有属性 
      borderBottomColor 	设置底边框的颜色 	
      borderBottomStyle 	设置底边框的样式 	
      borderBottomWidth 	设置底边框的宽度 	
      borderColor     	  设置所有四个边框的颜色 (可设置四种颜色) 	
      borderLeft       	  在一行设置左边框的所有属性 
      borderLeftColor 	  设置左边框的颜色 	
      borderLeftStyle 	  设置左边框的样式 	
      borderLeftWidth 	  设置左边框的宽度 	
      borderRight 	      在一行设置右边框的所有属性
      borderRightColor 	  设置右边框的颜色 	
      borderRightStyle 	  设置右边框的样式 	
      borderRightWidth 	  设置右边框的宽度 	
      borderStyle 	      设置所有四个边框的样式 (可设置四种样式) 
      borderTop 	        在一行设置顶边框的所有属性 
      borderTopColor 	    设置顶边框的颜色 		
      borderTopStyle 	    设置顶边框的样式 		
      borderTopWidth 	    设置顶边框的宽度 		
      borderWidth 	      设置所有四条边框的宽度 (可设置四种宽度) 
      margin 	            设置元素的边距 (可设置四个值)
      marginBottom        设置元素的底边距
      marginLeft 	        设置元素的左边距 	
      marginRight 	      设置元素的右边据
      marginTop 	        设置元素的顶边距 	
      outline 	          在一行设置所有的 outline 属性 
      outlineColor 	      设置围绕元素的轮廓颜色 	
      outlineStyle 	      设置围绕元素的轮廓样式 	
      outlineWidth 	      设置围绕元素的轮廓宽度 	
      padding 	          设置元素的填充 (可设置四个值)
      paddingBottom       设置元素的下填充
      paddingLeft 	      设置元素的左填充
      paddingRight 	      设置元素的右填充
      paddingTop 	        设置元素的顶填充 	
***** 布局
      clear    	        设置在元素的哪边不允许其他的浮动元素 	
      clip      	      设置元素的形状 	
      content 	        设置元信息 	
      counterIncrement 	设置其后是正数的计数器名称的列表其中整数指示每当元素出现时计数器的增量默认是 1
      counterReset 	    设置其后是正数的计数器名称的列表其中整数指示每当元素出现时计数器被设置的值默认是 0
      cssFloat 	        设置图像或文本将出现（浮动）在另一元素中的何处 	
      cursor   	        设置显示的指针类型 
      direction 	      设置元素的文本方向 	
      display 	        设置元素如何被显示 	inherit 父的属性继承
      height 	          设置元素的高度 
      markerOffset 	    设置 marker box 的 principal box 距离其最近的边框边缘的距离
      marks 	          设置是否 cross marks 或 crop marks 应仅仅被呈现于 page box 边缘之外 	
      maxHeight 	      设置元素的最大高度 	
      maxWidth 	        设置元素的最大宽度 	
      minHeight 	      设置元素的最小高度 	
      minWidth 	        设置元素的最小宽度 	
****** overflow 	规定如何处理不适合元素盒的内容 	
       overflow-x:      hidden;隐藏水平滚动条
       verticalAlign 	  设置对元素中的内容进行垂直排列 
       visibility 	    设置元素是否可见 
       width 	          设置元素的宽度
***** 列表
      listStyle 	在一行设置列表的所有属性 
      listStyleImage 	把图像设置为列表项标记 
      listStylePosition 改变列表项标记的位置 	
      listStyleType 	设置列表项标记的类型
***** 定位
      bottom 	设置元素的底边缘距离父元素底边缘的之上或之下的距离 	
      left       	置元素的左边缘距离父元素左边缘的左边或右边的距离 	
      position 	把元素放置在 static, relative, absolute 或 fixed 的位置 	
      right 	            置元素的右边缘距离父元素右边缘的左边或右边的距离 	
      top 	            设置元素的顶边缘距离父元素顶边缘的之上或之下的距离 	
      zIndex 	设置元素的堆叠次序
***** 文本
      color 	设置文本的颜色 
      font 	在一行设置所有的字体属性 
      fontFamily 	设置元素的字体系列
      fontSize 	设置元素的字体大小
      fontSizeAdjust 	设置/调整文本的尺寸 
      fontStretch 	设置如何紧缩或伸展字体
      fontStyle 	设置元素的字体样式 
      fontVariant 	用小型大写字母字体来显示文本 
      fontWeight 	设置字体的粗细 
      letterSpacing 	设置字符间距 
      lineHeight 	设置行间距 
      quotes 	设置在文本中使用哪种引号 
      textAlign 	排列文本 
      textDecoration 	设置文本的修饰 
      textIndent 	缩紧首行的文本 
      textShadow 	设置文本的阴影效果
      textTransform 	对文本设置大写效果 
      whiteSpace 	设置如何设置文本中的折行和空白符 	
      wordSpacing 	设置文本中的词间距 
***** Table 
      borderCollapse 	设置表格边框是否合并为单边框，或者像在标准的 HTML 中那样分离 
      borderSpacing 	设置分隔单元格边框的距离 
      captionSide 	设置表格标题的位置 	
      emptyCells 	设置是否显示表格中的空单元格
      tableLayout 	设置用来显示表格单元格、行以及列的算法
*** node
**** 节点属性
     innerHTML: 获取元素内容,很多东西
     nodeName 规定节点的名称
     nodeValue 规定节点的值 (文本节点有值)
***** nodeType 返回节点的类型 nodeType 是只读的
      #+BEGIN_SRC 
      元素 	1
      属性 	2
      文本 	3
      注释 	8
      #+END_SRC
      : 通过使用一个元素节点的 parentNode、firstChild 以及 lastChild 属性
**** 修改
     var para=document.createElement("p");
     var node=document.createTextNode("This is new.");
     para.appendChild(node);
**** 节点元素
***** 创建新的 HTML 元素 - appendChild()您首先必须创建该元素，然后把它追加到已有的元素上
***** 创建新的 HTML 元素 - insertBefore()
***** 删除已有的 HTML 元素
      var child=document.getElementById("p1");
      child.parentNode.removeChild(child);
***** 替换 HTML 元素
      : 如需替换 HTML DOM 中的元素，请使用 replaceChild() 方法：
      #+BEGIN_SRC 
      var parent=document.getElementById("div1");
      var child=document.getElementById("p1");
      parent.replaceChild(para,child);
      #+END_SRC
*** 事件
**** window 事件属性
     onload    页面结束加载之后触发   
     onresize  当浏览器窗口被调整大小时触发 
**** FORM 事件
     onselect      script 在元素中文本被选中后触发            
     onsubmit      script 在提交表单时触发                   
**** 键盘事件
     onkeydown  script 在用户按下按键时触发
     onkeypress script 在用户敲击按钮时触发
     onkeyup    script 当用户释放按键时触发
**** Mouse 事件
     onclick
     ondblclick
     onmousedown
     onscroll
**** Media 事件
     onabort
     onplay
**** onmousedown、onmouseup 以及 onclick 事件
* web 移动开发最佳实践
** 避免使用全局变量和函数
   var myApp = {
   lang: "en",
   debug: true,
   };
 
   myApp.setLang = function (arg) {
   this.lang = arg;
   }
** 高效的使用 try catch 语句
   var object = ['foo', 'bar'], i;
   try {
   for (i = 0; i < object.length; i++) {
   // do something
   }
   } catch (e) {
   // handle exception
   }
** 使用赋值运算来连接字符串
   str += "x";
   str += "y";
** 避免使用 eval()方法
** 使用事件委托
   在处理 DOM 事件的时候，你可以仅对一个父元素绑定一个事件而不是每一个子元素。
   这种技术即事件委托，它利用事件冒泡来分配事件处理程序，可以提高脚本的性能

   <a href="javascript:handleClick();">Click</a>
   <button id="btn1" onclick="handleClick();">One</button>
   <button id="btn2" onclick="handleClick();">Two</button>
   为了提高代码的性能，我们可以加一个 div 父元素，事件会向上冒泡，直到被处理。事件对象是触发事件的元素，我们可以根据它的 id 属性来判断是哪一个元素触发了事件：
 

   <div id="btngroup">
   <button id="btn1">One</button>
   <button id="btn2">Two</button>
   </div>
   document.getElementById("btngroup").addEventListener("click", function (event) {
   switch (event.srcElement.id) {　　//firefox 下为 event.target.id
   case "btn1":
   handleClick();
   break;
   default:
   handleClick();
   }
   }, false); // type, listener, useCapture (true=beginning, false=end)
** 尽量减少 DOM 操作
   　　DOM 是一个包含了很多信息的复杂的 API，因此即使是很小的操作可能会花费较长的时间执行（如果要重绘页面的话）。为了提高程序性能，应尽量减少 DOM 操作，这里有一些建议：
***  1.减少 DOM 的数目

    DOM 节点的数目会影响与它相关的所有操作，要尽量使 DOM 树小一些：

    避免多余的标记和嵌套的表格
    元素数尽量控制在 500 个以内（document.getElementsByTagName('*').length）
*** 2.缓存已经访问过的节点
    当访问过一个 DOM 元素后，就应该把它缓存起来，因为你的程序往往要重复访问某个对象的，例如：

    for (var i = 0; i < document.images.length; i++) {
    document.images[i].src = "blank.gif";
    }
    以上例子中，docum.images 对象被访问了多次，这并不高效，因为每一次循环中，浏览器都要查找这个元素两次：第一次读取它的长度，第二次改变相应的 src 值。更好的做法是先把这个对象存储起来：

    var imgs = document.images;
    for (var i = 0; i < imgs.length; i++) {　　//当然也可以把 imgs.length 提前算出来，这里不是重点
    imgs[i].src = "blank.gif";
    }
** 减少页面重绘
 　　在控制 DOM 元素数目的同时，你还可以通过减少修改元素（减少页面的重绘）的方法来提高性能。重绘有两种方式：repaint、reflow。

 1.repaint，也叫 redraw，即改变了元素的视觉效果，但是不影响它的排版（比如改变背景颜色）
 2.reflow，会影响部分或者全部页面的排版，浏览器不仅要计算该元素的位置，还要计算它影响到的周围的元素位置

 当你要改变页面布局的时候，reflow 就发生了，主要有如下情况：

 增加或删除 DOM 节点
 改变元素的位置
 改变元素的尺寸（如 margin，padding，border，font，width，height 等）
 调整浏览器窗口的尺寸
 增加或删除 css
 改变内容（如用户输入表单）
 命中 css 选择器（如 hover）
 更改了 class 属性
 利用脚本更改了 DOM
 检索一个必须被计算的尺寸（如 offsetWidth，offsetHeight）
 设置了一个 css 属性
 这里有一些减少页面重绘的建议：

 css 的建议：

 改变 class 属性时应尽量少的影响到周围的元素节点
 避免声明多个内联的样式（把多个样式放在一个外部文件里）
 有动画的元素使用绝对定位，这样不会影响其他元素
 避免使用 table 来排版，如果需要使用保存数据，那么要固定排版（table-layout:fixed）
 js 的建议：

 缓存计算过的样式
 对于固定的样式，改变 class 的名词而不是样式；对于动态的样式，改变 cssText 属性：

 // bad - changing the stle - accessing DOM multiple times
 var myElement = document.getElementById('mydiv');
 myElement.style.borderLeft = '2px';
 myElement.style.borderRight = '3px';
 myElement.style.padding = '5px';
 
 // good - use cssText and modify DOM once
 var myElement = document.getElementById('mydiv');
 myElement.style.cssText = 'border-left: 2px; border-right: 3px; padding: 5px;';

 当你要对一个 DOM 元素做出很多修改时，可以先进行一些‘预处理’，批量修改后再替换原始的元素
 创建一个副本（cloneNode()），对这个副本进行更新，然后替代原来的节点

 // slower - multiple reflows
 var list = ['foo', 'bar', 'baz'], elem, contents;
 for (var i = 0; i < list.length; i++) {
     elem = document.createElement('div');
     content = document.createTextNode(list[i]);
     elem.appendChild(content);
     document.body.appendChild(elem); // multiple reflows
 }
             
 // faster - create a copy
 var orig = document.getElementById('container'),
     clone = orig.cloneNode(true), // create a copy
     list = ['foo', 'bar', 'baz'], elem, contents;
 clone.setAttribute('width', '50%');

 修改一个不可见的元素，可以先让其不可见（display:none），修改完成后，再恢复其可见（display:block），这样就会减少 reflow 的次数

 // slower
 var subElem = document.createElement('div'),
     elem = document.getElementById('animated');
 elem.appendChild(subElem);
 elem.style.width = '320px';
             
 // faster
 var subElem = document.createElement('div'),
     elem = document.getElementById('animated');
 elem.style.display = 'none'; // will not be repainted
 elem.appendChild(subElem);
 elem.style.width = '320px';
 elem.style.display = 'block';

 创建一个文档片段（使用 DocumentFragment()），修改完成后，再把它追加到原始文档中

 // slower
 var list = ['foo', 'bar', 'baz'], elem, contents;
 for (var i = 0; i < list.length; i++) {
     elem = document.createElement('div');
     content = document.createTextNode(list[i]);
     elem.appendChild(content);
     document.body.appendChild(elem); // multiple reflows
 }
             
 // faster
 var fragment = document.createDocumentFragment(),
     list = ['foo', 'bar', 'baz'], elem, contents;
 for (var i = 0; i < list.length; i++) {
     elem = document.createElement('div');
     content = document.createTextNode(list[i]);
     fragment.appendChild(content);
 }
 document.body.appendChild(fragment); // one reflow

