* linux 内核
** 启动过程
*** 内核的引导
    首先读入 /boot 目录下的内核文件
*** 运行 init
    配置文件： /etc/inittab, /etc/init/*.conf
*** 系统初始化
    在 init 的配置文件中有这么一行：si::sysinit:/etc/rc.d/rc.sysinit　它调用执行了/etc/rc.d/rc.sysinit
    l5:5:wait:/etc/rc.d/rc 5
    这一行表示以 5 为参数运行/etc/rc.d/rc，/etc/rc.d/rc 是一个 Shell 脚本，它接受 5 作为参数，去执行/etc/rc.d/rc5.d/目录下的所有的 rc 启动脚本，/etc/rc.d/rc5.d/目录中的这些
    启动脚本实际上都是一些连接文件，而不是真正的 rc 启动脚本，真正的 rc 启动脚本实际上都是放在/etc/rc.d/init.d/目录下。
*** 建立终端 
    1:2345:respawn:/sbin/mingetty tty1
    2:2345:respawn:/sbin/mingetty tty2
    3:2345:respawn:/sbin/mingetty tty3
    4:2345:respawn:/sbin/mingetty tty4
    5:2345:respawn:/sbin/mingetty tty5
    6:2345:respawn:/sbin/mingetty tty6
*** 用户登录系统
    （1）命令行登录
    （2）ssh 登录
    （3）图形界面登录
*** 图形模式与文字模式切换
 Ctrl + Alt + F1 ~ F6
*** 关机
    正确的关机流程为：sync > shutdown > reboot > halt
    关机指令为：shutdown -h +10 10 分钟后
    最后总结一下，不管是重启系统还是关闭系统，首先要运行 sync 命令，把内存中的数据写到磁盘中。
** 系统目录
 /bin：
 bin 是 Binary 的缩写, 这个目录存放着最经常使用的命令。
 /boot：
 这里存放的是启动 Linux 时使用的一些核心文件，包括一些连接文件以及镜像文件。
 /dev：
 dev 是 Device(设备)的缩写, 该目录下存放的是 Linux 的外部设备，在 Linux 中访问设备的方式和访问文件的方式是相同的。
 /etc：
 这个目录用来存放所有的系统管理所需要的配置文件和子目录。
 /home：
 用户的主目录，在 Linux 中，每个用户都有一个自己的目录，一般该目录名是以用户的账号命名的。
 /lib：
 这个目录里存放着系统最基本的动态连接共享库，其作用类似于 Windows 里的 DLL 文件。几乎所有的应用程序都需要用到这些共享库。
 /lost+found：
 这个目录一般情况下是空的，当系统非法关机后，这里就存放了一些文件。
 /media：
 linux 系统会自动识别一些设备，例如 U 盘、光驱等等，当识别后，linux 会把识别的设备挂载到这个目录下。
 /mnt：
 系统提供该目录是为了让用户临时挂载别的文件系统的，我们可以将光驱挂载在/mnt/上，然后进入该目录就可以查看光驱里的内容了。
 /opt：
  这是给主机额外安装软件所摆放的目录。比如你安装一个 ORACLE 数据库则就可以放到这个目录下。默认是空的。
 /proc：
 这个目录是一个虚拟的目录，它是系统内存的映射，我们可以通过直接访问这个目录来获取系统信息。
 这个目录的内容不在硬盘上而是在内存里，我们也可以直接修改里面的某些文件，比如可以通过下面的命令来屏蔽主机的 ping 命令，使别人无法 ping 你的机器：
 /root：
 该目录为系统管理员，也称作超级权限者的用户主目录。
 /sbin：
 s 就是 Super User 的意思，这里存放的是系统管理员使用的系统管理程序。
 /selinux：
  这个目录是 Redhat/CentOS 所特有的目录，Selinux 是一个安全机制，类似于 windows 的防火墙，但是这套机制比较复杂，这个目录就是存放 selinux 相关的文件的。
 /srv：
  该目录存放一些服务启动之后需要提取的数据。
 /sys：
  这是 linux2.6 内核的一个很大的变化。该目录下安装了 2.6 内核中新出现的一个文件系统 sysfs。
 sysfs 文件系统集成了下面 3 种文件系统的信息：针对进程信息的 proc 文件系统、针对设备的 devfs 文件系统以及针对伪终端的 devpts 文件系统。
 该文件系统是内核设备树的一个直观反映。
 当一个内核对象被创建的时候，对应的文件和目录也在内核对象子系统中被创建。
 /tmp：
 这个目录是用来存放一些临时文件的。
 /usr：
  这是一个非常重要的目录，用户的很多应用程序和文件都放在这个目录下，类似与 windows 下的 program files 目录。
 /usr/bin：
 系统用户使用的应用程序。
 /usr/sbin：
 超级用户使用的比较高级的管理程序和系统守护程序。
 /usr/src：内核源代码默认的放置目录。
 /var：
 这个目录中存放着在不断扩充着的东西，我们习惯将那些经常被修改的目录放在这个目录下。包括各种日志文件。
** 忘记密码
 3 秒之内要按一下回车，出现如下界面
 然后输入 e
 在 第二行最后边输入 single，有一个空格。具体方法为按向下尖头移动到第二行，按"e"进入编辑模式
 在后边加上 single 回车
 最后按"b"启动，启动后就进入了单用户模式了
 此时已经进入到单用户模式了，你可以更改 root 密码了。更密码的命令为 passwd
** linux 的配置信息？
   $ cat /proc/cpuinfo
   $ cat /proc/meminfo
   $ cat /proc/net/sockstat
** 模块 
    rmmod 从运行的内核中移除指定的内核模块
    insmod 将给定的模块加载到内核中
    lsmod 显示已载入系统的模块
** 套接字
   服务器
 1.服务器创建一个套接字资源，并起个名字
 2.客户端连接到这个名字的套接字  
 3.服务器接听队列, 处理, 处理时新建一个套接字，释放原套接字给新的连接

 客户端
 1.创建一个未命名套接字，调用 connect 与服务器命名套接字连接
* linux 环境下 c 编程
** Managing Text-Based Screens with curse
      Compiling with curses                          
      Concepts                                       
      Try It Out—A Simple curses Program    
      Initialization and Termination                 
      Output to the Screen                           
      Reading from the Screen                        
      Clearing the Screen                            
      Moving the Cursor                              
      Character Attributes                           
      Try It Out—Moving, Inserting, and Attr
      The Keyboard                                   
      Keyboard Modes                              
      Keyboard Input                              
      Try It Out—Keyboard Modes and Input   
      Windows                                        
      The WINDOW Structure                        
      Generalized Functions                       
      Moving and Updating a Window                
      Try It Out—Multiple Windows           
      Optimizing Screen Refreshes                 
      Subwindows                                     
      Try It Out—Subwindows                 
      The Keypad                                     
      Try It Out—Using the Keypad           
      Color                                          
      Try It Out—-Colors                    
      Redefining Colors                           
      Pads                                           
      Try It Out—Using a Pad                
      The CD Collection Application                  
      Try It Out—A New CD Collection Applica
      Try It Out—Looking at main            
 
      Try It Out—The Menu                    
      Try It Out—Database File Manipulation 
      Try It Out—Querying the CD Database   
      Summary                                        
** Data Management                       
      Managing Memory                                
      Simple Memory Allocation                    
      Try It Out—Simple Memory Allocation   
                                                 
      Contents
      Allocating Lots of Memory                  
      Try It Out—Asking for All Physical M
      Try It Out—Available Memory         
      Abusing Memory                             
      Try It Out—Abuse Your Memory        
      The Null Pointer                           
      Try It Out—Accessing a Null Pointer 
      Freeing Memory                             
      Try It Out—Freeing Memory           
      Other Memory Allocation Functions          
      File Locking                                  
      Creating Lock Files                        
      Try It Out—Creating a Lock File     
      Try It Out—Cooperative Lock Files   
      Locking Regions                            
      The F_GETLK Command                     
      The F_SETLK Command                     
      The F_SETLKW Command                    
      Use of read and write with Locking         
      Try It Out—Locking a File with fcntl
      Try It Out—Testing Locks on a File  
      Competing Locks                            
      Try It Out—Competing Locks          
      Other Lock Commands                        
      Deadlocks                                  
      Databases                                     
      The dbm Database                           
      Introduction to dbm                     
      Getting dbm                             
      Troubleshooting and Reinstalling dbm    
      The dbm Routines                           
      dbm Access Functions                       
      dbm_open                                
      dbm_store                               
      dbm_fetch                               
      dbm_close                               
      Try It Out—A Simple dbm Database    
      Additional dbm Functions                   
      dbm_delete                              
      dbm_error                               
      xiv
      Co
      dbm_clearerr                              
      dbm_firstkey and dbm_nextkey              
      Try It Out—Retrieving and Deleting     
      The CD Application                             
      Updating the Design                          
      The CD Database Application Using dbm        
      Try It Out—cd_data.h                   
      Try It Out—app_ui.c                    
      Try It Out—cd_access.c                 
      Summary                                        
** MySQL                                 
      Installation                                   
      Precompiled Packages                         
      Post-Install Configuration                   
      Post-Installation Troubleshooting            
      MySQL Administration                           
      Commands                                     
      myisamchk                                 
      mysql                                     
      mysqladmin                                
      mysqlbug                                  
      mysqlimport                               
      mysqlshow                                 
      Creating Users and Giving Them Permissions   
      grant                                     
      revoke                                    
      Passwords                                    
      Creating a Database                          
      Data Types                                   
      Boolean                                   
      Character                                 
      Number                                    
      Temporal                                  
      Creating a Table                             
      Graphical Tools                              
      Accessing MySQL Data from C                    
      Connection Routines                          
      Error Handling                               
                                                 
      Contents
      Executing SQL Statements                     
      SQL Statements That Return No Data        
      Discovering What You Inserted             
      Try It Out                            
      Try It Out                            
      Statements That Return Data               
      Processing Returned Data                  
      Miscellaneous Functions                      
      The CD Database Application                    
      Creating the Tables                          
      Adding Some Data                             
      Try It Out                            
      Accessing the Application Data from C        
      Interface Definition                      
      Test Application Interface                
      Implementing the Interface                
      Summary                                        
** Development Tools                     
      Problems of Multiple Source Files              
      The make Command and Makefiles                 
      The Syntax of Makefiles                      
      Options and Parameters to make               
      Dependencies                              
      Rules                                     
      Try It Out—A Simple Makefile          
      Comments in a Makefile                       
      Macros in a Makefile                         
      Try It Out—A Makefile with Macros     
      Multiple Targets                             
      Try It Out—Multiple Targets           
      Built-in Rules                               
      Suffix and Pattern Rules                     
      Managing Libraries with make                 
      Try It Out—Managing a Library         
      Advanced Topic: Makefiles and Subdirectories 
      GNU make and gcc                             
      Try It Out—gcc -MM                    
      Source Code Control                            
      RCS                                          
      The rcs Command                           
      The ci Command                            
      xvi
      Cont
      The co Command                            
      The rlog Command                          
      The rcsdiff Command                       
      Identifying Revisions                     
      Try It Out—GNU make with RCS           
      The ident Command                         
      Try It Out—ident                       
      SCCS                                         
      Comparing RCS and SCCS                       
      CVS                                          
      Using CVS Locally                         
      Accessing CVS over a Network              
      gCVS                                         
      BitKeeper                                    
      Writing a Manual Page                          
      Distributing Software                          
      The patch Program                            
      Other Distribution Utilities                 
      RPM Packages                                   
      Working with RPM Package Files               
      Installing RPM Packages                      
      Building RPM Packages                        
      Gathering the Software                    
      Creating an RPM Spec File                 
      Building an RPM Package with rpmbuild     
      Other Package Formats                          
      Development Environments                       
      xwpe                                         
      C-Forge                                      
      KDevelop                                     
      Other Environments                           
      Summary                                        
** Debugging                            
      Types of Errors                                
      General Debugging Techniques                   
      A Program with Bugs                          
      Code Inspection                              
      Instrumentation                              
      Try It Out—Debug Information           
      Debugging without Recompiling             
      Controlled Execution                         
                                                 
      Contents
      Debugging with gdb                             
      Starting gdb                               
      Running a Program                          
      Stack Trace                                
      Examining Variables                        
      Listing the Program                        
      Setting Breakpoints                        
      Patching with the Debugger                 
      Learning More about gdb                    
      More Debugging Tools                           
      Lint: Removing the Fluff from Your Programs
      Function Call Tools                        
      ctags                                   
      cxref                                   
      cflow                                   
      Execution Profiling with prof/gprof        
      Assertions                                     
      Try It Out—assert                   
      Memory Debugging                               
      ElectricFence                              
      Try It Out—ElectricFence            
      valgrind                                   
      Try It Out—valgrind                 
      Summary                                        
** Processes and Signals                
      What Is a Process?                             
      Process Structure                              
      The Process Table                          
      Viewing Processes                          
      System Processes                           
      Process Scheduling                         
      Starting New Processes                         
      Try It Out—system                   
      Replacing a Process Image               
      Try It Out—execlp                   
      Duplicating a Process Image             
      Try It Out—fork                     
      Waiting for a Process                      
      Try It Out—wait                     
      Zombie Processes                           
      Try It Out—Zombies                  
      xviii
                                                 
      Input and Output Redirection                 
      Try It Out—Redirection                 
      Threads                                      
      Signals                                        
      Try It Out—Signal Handling             
      Sending Signals                              
      Try It Out—An Alarm Clock              
      A Robust Signals Interface                
      Try It Out—sigaction                   
      Signal Sets                                  
      sigaction Flags                           
      Common Signal Reference                   
      Summary                                        
** POSIX Threads                        
      What Is a Thread?                              
      Advantages and Drawbacks of Threads          
      A First Threads Program                        
      Try It Out—A Simple Threaded Program   
      Simultaneous Execution                         
      Try It Out—Simultaneous Execution of Tw
      Synchronization                                
      Synchronization with Semaphores              
      Try It Out—A Thread Semaphore          
      Synchronization with Mutexes                 
      Try It Out—A Thread Mutex              
      Thread Attributes                              
      Try It Out—Setting the Detached State A
      Thread Attributes—Scheduling              
      Try It Out—Scheduling                  
      Canceling a Thread                             
      Try It Out—Canceling a Thread          
      Threads in Abundance                           
      Try It Out—Many Threads                
      Summary                                        
** Inter-Process Communication: Pipes   
      What Is a Pipe?                                
      Process Pipes                                  
      popen                                     
      pclose                                    
      Try It Out—Reading Output from an Exter
                                                 
      Contents
      Sending Output to popen                       
      Try It Out—Sending Output to an Exter
      Passing More Data                           
      Try It Out—Reading Larger Amounts of 
      How popen Is Implemented                    
      Try It Out—popen Starts a Shell      
      The Pipe Call                                 
      Try It Out—The pipe Function         
      Try It Out—Pipes across a fork       
      Parent and Child Processes                    
      Try It Out—Pipes and exec            
      Reading Closed Pipes                        
      Pipes Used as Standard Input and Output     
      File Descriptor Manipulation by close and
      Try It Out—Pipes and dup             
      Named Pipes: FIFOs                            
      Try It Out—Creating a Named Pipe     
      Accessing a FIFO                            
      Try It Out—Accessing a FIFO File     
      Opening a FIFO with open                 
      Try It Out—Opening FIFO Files        
      O_RDONLY and O_WRONLY with No O_NONBLOCK 
      O_RDONLY with O_NONBLOCK and O_WRONLY    
      Reading and Writing FIFOs                
      Try It Out—Inter-Process Communicatio
      Advanced Topic: Client/Server Using FIFOs   
      Try It Out—An Example Client/Server A
      The CD Database Application                   
      Aims                                        
      Implementation                              
      Try It Out—The Header File, cliserv.h
      Client Interface Functions                  
      Try It Out—The Client’s Interpreter 
      Searching the Database                   
      Try It Out—Searching                 
      The Server Interface                        
      Try It Out—server.c                  
      The Pipe                                    
      Try It Out—Pipes Implementation Heade
      Server-Side Functions                    
      Try It Out—Server Functions          
      Try It Out—Plumbing the Pipes        
      xx
                                                 
      Client-Side Functions                     
      Try It Out—Client Functions            
      Try It Out—Getting Server Results      
      Application Summary                          
      Summary                                        
** Semaphores, Shared Memory, and Messag
      Semaphores                                     
      Semaphore Definition                         
      A Theoretical Example                        
      Linux Semaphore Facilities                   
      semget                                    
      semop                                     
      semctl                                    
      Using Semaphores                             
      Try It Out—Semaphores                  
      Shared Memory                                  
      shmget                                       
      shmat                                        
      shmdt                                        
      shmctl                                       
      Try It Out—Shared Memory               
      Message Queues                                 
      msgget                                       
      msgsnd                                       
      msgrcv                                       
      msgctl                                       
      Try It Out—Message Queues              
      The CD Database Application                    
      Try It Out—Revising the Server Function
      Try It Out—Revising the Client Function
      IPC Status Commands                            
      Semaphores                                   
      Shared Memory                                
      Message Queues                               
      Summary                                        
** Sockets                              
      What Is a Socket?                              
      Socket Connections                             
      Try It Out—A Simple Local Client       
      Try It Out—A Simple Local Server       
                                                 
      Contents
      Socket Attributes                           
      Socket Domains                           
      Socket Types                             
      Socket Protocols                         
      Creating a Socket                           
      Socket Addresses                            
      Naming a Socket                             
      Creating a Socket Queue                     
      Accepting Connections                       
      Requesting Connections                      
      Closing a Socket                            
      Socket Communications                       
      Try It Out—Network Client             
      Try It Out—Network Server             
      Host and Network Byte Ordering              
      Network Information                            
      Try It Out—Network Information        
      Try It Out—Connecting to a Standard Se
      The Internet Daemon (inetd)                 
      Socket Options                              
      Multiple Clients                               
      Try It Out—A Server for Multiple Clien
      select                                      
      Try It Out—select                     
      Multiple Clients                            
      Try It Out—An Improved Multiple Client
      Datagrams                                      
      Summary                                        
** Programming GNOME Using GTK+         
      Introducing X                                  
      X Server                                    
      X Client                                    
      X Protocol                                  
      Xlib                                        
      Toolkits                                    
      Window Managers                             
      Other Ways to GUI—Platform-Independent Windo
      Introducing GTK+                               
      GLib Type System                            
      GTK+ Object System                          
      xxii
                                                 
      Introducing GNOME                           
      Installing the GNOME/GTK+ Development Librar
      Try it Out—A Plain GtkWindow          
      Events, Signals, and Callbacks                 
      Try It Out—A Callback Function        
      Packing Box Widgets                            
      Try It Out—Widget Container Layout    
      GTK+ Widgets                                   
      GtkWindow                                   
      GtkEntry                                    
      Try It Out—Username and Password Entry
      GtkSpinButton                               
      Try It Out—GtkSpinButton              
      GtkButton                                   
      GtkToggleButton                          
      GtkCheckButton                           
      GtkRadioButton                           
      Try It Out—GtkCheckButton, GtkToggleBu
      GtkTreeView                                 
      Try It Out—GtkTreeView                
      GNOME Widgets                                  
      Try It Out—A GNOME Window             
      GNOME Menus                                    
      Try It Out—GNOME Menus                
      Try It Out—Menus with GNOME Macros    
      Dialogs                                        
      GtkDialog                                   
      Modal Dialog Box                            
      Nonmodal Dialogs                            
      GtkMessageDialog                            
      CD Database Application                        
      Try It Out—cdapp_gnome.h              
      Try It Out—interface.c                
      Try It Out—callbacks.c                
      Try It Out—main.c                     
      Summary                                        
** Programming KDE Using Qt             
      Introducing KDE and Qt                         
      Installing Qt                                  
      Try It Out—QMainWindow                
                                                 
      Contents
      Signals and Slots                              
      Try It Out—Signals and Slots          
      Try It Out—Using QBoxLayout Classes   
      Qt Widgets                                     
      QLineEdit                                   
      Try It Out—QLineEdit                  
      Qt Buttons                                  
      QButton—The Button Base Class            
      QPushButton                              
      QCheckBox                                
      QRadioButton                             
      Try It Out—QButtons                   
      QComboBox                                   
      Try It Out—QComboBox                  
      QListView                                   
      Try It Out—QListView                  
      Dialogs                                        
      QDialog                                     
      Modal Dialogs                            
      Nonmodal Dialogs                         
      Semimodal Dialog                         
      QMessageBox                                 
      QInputDialog                                
      Using qmake to Simplify Writing Makefiles   
      Menus and Toolbars                             
      Try It Out—A KDE Application with Menu
      CD Database Application Using KDE/Qt           
      Try It Out—MainWindow                 
      Try It Out—AddCdDialog                
      Try It Out—LogonDialog                
      Try It Out—main.cpp                   
      Summary                                        
** Device Drivers                       
      Writing Device Drivers                         
      Devices                                        
      Device Classes                              
      User and Kernel Space                       
      What Goes Where?                         
      Building Modules                         
      Data Types                               
      Try It Out—A Kernel Module            
      xxiv
                                                 
      Character Devices                                
      File Operations                                
      A Sample Driver: schar                           
      The MSG Macro                               
      Registering the Device                      
      Module Usage Count                          
      Open and Release                            
      Reading the Device                          
      The current Task                            
      Wait Queues                                 
      Writing to the Device                       
      Nonblocking Reads                           
      Seeking                                     
      ioctl                                       
      Checking User Rights                        
      poll                                        
      Try It Out—Reading and Writing to schar  
      Try It Out—ioctl                         
      Module Parameters                           
      Try It Out—modinfo                       
      proc File System Interface                  
      How schar Behaves                              
      Time and Jiffies                                 
      Small Delays                                   
      Timers                                         
      Try It Out—The Timer Implementation in sc
      Giving Up the Processor                        
      Task Queues                                    
      The Predefined Task Queues                     
      Memory Management                                
      Virtual Memory Areas                           
      Address Space                                  
      Types of Memory Locations                      
      Getting Memory in Device Drivers               
      kmalloc                                     
      vmalloc                                     
      Transferring Data between User and Kernel Space
      Moving More Data                               
      Simple Memory Mapping                          
      I/O Memory                                     
      Assignment of Devices in Iomap                 
      I/O Memory mmap                                
      Try It Out—The Iomap Module              
                                                 
      Contents
      I/O Ports                          
      Interrupt Handling              
      Allocating an Interrupt      
      Getting an Appropriate IRQ   
      The IRQ Handler                 
      Bottom Halves                   
      Re-entrancy                     
      Disabling Single Interrupts     
      Atomicity                       
      Protecting Critical Sections    
      Basic Spin Locks             
      Reader and Writer Locks      
      Automated Locking            
      Block Devices                      
      radimo—A Simple RAM Disk Module 
      Size Issues                  
      Registering a Block Device   
      Media Change                    
      ioctl for Block Devices         
      The request Function            
      The Buffer Cache                
      Try It Out—radimo        
      Going Further                   
      Debugging                          
      Oops Tracing                    
      Debugging Modules               
      The Magic Key                   
      Kernel Debugger—kdb             
      Remote Debugging                
      General Notes on Debugging      
      Portability                        
      Data Types                      
      Endianess                       
      Alignment                       
      Anatomy of the Kernel Source       
      Summary                            
** Standards for Linux      
      The C Programming Language         
      A Brief History Lesson          
      The GNU Compiler Collection     
      gcc Options                                    
      Compiler Options for Standards Tracking     
      Define Options for Standard Tracking        
      Compiler Options for Warnings               
      Interfaces and the LSB                            
      LSB Standard Libraries                         
      A Brief History Lesson                      
      Using the LSB Standard for Libraries        
      LSB Users and Groups                           
      LSB System Initialization                      
      The Filesystem Hierarchy Standard                 
      /bin                                           
      /boot                                          
      /dev                                           
      /etc                                           
      /home                                          
      /lib                                           
      /mnt                                           
      /opt                                           
      /root                                          
      /sbin                                          
      /tmp                                           
      /usr                                           
      /var                                           
      Further Reading about Standards                   
      Summary                                           
      Index                                               

* Linux系统 
  执行顺序为：/etc/profile -> (~/.bash_profile | ~/.bash_login | ~/.profile) -> ~/.bashrc 
-> /etc/bashrc -> ~/.bash_logout
** 基本操作 命令行界面 /图形界面  
   操作
   操作辅助（补全, 后删，前删，操作历史, 帮助, ）
   对象 (文件,进程，设备 )
** 常用操作以及概念
*** 帮助
    man 简略的帮助
    info 详细的帮助
*** 关机
**** 1. who
     在关机前需要先使用 who 命令查看有没有其它用户在线。
**** 2. sync
     为了加快对磁盘文件的读写速度，位于内存中的文件数据不会立即同步到磁盘上，因此关机之前需要先进行 sync 同步操作。
**** 3. shutdown
#+BEGIN_SRC shell
 # shutdown [-krhc] 时间 [信息]
 -k ： 不会关机，只是发送警告信息，通知所有在线的用户
 -r ： 将系统的服务停掉后就重新启动
 -h ： 将系统的服务停掉后就立即关机
 -c ： 取消已经在进行的 shutdown 指令内容
#+END_SRC
*** PATH
    用户可以执行的操作配置
*** sudo (用户提权）
    sudo 允许一般用户使用 root 可执行的命令，不过只有在 /etc/sudoers 配置文件中添加的用户才能使用该指令。
*** 管理工具集合
    对于发行版，最主要的是两种包.1.RPM 2.DPKG
+ RPM(Redhat Package Manager)
+ DPKG(Debian Package)
** 设备管理
*** 磁盘 
**** 接口方式
***** IDE 
     IDE（ATA）全称 Advanced Technology Attachment，接口速度最大为 133MB/s，因为并口线的抗干扰性太差，且排线占用空间较大，不利电脑内部散热，已逐渐被 SATA 所取代。
***** SATA
***** SCSI
***** SAS
 SAS（Serial Attached SCSI）是新一代的 SCSI 技术，和 SATA 硬盘相同，都是采取序列式技术以获得更高的传输速度，可达到 6Gb/s。此外也透过缩小连接线改善系统内部空间等。
**** 磁盘文件名(操作对象命名规范)
     Linux 中每个硬件都被当做一个文件，包括磁盘。磁盘以磁盘接口类型进行命名，常见磁盘的文件名如下：
 - IDE 磁盘：/dev/hd[a-d]
 - SATA/SCSI/SAS 磁盘：/dev/sd[a-p]

 文件名后面的序号的确定与系统检测到磁盘的顺序有关，而与磁盘所插入的插槽位置无关。
**** 分区
***** MBR
  MBR 中，第一个扇区最重要，里面有主要开机记录（Master boot record, MBR）及分区表（partition table），其中主要开机记录占 446 bytes，分区表占 64 bytes。

  分区表只有 64 bytes，最多只能存储 4 个分区，这 4 个分区为主分区（Primary）和扩展分区（Extended）。其中扩展分区只有一个，它使用其它扇区用记录额外的分区表，
  因此通过扩展分区可以分出更多分区，这些分区称为逻辑分区。

  Linux 也把分区当成文件，分区文件的命名方式为：磁盘文件名 + 编号，例如 /dev/sda1。注意，逻辑分区的编号从 5 开始。
***** GPT
  不同的磁盘有不同的扇区大小，例如 512 bytes 和最新磁盘的 4 k。GPT 为了兼容所有磁盘，在定义扇区上使用逻辑区块地址（Logical Block Address, LBA），LBA 默认大小为 512 bytes。

  GPT 第 1 个区块记录了主要开机记录（MBR），紧接着是 33 个区块记录分区信息，并把最后的 33 个区块用于对分区信息进行备份。这 33 个区块第一个为 GPT 表头纪录，
  这个部份纪录了分区表本身的位置与大小和备份分区的位置，同时放置了分区表的校验码 (CRC32)，操作系统可以根据这个校验码来判断 GPT 是否正确。若有错误，可以使用备份分区进行恢复。

  GPT 没有扩展分区概念，都是主分区，每个 LAB 可以分 4 个分区，因此总共可以分 4 * 32 = 128 个分区。
  MBR 不支持 2.2 TB 以上的硬盘，GPT 则最多支持到 2<sup>33</sup> TB = 8 ZB。
**** 开机检测程序
***** BIOS  
***** UEFI
      BIOS 不可以读取 GPT 分区表，而 UEFI 可以。
*** 软盘
** 文件管理
*** 文件系统
**** 分区与文件系统
   对分区进行格式化是为了在分区上建立文件系统。一个分区通常只能格式化为一个文件系统，但是磁盘阵列等技术可以将一个分区格式化为多个文件系统。
**** 组成
     最主要的几个组成部分如下：

     inode：一个文件占用一个 inode，记录文件的属性，同时记录此文件的内容所在的 block 编号；
     block：记录文件的内容，文件太大时，会占用多个 block。
     除此之外还包括：

     superblock：记录文件系统的整体信息，包括 inode 和 block 的总量、使用量、剩余量，以及文件系统的格式与相关信息等；
     block bitmap：记录 block 是否被使用的位域。
**** 文件读取
     对于 Ext2 文件系统，当要读取一个文件的内容时，先在 inode 中去查找文件内容所在的所有 block，然后把所有 block 的内容读出来。
     而对于 FAT 文件系统，它没有 inode，每个 block 中存储着下一个 block 的编号。
**** inode
     inode 具体包含以下信息：
     
     权限 (read/write/excute)；
     拥有者与群组 (owner/group)；
     容量；
     建立或状态改变的时间 (ctime)；
     最近一次的读取时间 (atime)；
     最近修改的时间 (mtime)；
     定义文件特性的旗标 (flag)，如 SetUID...；
     该文件真正内容的指向 (pointer)。
     inode 具有以下特点：

     每个 inode 大小均固定为 128 bytes (新的 ext4 与 xfs 可设定到 256 bytes)；
     每个文件都仅会占用一个 inode。
     inode 中记录了文件内容所在的 block 编号，但是每个 block 非常小，一个大文件随便都需要几十万的 block。而一个 inode 大小有限，无法直接引用这么多 block 编号。因此引入了间接、双间接、三间接引用。间接引用是指，让 inode 记录的引用 block 块记录引用信息。
**** 目录
     建立一个目录时，会分配一个 inode 与至少一个 block。block 记录的内容是目录下所有文件的 inode 编号以及文件名。

     可以看出文件的 inode 本身不记录文件名，文件名记录在目录中，因此新增文件、删除文件、更改文件名这些操作与目录的 w 权限有关。
**** 日志
     如果突然断电，那么文件系统会发生错误，例如断电前只修改了 block bitmap，而还没有将数据真正写入 block 中。

     ext3/ext4 文件系统引入了日志功能，可以利用日志来修复文件系统。
**** 挂载
     挂载利用目录作为文件系统的进入点，也就是说，进入目录之后就可以读取文件系统的数据。
*** 文件
**** 文件属性
     用户分为三种：文件拥有者、群组以及其它人，对不同的用户有不同的文件权限。
 
     使用 ls 查看一个文件时，会显示一个文件的信息，例如 drwxr-xr-x. 3 root root 17 May 6 00:14 .config，对这个信息的解释如下：

     drwxr-xr-x：文件类型以及权限，第 1 位为文件类型字段，后 9 位为文件权限字段
     3：链接数
     root：文件拥有者
     root：所属群组
     17：文件大小
     May 6 00:14：文件最后被修改的时间
     .config：文件名
     常见的文件类型及其含义有：
 
     d：目录
     -：文件
     l：链接文件
     9 位的文件权限字段中，每 3 个为一组，共 3 组，每一组分别代表对文件拥有者、所属群组以及其它人的文件权限。一组权限中的 3 位分别为 r、w、x 权限，表示可读、可写、可执行。
 
     文件时间有以下三种：

 modification time (mtime)：文件的内容更新就会更新；
 status time (ctime)：文件的状态（权限、属性）更新就会更新；
 access time (atime)：读取文件时就会更新。
 文件与目录的基本操作

 1. ls

 列出文件或者目录的信息，目录的信息就是其中包含的文件。

 # ls [-aAdfFhilnrRSt] file|dir
 -a ：列出全部的文件
 -d ：仅列出目录本身
 -l ：以长数据串行列出，包含文件的属性与权限等等数据
 2. cd

 更换当前目录。

 cd [相对路径或绝对路径]
 3. mkdir
**** 文件操作
     创建目录。
  # mkdir [-mp] 目录名称
  -m ：配置目录权限
  -p ：递归创建目录
  4. rmdir

  删除目录，目录必须为空。

  rmdir [-p] 目录名称
  -p ：递归删除目录
  5. touch

  更新文件时间或者建立新文件。

  # touch [-acdmt] filename
  -a ： 更新 atime
  -c ： 更新 ctime，若该文件不存在则不建立新文件
  -m ： 更新 mtime
  -d ： 后面可以接更新日期而不使用当前日期，也可以使用 --date="日期或时间"
  -t ： 后面可以接更新时间而不使用当前时间，格式为[YYYYMMDDhhmm]
  6. cp

  复制文件。

  如果源文件有两个以上，则目的文件一定要是目录才行。

  cp [-adfilprsu] source destination
  -a ：相当于 -dr --preserve=all 的意思，至于 dr 请参考下列说明
  -d ：若来源文件为链接文件，则复制链接文件属性而非文件本身
  -i ：若目标文件已经存在时，在覆盖前会先询问
  -p ：连同文件的属性一起复制过去
  -r ：递归持续复制
  -u ：destination 比 source 旧才更新 destination，或 destination 不存在的情况下才复制
  --preserve=all ：除了 -p 的权限相关参数外，还加入 SELinux 的属性, links, xattr 等也复制了
  7. rm

  删除文件。

  # rm [-fir] 文件或目录
  -r ：递归删除
  8. mv

  移动文件。

  # mv [-fiu] source destination
  # mv [options] source1 source2 source3 .... directory
  -f ： force 强制的意思，如果目标文件已经存在，不会询问而直接覆盖
  修改权限

  可以将一组权限用数字来表示，此时一组权限的 3 个位当做二进制数字的位，从左到右每个位的权值为 4、2、1，即每个权限对应的数字权值为 r : 4、w : 2、x : 1。

  # chmod [-R] xyz dirname/filename
  示例：将 .bashrc 文件的权限修改为 -rwxr-xr--。

  # chmod 754 .bashrc
  也可以使用符号来设定权限。

  # chmod [ugoa]  [+-=] [rwx] dirname/filename
  - u：拥有者
  - g：所属群组
  - o：其他人
  - a：所有人
  - +：添加权限
  - -：移除权限
  - =：设定权限
  示例：为 .bashrc 文件的所有用户添加写权限。

  # chmod a+w .bashrc
  文件默认权限

  文件默认权限：文件默认没有可执行权限，因此为 666，也就是 -rw-rw-rw- 。
  目录默认权限：目录必须要能够进入，也就是必须拥有可执行权限，因此为 777 ，也就是 drwxrwxrwx。
  可以通过 umask 设置或者查看文件的默认权限，通常以掩码的形式来表示，例如 002 表示其它用户的权限去除了一个 2 的权限，也就是写权限，因此建立新文件时默认的权限为 -rw-rw-r--。
**** 目录的权限

   文件名不是存储在一个文件的内容中，而是存储在一个文件所在的目录中。因此，拥有文件的 w 权限并不能对文件名进行修改。

   目录存储文件列表，一个目录的权限也就是对其文件列表的权限。因此，目录的 r 权限表示可以读取文件列表；w 权限表示可以修改文件列表，具体来说，就是添加删除文件，对文件名进行修改；x 权限可以让该目录成为工作目录，x 权限是 r 和 w 权限的基础，如果不能使一个目录成为工作目录，也就没办法读取文件列表以及对文件列表进行修改了。

   链接

   # ln [-sf] source_filename dist_filename
   -s ：默认是 hard link，加 -s 为 symbolic link
   -f ：如果目标文件存在时，先删除目标文件


   1. 实体链接

   在目录下创建一个条目，记录着文件名与 inode 编号，这个 inode 就是源文件的 inode。

   删除任意一个条目，文件还是存在，只要引用数量不为 0。

   有以下限制：不能跨越文件系统、不能对目录进行链接。

   # ln /etc/crontab .
   # ll -i /etc/crontab crontab
   34474855 -rw-r--r--. 2 root root 451 Jun 10 2014 crontab
   34474855 -rw-r--r--. 2 root root 451 Jun 10 2014 /etc/crontab
   2. 符号链接

   符号链接文件保存着源文件所在的绝对路径，在读取时会定位到源文件上，可以理解为 Windows 的快捷方式。

   当源文件被删除了，链接文件就打不开了。

   可以为目录建立链接。

   # ll -i /etc/crontab /root/crontab2
   34474855 -rw-r--r--. 2 root root 451 Jun 10 2014 /etc/crontab
   53745909 lrwxrwxrwx. 1 root root 12 Jun 23 22:31 /root/crontab2 -> /etc/crontab
   获取文件内容
***** 目录的权限
** 内存管理
** 进程管理
*** 查看进程
**** ps

  查看某个时间点的进程信息

  示例一：查看自己的进程

  # ps -l
  示例二：查看系统所有进程

  # ps aux
  示例三：查看特定的进程

  # ps aux | grep threadx
**** pstree

  查看进程树

  示例：查看所有进程树

  # pstree -A
**** top

  实时显示进程信息

  示例：两秒钟刷新一次

  # top -d 2
**** netstat

  查看占用端口的进程

  示例：查看特定端口的进程

  # netstat -anp | grep port
  进程状态

  状态	说明
  R	running or runnable (on run queue)
  D	uninterruptible sleep (usually I/O)
  S	interruptible sleep (waiting for an event to complete)
  Z	zombie (terminated but not reaped by its parent)
  T	stopped (either by a job control signal or because it is being traced)
** 文件
     * [文件属性](#文件属性)
     * [文件与目录的基本操作](#文件与目录的基本操作)
     * [修改权限](#修改权限)
     * [文件默认权限](#文件默认权限)
     * [目录的权限](#目录的权限)
     * [链接](#链接)
     * [获取文件内容](#获取文件内容)
     * [指令与文件搜索](#指令与文件搜索)
** 进程管理
     * [查看进程](#查看进程)
     * [进程状态](#进程状态)
     * [SIGCHLD](#sigchld)
     * [wait()](#wait)
     * [waitpid()](#waitpid)
     * [孤儿进程](#孤儿进程)
     * [僵尸进程](#僵尸进程)
