* 数学学习范围
1，微积分上，下。（网易公开课里有相应的MIT视频）

2线性代数（网易里有相应MIT课程，讲法和国内的不一样，不过对于初学者只推荐最多看前
20集，后面难度系数增加了）

3，常微分方程（推荐单独看此书，高数书真的少了很多内容，而且网易上MIT的课程真的很
棒，很实际的，不理论）

4，数值分析 (结合matlab)
5，组合数学（学堂在线里有相关课程,这是初等级别的～） 
6，复变函数（结合思考高等数学里的结论及更深刻原因）, 

7，抽象代数（很实用的一门课，因为里面的代数结构很常见） 北大有两本抽代，一般工科，
前一本就够了。还一本更多的涉及交换代数。

8，傅里叶分析（网易上有斯坦福大学相关课程，此课程的英文讲义很不错,大抵是课上的内
容，搜索 斯坦福大学傅里叶变换pdf 就可以找到，配合课程就可以看懂讲义）

9，微分几何（网上搜 梁灿彬微分几何与广义相对论，他的书的前面微分几何部分还是很不
错的） 但入门的微分几何，我推荐，张幼宁的。

10，张量分析（建议先学习矩阵分析，再学这个，这样就有很具体的东西进行计算了） 
11，实变函数与泛函分析（课程搜 台湾交大相关课程，还行）
12，点集拓扑～(感觉这门课很无聊，分析的味道特别重)
13，代数拓扑（相对更有趣） ...... 

注意，以上推荐的都是中文系列，如果你能翻墙，上Youtube 看视频就再好不过了，因为
Youtube上有很多很棒的视频，并且很多高年级数学的视频，都齐全。比如，范畴论，交换
代数，同调论，同调代数，代数拓扑，代数数论，代数几何，李群李代数，群表示论，泛函
分析，算子代数，随机过程……

其实还有一些很实用数学书可以看看，个人受益匪浅!!!(没找过相关视频看)

①图论(不需要很多基础，学完高数线代，就可以看，也很有趣，不过里面的各种算法不得
不令人吐槽)

②偏微分方程(搞完高数，线代，复变函数，傅里叶分析(学过更好)，就可以看了，不过里
面解的过程会很繁杂……慎入)

③初等数论(感兴趣的玩一玩，主要应用在密码学。解密，加密，想想就有神秘感，对不对?)

④解析数论(说大实话，我没怎么用到过，各种估计虐死狗，好吧(∩_∩)，其实可以在里面
遇到很可爱的黎曼zeta函数呀!)

⑤具体数学(听一同学说挺有趣，不过和计算机算法扯上了)

⑥离散数学(典型计算机专业课本，里面包括了逻辑，数论，组合，一点点抽代……一堆东
西汇集，是个大杂烩!!!)

⑦博弈论(从此，我知道我不是一个理性的人……泪崩。如果能外加几本经济学的书就更好了)

⑧运筹学((∩_∩)其实我是接触单纯形法时才造有这玩意的)

⑨数学建模(…)

如果在上面只能选三本书，我会选①③⑦，相对而言 简单又实惠


至于纯数学里的交换代数，同调代数，范畴论，代数几何很多东东……这些资料可以翻墙，
用google 搜索，而后下载pdf复印。
* 数学分析方法
** 数学归纳法(逻辑推断）
** 分割法
** 绝对值
* 数学 研究数量、结构、变化以及空间等
  : 量的存在性 （实数 虚数）对象（东西 )量的属性的行为
** 实数  用途：用于装填游戏   买菜
*** 有理数 
**** 整数(独立的东西) 
***** 东西表示 (用图像符号)  1,2,3,4,5...
***** 行为 东西的加减 东西的倍数 份数
      分数  乘法 
***** 复杂行为的规律
      等差数列求和
      等比数列求和
      前 n项平方和 
      二项式定理
*** 无理数 无限不循环 超越数
** 虚数
** 函数 复杂对象
*** 按变量数分 
**** 一元函数 
**** 多元函数
*** 变化规律 导数
*** 微分学
** 几何 对象（东西 )空间的属性的行为
** 解析几何 
*** 三角函数
**** sin
    在直角三角形中，∠α（不是直角）的对边与斜边的比叫做∠α的正弦，记作sinα，即
    sinα=∠α的对边/∠α的斜边 。sinα在拉丁文中记做sinus。
**** cos
**** tan
**** asin
**** acos
** 极限论   
*** 有极限
*** 无极限 无穷大，无穷小
** 集合
*** 集合运算 
    交集 并集 差集  
** 非欧几何 三维几何
** 微积分
   微积分（Calculus）是高等数学中研究函数的微分（Differentiation）、积分
   (Integration)以及有关概念和应用的数学分支。它是数学的一个基础学科。内容主要包
   括极限、微分学、积分学及其应用。微分学包括求导数的运算，是一套关于变化率的理论。
   它使得函数、速度、加速度和曲线的斜率等均可用一套通用的符号进行讨论。积分学，包
   括求积分的运算，为定义和计算面积、体积等提供一套通用的方法。

   切线、函数、极限、积分、微分
