* 何以为家 [ 贫穷,苦难 ]
  　　法庭上，十二岁的男孩赞恩向法官状告他的亲生父母，原因是，他们给了他生命。是什
  么样的经历让一个孩子做出如此不可思议的举动？故事中，赞恩的父母在无力抚养和教育的
  状况下依然不停生育，作为家中的长子赞恩，弱小的肩膀承担了无数生活的重压。当妹妹被
  强行卖给商贩为妻时，赞恩愤怒离家，之后遇到一对没有合法身份的母子，相互扶持勉强生
  活。然而生活并没有眷顾赞恩，重重磨难迫使他做出了令人震惊的举动……
* 教父 [ 男人 ]
　40 年代的美国，“教父”维托·唐·柯里昂（马龙·白兰度 饰）是黑手党柯里昂家族的首领，
带领家族从事非法的勾当，但同时他也是许多弱小平民的保护神，深得人们爱戴。

　　因为拒绝了毒枭索洛索的毒品交易要求，柯里昂家族和纽约其他几个黑手党家族的矛盾
激化。圣诞前夕，索洛索劫持了“教 父”的参谋汤姆，并派人暗杀“教父”；因为内奸的
出卖，“教父”的大儿子逊尼被仇家杀害；小儿子麦克（阿尔·帕西诺 饰）也被卷了进来，
失去爱妻。黑手党家族之间的矛盾越来越白热化。

　　年老的“教父”面对丧子之痛怎样统领全局？黑手党之间的仇杀如何落幕？谁是家族的
内奸？谁又能够成为新一代的“教父”？

　　血雨腥风和温情脉脉，在这部里程碑式的黑帮史诗巨片里真实上演
* 肖生克的救赎 [ 梦想 ]
　20 世纪 40 年代末，小有成就的青年银行家安迪（蒂姆·罗宾斯 Tim Robbins 饰）因涉
嫌杀害妻子及她的情人而锒铛入狱。在这座名为肖申克的监狱内，希望似乎虚无缥缈，终身
监禁的惩罚无疑注定了安迪接下来灰暗绝望的人生。未过多久，安迪尝试接近囚犯中颇有声
望的瑞德（摩根·弗里曼 Morgan Freeman 饰），请求对方帮自己搞来小锤子。以此为契机，
二人逐渐熟稔，安迪也仿佛在鱼龙混杂、罪恶横生、黑白混淆的牢狱中找到属于自己的求生
之道。他利用自身的专业知识，帮助监狱管理层逃税、洗黑钱，同时凭借与瑞德的交往在犯
人中间也渐渐受到礼遇。表面看来，他已如瑞德那样对那堵高墙从憎恨转变为处之泰然，但
是对自由的渴望仍促使他朝着心中的希望和目标前进。而关于其罪行的真相，似乎更使这一
切朝前推进了一步……
* 泰坦尼克号 [ 爱情 ]
  1912 年 4 月 10 日，号称 “世界工业史上的奇迹”的豪华客轮泰坦尼克号开始了自己
的处女航，从英国的南安普顿出发驶往美国纽约。富家少女罗丝（凯特•温丝莱特）与母亲
及未婚夫卡尔坐上了头等舱；另一边，放荡不羁的少年画家杰克（莱昂纳多·迪卡普里奥）
也在码头的一场赌博中赢得了下等舱的船票。

  罗丝厌倦了上流社会虚伪的生活，不愿嫁给卡尔，打算投海自尽，被杰克救起。很快，美
丽活泼的罗丝与英俊开朗的杰克相爱，杰克带罗丝参加下等舱的舞会、为她画像，二人的感
情逐渐升温。

  1912 年 4 月 14 日，星期天晚上，一个风平浪静的夜晚。泰坦尼克号撞上了冰山，“永
不沉没的”泰坦尼克号面临沉船的命运，罗丝和杰克刚萌芽的爱情也将经历生死的考验。
* 机器人总动员 WALL·E [ 爱情 ]
  公元 2805 年，人类文明高度发展，却因污染和生活垃圾大量增加使得地球不再适于人类
  居住。地球人被迫乘坐飞船离开故乡，进行一次漫长无边的宇宙之旅。临行前他们委托
  Buynlarge 的公司对地球垃圾进行清理，该公司开发了名为 WALL·E（Waste Allocation
  Loa d Lifters – Earth 地球废品分装员）的机器人担当此重任。
  
  这些机器人按照程序日复一日、年复一年辛勤工作，但随着时间的流逝和恶劣环境的侵蚀，
WALL·E 们接连损坏、停止运动。最后只有一个仍在进行这项似乎永无止境的工作。经历了
漫长的岁月，它开始拥有了自己的意识。它喜欢将收集来的宝贝小心翼翼藏起，喜欢收工后
看看几百年前的歌舞片，此外还有一只蟑螂朋友作伴。直到有一天，一艘来自宇宙的飞船打
破了它一成不变的生活……
* 赛德克·巴莱 [ 灵魂 ]
在险恶的日据时代，赛德克族被迫失去自己的文化信仰，男人须服劳役不得狩猎、女人帮佣
不能编织彩衣，骁勇善战的英雄莫那鲁道（林庆台 Ching-tai Lin 饰），见证三十年来的
压迫统治。因一场误会种下日警和赛德克族的紧张关係，自此族人便活在恐遭日警报复的阴
霾中，忍辱负重的莫那鲁道在深思后，虽知将面临灭族危机，但他明白唯有挺身为民族尊严
反击，才能成为真正的赛德克人，于是决心带领族人循着祖灵之训示，夺回属于他们的猎场
* 人生果实[ 家庭,人生 ]
人生果实 人生フルーツ，英文名为 Life Is Fruity，是 2017 年上映的日本纪录片电影。
一部极其感人的纪录电影《积存时间的生活》，日本导演伏原健之拍摄，由日本影后树木希林担任旁白，日本现代陶渊明津端夫妇生活纪录片。藉由津端修一夫妇丰富的生活阅历，一幢深居林间的小屋，探索那些深藏于时间长河中的真正瑰宝。
一部极其感人的纪录电影，由新闻工作出身的日本导演伏原健之拍摄，他在三顾茅庐后，终以四封信获得隐居山林建筑师津端修一与英子夫妇点头「我们愿意协助」，开始著手拍摄这部电影。
一幢深居林间的小屋，位于日本高藏寺新城的一隅。那是建筑师津端修一、按著其师安东尼雷蒙德自豪的木造住宅所建成的。一年四季景緻万千，庭园栽植的上百种蔬果，经由其妻英子的巧手都成了道道佳餚。不论烹饪、裁缝、耕作，没有一样能难得倒她。他们的家居处处充满体贴与用心，印证建筑大师科比意的名言「房子该是生活的藏宝盒」。
津端修一曾任日本住宅公团首席建筑师，60 年代便提出保留树林为风开道…
* 狗十三 [ 家庭 ]
  13 岁的少女李玩，由于父母离异，与爷爷奶奶生活在一起。正处于青春期的她渴望了解、
  陪伴和爱。在“要听话”的中国式教育里，李玩也完成了属于她的“成人礼”。电影中，
  父亲希望通过一条宠物小狗完成与女儿的和解与沟通，李玩为狗取名“爱因斯坦”，暗潮
  涌动的青春因“爱因斯坦”意外走失，开启了它汹涌又无奈的成长之路。
* 萤火虫之墓[ 苦难，灵魂 ,人性]
   https://www.youtube.com/watch?v=h3LhdgNBZOY
* 新喜剧之王 [ 拒绝，坚持 ]
https://www.youtube.com/watch?v=EJsE6i3_6TY
