* 博客
  | https://hanyudeye.github.io/ | 0 元 |

* 《Start Small, Stay Small》着眼小众市场，程序员的微型创业项目指南
Jun 1 2017 原创  
扫描二维码
 

《Start Small, Stay Small》这本英文书(目前没有中文版)是由 Bob Walling 编写，亚马逊评价 4.5 星。Bob 是微型创业者的标杆式人物，作者已经成功构建了几十个软件项目，过着自己独立自由的生活。这次分享将为你解读这边好书。

如果你是个人开发者或者是几个人的小团队尝试做一些项目，这本书能帮助你发现一个好的想法，验证市场可行性等。目标读者比较适合开发者，因为作者也是一个程序员，从一个开发者为中心去实现微型创业的目标。

一、微型创业者
微企创业者更倾向于生活方式的选择(自由，收入独立，工作地自由)，对自己的生意会更加兴奋和有挑战的欲望。或者是追求一种平等，对自己所做的事有更大的掌控力。做一个微型创业者是挺有意思的，但是这是建立在数百小时认真做事的基础上的，需要我们按照一定的策略和方法踏实践行。

一个开发工程师具备在市场上运营一个产品的能力是很难得的，也是有竞争力的。一个微型创业者既是开发人员、也是站长、也是市场人员，需要有一个创业者的视角来看待你要做的项目。

一项研究表明，做下面 3 件事可以大大增加你做成事的可能性。

写下你的目标 - 写下目标比没有写的有更大的成功可能性
公开承诺 - 跟你周围的朋友承诺会有更大的成功几率
对自己的事负责 - 发周报更新你的进展给你的朋友会有更大的成功可能性
我们首先要具备一个清晰的概念—- 市场比你的产品要重要的多
一个没有市场的软件应用仅仅是一个产品而已。大部分的开发者首先是从做一个产品出发，却很少更多的考虑怎么把产品触达到用户。

这是我身边同事的一个例子，他当时做了一个淘宝订单管理的 SaaS 工具，大概做了一年的时间，但是当一年后上线时，淘宝说类似的工具太多，调整了政策，就没上成。一年的时间开发，才知道这个需求是不成立的，这样做的产品的代价太大了。

二、 如何找到适合你的小众市场？
产品成功的最重要因素不是创始人、不是市场的运营也不是产品。而是是否有一群人愿意付费购买。

为什么选择小众市场？
1、小众市场用户更集中
大部分开发人员往往是你有一个很棒的点子，然后花了几个月去实现它，上线后却发现没有人愿意购买。极端一点，你甚至可以把一个垃圾一样的产品卖给极端饥渴的市场而且还能赚钱。
举个例子，下面四种，你会更愿意买哪一本？

一本关于市场营销的书
一本关于产品市场营销的书
一本关于软件市场营销的书
一本关于小众软件产品的市场营销的书，由一个小的创业团队编写，并且销量巨大
我想你会选择第四个。
从这个小例子里应该可以了解到，做小众市场依然是有巨大的空间，并且越聚焦越容易做出利润。很简单— 如果你能找到一小群人并且满足他们的需求，你就可以赚到钱。

你是选择把你的软件的卖给小众市场里只有 5000 人的 100%，还是卖给有 50000 人的 10%？ 他们同样是 5000 人。
正确的选择是：5000 人的 100%
为什么？向这 5000 人营销的成本更低，而且这些人喜欢待在相同的地方，也可能是一个网站、一个论坛、一个博客或者是一本杂志。竞争压力也会小很多。

2、小众市场的广告更有效
比如：用 Google 的 AdWords 搜索关键字“travel”，预估会有 3 百万一个月的展示量，大概会$1.75 一个点击。大概需要$146,000 – $239,000 预算来覆盖这个关键词的前 3 个展示。
那估算一下，上个月在 Google 上，如果 5000 人搜索“Oregon(俄勒冈州) travel”会是什么样呢？大概$1.25 一次点击，花费$110-$180 就可以覆盖这个关键词的一个月的展示，这样的话花费更少，而且点击你广告的人，更加可能是你的目标用户。

3、 更小的市场竞争
Nota Bene 是一个做文字排版的产品，可以卖到$399，而微软的 Office 是$79，Notea Bene 面向的是学术界的用户，可以很方便的支持引用目录和论述，而 Office 是满足不了这部分小众用户的需求的。
如果在一个小众市场里的有$100 的空间，而你没有发现像微软这样的大公司。那么这样的小众市场是有很大的成长空间的。竞争会小很多。

4、 更大的利润空间
Nota Bene 并不容易使用，功能也不够强大，但是为什么价格会这么高？因为 Nota Bene 是唯一做学术领域文字排版这个小众市场的产品。

5、 小众市场不适合大公司的营销
你对比过纽约时报上的广告和你当地报纸上的广告的不同吗？
小众市场更适合特定人群的需求；大公司没有这样专门的人才或者人力来做这方面的营销

6、 更容易取得信任
在小众市场里你更容易被人记住。
在传统的营销里有个理论，当你的产品有 7 次触达的时候，人们才会记住你。但现在这个时代，明显不同了。当你周围的朋友向你推荐一个电影，你会选择性忽略它，但第二次提及的时候，你会产生好奇，第三次被提及的时候，这时候就会放到我的 Netflix 里了。对小众市场的产品来说，更是如此。

寻找你的小众市场
从你喜欢的领域着手
看看你平时关注的领域有哪些？体育、学术、艺术、雕刻还是健康？

从你周边开始
有哪些是你了解的朋友或者你周边人了解的行业，职业，解决他们的痛点

借鉴
去这些网站里你可以参考下，看看别人都有哪些点子
http://ycombinator.com/ideas.html
http://www.ahbbo.com/ideas.html

你也可以去国家统计局网站上看下相关的数字，或者 58 同城等网站上寻找一些小众市场人群，为他们提供产品服务。

找到证据来确定需求
比如作者博客大概每个月会有 60 个人通过关键字“make your own magazine cover”来到他的网站，而这篇文章是他 2005 写的。作者从来没有想到过人们会有这方面的需求，

如果以这个需求点出发，做一个产品。你可以让用户付费下载你的 APP, 或者是一个网站。雇人来制作一些模板和好的设计。允许用户免费制作封面，但是要花$0.99 美金导出成 PDF 格式，
$4.99 美金得到一个印刷品(也可以寄送到朋友)，$9.99 一年内可以不限量制作 PDF 格式。甚至$19.99 美元制作一件 T 恤。

每个人都可以用关键字工具找到这样比较好的小众市场，并且实施起来比较快。最好的小众市场用雷达是可以探测到的，但是你必须行动起来并做一些工作在找到它们之前。

一个通过关键字寻找需求的例子
这里补充一个亦仁(推荐他的小密圈：生财有术)的一个通过关键词查找需求的例子：
在资源有限的情况下，常用的挖掘痛点方式是从互联网巨头产品周边挖掘出一些痛点。对于任何一个大的互联网产品，都有很多产品需求点。下面通过 Instagram 上找到真实痛点和产品机会的例子。

第一步、先 Google 搜索『Instagram』，在 Google 的下拉框和推荐搜索词提示了下面几组词. “Instagram download”、“Instagram for pc”等关键词
第 2 步、除了『instagram download』其他词看起来都很普通。Google 这个词看看有什么机会，除了最后两个词『instagram download video』、『 instagram download pictures』，其余的搜索官方都已经满足了需求。
第 3 步、继续 Google『instagram download pictures』，在搜索结果的第一页出现了 6 个解决此痛点的小工具。点开排名第一的网站，功能和模式都比较简单，直接通过输入 Instagram 图片的链接就可以将图片直接下载下来，盈利方式是 Google Adsense 广告系统。
第 4 步、用 SimilarWeb（网站流量数据统计插件）查一下，每月 120 万访问量，每日 4 万访问量。 按照千次访问 2 美元的收入来估算，此网站估计每天收入 80 美元，每个月收入 2400 美元，每年收入 28800 美元，约人民币 20 万元。

三、如何评估你的想法？
作为一个自己构建的创业项目，你需要找到已经有人在找你的产品的市场，甚至是没有产品的市场。因为创造需求是代价很大的，大公司才玩的起。我们这里讲的项目主要是讲线上的项目。

关注转化率
关注转化率是必须的，能了解你的构建是否可行。

举个例子，如果你售卖$10 的产品，一般网站的转化率在 5%左右，你需要 1000 个访问才能达到一个月$500

1000x0.5x$10=$500

这里面给一个参考：

如果你的定价在$1 至$50 之间，那么你的转化率大概在 1%至 4%；
如果你的定价在$50 至$1000 之间，那么你的转化率在 0.5%到 2%

那倒推的话，你就可以大概确定知道需要多少的流量来达到你的销售目标，假设我的定价是$200, 转化率是 0.5%, 达到月销售$1000 的目标的话就需要
“1,000 visitors × .005 × $200 = $1,000”

构建一个最小的销售网站
确定了你的细分市场之后，怎么来检验你的产品是否有用户愿意购买呢？可以通过一个迷你站点来帮助你。
通过下面这些步骤具体操作：

1、 从你的想做的产品中选择最吸引你的来做
2、 构建你一个迷你站点，包括 2 到 3 个页面
首页
产品介绍
定价&注册
3、 你的首页和展示产品页需要包含产品的截图(这个页面不一定真的实现出来，你可以找设计师仅仅做个图片出来)，一些功能特性的描述，产品信息。一个 try/buy 的按钮。
4、 如果你的产品可以下载并少于$40, 引导用户去点击“Buy Now”
5、 如果你的产品可以下载并大于$40，需要引导用户点击“免费试用”按钮
6、 如果你的产品是一个 SaaS 或者移动应用，引导用户点击“购买”
7、 创建 AdWords 广告，并设置流量到你的站点
8、 当有人点击“试用”或者“购买”，用 Google 的 AdWords 来跟踪转化，并提示用户你的产品正在开发当中。希望他们留下邮箱，会在产品上线的时候及时通知。他们可能留下邮箱，也可能不会。没关系，你需要通过 AdWords 来知道哪些关键字的转化是最有效的，每个转化大概需要花费多少。
你可能会觉得在没有产品的情况下，对用户这样不太好。但是你要知道，网上的用户如果对你的产品不感兴趣，他们是不会点击购买或者试用的。而真正有兴趣试用你的产品的人，也会等上几个月的时间来等待你的上线的。
同时你获得了可以衡量的参考来知道哪些关键字是最有效的。
在 100 至 200 人访问了你的网站之后，看看“试用”和“购买”的数据。假设有 2%到 5%的人点击了“试用”。点击“试用”的这些人中的 40%可能会有意愿完成购买。

通过这种方式需要你投入一些时间和钱。但是你要知道，如果你投入了 8 个小时来做这个测试工作，你会有足够的信心来在接下来的几个月时间里来开发完成你的产品。如果测试不理想，也会节省你数百小时的投入来开发一个根本没有人愿意使用的产品。

四、营销和流量
不要完全相信像 Facebook、Twitter 上的创业公司的营销文章。很多方法都不适合你所面对的市场。
强调多次都不为过：只有特定的营销策略会对你的项目有利。这些策略也会改变，取决于你所在的小众市场。

高质量流量的重要
好的流量是访客跟你的目标用户非常接近，而且他们了解并信任你。
那些你邮件交流过多次的用户显然比一般流量到你网站的用户转化率更高。相差 10 倍都不止。这也是高质量的好处。

很难说哪种流量适合所有的网站。但是基于作者的这些年的经验。流量的策略大概分成长期持续策略和补充策略

最优流量
1、邮件
2、博客、播客、视频 blog
3、自然搜索流量

辅助流量
1、社交化媒体
2、点击广告
3、论坛
4、产品发布会
5、Affiliate 程序
6、其它

重要的是明白，投入时间在 Twitter 和 Facebook 上确实比较有意思，而且能带来一些流量。但是构建长期、可持续的流量才是最重要的。
通过邮件、blog 或者 podcast 触达用户是最好的方式。我推荐你至少使用其中一个。
最后，SEO 是必须的，创建每个页面的关键词列表并不断优化你的搜索的排名。

五、什么是虚拟助理？
虚拟助理的好处能价值最大化你的时间。如果你的时薪是 50$/hour，你可以用$6/hour 的价格支付给虚拟助理一些任务。这些省下来的时间你可以创造更有价值的事情，像开发新的功能或者市场营销。一些可操作性的工作让创业者自己去做，是非常不划算的。
那些虚拟助理在这些年里已经帮我节省了数百个小时。

不要陷入什么事都自己做的陷阱当中。你现在是一个企业家。

举一个作者的例子：

2009 的时候，我打算构建一个微型创业者的研讨会。我需要联系许多的博主来参加这次会。我自己有一个博客列表，可以通过发邮件主动联系他们。但是除了这些，我知道网络上还有很多的博主是我想邀请的。但是我又不想花太多时间来找他们的联系方式。这时候就要考虑虚拟助理了。
我制定的任务是找到排名前 1000 的技术博客里，关注微型创业领域的人。通过 Google spredsheet 来整理出他们的博客地址，博客名称和联系邮箱。最后虚拟助理确定了 28 个最适合的博客。对我来说已经最够了。
通过这些联系方式，发送我个人有针对性的个人邮件，达到了我的预期。这个搜索工作仅仅花费了我$12。

雇人的价格参考如下：

基于单个任务 — “($3-10/hour 海外, $12-50/hour 美国)”，需要明确完成时间点和花费时间。
兼职 —- “($2-7/hour 海外, $10-40/hour 美国)”
全职 — “($1-5/hour 海外, $8-35/hour 美国)”
多年来，雇佣最有效的虚拟助理来自菲律宾，因为他们英语沟通顺畅，这方面服务的人的基数比较大，达到的效果也符合预期。
在中国国内大家可以去万能的淘宝来找类似的虚拟助理或者猪八戒这样的网站来找到虚拟助理来帮助你。

以上就是这次分享的主要内容，作为一个开发者，我们很多时候想尝试自己做一个产品，并产生价值。这本书重要的是从生活方式上给了我们开发人员一个选择，那就是未来我们也可以考虑以微型创业者的身份来生活。做自己喜欢的产品，通过运营，变现并盈利。在现在这个时代，每个人都是自由人，不局限于公司、组织和团体也能赚到钱。利用我们自己的技能和聪明才智，是有机会实现自己的财富自由的。

本书从如何确定一个小众市场？怎么来实现你的想法？如何做好营销和流量？怎么来利用虚拟助理？这几个方面来帮助我们梳理一个小众产品的实现。希望给打算自己做东西和已经做东西的程序员们打开一扇小窗，了解我们是微型创业者，关注小众市场，是可以实现赚钱这个小目标的。

注：这本书的电子版和纸质版可以从网站上购买到（官网：http://www.startupbook.net/ ），电子版是$19 美元，运到国内的纸质版大概是￥245

⌈ 另外 ⌋
周四晚 8 点(6 月 15 日)，我将在知乎 Live 上进行一场直播。

你是否在做着“低水平勤奋”的事，重复的多，却收效甚微；高手却在“刻意练习”，不断的精进。
时间紧、任务重的活动策划，不知如何下手；高手在用“杠杆思维”迅速切入，不断的撬动更多的资源。
做了太多的准备工作，开发很长时间的产品，一上线，无人问津；高手却用最小的代价来验证需求
你总感觉每天都没有整块的时间来做自己的事；高手却利用“第三空间”每天有近 5 个小时的时间做自己喜欢的事。
以上类似的情况，我们每天浪费了很多精力和时间在做效率低下的事。原因是习惯性的思考模式，让我们察觉不到这么做的问题。但实际上，高手的思维方式是不一样的，他们有自己的套路，效率高，成功几率大。这些思维方式并不复杂，简单的甚至是原先我竟然没有这么去想过的差别，效果却迥然不同。这次 Live 将介绍高手的 7 种思维方式。


* 什么是「富人思维」？
我出来工作这么几年，穷人接触过，富人也接触过。最深的感觉就是：
人和人之间的差别实在是太大了。最可怕的不是阶级固化，而是思维固化。
这种感觉有点像，同样是一分钱都没有，有些人，你为他做事，都会感到很开心、很有成就感，一切的付出都是值得的。而有些人，他为你做事，做完了反而让你不开心，浑身不舒服。人与人之间的差别，事实上在金钱上已经被量化了。
在这里我需要先说明一下，这个里面讲的是一种普遍现象和总体趋势，而不是概括所有的 100%的穷人和富人，穷人里也有很聪明具有富人思维的，富人思维里也有穷人思维的。
否则这个世界上就不会有穷人靠勤劳致富，也不会有富人一夜之间沦为穷人。
01.
从金钱的维度：
穷人，会在做很多事情的时候，首先考虑的第一件事情就是钱，而忽略了一件事情的本质。我见过很多对待金钱很极端的例子，尤其在穷人身上。我有个亲戚，以前家里摆着台空调，但总是不开。南方的冬天冷，家里几个人认为，冬天穿多点就行了，舍不得开空调，一直冻到三个人感冒了才心安理得地打开：你看，我都感冒了，当然就要开空调了。一台空调，价值两三千块钱。按照他们家这样的省法，可能用到空调罢工了，电费还用不到一台空调的钱。他们以为自己是赚了，其实是亏了：一件物品买回来，并没有发挥他应有的价值。对于富人来讲，空调使得他们不再拘束于天气的左右，给了他们更加优越的工作环境，从而提高工作的效率，创造比这个电费高得多得多的价值。空调，买回来本来就是让人过得更加的幸福、舒适，而穷人常将这些本末倒置：先扛着，实在扛不住了再开。一开始买的时候，就忽略了一件事情的本质。
02.
从时间的维度：
对时间的理解不同，造成了贫富的巨大差别。
别人跟我说过一个事，很有意思。他说：“你看啊，你餐餐在外面吃饭，外面的东西又脏又不新鲜，而且价格也高，我说这做饭还是得自己做，又干净又卫生。”
我说：“我有钱请一个人回来做不就得了吗?”
他说：“请一个人?何必呢?我这自己做一做，不就把那个钱省下来了吗?”
这个观点很有意思，很多穷人都是这种思想：只要能省钱，花再多的时间也不惜。
反正我的时间也不值钱，放着也是放着，不如让他省钱：宁愿花半个小时在寒风中等公交车，也不愿花十几块钱打的。宁愿每天花 2 个小时做饭，也不愿意花几十块钱让一个专业的人做好端上。宁愿花一下午搞卫生，也不愿意花钱让阿姨来打扫。“能省则省”，这是他们的惯用语。
事实上，我们每个人，赤条条地来到这个世界，身上本来是一分钱没有的。
你能坐在咖啡馆里悠闲地喝咖啡，是因为你在喝咖啡之前，就花了时间在工作，你拿着工作时间换来的钱，花在喝咖啡上。事实上，你坐在这里，是拿着双份的时间在喝这杯咖啡。钱在这两段时间中，仅仅是起了一个介质的作用。
从本质上来说，你是拿着工作时间换喝咖啡的休闲时间，是一种时间上的交换。
对于穷人来说，恨不得自己将每个该花钱的地方都承包了，在一分钱都不支出的情况下，又赚了钱。
他以为自己这样是“省”了，其实算下来，反而是成本最高的。一个人，想什么地方都占便宜，到得最后，反而会走了远路。倒不如将这些专业的事情包出去：转给专业的司机、专业的厨师、专业的清洁人员，效率将是成倍的提升。
而省下来的时间，可以做更多自己擅长的事，创造出更多的价值。
穷人只看到眼前的一顿饭钱，而一餐饭的钱就摆在那里，这个数额是有限的并且是看得到的。倒莫若将他的时间花在事业上，前景将更为广阔。
03.
视野的维度：
富人因为富裕，闲暇时间比穷人要多，因此，他们才会有时间受更好的教育，享受书籍、等精神食
粮，从中提升自我。
我很多时候觉得，并不是出生或者什么造成了穷人和富人之间的巨大差别，而是思维造成了两者的
落差，这种落差，在你的一生，会逐渐积累，最后越变越大。
我在工厂里工作的时候，遇到一件很有意思的事情：我坐在办公室，隔壁就是车间，车间里的工
人，一闲下来就喜欢往办公室里看，看看我们在做些什么。
不过很有意思的是，办公室经常会很闲，大家忙完了，有时候会坐在办公室看电影、打牌、玩手
机。
我经常和这些工人对话，他们有机会会阴阳怪气地对我说：“你们办公室就好咯，每天坐在那里玩
手机、看电影就能收钱。哪像我们，每天加班到 10 点，还没有休息。“
我说：“我不用工作吗?你出的货，做完了难道就摆在工厂里?谁帮你联系出货，谁报关呢?“
“你当然不用啦，你就每天看看电脑，打打字，打几张纸，一个月工资就到手了。“
他们这样说，但我并不生气，因为我知道，有些东西是见识的高低。
在他们的视野来看问题，这个世界上，只有像他们一样，每天辛勤地劳动，将一件件地东西造出胡
来，才是真正创造价值的。用他们的话说：那叫脚踏实地。而我们每天在电脑面前敲敲打打，都是
虚的。
但正是他们看起来有价值的这些事情，恰恰是最没有价值的。中国的制造业正在逐年的萎缩，一个
很重要的原因是：目前很多国家，正在通过机器人来代替人工。
在手机制造、汽车制造很多流程里面，已经开始使用机器人，未来，机器人代替重复单一的手工劳
动将是不可避免的趋势，鞋子行业，我相信也是其中的一个。
要论先下岗，怎么说也是他们在我之前。
重复的做单一的劳动，是最没有价值的，比如收银、比如清洁、比如制造业，现在我们很多家庭用
的清洁机器人就是一个例子。
我以前有个亲戚，很有钱，有一天穷困潦倒了，没办法，还是要吃饭，跑到居委会去申请扫大街。
结果，扫大街也没人要。为什么呢?因为抢这个饭碗的人实在太多了，只要是个人，就会扫地。
当然，我在这里没有任何看不起任何扫地工人的意思，我的意思是，这些工作的可替代性太高了，
你可以做，我可以做，他也可以做，机器人可以做。因此就没有什么独特的价值。
聪明人，会想尽办法，提高自己的水平，离开这个低收入的圈子，进入另外一个价值含量更高的圈
子。
而不是每天嫉妒身边的这个收入比你高，那个比你做的事情少，几个老熟人，差来差去就那么几千
块钱，都是没有意义的事情。除开让自己心塞和别人心塞以外，没有其他作用了。
其实像由一个工人出身，靠着自身的学习和提高，最后跳出自己的圈子，这样的人是有的，张艺谋
就是一个。
只是很多人在忙完之后，就想着打牌、喝酒、吃饭、睡觉，没有想着改变一些什么，将时间都白白
的浪费了。
一个人之所以富，如果不是富二代，我想是有他的原因的。
穷人的思维最可怕的地方在于，他不但让自己穷，而且总是会影响别人：
(1)很多时候，在金钱方面，一个穷人对自己吝啬，对别人可能也好不起来。
我在工厂里的时候，办公室里放着一台空调。哪怕是广东一年最热的时候，温度计哪怕是升到 40
度，摸着桌子都发烫，他也不会开空调给你用。老板给出的理由还非常坦然：“你看，我还不是和
你一样，一起受着酷暑吗?”
而一见到客人，哪怕只有一个，都把空调打开，这样给人的感觉非常难受：仿佛只有客人才是人，
而我们都不配吹空调。
相对于其他行业，制造业是相对比较穷的行业。我相信互联网公司，要哪个敢说自己能工作时间不
开空调，基本上招不到人。而一些最丑恶的现象：拖欠工资、没有福利、工作餐难吃，基本上都是
集中在制造业。
(2)穷人不仅不珍惜自己的时间，也不珍惜别人的时间。
我刚开始接触富人群体的时候，发现一个现象：这个群体很少话。
刚开始我会觉得，这个群体很冷漠、清高，自以为了不起，后来我发现，实际上他们是很珍惜自己
的时间，把有效的时间都用在有意义的事情上。
而穷人废话很多，一个很明显的现象：喜欢过度地强调自我，比如：今天我在商店里，谁谁谁对我
态度差，某个人的人品不好、等等之类。这种人带到工作里，会影响团队，带到家里，会影响家人
的情绪。
跟他们沟通也非常的困难，交流的时候经常先“我很难过”、“气死我了”、“那人真是狗眼看人
低”咔咔咔描述一大圈，最后才说正事，既浪费了自己的时间，又浪费了别人的时间。
而富人则很少这些埋怨，我见过很多富人，都是默默地忽略这些不紧要的小事，将自己的精力和时
间放在自己认为最重要的事情上。讲话都是言简意赅、简明扼要、直达重点，没有什么废话，跟这
种人沟通起来，想不开心都难。
(3)视野的狭窄导致了胸襟的狭窄，更容易造成冲突和矛盾。
在我们工厂，平时发工资，很有意思。工人拿了工资还不算，还得到处翻着工资表，看别人的工
资。比如做鞋面的，喜欢和拉帮的比工资：“为什么大家同样是做一双鞋子，只是做不同的部位，
拉帮的就比做面的高?”
结果跑到老板那边大吵一通，吵到最后，什么都改变不了，因为不仅仅是我们厂，你去别的厂，给
出的价钱也都是这样。
其实这些，都是一些没有意义的事情。一个人，如果稍微将一些规律看透，他会明白这样一个道
理：市场总是很聪明的，他给出的最终定价就是合理的，价格，是人与人、人与钱最后博弈所产生
的结果，老板也没有傻到多给拉帮的钱，而少给做鞋面的钱。
这些人在看到别人的工资比自己高，首先第一反应就是生气，而不是想到：我自己和别人比，有哪
些不足和短板?要去迎头追上。为什么我干的活儿比别人多，而拿的工资比别人少?
相反，还极尽讽刺之能——实际上这不仅是一种胸襟的狭隘，更是一种愚昧和情商低。一个聪明的
人，在说这句话之前，你就应该预料到，这话说出来，只会招人嫉恨，除此之外，就没有其他作用
了。损人不利己的话，说了还不如不说。
我们从小就在被灌输一种思想：金钱是万恶之源。
而在我看来，金钱本身既不恶，也不善。他如同河流一样，总是流向他该去的地方。
史玉柱曾说：企业最大的罪恶就是不赚钱。
无论是对于企业还是个人，贫穷似乎天生就流着一股罪恶的血。
从世界范围上来看，富裕地区的人，总体人口素质比穷的地方的人要高得多。从历史的范围来看，
富裕时代的人们，道德感、人均素质、教养比穷时代的人们要高。
穷并不可怕，可怕之处在于：穷导致了穷人的思维，而穷人思维进一步加剧了穷困潦倒。
跟贫穷的人比起来，我们经常感觉到，跟富人相处，更加的舒适、自然、甘之若饴。
我们每个人，都喜欢勤勤恳恳、少说多做的富人，而不喜欢怨天尤人、口水比茶多的穷人。
喜欢出手大方、干净利落的富人，不喜欢心胸狭窄、拖泥带水的穷人。
喜欢勤劳聪明、谦虚谨慎的富人，不喜欢懒惰愚蠢、骄傲自大的穷人。
与其说是嫌贫爱富，莫若说，在我们每个人的内心深处，
都“喜欢富人思维，而厌恶穷人思维”，这实乃天经地义。
