* 每日一笑
 1.32 岁的表哥单身多年，一直都找不到媳妇，
我们哥俩一起喝酒消愁，喝到半夜民政局门口待着！
我一听浑身一哆嗦，对啊，我怎么没想到！
我也去物色一个媳妇回来，结过婚的会疼人，
有孩子也不用再花奶粉钱了，啧啧啧，一举多得啊，
我不禁为自己的聪明又跟表哥碰了杯，继续喝！

2.一次，某学校组织数学考试，老师允许同学们可以使用计算器。
考场上，同学们奋笔疾书，用计算器演算卷子上的各种考题。
这时，突然从考场的某个角落传来了一声惊呼：
“天哪，我怎么把家里的遥控器拿来了？

3.家里水龙头漏水了，整天滴水声甚是烦人。回到家看到她一个人在那捣鼓，
嘴里嘟嘟囔囔的说:没用的东西，一天到晚滴嗒滴嗒的，要是再修不好，我就换个新的。
站在门口，我紧了紧手里的前列康片，一股紧迫感油然而生。

4.我老板脾气暴躁，而且烟瘾特别大。 
　　这天我和他刚走出公司门口，老板刚点着烟，突然前面出现一个衣着朴素但十分有气质的女士，老板竟然一哆嗦，赶紧把烟熄灭。 
　　那个女士走到老板跟前，微笑着说你好，老板鞠躬说你好。 
　　女士问老板，又抽烟了？ 
　　老板连连摆手，没没没。 
　　女士微微一笑，以后少抽点。 
　　老板点头哈腰，诶诶诶，记住了。 
　　女士走后，我问老板她是谁？ 
　　老板说，那是他中学班主任……

5.“妈妈，给你吃糖！”
“谢谢宝贝。”
“好吃么？”
“好吃～甜到心里了。”
“哦，那为什么咱家的狗狗总是吐出来？”
我。。。

6.媳妇儿和女儿打闹中。。。
女儿敌不过于是大呼救：爸，妈妈虐待你宝贝女儿。。。
我刚想说点啥，就听儿子幽幽说道：姐你就忍忍吧，你不见爸也经常被妈妈虐待，也是可怜人。。。

7.小侄女今天放学有些闷闷不乐，我问她怎么了？
她说：班上有两个男生因为都想和我坐同桌，所以打起来了，我很烦恼。
我。。。

8.小时候我哥看了我的考试成绩之后说:你回家别提考多少分，说了就准备挨揍吧！
我不信，考双百还能挨揍？回家就给我妈看卷子，我妈看完我的又看我哥的，我哥没考好，被我妈修理了一顿。
后来我果然挨揍了！是我哥打的！

9.前两天，小外甥来家里玩。我让三岁的儿子和小外甥比赛背古诗。
小外甥抢着说：“我给你出题，我给你出个难的。”
儿子道：“我给你出个女的！”

10.女朋友今天把我银行卡刷爆了，晚上下班回到家
我冲她吼道：“劳资辛辛苦苦一个月的工资
竟然被你一天全刷了，我们还是分手吧！
我养不起你，爱找谁找谁去……”
女朋友委屈道：“我爱你才花你的钱，
别人送我我都不要…”我竟然无言以对，
一把将她搂进怀里…第二天上班时
收到短信，银行卡里转进三十万… 
