 #+title: 用物质的眼光看待学问, 看懂人生
文字是高度概括的抽象的, 而想象是具体的, 具体分析, 然后得出结论, 相较于死记硬背...
无意识的弱点GTD
24小时，几天，几周，做一个真正的程序员？光靠读书可读不出来。你尝试过连续24个月不懈努力提高自己么？呵呵，如果你做到了，好吧，那么你开始上路了……
每个人都会追求自己的利益, 然后比如医生会把事情说的很惨, 以获取利益.利益建立在这种基础上.
* 追女 
* 哈佛幸福课
  积极的环境能改变人
  过犹不及
  幸福与幽默
  收获交流
  完美主义
  自尊与自我实现
  爱情与自尊
  享受过程
  写日记
  睡眠
  感激
  环境的力量
  逆境还是机遇
  乐观主义
  积极情绪
  运动与冥想
  如何去改变
  养成良好习惯
  面对压力
* 
#+AUTHOR: wuming
#+DATE: 2016-12-28
#+TITLE: 世上无难事, 用对象, 物质的眼光看待学问
#+TITLE: 做学问,做生活,要有研究精神,不要浑浑噩噩
人活着，每天都要跟以前的自己比较，看进步了没有。历史，自己的人生。
编程的本质是建立某种抽象，而那种抽象只在某种环境下才有效！
信任某种物质的存在，信任有物质。并且信任物质有某种用途。信任的另一面就是接受。信仰自己的哲学，真理。 
人的磁场很奇怪，你不感恩，就不顺利；你不承担责任，就不成长；你不付出，就得不到；
你没有爱心，就没有人爱你。如此一来，便得出人生的规律：感恩=顺利，责任=成长，付出=得到，爱心=快乐。
原来生活如此简单，你希望自己好运，就祝福别人好运。一切美好，皆源于一颗感恩的心。

* 心学
  无善无恶心之体，有善有恶意之动。知善知恶是良知，为善去恶是格物。
* 格言
* 点子
本文讲宅在家里赚小钱的一些体会——我靠这些养活一家人。
目前据我观察和实践，“宅钱”有几种模式。
大家谈的很多的两种——当站长和开发共享软件就不提了。这里谈下其它途径：
（0）当站长和开发共享软件
（1）第一种是平台+定制，典型的是 ucenter home, supersite, dz 的定制和集成，这类活比较多，一般金额5000-20000。.Net下主要是dnn的定制，主要是国外项目。
再如，火车头规则定制，这个便宜。这些本人没尝试过——主要是php的，.net国内的少。
（2）第二种是平台+装修，比如，cms系统的装修，淘宝网店的装修，价格在千元上下。淘宝网店装修成品的话，一般卖几十到一二百元，有的专门搞淘宝装修的工作室，
一年收入几十万。
（3）第三种是平台+产品，比如，iphone平台，以及mmarket平台。这方面，本人没尝试过，只是关注。javaeye上有几个家伙做iphone上的开发，
一个哥们目标市场定的非常明确——iphone下日本人需要的软件，这哥们第一个月收入1W，后来的不清楚。
（4）第四种是简单任务外包。简单任务外包主要是为了降低成本或者缩短项目周期。据我的观察，以降低成本的为主。国内这种任务，折算成时间收入，
大致是2000-6000一月（我的估计值），也有高的，也有低的。
（5）第五种是困难任务外包。困难的任务外包主要是解决技术难题，很多企业都没有牛人，或者有牛人，术业有专攻，有解决不了的问题，外包一下。
估算一下，基本上能达到5000-30000一月。问题是其一数量不多，其二有技术风险，算期望值下来，每月收入也比上面第四种高不了多少。
现在手中有需求，需求非常简单，就是识别图片上的对象，要求识别率高，如果将项目预算除以开发时间，大致是 50000/月。但是，开发成功率不高，未必有20%。
第四种活是你干的时间越长钱越多，第五种活是你干的时间越短钱越多——客户巴不得你一天干完呢。
我目前第五种结合第四种过日子。
谈谈体会：一、收入 不要小瞧外包网站上的项目价格比较低，实际上投入去做的话，收入和上班差不多。但是，再向上，月收入要上万是相当的难
二、信用 信用很重要，大家都知道，不多说了
三、细分 细分很重要。细分就是你只做这一块，你就比别人有优势，当你哗啦哗啦列出案例，客户一下子就认定你了。
你如果不细分的话，啥都做一点，啥都不多，对比你的竞争对手就没有优势了。只做自己有优势的。这里有我最大的教训。
我以前搞过管理、搞过技术、搞过写作，三分兵力，结果都能过日子，但都过不了好日子。
现在在家里做宅男赚钱，有一段时间我想扩大收入，多涉及了几个自己不擅长的领域（Web开发），结果收入没扩大反而缩小了。
Web 开发人多，价格压得低，自己不擅长，开发效率又低，收入自然不高。非常赞同吉日兄的只做XXXX。只做一点，做到老大。
永远记住太祖评价诸葛亮的话：其始误于隆中对，千里之遥而二分兵力。其终则关羽、刘备、诸葛亮三分兵力，安能不败！
和吉日兄不同，俺没有工作，只做一点，活太少，不够养家糊口。所以定了3个方向——协议分析、网络推广、图像处理，
但三体合一（哈哈，最开始搞图像处理是因为要搞定验证码，搞协议分析也是为了推广。别骂哥，哥要过日子 。。。。。。）
四、平台 平台相当重要。做（1）-（3），你得熟悉所涉及到的平台和主要的定制需求。做（4）-（5），你也得有自己的平台，才能收入高。
否则，只是苦力收入。（btw. 顺便提一句，我认为金色海洋那种什么自然架构是我这里所说的平台，是方便为自己定制的平台，而不是为广泛的程序员制作的普适框架。）
我的其他尝试：
自从离开北京，回到我这个四线城市，我取得的最好的月收也只是1W。因为这种活，基本属于苦力活。你没有关系，又没有扎根一个行业（扎根一个行业的话就没法宅了），
想取得更高的收入，无法做到。而我又想突破这个收入，所以我做过或正在尝试以下尝试：
（2）规模化（已失败）——招聘人，组织开发项目（俺接小项目还挺好接的，基本随便接接就够干好一阵子）——失败。本地严重缺乏人才，自己培养浪费时间。而我又想保持目前这种生活方式。
（3）专业化——在某一两个领域做到国内顶尖乃至国际顶尖——努力中。目前协议分析在国内处于前列，现在在努力图像理解——哥的最好伙伴是电脑，哥得让电脑具备最大的能力——bot技术和机器智能是好帮手。
（4）平台化——一是网站平台，二是技术平台。技术平台在逐步完善，网站平台还没时间搞。三是第三方平台，比如mm平台，淘宝平台，这个还在观察，没找到一个好的切入点。
（5）服务化——简单说，就是“哥不提供产品，只提供服务”。比如说，验证码识别，提供一个接口，你传一个图片，给你识别传一个结果回去，识别一张一分钱或者半分钱。
既要能入世赚人民币，又要能出世逍遥自在，难啊！！

