* 王守仁
大明南京兵部尚书兼都察院左都御史                                                                                     
  爵位   新建伯                                                                                                      
  籍貫   浙江承宣布政使司紹興府餘姚縣                                                                                
  族裔   漢族                                                                                                        
  原名   王雲                                                                                                        
  字號   字伯安，號陽明子                                                                                            
  諡號   文成                                                                                                        
  出生   成化八年（1472年10月31日）                                                                                  
         浙江等處承宣布政使司紹興府餘姚縣                                                                            
  逝世   嘉靖七年（1529年1月9日）                                                                                    
         江西承宣布政使司南安縣                                                                                      
  墓葬   王守仁墓                                                                                                    
  配偶   諸氏                                                                                                        
         王導（远祖）                                                                                                
         王綱（六世祖）、王彥達（五世祖）、王與準（高祖父）                                                          
         王世傑（曾祖父）、王天叙（祖父）                                                                            
         王華（父）、諸養和（岳父）                                                                                  
  親屬   王守文（弟）                                                                                                
         王正憲、王正億（子）                                                                                        
         王承勳、王承學、王承恩（孫）                                                                                
         王先進、王先達、王先通、王先鋐、王先鐸（曾孫）                                                              
         王業弘、王業洵（玄孫）                                                                                      
                                                        出身                                                         
  * 弘治十二年己未科進士出身                                                                                         
                                                                                                                     
    著作                                                         
  《王文成公全书》、《传习录》、《大学问》、《瘗旅文》、《教条示龙场诸生》、《朱子晚年定论》、《五经臆说》、《世德纪》 

王守仁（1472年10月31日－1529年1月9日），幼名雲，字伯安，号阳明子，諡文成，人稱王阳明。浙江餘姚縣（今浙江省宁波餘姚市）人。明代著名的
思想家、哲学家、书法家兼军事家、教育家，官至南京兵部尚书、都察院左都御史，因平定宸濠之乱等军功而封爵新建伯，隆慶時追赠侯爵。王守仁是
陆王心学之集大成者，非但精通儒、釋、道三教，而且能够统军征战，是中国历史上罕见的全能大儒。

因他曾在贵阳修文阳明洞天居住，自号阳明子，故被学者称为阳明先生，後世现在一般都称他为王阳明，其学说世称“阳明学”。在中国、日本、朝鲜半
岛都有重要而深远的影响。

目录

  * 1 生平事蹟
      + 1.1 童年生活
      + 1.2 出入宦途
      + 1.3 軍事功績
          o 1.3.1 平定江西
          o 1.3.2 擒获宁王
          o 1.3.3 军功封爵
          o 1.3.4 总督两广
      + 1.4 病逝归途
  * 2 哲學思想與個性
      + 2.1 阳明學
      + 2.2 《大學問》
      + 2.3 戒慎保真
      + 2.4 個性
  * 3 文學與書法造詣
      + 3.1 文學
      + 3.2 書法
  * 4 影响與門派
  * 5 紀念與遗跡
      + 5.1 中国大陆
      + 5.2 台湾
      + 5.3 日本
  * 6 参考文献
      + 6.1 引用
      + 6.2 书籍
      + 6.3 文章
  * 7 研究書目
  * 8 外部連結
  * 9 参见

生平事蹟[编辑]

童年生活[编辑]

王阳明於明憲宗成化八年九月三十日（1472年10月31日）出生于一个書香門第、官宦世家，家族自称是东晋丞相王导的后裔。其父王华，成化
十七年（1481年）狀元，為官頗有情操，為明孝宗器用，歷任禮部侍郎。正德年間因得罪劉瑾，被外派南京吏部尚书，又被貶職，之後被罷免。据
《年譜》记载，王守仁出生前夕祖母梦见有人从云中送子来，梦醒时他刚好出生，祖父王伦便为他起名叫王雲，乡中人亦称其降生处为“瑞云楼”。然而
，他到了五岁还不会说话，一天一位奇特的人经过，抚摸他的头说“好个孩儿，可惜道破”，意指他的名字“雲”道破了他出生的秘密。其祖父恍然醒悟，
遂更其名为守仁，此後他便开口说话了。和通常的書香門第不同，年轻的王守仁則經常跟從父親出游居庸關、山海關，并時常出關外，縱覽山川地
理。

出入宦途[编辑]

十七岁时，他到南昌與諸養和之女諸氏成婚，可在结婚的当天，大家都找不到他。原来这天他闲逛中进了主奉道教旌陽真君的鐵柱宮，遇见一道士在那
裏打坐，他就向道士请教，道士给他讲了一回長生，他便与道士相对静坐忘归，直到第二天岳父才把他喚回去。十八岁时，与夫人诸氏归余姚，船过广
信，王阳明拜谒娄谅。娄谅向他讲授“格物致知”之学，王阳明甚喜。之后他遍读朱熹的著作，思考宋儒所谓“物有表裏精粗，一草一木皆具至理”的学说
。为了实践朱熹的“格物致知”，有一次他下决心穷竹之理，“格”了七天七夜的竹子，什么都没有发现，人却因此病倒。从此，王阳明对“格物”学说产生
了极大的怀疑，這就是中國哲學史上著名的“守仁格竹”。

二十歲時，王守仁第一次參加鄉試，中舉人，之後的他更加适才討論軍事，並且善於射箭。然而，二十二岁时考进士不中，內閣首輔李东阳對
其笑道：“你这次不中，来科必中状元，试作来科状元赋。”王阳明悬笔立就，朝中诸老惊为天才。嫉妒者议论说，这个年轻人若中了上第，必然目中无
人。二十五岁再考时被忌者所压，又未考中。同学中有人以不中举为耻者，他笑道：“汝以不得第为耻，吾以不得第动心为耻。”二十七岁，他在读朱熹
的《上光宗疏》，讀到讲到：“居敬持志为读书之本，循序致精为读书之法。”于是王阳明开始懊悔以前读书虽然勤奋却无所得，都是因为自己过于贪图
读书的速度。于是他开始循序以求，但终于认识到“物理吾心，终判为二”，以致旧病又復发，这时见到有道士谈养生之说便因之而喜。

弘治十二年，二十八岁的他參加礼部会试，因考试出色，举南宫第二人，赐二甲进士第七人，观政工部。出使治葬前威寧伯王越，還朝后上奏談論西北
邊疆防備等八件事情，隨後授刑部主事，在江北等地決斷囚獄，隨後因病請求歸鄉。久之，起用授兵部主事。

明武宗正德元年（1506年）冬，宦官劉瑾擅政，并逮捕南京給事中御史戴銑等二十餘人。王守仁上疏論救，而觸怒權閹劉瑾，被施廷杖四十，謫貶至貴
州龍場（貴陽西北七十里，修文縣治）當龍場驛驛丞，沿途為了躲避劉瑾派來的刺客，他還假裝自盡，隨即來到中國西南山區，龍場萬山叢勃，苗、僚
雜居。王守仁親自勸導當地民眾學習，受到民眾愛戴。在這個時期，他對《大學》的中心思想有了新的領悟。王守仁認為，心是萬事萬物的根本，
世界上的一切都是心的產物，認識到“聖人之道，吾性自足，向之求理於事物者誤也”。他在這段時期寫了“教條示龍場諸生”，史稱龍場悟道。其眾多弟
子對於他的“心外無理，心外無物”理論迷惑不解，向他請教說：南山里的花樹自開自落，與我心有何關係？他回答說：“爾未看此花時，此花與爾心同
歸於寂。爾來看此花時，則此花顏色，一時明白起來。便知此花，不在爾的心外。”

不久，劉瑾被誅殺，王守仁升為廬陵縣令，后升爲南京刑部主事，吏部尚書楊一清改其供職于驗封司。此後他屢次升遷，歷任考功司郎中。正德七年，
再升南京太僕寺少卿。正德九年，改鴻臚寺卿。

軍事功績[编辑]
平定江西[编辑]

正德十一年（1516年），兵部尚书王琼举荐王守仁为都察院左佥都御史，巡抚南赣。当时，江西南部以及江西、福建、广东交界的山区爆发民變
。谢志山据横水、左溪、桶冈，池仲容据浰头，皆称王，与大庾陈曰能、乐昌高快马、郴州龚福全等进攻府县。而福建大帽山詹师富等又发生暴乱。前
任巡抚文森托病离任。山民依靠山地据洞筑寨，自建军队，方圆近千里。

正德十三年（1518年）正月，王守仁平定池仲容（池大鬓）部，奏请设立和平县，并兴修县学。三月，守仁抵达江西蒞任。他迅速调集三省兵力，镇压
了信丰等地的民變。七月，王守仁念战争破坏巨大，上奏请求朝廷允准招安。明廷遂賜以節度地方军政，准其便宜行事。十月，王守仁率兵攻破实力最
强的江西崇义县左溪蓝天凤、谢志山军寨，并会师于左溪。王守仁并亲自前往劝降。十一月，王守仁遣使招安，并攻破蓝天凤部。

擒获宁王[编辑]

王守仁一生最大的軍事功績，是平定南昌的宁王宸濠之乱。王守仁将去福建剿匪時（无大量军队），所率部队行軍剛到丰城，宁王朱宸濠突然举事。因
此王守仁积极备战，调配军粮，修治器械，然后发出讨贼檄文，公布宁王的罪状，要求各地起兵勤王。

当时，王守仁最為担心者，就是宁王挥师东下，占领故都南京金陵。如果南京失守，宁王就有了称帝的資本，同时也占了地利，那就不容易消灭了。王
守仁虚张声势，利用假宣传假情报，扰乱宁王的视线，逼他做出错误的判断，以为各路大军已经組成合围态势。同时使用反间计，使宁王猜疑自己部下
的进攻南京策略。宁王果然上当，有半个月时间猶豫觀望、不知所措，没敢发兵攻打南京。王守仁利用這一时机，做好了防守南京的准备，使宁王欲攻
南京，已無可能。

七月，宁王率六万士卒，攻下九江、南康，渡长江攻安庆。王守仁这时已经调集了八万大军（主要成份为雜牌兵，包含各地民兵，农民及土匪），对外
号称三十万。有人指出应该急救安庆，王守仁说：“现在九江、南康已经被敌军占领，如果我们越过南昌跨江救援安庆，就会腹背受敌。现在南昌空虚
，我军锐气正盛，可以一举攻破。敌军听说南昌失守，定会回师来救，这时我们在鄱阳湖迎击他，肯定能取得胜利。”

南昌很快攻破，停了两日，王守仁便派诸将分五路迎击回援南昌的宁王大军。四路分兵迎进，一路设伏。交战以后，宁王大军很快腹背受敌，被分割成
几部分，后又中了埋伏，慘遭大败，溃逃退守八字脑地区。宁王眼觀局势不妙，急忙调九江、南康的精锐部队出击，王守仁派几路大军迎战並取南康。

这一仗打得相當激烈，是关键的一战。官军一度退却，王守仁部將吉安知府伍文定立即斩杀了后退之人，命令诸军一決死战。最後终于打败了寧王軍，
寧王軍退保樵舍地区，将大船结成方阵，宁王拿出金银珠宝犒赏将士，要求他們死力一搏。

但宁王軍的方阵被王守仁看出破绽，他决定仿效鄱陽湖之戰，放火烧船。第二天，宁王群臣聚集在一起，正在船上召开“早朝”会议，王守仁大军杀到，
用小船装草，迎风纵火，烧毁了宁王的副船，王妃娄氏以下的宫人以及文武官员们纷纷跳水自杀。宁王的大船搁浅，不能行动，仓促间换乘小船逃命，
被王阳明的部下王冕部追上擒获，宁王的其它文武大臣也成了階下囚。不久，南康、九江也被官军攻陷，宁王之乱全面平息，前后只有三十五天時間。
王守仁因此而獲“大明军神”之称 ^[15]。

後來，明武宗以「威武大將軍朱壽」之化名出征，江彬有意釋放宁王，讓武宗與寧王打一仗並親自俘獲，藉此討好皇上。王陽明對宦官張永動之以情、
曉之以理，說明這樣做會死更多人。最後協調結果是：讓明武宗到了南京，再放出寧王讓皇帝俘虜，高興一下。

平宁王《记功碑》全文：

正德己卯，六月乙亥，宸濠以南昌叛，称兵向阙。破南康、九江，攻安庆，远近震动。

七月辛亥，臣守仁以列郡之兵复南昌，宸濠擒，余党悉定。当是时，天子闻变赫怒，亲统六师临讨，遂俘宸濠以归。

于赫皇威，神武不杀。如霆之震，靡击而折。神器有归，孰敢窥窃。天鉴于宸濠，式昭皇灵，以嘉靖我邦国。

正德庚辰正月晦，都督军务都御史，王守仁书。从征官属列于左方。

军功封爵[编辑]

正德十六年正德皇帝朱厚照去世，新皇帝朱厚熜继帝位，因念王阳明平定宁王之乱，特敕封其为新建伯、奉天翊卫推诚守正文臣、特进光禄大夫柱国、
兼南京兵部尚书、照旧参赞机务，并于嘉靖二年在绍兴开府。

明朝除了皇親國戚之外，无军功不得享爵位，文官封爵屈指可数，王阳明是明朝开国以来第二位因军功封爵的文官，南京兵部尚书挂参赞机务衔与镇守
太监、南京守备共同负责南京军务。

总督两广[编辑]

参见：藤峽盜亂

明世宗嘉靖六年（1527年），两广事变，都御史姚镆无力解决，嘉靖賜姚镆致仕，任命王守仁以原职南京兵部尚书兼都察院左都御史总督两广军务，擊
潰瑶族和僮族民變。嘉靖七年二月，王守仁率湖廣兵抵達南寧，而盧蘇、王受剛歸降，願意立功自贖。王守仁於是派遣大臣商議，并命湖廣僉事汪溱、
廣西副使翁素、僉事吳天挺及參將張經、都指揮謝佩監湖廣土兵，襲剿斷藤峽叛軍。此後仍然總督分永順兵進剿牛腸等寨，保靖兵進剿六寺等寨，約好
以四月初二各至抵達地點^[16]。

當時，叛軍聽聞明軍檄湖廣土兵抵達，均逃匿深險之中；又聽聞盧蘇、王受歸降，王守仁進駐南寧，故以為王守仁以散遣諸兵佈陣，於是防備弛緩。至
此，湖廣兵皆偃旗臥鼓馳馬抵達，與明軍一同突進，四面夾擊。叛軍大敗，於是退守保仙女大山，據險結寨。官軍攀木緣崖仰攻，并隨後連連攻破油榨
、石壁、大陂等地，直擊斷藤峽。隨後王守仁密檄諸將移兵剿仙臺等賊，分永順兵、保靖兵各自進剿，約定在五月十三日抵達巢穴。叛軍退守永安力山
，仍然被王守仁圍困的大軍進攻得敗，后潰軍均為為防截參將沈希儀等所擒。至此，斷藤叛軍幾乎全盡^[17]。

此役前後擒斬三千餘人，兩江徹底安定。王守仁班師，上疏舉薦林富為都御史，巡撫其地，諸位將領各自均論功褒賞^[18]。

病逝归途[编辑]

兩廣役後，陽明肺病加疾，上疏乞歸。后自知等不及，不等朝廷许可即归。嘉靖七年十一月二十九日（丁卯）（1529年1月9日），陽明病逝於江西省南
安舟中。在臨終之際，他身邊學生問他有何遺言，他說：“此心光明，亦復何言！”

卒後，朝廷予諡文成，贈光禄大夫、柱国、新建伯，隆慶時追封侯爵，稱新建侯。万历十二年从祀于孔庙。

哲學思想與個性[编辑]

儒家                   

Confucius Tang Dynast                     
儒學理論                                  
仁義礼智信                                
                                          
天命良知天理中庸                          
三綱五常四端五倫七情六欲四維八德          
名教禮樂制度宗法井田                      
格物致知内圣外王教化和谐大同 (思想)       
道統聖賢君子小人                          
                                          
仁政王道 (儒家思想)                       
儒門人物                                  
堯舜禹商湯                                
                                          
周文王周武王周公                          
孔子孟子荀子                              

四配                                      
顏回孟子                                  
曾参孔伋                                  

十二哲                                    
闵损冉雍端木赐仲由卜商有若                
                                          
宰予冉耕冉求言偃颛孙师朱熹                
古代儒者                                  
中國                                      
                                          
董仲舒何休施讐丁恭                        
王通賀德基韓愈程颢                        
邵雍周敦頤張載程颐朱熹                    
陳永華陸九淵俞樾吴汝纶段玉裁              
曾国藩薛瑄吕坤曹端王守仁罗钦顺            
王夫之顾炎武黄宗羲颜元方苞                

日本                                      
藤原惺窩林羅山室鳩巢                      
新井白石雨森芳洲                          

朝鮮                                      
薛聰權近吉再安珦李穡                      
李滉王仁李齊賢鄭夢周鄭道傳                
崔致遠徐敬德趙光祖李彥迪李退溪李栗谷      

越南                                      
朱文安阮秉谦阮廌                          
黎贵惇阮文超吳時任                        

琉球                                      
                                          
程順則向象賢蔡溫                          
儒家經書                                  
六经　五经　九經　四书　十三经            

周易　尚書　詩經                          
周禮　儀禮　禮記                          
春秋　左傳　公羊傳　穀梁傳                
孝經　論語　爾雅　孟子                    
大學　中庸                                

十三經注疏　四書章句集注                  
古典儒學                                  
中国儒学                                  
                                          
经学                                      
程朱理学陆王心学                          
朴学經世之學实学                          

日本儒学                                  
水戶學石門心學                            

朝鮮儒學                                  

越南儒學                                  

琉球儒學                                  
當代儒學                                  
學者                                      
                                          
熊十力梁漱溟马一浮唐君毅                  
牟宗三方东美徐复观张君劢                  
蔣慶杜維明成中英刘述先蔡仁厚              

學派                                      
                                          
新儒家孔教運動學衡派波士頓儒家            
相关事项                                  
六艺诸子百家孔子弟子纲常                  
                                          
儒教书院孔庙祠堂宗族                      
                                          
衍聖公科举国子监五经博士批林批孔孔子和平獎
儒家文化圈                                
  * 查                                    
  * 论                                    
  * 编                                    

王守仁留有三本傳世之作《传习录》、《阳明全书》（即《王文成公全书》）三十八卷（门人所辑）、《大学问》。《大学问》被认为是王阳明最重要
的哲学著作。

阳明學[编辑]

主条目：心学和知行合一

王守仁繼承陸九淵強調「心即是理」之思想，反對程頤朱熹通過事事物物追求「至理」的「格物致知」方法，因為事理無窮無盡，格之則未免煩累，故
提倡從自己內心中去尋找「理」，認為「理」全在人「心」，「理」化生宇宙天地萬物，人秉其秀氣，故人心自秉其精要。

在知與行的關係上，強調要知，更要行，知中有行，行中有知，所谓“知行合一”，二者互为表里，不可分离。知必然要表现为行，不行则不能算真知。

《大學問》[编辑]

《大學問》是王陽明的主要哲學論著，反映了他的世界觀。「大學者，昔儒以為大人之學矣。敢問大人之學何以在於明明德乎？」陽明子曰：「大人者
，以天地萬物為一體者也。其視天下猶一家，中國猶一人焉。若夫間形骸而分爾我者，小人矣。大人之能以天地萬物為一體也，非意之也，其心之仁本
若是，其與天地萬物而為一也。豈惟大人，雖小人之心亦莫不然，彼顧自小之耳。是故見孺子之入井而必有怵惕惻隱之心焉，是其仁之與孺子而為一體
也，孺子猶同類者也；見鳥獸之哀鳴觳觫而必有不忍之心焉，是其仁之與鳥獸而為一體也，鳥獸猶有知覺者也；見草木之摧折而必有憫恤之心焉，是其
仁之與草木而為一體也，草木猶有生意者也；見瓦石之毀壞而必有顧惜之心焉，是其仁之與瓦石而為一體也。是其一體之仁也，雖小人之心亦必有之，
是乃根於天命之性，而自然靈昭不昧者也，是故謂之「明德」。小人之心既已分隔隘陋矣，而其一體之仁猶能不昧若此者，是其未動於欲，而未蔽於私
之時也。及其動於欲，蔽於私，而利害相攻，忿怒相激，則將戕物圮類，無所不為其甚，至有骨肉相殘者，而一體之仁亡矣。是故苟無私欲之蔽，則雖
小人之心，而其一體之仁猶大人也；一有私欲之蔽，則雖大人之心，而其分隔隘陋猶小人矣。故夫為大人之學者，亦惟去其私欲之蔽，以明其明德，復
其天地萬物一體之本然而已耳。非能於本體之外，而有所增益之也。」

戒慎保真[编辑]

人性本善，良知現成，但要懂得戒慎恐懼，所謂“慎獨”（獨處時猶如在大庭廣眾前，言行、思想均合乎禮儀），“如臨深淵、如履薄冰”，沒有絲毫不善
夾雜，“非禮勿視，非禮勿聽，非禮勿言，非禮勿動，”使心靈不受任何染污，這樣良知自能百發百中。王陽明解釋說：“夫心之本體，即天理也。天理
之昭明靈覺，所謂良知也。君子戒懼之功，無時或間（間斷），則天理長存，而其昭明靈覺之本體，自無所昏蔽，自無所牽擾，自無所歉餒愧怍，動容
周旋而中禮（合乎禮節），從心所欲而不踰（矩），斯乃所謂真灑落矣。是灑落生於天理之常存，天理常存生於戒慎恐懼之無間（間斷）。孰謂敬畏之
心反為灑落累（牽累）耶？”

王陽明四句教

  * 「無善無惡心之體，有善有惡意之動，知善知惡是良知，為善去惡是格物。」（四句教）

個性[编辑]

他十岁时，父亲高中状元，王阳明隨祖父赴京，路過金山寺時，他祖父與人聚會，在酒宴上有人提議做詩詠金山寺，大家還在苦思冥想，王阳明已先一
步完成：“金山一點大如拳，打破維揚水底天。醉倚妙高臺上月，玉箫吹徹洞龍眠。”四座無不驚歎，又讓他做一首賦蔽月山房詩，王阳明隨口誦出：“
山近月遠覺月小，便道此山大於月。若人有眼大如天，當見山高月更闊。”表現出非凡的想象能力和深厚的文化素養。十一、二岁在京师念书时，他问
塾师“何谓第一等事？”老師说“只有读书获取科举名第”，他当时说：“第一等事恐怕不是读书登第，应该是读书学做圣贤”。尽管如此，他从年少时代起
就从不循规蹈矩，所有记载都说他自少“豪迈不羁”。如13岁丧母後^[19]，继母待他不好，他竟买通巫婆捉弄其继母，使得她从此善待他。他学习并非
十分用功，常常率同伴做军事游戏。^[20]

跟“老好人”鄉愿相比，王陽明更欣賞狂狷之士。他解釋說：“鄉愿以忠信廉潔見取於君子，以同流合污無忤於小人，故非之無舉，刺之無刺。然究其心
，乃知忠信廉潔所以媚君子也，同流合污所以媚小人也，其心已破壞矣，故不可與入堯舜之道。狂者志存古人，一切紛囂俗染，舉不足以累其心，真有
鳳凰翔於千仞之意，一克念即聖人矣。惟不克念，故闊略事情，而行常不掩。惟其不掩，故心尚未壞而庶可與裁。”他五十二歲時評論自己說：“吾自南
京以前，尚有鄉愿意思。在今只信良知真是真非處，更無掩藏迴護，纔做得狂者。使天下盡說我行不掩言，吾亦只依良知行。”

文學與書法造詣[编辑]

文學[编辑]

王阳明的文学成就也很高，但往往被其事功、哲学所掩盖。《古文观止》中收录有王阳明的名篇《瘗旅文》、《教条示龙场诸生》、《象祠記》。其中
《教条示龙场诸生》又入选香港中小学课本。

《四库全书》中有評論曰：“守仁勋业气节，卓然见诸施行，而为文博大昌达，诗亦秀逸有致，不独事功可称，其文章自足传世也。”

王阳明早年作诗刻意求工整，晚年融会哲理。王世贞《书王文成集后》评：“伯安之为诗，少年有意求工，而为才所使，不能深造而衷于法；晚年尽举
而归之道，而尚为少年意象所牵，率不能深融而出于自然。其自负若两得。”

書法

王阳明在书法上亦可称为明代大家。作品以行草为主。王阳明将心学融入书法，丰富了中国的书法理论。

相关评论有：

  * 王羲之“以书掩其人”，王阳明则“以人掩其书”。——明朝徐渭
  * “诗笔清婉，书法尤通神，足为临池之模范”。——清朝朱彝尊

影响與門派[编辑]

主条目：王阳明学生列表

陽明學在現代中國仍有廣泛影響。現代新儒學的開山祖師之一熊十力，及其弟子牟宗三都繼承並發展了陽明學。著名學者徐梵澄經過幾十年對中國、印
度、歐洲思想研究以後，在晚年也對陆王心學讚譽有加（見《陸王學述》收錄于《徐梵澄文集》第一卷，上海三联书店出版社）。中國大陸的當代學者
蔣慶也對陽明讚譽有加（見《政治儒學》一書）。蔣中正是王陽明學說的信徒，並因此將臺北草山改名為陽明山。此外，据传日本近代的著名軍事家東
鄉平八郎，爲王陽明學說所折服，随身腰牌上刻有七字"一生伏首拜阳明"。

紀念與遗跡[编辑]
中国大陆[编辑]

王陽明文廟和王文成公祠兩組建築包括王陽明的塑像，全部在文革被平毀無遺。

浙江省留有：

  * 浙江余姚龙泉山上“四碑亭”留有纪念王阳明的碑亭。碑文是：明先贤王阳明故里。楹联：曾将大学垂名教，尚有高楼揭瑞云。横额：真三不朽。
  * 瑞云楼：王阳明出生处，现位于浙江余姚市陽明街道北武胜门路。
  * 王阳明墓：位于浙江绍兴城南的仙霞山麓，碑文“明王阳明先生之墓”。
  * 王阳明故居
  * 阳明东路，阳明西路，余姚城区的重要街道。
  * 新建路，余姚的最主要的商业街之一，新建伯——阳明先生爵位。
  * 余姚市阳明小学，余姚市阳明中学，余姚阳明学院。
  * 阳明桥：位于浙江省杭州市浙江大学紫金港校区內。浙江大学校训中的“求是”二字取于王阳明“君子之学，唯求其是”一句，亦是该校前身“求是书
    院”之溯源。
  * 宁波至余姚城际铁路两列CRH6F列车命名为“阳明号”。

贵州省：

  * 贵州贵阳扶风山阳明祠：始建于清嘉庆十九年（1814年）。
  * 阳明洞天：位于现贵阳市修文县，龍場悟道處，今蔣慶之陽明精舍所在26°50′58.15″N 106°36′21.51″E / 26.8494861°N 106.6059750°E / 
    26.8494861; 106.6059750。

江西省：

  * 王阳明石刻：位于江西赣州市龙南县玉石岩。
  * 南昌市，有阳明路、阳明东路。
  * 王阳明记功碑：位于庐山。

台湾[编辑]

中華民國先總統蔣中正留學日本時，接觸到陽明學，從此崇敬王陽明，故後來在台灣將許多校名、地名、路名改為「陽明」二字，以示紀念。

  * 陽明山：原名草山，蒋中正將其更名为“阳明山”，後依此為主體設立陽明山國家公園。
  * 陽明書屋：原名中興賓館，在陽明山國家公園內，是蔣中正在臺灣所建最大，也是最後一個行館，民國68年（西元1979年）國民黨黨史委員會進駐
    ，並將其更名為陽明書屋。
  * 阳明海运
  * 國立陽明大學（前身為國立陽明醫學院）：一般亦認為是因蔣中正喜好之故，方定名為「陽明」。
  * 各地的陽明高中，陽明國中、陽明小學等等。
  * 各縣市的陽明路。

日本[编辑]

  * 阳明园：位于日本近江圣人中江藤树纪念馆内。

参考文献[编辑]

引用[编辑]

 1. ^ 在尘封的历史中走近王阳明家世
 2. ^ 诸焕灿《王阳明世系考索》浙江万里学院学报 2001年第4期
 3. ^ 清·张廷玉等，《明史》（卷195）：“父華，字德輝，成化十七年進士第一。授修撰。弘治中，累官學士、少詹事。華有器度，在講幄最久，孝
    宗甚眷之。李廣貴幸，華講大學衍義，至唐李輔國與張后表裏用事，指陳甚切。帝命中官賜食勞焉。正德初，進禮部左侍郎。以守仁忤劉瑾，出為
    南京吏部尚書，坐事罷。旋以會典小誤，降右侍郎。瑾敗，乃復故，無何卒。華性孝，母岑年踰百歲卒。華已年七十餘，猶寢苫蔬食，士論多之。
    ”
 4. ^ 清·张廷玉等，《明史》（卷196）：“守仁娠十四月而生。祖母夢神人自雲中送兒下，因名雲。五歲不能言，異人拊之，更名守仁，乃言。”
 5. ^ 清·张廷玉等，《明史》（卷196）：“年十五，訪客居庸、山海關。時闌出塞，縱觀山川形勝。”
 6. ^ 清·张廷玉等，《明史》（卷196）：“弱冠舉鄉試，學大進。”
 7. ^ 清·张廷玉等，《明史》（卷196）：“顧益好言兵，且善射。”
 8. ^ 清·张廷玉等，《明史》（卷195）：“登弘治十二年進士。使治前威寧伯王越葬，還而朝議方急西北邊，守仁條八事上之。尋授刑部主事。決囚
    江北，引疾歸。起補兵部主事。”
 9. ^ 清·张廷玉等，《明史》（卷195）：“正德元年冬，劉瑾逮南京給事中御史戴銑等二十餘人。守仁抗章救，瑾怒，廷杖四十，謫貴州龍場驛丞。
    龍場萬山叢薄，苗、僚雜居。守仁因俗化導，夷人喜，相率伐木為屋，以棲守仁。”
10. ^ 《明實錄：武宗實錄》（95卷）
11. ^ 《明實錄：武宗實錄》（109卷）
12. ^ 清·张廷玉等，《明史》（卷196）：“瑾誅，量移廬陵知縣。入覲，遷南京刑部主事，吏部尚書楊一清改之驗封。屢遷考功郎中。擢南京太僕少
    卿，就遷鴻臚卿。”
13. ^ 上海古籍出版社《王阳明全集》下册，卷三十三年谱一
14. ^ 《明史》（卷196）：兵部尚书王琼素奇守仁才。十一年八月擢右佥都御史，巡抚南、赣。当是时，南中盗贼蜂起。谢志山据横水、左溪、桶冈
    ，池仲容据浰头，皆称王，与大庾陈曰能、乐昌高快马、郴州龚福全等攻剽府县。而福建大帽山贼詹师富等又起。前巡抚文森托疾避去。志山合乐
    昌贼掠大庾，攻南康、赣州，赣县主簿吴玭战死。
15. ^ [1]
16. ^ （清）谷應泰，《明史紀事本末》（卷39）：“七年春二月，王守仁以湖廣兵至南寧，而盧蘇、王受初降，亦願立功自贖。守仁乃集諸守臣將帥
    議，命湖廣僉事汪溱、廣西副使翁素、僉事吳天挺及參將張經、都指揮謝佩監湖廣土兵，襲剿斷藤峽賊。仍督分永順兵進剿牛腸等寨，保靖兵進剿
    六寺等寨，期以四月初二各至信地。”
17. ^ （清）谷應泰，《明史紀事本末》（卷39）：“先是，峽賊聞軍門檄湖廣土兵至，皆逃匿深險。後聞以蘇、受降罷兵，又守仁駐南寧，故為散遣
    諸兵狀，寇弛不為備。至是，湖廣兵皆偃旗臥鼓馳至，與官軍突進，四面夾攻之。賊敗，退保仙女大山，據險結砦。官軍攀木緣崖仰攻之。初四日
    破賊寨，初五日復攻破油榨、石壁、大陂等巢，賊敗奔斷藤峽。官軍追擊破之，賊奔渡橫石江，覆溺死者六百餘人。官軍自後急擊，俘獲甚眾，賊
    潰散。初十日遍搜山峒無遺，還兵至潯州。守仁密檄諸將移兵剿仙臺等賊，二十一日，仍前分佈各哨，永順兵由盤石、大黃石登岸，進剿仙臺、花
    相等處；保靖兵由烏江口、丹竹埠登岸，進剿白竹、古陶、羅鳳等處，期五月十三日抵巢。各賊聞牛腸等寨破滅，則大懼。方據險設伏待之，官軍
    驟進，奮勇夾擊。賊不支，奔入永安力山。乃分兵圍之，賊復大潰，奔諸路者多為防截參將沈希儀等所擒。於是斷藤之賊略盡。”
18. ^ （清）谷應泰，《明史紀事本末》（卷39）：“先是，守仁因八寨賊去斷藤稍遠，四月初五日，別遣布政使林富、副總兵張佑監督土目盧蘇、王
    受五千餘眾，進剿入寨瑤賊，各兵乘夜銜枚襲之。二十三日，昧爽抵賊巢，遂破石門天險，賊始驚覺，且戰且走。日午，賊結聚二千餘人來拒，官
    軍奮擊之。賊既失險氣奪，不能支，遂大潰，奔入重險。官軍夜募死士俺其不備，二十四日，襲古蓬寨，破之。連克周安、古缽、都者峒諸寨，於
    是八寨之賊亦盡。前後擒斬三千餘人，兩江底定。守仁乃班師，疏薦林富為都御史，巡撫其地，論功褒賞有差。”
19. ^ 關于喪母年齡，尚有爭議，《年谱》说是13岁，但王华（阳明父亲）的行状、墓志铭均说先王华36年卒，即阳明15岁时卒
20. ^ 继母、军事游戏云云出自冯梦龙的书，可靠性存疑

书籍[编辑]

  * 《王文成公全书》
  * 馮友蘭著：《中國哲學簡史》
  * 陳　來著：《有無之境——王陽明哲學的精神》
  * 蔡仁厚著：《王陽明哲學》

文章[编辑]

  * 杜保瑞：《王陽明功夫哲學進路的哲學體系探究》
  * 劉桂標：《論王陽明心即理說的主要觀念》

研究書目[编辑]

  * 秦家懿：《王陽明》（臺北：東大圖書公司，1987）。
  * 岡田武彥著，吳光等譯：《王陽明與明末儒學》（上海：上海古籍出版社，2000）。
  * 吳震：《王陽明著述選評》（上海：上海古籍出版社，2004）。

外部連結[编辑]

#    维基共享资源中相关的多媒体资源：王守仁 

[34] 维基语录上的相关摘錄：王守仁 

  * icon中国主题
  * #   人物主题
  * # 哲学主题

  * 劉述先：〈論王陽明的最後定見〉。
  * 祝平次：〈王陽明的經典觀與理學的文本傳統〉。
  * 姜允明：〈王陽明何以不提陳白沙──「儒佛會通」在明代心學史的實例〉。
  * 柳存仁：〈王陽明與佛道二教〉。
  * 林維杰：〈王陽明論知行: 一個詮釋倫理學的解讀〉。
  * 李明輝：〈從康德的實踐哲學論王陽明的「知行合一」說〉。
  * 朱鴻林：〈陽明從祀典禮的爭議和挫折〉。
  * 劉桂標 : 論王陽明心即理說的主要觀念
  * 王陽明全集 (香港人文哲學會)
  * 王陽明 : 古本大學 (明洽29年)
  * 香港人文哲學會 : 其他宋明理學書籍索引
  * 王陽明 : 大學古本旁釋 ( 佐藤一齋補)
  * 杜保瑞 : 王陽明功夫哲學進路的哲學體系探究
  * 王陽明 : 王文成全書
  * 王陽明 : 傳習錄 (香港人文哲學會)
  * 不一樣的王陽明

参见[编辑]

  * 陽明學、心學
  * 傳習錄、四句教

            餘姚四賢             
严子陵 · 王守仁 · 朱之瑜 · 黄宗羲

己未

