#+TITLE: 【置顶】乐观的灵魂
#+TAGS[]:  人生
#+CATEGORIES[]: 生活
#+DATE: 2020-11-20T06:55:56+08:00
#+DRAFT: nil
#+WEIGHT: 0

忧郁焦虑的人, 会想的多做的少,或者说的多做的少. 这很不利于自己的发展.
想起以前看过讲积极心理学的视频课程,叫 <哈佛幸福课> ,感到心态积极比心态忧郁更好些,就此说明下.

# more
积极心理学并不是给你打积雪, 情绪奋进,而是要行动上的积极.
* 章节主题
** 什么是积极心理学

 1、成功最重要的两点，一是自信，强烈的愿望，相信自己能成功；二是好奇，多问问题。

 2、最重要的往往是常识，大道至简。做减法比做加法让心灵成长更快，复杂之后的简单才是真简单。

 3、我们大多数时间花在外部，关照自己的时间太少了。关照自己和沉默有关系，多给自己一些沉默的留白，对于生活、工作、修身都很重要。语言信息的交流并不是教与学的全部，沉默是学习的必要环节。

 4、信息的解读比信息本身更重要。information如同填满一个容器，而transformation如同改变这个容器的形状。
** 为什么要学习积极心理学

 1、问题缔造现实，你的关注点影响你的认知。感谢和追求那些美好的事物，美好的事物也会回报你。

 2、从普通变得不普通，你需要：适应力强、有榜样、有助人行为、关注优势承担责任。

 3、预防困苦最有效的方法——不管是抑郁还是焦虑——实际上是专注于培养积极心态。
** 幸福是一种随机现象吗

 1、培养内心和周围人的正面力量。我们通过培养正面力量使心理引擎更强大，解决更多的问题。

 2、向最优秀的人学习，比如一个领域排名前5%的，不要向平均水平看齐。

 3、向自己的巅峰时刻学习。

 4、美国人平均每周4个小时的时间奉献给社会，世界上最成功的人一周三次运动，每次保证半小时。花时间沉思。
** 积极的环境能改变人

 1、内在因素对幸福感的决定性——基本需求满足后，财富对幸福感的影响很小。内在因素是指对世界的解释、关注点等。

 2、一个阻碍人们改变的最大障碍是人们低估了自己能改变的能力。

 3、痛苦等负面情绪对于人来说不可或缺，我们要允许自己作为人所产生的任何情绪，学习积极心理学不是避免负面情绪，而是能处理负面情绪。

 4、非常有益于心理健康的冥想：坐直，放松背，放平脚，深呼吸，思想聚焦在呼吸上，平静之后让所有的情绪释放。
** 环境的力量

 1、快乐是道德追求和最终目标。

 2、对于领导、家长而言，员工和孩子会按照你做的去做，而非说的。

 3、信念即自我实现的预言，它强大到可以控制身体。

 4、境随心转，全有意念升起，我们的念头造就了世界。

 5、皮格马利翁效应——当我们怀着对某件事情非常强烈期望的时候，我们所期望的事物就会出现。期望什么，就会得到什么，坏事也一样。
** 乐观主义

 1、最成功的科学家也是失败次数最多的。

 2、错误的自尊公式=实际/期望。

 3、赢得彩票会让你快乐一时，但基本几个月后你的快乐水平就回到从前；失去一百万会让你难过一时，但基本几个月后你的快乐水平就回到从前。

 4、在真正着手处理之后，实际的失败远远小于想象中的，远没有那么严重和深远。
** 逆境还是机遇
 1、行动——把自己置于风险之上，一点点的成功也能有助于提高自我效能。
 2、想象——想象可以愚弄大脑，使之无法区分真实和虚幻，由于大脑无法忍受不一致的情况，所以大脑会启动内部的各种力量打破这种不一致。

 3、认知——选择去负责，而不是抱怨。遇到事情问自己：是不是走了极端？是不是以点概面？是不是用情绪代替了判断？
** 感激

 1、培养感恩习惯，不把好事习以为常，感恩让人感到平静。与孩子每晚谈感激与快乐的事，有助于培养其乐观性。

 2、关注正面新闻，躲避媒体为了博眼球的负面煽动。从艺术中学习，无论音乐、电影、雕塑，美术何种艺术形式，艺术都是将美好的一面表现出来。
** 积极情绪

 1、艾默生说：如果星星每千年闪烁一次，我们都会仰视赞美这个世界的美丽，但是因为他们每天都在闪烁，我们将之视为理所当然。

 2、练习感激，甚至将它们记下来，你将看到越来越多的积极事物 。

 3、美德是可以不断训练出来的。
** 如何去改变

 1、潜意识中可能不想改变密切关联的品性，如：完美主义——动力雄心，担忧焦虑——责任感，精简化——失去优势，古板——言行一致，幸福——偷懒。

 2、神经可塑性是指神经元有可塑性，神经元是发展的，在人的一生中不断生成，直到我们死去。

 3、关于改变的ABC理论。A代表情感情绪：强化高峰体验，提供情感动力。B代表行为行动：走出自己的舒适区，做你害怕的事，害怕就会消失。 C代表认知、思维 ：认识到自己脑子中存在不少根深蒂固但未必正确的观念。
** 养成良好习惯

 1、如果想要养成好习惯，不断地重复吧。我们培养习惯，而习惯将造就我们。 如果你想说服一个人，不断地重复吧，一般说服一个人要改变原来的观点，最少需要6次。

 2、远离舒适区，当你感觉无助的时候，可能正处在健康的改变状态。

 3、很多时候不是自律起作用，而是习惯起作用。记录好习惯的培养过程，比如30天内培养一个好习惯，就会与众不同。

 4、遇到事情留给自己一个解读时间：这是机会还是威胁？是竞争还是合作？是自愿还是责任？是成长还是灾难 ？
** 写日记

 1、自传书是最好的自助书，把美好的事情写下来，内心会有力量。

 2、写日记可以增强神经通路，增强对生命的控制力和预见能力。

 3、刚开始写日记焦虑程度会上升，持续4天后焦虑水平会稳定在比原本更低的水平，同时免疫系统提升，变得更social。
** 面对压力

 1、工作or职业or使命？所有的工作都可以分为以上三种，选择权在你。

 2、自我和谐，才算真正生活过。

 3、睡觉少，智商减分。适当的压力是积极的，不积极的地方是压力带来的不休息和持续运作。
** 过犹不及

 1、克服拖延症，忽略态度和情绪，先着手干5分钟。

 2、在做成的时候奖励自己，好过在刚开始做的时候激励自己。

 3、对于父母来说，为自己的孩子营造心理安全，让他们不害怕告诉你他们做得不好，这样他们就不容易成为完美主义。
** 完美主义

 1、完美主义：对失败的失能性恐惧，尤其是对我们在意的方面。

 2、完美主义的特征是过度关注失败，自卫性强，会带来自尊和精神上的双重压力。而追求卓越的特征是心胸开阔、关注成功，享受过程。

 3、治疗完美主义的方法是专注于对努力的嘉奖，而非对胜利结果的嘉奖。尊重螺旋上升的理论。
** 享受过程

 1、锻炼提高自尊，对治疗焦虑和压力也十分有效。跑步锻炼有利于形成新的神经通路，锻炼后能更好地吸收所阅读的东西。

 2、从失败中挖掘闪光点，失败是成长的学费。

 3、完美主义是阻止我们帮助他人的最大障碍之一，接受“困难存在并且可能不容易解决”这件事，不要把用完美主义要求别人。
** 运动与冥想

 1、压力增大时可能会首先放弃运动，要在潜意识里觉得自己值得幸福，值得拥有美好的身体。

 2、长期冥想者的惊吓反应更少；平静会传染，不宜生气。平静增强免疫力，焦虑会使免疫力降低。

 3、苦苦思索是问题的症结之一，不是解决办法。

 4、在冥想过程中察觉并接收身体信号，身体有自我疗愈功能。
** 睡眠和爱情的重要性

 1、尽量深一些呼吸，现代人的呼吸很浅，深呼吸能帮助我们心平气和。

 2、保证充足的睡眠是一种投资：对免疫系统、精力水平、体重、创造力、降低事故发生等各方面都有益处。

 3、不对外人做的事，也不要对亲密的人做。（例如对亲人吼叫）
** 如何让爱情天长地久

 1、幸福的婚姻，基于深厚的友情之上——尊重对方、享受相处，深入了解对方，熟知好恶、持久尊重，在大问题及琐事上，表现出爱意。

 2、在爱中展示真实的自己，不固执、不计较，亲密关系是爱情保鲜的秘方。

 3、允许冲突的发生并把它当成两人携手成长的机会，永远不要因为争执恶语相向。
** 幸福与幽默

 1、人们倾向于在平日生活中和幽默的人多接触，幽默的生活方式也是会传染。

 2、幽默是可以培养的，多寻找令你开心的事；向幽默的人学习他们思维和话语中的幽默模式。

 3、经历过人生起伏还能笑对生活的人，内心是真正的强大。
** 爱情与自尊

 1、真正的恋情，基础不是责任感，不是否定自我的利他主义者，我们越独立，就越相互依赖。

 2、自尊不是空洞的心理强化能产生的，也不依赖于别人的表扬。自尊存在于现实中，是努力的产物。

 3、可以提高自尊的实践：

 （1）正直——“我的话很重要，可以信赖。”

 （2）自我觉察——“我的价值不需要通过赞扬证明。”

 （3）努力追求有目标、有使命的生活。

 （4）担起责任，承认自己在某方面有不可替代性。

 （5）自我接纳。

 （6）有主见，支持所信仰的东西。
** 自尊与自我的实现

 1、独立的人，比较心不那么强烈。从如何对待别人，可以看出如何对待自己。

 2、荣誉的本质：尊敬自己，相信自己。
** 收获、交流

 总结、邀请同学分享收获。

* 下面是一些网络摘抄.

1、你是一个人，是人就有喜怒哀愁，有起起落落，会紧张，会嫉妒。同样他人也如此。
（重点其他人也一样。）一切感情起伏和心态变化都是正常的。我们要做的是从提高自己的
幸福水平，这个提高是一个终身的目标。（重点幸福水平是和自己过去的平均水平比较，不
是和他人，人与人的先天和后天差异是客观存在的。总是拿自己最好的时候比也不对，没有
人能永远停留最幸福的时刻。）这是一个缓缓上升的波浪线，几乎没有人是因为某一件事的
发生，人生的幸福水平从此就直线上升的。这是需要一点点努力积累。下面是具体方法。

2、每周坚持3次30分以上的运动，还是那句话，你是人。人是生物，心理状态就要受身体健
康的影响。

3、把自己的想法写出来，日记，朋友圈，微博都行。和朋友家人同事，小区门口老大爷，
广场舞大妈，或者陌生人聊聊天。说废话也行。人是群居动物，这是多少年进化的结果，不
是马上可以改变的。所以你需要交流，需要表达自己的情绪观点想法。

4、阅读，特别是睡前阅读。有助于睡眠。另外晚上把光调暗，开夜间模式。读各种各样的
书，不同国家不同题材不同文化背景。也不用非常认真的读，不求甚解就可。见多了，便心
怀宇宙天地宽。

5、培养爱好，要兴趣，对世界有好奇心。对什么都不感兴趣，是非常值得注意的，在我看
来是一个很危险信号。

6、远离S B，键盘侠，喷子，各种奇奇怪怪的人。一旦被带偏，多少匹马都拉不回来。

7、摆平心态，你就是一个人，一个普普通通的人，你不牛到上天入地也没有什么。认认真
真活，便是精彩，愿不负每日晨曦。要是有人觉得你普通就是丢人，请看上一条。

8、最后一点，这个课对我最大的启示就是，如何理解“人”这个字。然后就是坚持去做，
上面说其实都知道的人多，做的到少。
