* 心理学
** 人们对世界的了解，而对世界作出反应
** 障碍
*** 沉迷（永动机)  
*** 浮躁（） 
* 学习(对世界的了解行为)
** 提升学习力的呼吸法和提高欲望与恐惧的最大化
   6秒呼吸
*** 一种少有人提到的技巧，迅速提高学习效率，效果谈不上逆天但也很不错，亲身经历！

 我喜欢黑客技术，在高中的时候买了一本精通脚本黑客，每次看书的时候都感觉特别累，但记忆和理解力非常强，我一度将这认为是我的天赋，实则是无意中的一种呼吸方式所触发的。

 熟悉国术，打坐、内家拳、站桩….任意的一种都应该听过腹式呼吸法，事实上据我目前所知世界所有的宗教入门都是从调节呼吸开始的。

 佛、道、瑜伽…莫不如此

 我当时看书的的时候下意识深吸一口气，下沉丹田，停留5秒钟左右，然后慢慢的吐气（可以理解为憋气，但和那种盲目的憋气是有区别的，有一定的节奏感且有规律可循），每次看完一个章节，我就会感觉非常累，但效果似乎很不错。

 因为买一本书不容易，高中在县城里，所有书店里都没有黑客相关的，所以网上买回来的第一本黑客书格外的珍惜和慎重，读书的时候极端专注，就是在这极端的专注下，莫名其妙这样呼吸的。

 后来在学习宗教的一些禅坐的方法的时候发现呼吸方法居然类似，然后我搜索了一些和呼吸方法相关的资料，结果找到一些姑且称之为科学依据的内容。（毕竟不是来自权威文献，但有一定参考意义）

 四种脑波是：德尔塔脑波（DELTA），塞他脑波（THETA），阿尔法脑波（ALPHA）和倍他脑波（BETA）。这四种脑波构成脑电图（EEG）。阿尔法脑波的振荡平均为10次/秒。

 我要说就是“α波” ，也就是阿尔法脑波。

 科学仪器早已检测出在大脑工作时存在四种波态： 
 1：β波，频繁13-30HZ，表人处于警觉态，数值越高越警觉，在左脑，表人的注意力的高度集中或紧张状态，在右脑，侧重于表惊恐（绝大多数如此）。 
 2：α波，9-12HZ表人在平静深思态，是一个人学习思维效率最适宜的波态。 
 3：θ波，5-8HZ，表人在浅睡冥思态。 
 4：δ波，0.5-4HZ，为无梦沉睡态。 

 阿尔法脑波在大脑中有时出现，有时消失，它并不总是存在。例如，在深睡情况下没有阿尔法波；如果一个人在激动状态下，或恐惧，愤怒时，大脑中也没有阿尔法脑波。

 达到阿尔法波状态的方法

 腹式呼吸（丹田呼吸） 

 我们正常无意识状态下的呼吸方式是：吸气时胸部凸起，腹收进，呼气则胸部凹陷，腹轻微凸起。这里介绍的腹式呼吸法是指吸气时让腹部凸起，吐气时腹部回缩的呼吸法。 

 开始时，细长而均匀地吸气中，此时腹部会充满空气而鼓起，不要停止，继续呼吸，感觉胸部也鼓起了。

 停6秒或更长，一般情况下是越深的呼吸停顿的时间就会越长，这种屏息不会让你有憋气的感觉，还会觉得很舒服，接著再细长而缓慢地将气吐出。

 这6秒钟就是阿尔法波持续产生的情况，记忆力会快速增大，随着呈现衰减，知道吐气的时候有开始增大。

 这样大脑就能持续的出于一种高度的学习状态中。

*** 另一种力量就是欲望和恐惧

 我在学习的时候内心其实潜藏最大的东西就是欲望，我渴望拥有很多东西，但是我又没有，然后就不断地强化等我学会后我就能拥有一切。

 这种最原始的欲望推动我学习。

 还有一种是恐惧，我太害怕什么都没有，一个人孤单的被世界遗弃的情况了。

 所以我一定要学习，这是在这个世界唯一可以通过自我努力拥有的力量，例如掌握了金融的力量就可以在二级市场买进卖出，赚取利差，诞生数以万亿计的财富，而且不需要看别人的脸色。

 如果掌握黑客的力量，整个世界又有什么能够阻挡你前进的脚步呢？

 美国那么大的国家，指挥打仗用的是纯电子化系统，掌握计算机的力量无疑是可怕的。

 所以如果受到伤害，只能证明自己还是太弱了。

 所以将欲望和恐惧用到极致，这也是推动学习的一股强大动力。
** 针对困难学习要比你为了学习而学习效果要好得多
** 思考是学习的重头
** 没有自己的思维，执行力越强，死的越痛苦
   这个圈子要么你足够聪明有悟性，要么有钱，还有一种人能够成功，找对路子，听话、执行。
   最惨的就是有点聪明的人，任何东西他们看一眼就知道是什么，嗤之以鼻，让他做他却又做不来。
** 做
** 群众学的是君君臣臣父父子子，皇帝学的是驭人之术
** 高效率地学习、工作、生活 田海龙  轻松读书人 
*** 一、立刻做
**** 1、2分钟原则
     凡是2分钟内就可以完成的事，立刻去做不要犹豫。人的大脑擅长分析处理，不擅长记忆。


  应用举例：
  a、加微信加QQ顺手添加备注名，或许下次联系已经是三个月后了。
  b、吃完饭立刻洗碗，分分钟的事。
  c、物归原处分分钟，下次再找好轻松。
  d、想到给谁打电话，立刻打。
  等等，自己去延伸吧。
**** 2、5分钟原则
  开动前，先给自己一个5分钟的高度集中精神工作的时刻，全力以赴，迅速进入工作状态。由于限定的是5分钟，心理焦虑就不严重，会很快把工作状态调动起来。拖延的多数原因是因为心理焦虑造成的，而仅限定五分钟的工作时间，从一开始就没有焦虑，可以帮助你迅速进入状态。

  a、写作，从写标题开始。

  b、整理书柜，从眼前这本书开始。

  等等，自己去延伸吧。
**** 3、随时记录
  任何时候的灵感、想法、思路等等一切东西，觉得有用就务必要记录下来，因为分分钟你会再忘记，只有记录下来才有实现的可能。

  a、关于工作的想法。

  b、关于给亲人的礼物。

  c、创作。


  4、立刻起床


  听到闹铃立刻起床，不要给自己设置缓冲时间，回笼觉对身体百害无一利。
*** 二、系统做
**** 1、思维导图做读书笔记
   读书时，试着用思维导图做梳理，你会发现读完了可以很方便地回顾，以后时长翻翻自己的思维导图笔记，再也不用发愁读过书会忘记了，而且脑子中往往会结构性地出现整本书的模型，非常有用。
**** 2、横向读书法


    当你了解一个有立场的学科或者主题时，不妨几个立场的书一起读，可以有效帮助你辨别更全面的事实，尤其是历史、宗教、哲学等。
**** 3、纵向读书法
    想快速了解一个学科，最好的办法就是迅速大量阅读同学科的书，不求甚解，多读几本你就懂了，因为精华的部分会重复出现的。
**** 4、主动分享
    想真正掌握所学，就要不吝分享，分享是把所学化为所用最快的方法。
**** 5、学会做计划
    凡事预则立，学会做年度大事件计划，月度计划，周计划，最好每天早上也做个晨间计划，1分钟搞定高效率的一整天。其他事情也是如是，不要迷茫，按照计划走，才有方向感。
**** 6、学会做总结
    每天晚上给自己一个独处的时间，思考自己的言行，得与失，最好做个记录，比如日记。完成一个大的项目或者事件时学会做总结，为下一次同样的事情打基础。
**** 7、利用碎片时间
    学会利用碎片时间，集腋成裘，比如阅读、思考，甚至休息。
*** 三、享受做
**** 1、常用的东西要舒服
    常用的鼠标、键盘、手机、包等，这方面不要吝啬，甚至要学会适当奢侈，选择最舒适的，工欲善其事，必先利其器。
**** 2、学会放松
    会娱乐会放松，才能更快乐地活着，所以学会主动放松，投入地放松。
**** 3、冥想
    冥想是非常值得学习的技巧，可以在冥想中仔细观察自己，体会自己，彻底放松自己，了解自己。
**** 4、把锻炼和兴趣联合起来
    比如跑步是一件很痛苦的事，我就在跑步的时候听评书，一下就觉得跑步的痛苦好像消失了，听书的乐趣让我慢慢坚持了下来。
** 记忆
   通过听讲学习可以记住5% (如大学课程)
   通过阅读学习可以记住10% （如阅读书籍、文章）
   通过视听软件学习可以记住20% （如APP、 视频）
   通过示范和演示学习可以记住30% 
   通过小组讨论的形式学习可以记住50% 
   通过练习所学知识可以记住75% 
   如果学完马上应用（或教给别人）的话可以记住90%。
** 2分钟思维  
** 注意力训练  躲掉杀人的子弹
* 巨人(物质组成 商业组成 文化产业 计算机科学)
** 爱因斯坦, 哥德尔，巴赫，爱舍尔, 比尔盖茨，乔布斯

