* 思维
1.基础能力，如机械记忆力，反应的快慢，思考的速度等。这些在年幼时的作用最为明显，
当别人需要3秒钟才能算出一道加法题时，你只需要2秒钟，那这种微弱的优势慢慢积累，能
让你自己有更高的自我效能感（俗称自信心），从而挑战更有难度的任务。师长也会注意到
你和其他孩子的区别，给你更特殊的优待。

2.学习技能，如提前预习、复习，将学习材料关联起来以加深记忆。在年幼时，智商高的孩
童和智商较低的孩童的差距，就像两个人都去游泳，都是狗刨，智商高的只是狗刨得更快一
些，取得了微弱的优势。但随着年龄的增长，智商高的孩童已经知道“（瞎）努力和收获不
成正比”，他们会先花时间学会蛙泳或自由泳等更快速的泳姿。而在之后的学习过程中，掌
握了更先进方式的学生在同样的努力程度下能取得更高的收益。

3.兴趣取向和动机。由于智商高的孩子更易取得学习成就，而取得学习成就之后能得到来自
师长与同伴的奖励（夸赞等），这样就形成了一个正向反馈，使得这些孩子有更强的动机去
学习，继而获得更高的成就，形成良性循环。而其他没有建立正向反馈的孩子则可能将兴趣
转向其他领域（体育、电子游戏等），避免与这些孩子正面竞争，去建立自己的其他领域的
良性循环。

4.思维习惯，智商高的孩子在以上机制的作用下，拥有了更多的知识，更多的智力技能，更
高的自信心。他们与其他孩子在面对同样的问题时就会采取不同的策略，这就是不同的思维
习惯。比如难度为n的问题，智商高的孩子可能会先认为其难度可以接受，然后思考解决问
题的方式，再付诸行动，如果失败还可以调整方式继续进行。而智商较低的孩子可能第一步
便认为该问题难度过高，只能接受n-m难度的问题，从而失去锻炼自己的机会。或者即便这
些孩子自己去做，也可能因为不懂解决问题的技巧而采取机械试错的方式，在失败后也容易
丧失信心，而作为挫折的失败感给这些孩子带来了负反馈，使他们不愿意再继续面对类似的
问题。

* 物料整理归类
** 资料收集和整理和归类(方便学习)
*** 建立分类文件夹
  搜集前要明确主题，以搜集相关文章为例，可以按照某类文章的作者、写作年份、文章类
  型等等来建立文件夹分类。如果是纸质文档，可以通过建立纸质文件夹，或者是图书馆的
  模式，存放纸质材料，特别重要的可以通过拍照片、扫描的方式保存。
*** 资料归类
**** 网络书签   
     按照类型，把浏览器的书签功能运用得当，建立分类管理的思维，操作上与在windows系统
     中建立一层一层的文件夹是非常类似的，所谓熟能生巧，不要嫌弃他麻烦，日积月累他就是
     你的好帮手。
**** 网络备份
     学会运用好网络云，计算机云存储功能给你的信息存储提供更多保障，由于计算机、硬盘等
     仍然是机械化的设备，可能出现损坏、数据丢失等悲剧，所以采用百度云等云软件备份重要
     资料是保障你的信息的好办法。
*** 资料收集
    图书馆、搜素引擎等工具，百度学术、百度文库等等
*** 资料查找
    用excel表格建立起资料存储的位置、时间、作者、标题等等你需要的信息，不用详细，
    达到目的就好，他会帮你省去很多回忆和查找的时间，你也可以通过搜索关键词来查找
    相关的信息。
*** 多看一些国外的资讯和文章，拓宽自己的眼界。
*** 主见很重要：
务必记得，要有主见，不要盲目听从别人的经验——务必要结合自己的实践，必要时完全可以
   推翻别人给你的指导，总结自己的经验。
** 思路整理归类(方便用)

* 你经历过哪些思维上的转变？
你被身边的人嘲讽是因为你和他还在同一个阶级。

这事发生在我准备考研之后，我是一个普通的二本，准备考研，A听说我要考北邮之后，平
时有时没事嘲讽我一句：“就你这样的还想考北邮，考本校吧！”一开始我着实生气，心里
想一定考上让你闭嘴。可是后来有一天我突然想通了，我想考北邮不就是为了离这样的人远
一点么？

他为什么不对专业第一说这种话？因为学霸用了三年的时间和他拉开了差距，已经和他不是
一个阶层的了，所以他不嘲讽学霸。

穷人不会嫉妒马云比他有钱，只会嫉妒比他富有一点的穷人。

或许等我考上北邮，也会有北邮的朋友说我：“就你这样的还想去清华读博呢，读本校
吧！”等我去了清华，：“就你这样的还想去剑桥读书呢？就在本校读吧！”

当我自己的能力高了，身边的人阶层自然就换了。当有人嘲讽你的时候，多半，你还和他处
于一个阶级，当你超过他时，他就再也没资格嘲讽你了。

同时我也想清楚另一个道理，当你在嘲讽别人时，也就是在嘲讽你自己。
​
掐指一算，我工作也有8个年头了，看到这道题，不禁想起了这些年的往事和自己的改变。

年纪大的人爱说教，我还年轻，所以，只是分享。

1，

我家境并不算好，但爸妈从小就疼爱，从不让我干活，想吃什么想玩什么，也都一一满足。
而他们唯一的期望，就是我的学业，与大部分中国父母一样。

也许是天生有些小聪明，我还算争气，从小到大成绩一直很好，但其实，我除了学习，其他
的各方面都是空白。这一点，在刚工作的那段时间，给了我很大的打击。

印象比较深刻的一次，是公司有一个新的项目，上司想让我去负责。

这是个很难得的机会，用同事的话说，为了得到这个项目，他愿意被睡。这没什么，关键是
上司是男的，而他，也是男的。

由此可见，这项目是有多诱人了。

但由于这是我完全没接触过的东西，所以心里不禁发怵，犹豫了半天，最终推脱掉了。

上司对我非常失望，然后这个项目就交给了其他的同事。

其实那个同事也对这个项目一无所知，但他边学边做，不停的请教别人，找人帮忙，后来这
项目就真被他做成了，他的能力也因此得到了极大的提升，之后不断被重用，眼瞅着就是迎
娶白富美，走上人间巅峰的节奏。

后来有一次吃饭，上司语重心长的跟我说：

“你想什么事都准备妥当了再去做，哪有这种好事，你还以为你在学校啊，准备一个学期再
来考试，门都没有。

谁是一开始就什么都会的，都是边做边学的，根本就没有时间给你准备，机会是不等人的。
你不懂可以去问别人，你可以找人帮你，你看那谁不就到处找人帮忙吗，你闷在那里纠结是
不行的。”

原文记不太清楚了，意思大致如此。这番话给了我很大的启发，甚至可以说是颠覆性的。

在这之后，我开始尝试着去硬着头皮接下一些自己不太熟的业务，边学边做，不懂的，就找
人请教。

虽然一开始做的并不好，甚至有些项目还搞砸了，但这过程中，我的能力得到了肉眼看得见
的提升，各方面都得到了极大的成长。

这就是我的第一个思维转变：

永远不要等着准备好了再去做，机会是不等人的，边学边做才是最快的成长方法。



2，

在我工作第二个年头的时候，我开始对未来感到迷茫。

其实据我所知，大多数人在工作一两年的时候，都会开始迷茫。

我是一个很容易多想的人，只要一有时间，就在那里思考。我甚至觉得，中国未来在世界的
哲学地位，妥了，因为有我。

从上句话你也许能感觉得出来，没错，我走火入魔了。

那是一个雾霾很重的上午，挤在地铁里胸口发堵，结果还是迟到了，为了赶时间，路上摔了
一跤，到了公司还给小头头批了两句，还真他妈的天时地利人不和了。

借着一股子未冷的血气，不待明月，也等不及明天，一咬牙就递交了辞呈，然后闲赋在家，
整天打座冥想，害老妈以为我入了邪教。

杨绛有一句话很有名，她说你的问题就是书读太少却想的太多。

这也是我的问题。

我读书确实不多，学生时期天天研究学业，没什么时间读课外书。另外，我阅历也不多，年
龄也不够，但又非常迷茫，所以只能局限在很小的范围内一直在那里想啊想啊想。

想来想去，想不出去。

就好像一只井底的青蛙，一直在思考外面的世界一样。

坏处是很多的。

第一，非常耽误时间，加剧了我的拖延症。

第二，非常消耗精力，坐办公室一天，什么活没干，但到家就累瘫了。

第三，由于知识太少，见识太少，想的东西完全没有质量，没产出任何有用的东西来。

但我意识到这个问题，已经是四年之后了。

以前我以为只要在那想，就能想清楚。后来随着阅历增多，年龄渐长，慢慢的就发现，很多
以前想不明白的，其实不需要想，你看见了，就懂了。

现在，我已经很少去想那些没什么意义的东西了。确定好自己的目标，然后多做事，多看书。
想不明白的，就不再去想，就算想，也不要停下来想，要边做边想，边读边想，这样才是高
质量的思考。

这就是我的第二个思维转变：

你的问题就在于读书太少而想的太多，永远不要在无意义的思考上耗费太多时间，多读书，
多行动，只有在知识和阅历增长之后，你的思考才会更有价值。



3，

有一段时间，我很不平衡。

我的工作很辛苦，难度也高，但赚的钱却不如一些没我辛苦的同学。

有一天，我家里电线坏了，就打电话找来维修师傅。那次坏的很严重，电线抽不出来，要重
新打洞铺线才行，反正两个维修师傅忙活了很久，最后加上新的电线之类的材料钱，以及两
个人忙活了半天的工钱，也才一共200。

他们比我更辛苦，而且也并不是完全没有技术含量，但赚的钱却比我少太多。

这时我忽然想明白，你赚钱的多少，与你的劳动强度，技能水平，有关系，但都不大。

关键在于你的不可替代性，以及你所在的平台，你的行业。

我有年薪百万的投行朋友，也有年薪40~50万的程序员朋友，也有年薪10万的传统行业朋友，
他们都是高材生，精英，也都非常努力，但收入却天差地别。

这就是行业的区别！

选对行业非常重要。当然，工作的意义并非收入一个衡量维度，但收入始终是非常重要的一
个维度，而且在一个新兴的，有朝气的，精英聚集的行业，从哪方面来说，都会是更好的选
择。

另外，提升自己的不可替代性也非常重要。

如果你的工作分分钟可以被一个实习生替代，那老板为什么要给你那么高的薪水？

只有你变得不可替代了，你的议价能力才能提高。

不可替代性其实包括很多，一种是你业务水平的提升，一种是你是复合型人才，另外一种是
积累人脉。

提高业务水平很容易理解，就是不断提升你的专业水准。

而复合型，则指的是，能够将两种或多种不同的技能进行融合，从而产生新的技能。

举个简单的例子，比如你拥有较强的写作能力，同时又对电影非常有研究，那你就可以去写
影评，在知乎、豆瓣、微信公众号发表，很容易就成为所谓大V。

具体如何组合，哪些可以组合，大家可以结合自己的优势去思考，总之，不同技能的融合，
可以让你变得独特，且不可替代。

另外，人脉也是一种稀缺资源。

比如，你与某个人认识，但并不算多深厚的交情，但要谈合作的话，和他完全不熟的人相比，
还是有着很大区别的，他更愿意相信你，且可能会给更优惠的条件。

很多时候，我们身处在一个行业内，会觉得很多东西都是理所当然的，并不是那么宝贵。但
要知道，行业外的人，想要找到合适的人办事，经常是求告无门的。

当你在一个行业足够久了，你的行业人脉将变得不可替代。尤其是一些管理岗位，大部分的
工作都需要协作，需要你去调动资源，而只有掌握了人脉的人，才能做成这种事，这不是一
个实习生可以替代的了的。

这里，我的建议是，三种都需要兼顾，不能只闷头发展一种。不要有太大的短板，否则在未
来，你很容易因市场或政策的改动而变得被动。

这就是我的第三个思维转变：

你的赚钱能力与你的专业水平及劳动强度关系不大，更重要的是你所在的行业、平台和你的
不可替代性。想要在职场中获得更好的发展，想要赚更多的钱，只有去提高自己的不可替代
性，这也是应对未来市场、政策变数的唯一方法。



处理过一个纠纷，双方是一姑娘一小伙子，就称作丹丹和阿伟吧。

起因我都不好意思说，芝麻粒儿大的事。好像是这样：当时下雨，地铁口，丹丹跑得急，踩
进水坑溅了阿伟一身泥水，俩人吵起来，但丹丹拒不道歉还出口成脏，阿伟甩手给了丹丹一
耳光，丹丹报警，一起打架警情新鲜出炉。

说实话，虽然肯定是阿伟打人不对，但我对这个丹丹特别没好感，我觉得她特别不可爱！

当我问双方想怎么处理这件事时，双方需不需要沟通一下？人家阿伟说的是：我和对方没什
么好沟通的，直接走法律程序吧，我认了。而丹丹则简单粗暴：他打了我，他得赔！（印象
中说到“赔”字还喷出唾沫来了）

我看了看丹丹被打的脸蛋，没伤。丹丹不信，坚持要求司法鉴定。我开车带她去法医中心，
法医说你这没伤啊，连轻微伤都构不成啊，回去吧。丹丹沮丧极了，跟丢了钱似的。

我问她：你想让对方赔你多少钱？

她想了想：二百吧！

结果阿伟说：毛！我一分钱都不给她！你们处理我吧！

我不敢把这话告诉丹丹，正在楼道里想对策，就听丹丹在另一个屋子里叫我：马拓，你来一
下！

卧槽，这个女人真不简单。

她问我对方准备赔多少。我说对方不想与你私了。

她抠着墙皮凝眉沉思：一百吧，不能再少了。

结果阿伟仍是宁为玉碎不为瓦全，一分不出。说打人我不对，国家随便处理我，但就是不能
让她这种人捞到好处。

最后的结果是，我给阿伟做了行政警告处理，当我把处罚决定书拿给丹丹看时，丹丹特别生
气：我不是说让他赔我钱吗？你怎么这么处理？

我说人家就是不赔你啊，你要钱可以去法院起诉了。

丹丹哭了，说：“我老公原来就是不知道打人的严重性，被你们公安局罚过一回，后来有前
科找工作都不好找，现在又是积分落户，我不想这么整他的呀！我让他赔点儿钱是给他一个
台阶下，我想着一百块钱也不多吧？”

“你怎么不早说呀？”

“我想的是我这一巴掌也不能白挨啊！你说说，一个大男的扇了女孩子一大耳贴子，赔一百
块钱多吗？不就是一个意思吗？”

我真是服了这个丹丹。不过在我眼里，她又不是那么面目可憎了。真像是小时候动画片里的
人物，性格惊奇，跋扈张扬，透着点儿小聪明小善意，又不那么争气。

人呐，总是被表面的情绪化挡住了单纯的内心。

还有一回，也是男打女。起因也是小事：男的在车上整个身子靠着扶手，女的没地方扶，一
言不合吵起来，女的说一句“素质真低”，遂挨揍。

拘留所的路上男的就跟我哭，说从小到大就怕听到这话。他家几代农民，村里连条正经的土
路都没有，去镇上都是爬坡跳坑，他上高中时才知道什么叫顺行什么叫逆行；小学中学时条
件差，没有食堂，学校厨子都是把做好的饭菜盛到桶里摆到操场中央，学生们一下课端着饭
盆就百米冲刺一拥而上，哪儿知道啥叫排队？所以上了大学进了城市的他特别震惊，感受着
秩序，也感受着落差。所以他最怕别人跟他说素质怎样怎样，这个词太绝对，太不负责任。
他觉得素质这个词本身就是优越者的皇冠，里面充斥着不公和自以为是，能触发自卑，引爆
矛盾。明明是加班疲惫靠了一下扶手，干嘛要用这么一个恶毒的词对他盖棺定论？

还有一次，一个女人在挤车时耳机套被乘客挤掉了，死乞白赖要让对方赔钱。问赔多少，说
不贵，地摊上买的，二十。对方觉得冤，耗了一上午，说她无理取闹。我劝她，她说小伙子，
我要真是无理取闹干嘛还说实话是在摊上买的，直接说是专柜正品即使最后查出来了也不能
拿我怎样吧？二十块是我一天的伙食费你信吗？

经过这些事，我的思维真的是有些转变。我开始不再对一个人进行非黑即白的评价。即使前
期对这个人有着脸谱化的代入，过程中也更愿意听一听他们真实的想法，犯错或者纠结的根
源。因为每个人都有着不同的人生经历，这些经历不论美好与灰暗，都是他们躲之不及的。
经历带给他们影响，塑捏着每个人的处事态度、本身性格。但是好是坏，都不全是他们能够
决定的啊。

都觉得“愿你走出半生，归来仍是少年”美好，但谁又能做到这样？社会那么大那么深，造
就的当然就是各种各样、形形色色的人。谁和谁的三观能完全相符啊，能贴上百分之几，恐
怕就是红蓝颜知己了吧？更别提矛盾爆发的时候了。

即使不能够理解他们内心的想法，也应该去听，去想，去尝试感受。因为你面对不仅仅是一
张脸一张嘴，而是一个完整的人。


我今年41岁了，古人说三十而立，四十不惑。不敢妄称“不惑”。职业生涯几经起落，最终
走上了创业的道理。家有两个调皮的女儿。成家立业的立算是做到了。


这里的“立”，我的理解，并不是指事业或者家庭，而是一种承担责任的能力。


这种能力，并不是随着年龄的增长就能获得，它需要你转变自己的思维模式，去不断挑战自
己，训练自己，最终才能得到真正的成长。

你问我：你经历过哪些思维上的转变？


一个让我获益良多的改变是：

我意识到，很多时候我们停止成长，是因为一时的成绩让我们骄傲和固执，使得我们不再去
探索更多可能性。只有怀着空杯心态，我们才能获得更多的成长。


这里，我想讲讲自己的故事。


刚毕业那会儿，由于很想做市场营销，所以辞去了收入更高的记者的工作，去做了最底层的
销售代表。


由于什么都不懂，所以一切对我来说都是困难的。但同时，一切对我来说，又是新鲜的。


譬如，有一次批发客户“发难”，说半年前进的一批卫生巾的背胶粘不牢，要退货。按照规
定，半年前的产品是不能做退货处理的。好说歹说，客户就是坚持要退。


那时候我不知道该怎么办，就去请教了一些经验更丰富的“老”销售，但他们也说这事也没
有太多很好的办法，说要不就退了呗。


但作为初生牛犊的我，并不觉得有什么事是不可能的，一定有解决的办法。


可能是比较楞的缘故，最后我决定亲自试验这批卫生巾，身为大老爷们的我把一片卫生巾贴
在自己的内裤上，之后一天走街串巷，下班后还打了一场篮球，并没有出现脱胶现象。第二
天和颜悦色地跟批发商说，大姐这批卫生巾我亲测过，粘得很牢。批发商又好笑又好气，也
就不再提退货的事了。


功不唐捐，半年后，我成了正式员工，之后，更是成功转岗，到了品牌部门。


但是，当我在公司呆了几年之后，在不知不觉中，变成了当初请教的那些“老员工”那样。


虽然业务能力得到了很大提升，但思维模式得到了固化，做事更多的开始依赖过往的“经
验”，而不去思考它的其他可能性。


我再也没有像当初那样，把卫生巾贴自己内裤上，跑一天试验它到底粘不粘的牢。


换言之，我封闭了自己成长的边界，停止了进一步的成长。


有一次，我接到了一个非常棘手的项目，出于经验，我判断很多地方是不可能做到的，所以
当时就在反驳，一条条说明，哪些地方是不可能的，因为什么什么。


的确，在业务水平方面，我是当时全组最强的，所以当我听到一些不太合理的要求，我都是
嗤之以鼻的，觉得领导很外行，很傻比，一定要反驳。


但那时候新进来的几个新人，却一直在努力思考，尝试着各种可能性。


后来，我就没管了，跟进了其他的项目，并觉得那几个新人都是在做无用功。几天之后，我
惊讶的发现，那几个实习生做出了我以前从没想过的方案，而且所有问题都得到了巧妙的解
决。


我十分震惊，并且羞愧。


我震惊于他们的成功，我羞愧于我的轻慢。看到他们，我仿佛看到了当年的自己。


“我以前不也是那样的吗？怎么现在变成了这副模样。”


痛定思痛，我开始有意识的让自己不再去轻易说“不可能”，我收掉了自己的傲慢，而是积
极探索一切可能性。


之后的几年，我的成长速度非常快，而且开始领悟到工作的真谛——


工作并不是生活的对立面，它是生活的一部分，不能享受工作的人，也无法真正享受生活。


没有思想上的转变，我之后也不会几次离开较高的职位、选择在新的岗位、公司从零做起
（这些经历可以写一篇新的回答了，敬请期待）。


在2015年离开宝洁前，我曾任年薪百万的市场总监职务，负责过几十亿年销售额的国民洗发
水品牌的营销工作。之后我还是走上了创立自己的氨基酸洗发水品牌的道路。我们这个月刚
完成了数千万的A轮融资，天猫双十一也做到了美发护发类目的第11名。妄论成功现在还太
早，这在资本寒冬的当下也算是不容易了。


现在，我有了自己的公司和一起奋斗的小伙伴们。我能看到像当初刚工作时的我那么拼的，
但也能看到像工作了几年以后的我的那种年轻人，我能看到他眼神里对工作的痛苦和煎熬。


每当这个时候，我就会跟他讲我的故事，告诉他，我也是这么过来的。做为公司的创始人，
我最希望看到小伙伴眼里闪着的光芒。41岁的我还充满着激情和梦想呢。20多岁的人不要跟
我说你已经没有激情和学习的动力了。


Stay hungry and stay foolish！


最后，我想啰嗦几句提一些具体的建议：


1，不要轻易说不：工作、生活中遇到问题，不要轻易放弃，不要轻易说“不可能”，而是
积极去思考它的可能性。这里面，蕴含着宝贵的成长机会。


2，不要轻易跳槽：工作里遇到问题，往往可能是你自己的问题，虽然跳槽之后，你因为新
的环境，一开始会打开自己的边界，积极学习，但一旦熟悉了业务模式后，你又会变成那个
故步自封的人，新的问题又会接踵而来。所以不要轻易跳槽，而是去想自己的问题在哪里。


3，不要天天熬夜：熬夜并不意味着工作时间的增多，它只能让你的工作效率下降。而且年
轻的时候觉得熬夜没什么，但要知道，你25岁要是继续熬夜，熬到30岁，很大可能你会变秃。


4，不要忽略家人：家人比任何事情都重要，25岁以后往往会因为工作繁忙，很少有时间能
与自己的家人在一起。但你至少需要多去和他们沟通，聊聊自己的生活，不要多年以后去悲
叹“子欲养而亲不待”，后悔自己年轻的时候什么都没做。
** 
 六子拿着碗，盛着血肉模糊的一团东西向围观的民众高声喊：“看见了吗，看见了吗，是
 不是只有一碗？是不是只有一碗！？” 没有人关心他到底吃了几碗粉，围观众对那团东西
 到底代表几碗粉并没有兴趣。六子虽然还在声嘶力竭地辩白，人却已经走光了。 清白，是
 非，本身就不重要，对于那些围观的人，戏才重要。​
** 最自己
 生活充满惊喜，愿你流年不再孤单。
 
 一直以来，我在各种各样的地方都看到过：拥有拖延现象的人，一定程度上是有完美主义
 倾向的。所以当你拖延的时候，不要觉得事情很难，直接去做就行了。

 后来我每次下定决心去做某件事情之前，都说直接去干，不要管结果如何如何。

 但是一直不明白完美主义的意思。

 就这样我还是浑浑噩噩的。

 知道后来我通过观察那些不拖延，做事迅速的人，我才发现这句话之后的意义，可以称作
 一种思维转变吧。我发现那些人做的东西我都不满意，我觉得怎么能做的这么差？例如做
 ppt，基本的对齐都没做到。

 但是，你会发现，有一个需要改进的版本总比你一直在构想一个你心目中很好的版本，完
 美的版本要好。因为：想象再美好，那也只是想象。你觉得你的ppt应该怎样怎样，你觉得
 你的结果应该是完美的，不需要再修改的。所以你会觉得这个挺麻烦的，而且做不出完美
 的东西会很丢脸，会收到批评与鄙视。而现实是：如果你什么都不做才会收到批评。可能
 有时候我们总在猜测他人对自己的看法与评价，但是事实上可能他人也是如此。所以你为
 何只在乎自己给他人的印象，而不是真心的去帮助别人，与别人沟通，拥有同理心。

 所以：我现在慢慢的明白了，做一件事情之前不能给自己下一个好高骛远的目标。慢慢找
 到适合自己的量度和长度。不要太注重结果，注重一下过程。

 把一个浩大的工程分为一步一步小的可行的步骤也是这个道理。

 因为在这个过程中，你会明白不能够一次急功近利的完成一项大的目标，而是先完成小的，
 要求不那么严格的目标。若是总是把事情拖到最后才做，总觉得只有大块的集中的时间才
 能够做这件事情的话，那么你会越来越焦虑的。

 希望大家都能走在变得越来越好的路上。

 不畏将来，不念过往。
**  同事借我的球拍用，结果戳在台子上，握把给戳断了。

 我说，不值钱的，没让他赔。其实，球拍花了近一千块。我当然有点心疼，不过觉得球拍
 已经用了几个月，而且这只是个“玩具”，给同事要赔偿，有点不妥。

 这事就这么过去了，几天以后，我却亲耳听到那同事给别人说，我的球拍是本来就坏了的，
 握把那里有“暗伤”；而且我的球拍不值钱，不然怎么会“一戳就断了”；而且据他观察，
 我还犹犹豫豫得想让他赔，实在是……

 我火了，当时就把淘宝买拍子截图给他，要他七折赔我。他弄了一堆说辞，不想赔，我立
 即翻了脸，要揍他。他服了软，又解释不知道拍子这么贵，以为几十块什么什么的。

 有的人，你敬他一尺，他敬你一丈；
 
 有的人，明明损害了你的利益，你要原谅他，你不给他翻脸，不揍他，他就认为他才是受
 害者。

 答评论区的部分已经删掉。大家不要再做争论了。没意思。新拍子已经买了。谢谢各位。
 另外，我本人也有反思，比如是不是应该更从容淡定一些，或者是不是应该更“轴”一些，
 都需要慢慢考虑，沉淀。​
**  吕不同
 很多年前刚出来的时候，尽管一无所有，但我常会做一个衣锦还乡的梦。

 那时每天拧完几百个一分钱一个的螺丝后，我躺在乱糟糟的工厂宿舍里，常常畅想自己闯
 出一番事业，赚到一笔大钱，用漂亮的跑车载一个漂亮的姑娘回家见父母，让那些压根跟
 我没什么关系的人对我投来艳羡和钦佩的目光。

 那几年我觉得自己是在拼搏、上进，但我的性格却在不知不觉中变得暴戾，为人处世透着
 令人难堪的傲慢，什么都不会，但什么都看不起。而被别人看不起时，我又想，总有一天，
 总有一天，我会让这所有的俯视都变成仰视。

 如此浪荡了几年后，随着现实一天天向自己迫近，落在身上的冷眼越来越多，那个畅想的
 未来更是已经成了不中大乐透就无法实现的幻梦。

 那时我刚二十岁，按理说并不大，处于一个可以直接打电话问父母要钱的年纪。但想想自
 己出来五年了，一千多日日夜夜了，可依然两手空空，没有任何可以拿得出手的成绩。每
 年出来时什么样，回去时还是什么样，而在可预见的未来，这个事实也看不到任何变化的
 迹象。

 这让我莫名恐慌起来。

 人一恐慌，就会想方设法做一些事来证明自己的能力和存在。而一个人需要想方设法去证
 明自己的存在时，那折腾出来的事，肯定不会太好看。几乎把生活全搞砸了以后，我意识
 到了自己的心态出现了某种偏差。

 我开始想，为什么我会如此期望他人艳羡的目光，又会如此怯于向他人真心的表露自己的
 艳羡？

 我所期望的衣锦还乡，到底是想让操劳半生的父母过上日子，以一己之力庇佑家族里的孩
 子，还是仅仅是要站得足够高，让曾出现在我生活里的那些人仰视我、惧怕我、纵使恨我
 也要在表面上装出尊重我的样子？

 假如成功是为了让别人向自己投来的目光发生改变，那这成功，到底是我的，还是别人的？

 我毫不讳言自己讨厌那些有了点成就就不说人话，不办人事，把皮带头挂在屌上，连路都
 不好好走的人。可假如我混出了点名堂，在手中握有世俗资源的情况下，以我当时的心境，
 我首先会做的肯定也是不说人话，不办人事，拼命去折腾，去把自己的能力展示给每一个
 人看。

 我读高中时，身边很多男同学都在看网络小说，我看过一本，然后就觉得没什么劲，毕竟
 那时的我是不需要意淫的，那时的我触目可及，方圆十里，压根就没有能让我生出比较之
 心的人。但走向社会后，我突然无比渴望成功，而那时成功的吸引力于我而言，跟那些网
 络小说是一样的，就是想感受那种天上地下，唯我独尊的感觉，就是想让别人求我、畏惧
 我、对我战战兢兢。

 更要命的是，我还把这种心态当作热血。把那些轻视自己的人，当成恶龙。不考虑意义，
 不考虑父母，不考虑真正的幸福，就是想在有生之年，让人仰视自己。

 几乎每个哥们比二十岁左右的时候都做过一个站在落地窗前，俯视灯火人间的梦。但几乎
 没有任何哥们想过，落地窗之所以迷人，到底是因为它本身迷人，还是透过它去俯视的那
 个动作迷人。

 很小的时候，捡到没灭的烟头我就会去烫蚂蚁，拿到一把刀就想去砍树，摸到一把锄头就
 想去挖坑、除草，而当我手里什么都没拿的时候，我对蚂蚁和树以及大地都不感兴趣。

 长大后当然不会再去做那些幼稚的事情，但心底的残忍和有了机会就会给人带去伤害的本
 能，我知道，它们一直都在。我们大多数人之所以渴望的成功，不过是追求那个烟头、那
 把刀、那把锄头。我们痛恨自己变成那只被烫的蚂蚁，但一旦有了机会，我们一点也不介
 意拿起烟头，去烫别人。

 我倒不是反对成功，反对励志，而是在迷茫和堕落之后，我意识到自己过去追求的并不是
 成功本身，倒更像是追求某种可以肆意处置他人的能力。

 我不想讨论这种心态的善恶，尽管当今社会之所以紧绷如弦，跟很多人有这种心态有莫大
 的关系。我只是想说，当一个人出发时就跟自己的目标出现了本质上的偏差时，那走出来
 的路，一定不会如当初设想的一样。

 而在这条新的道路上，会有更多的不择手段，会有更多布满诱惑的岔道。多少人，不是毁
 灭于那些岔道，就是毁灭于最终发现纵使自己不择手段了，却依然看不见终点的绝望。

 我不知道这篇回答可以让多少人停下来调整一下自己的心态，认清自己的努力和奋斗的终
 极目的。但于我个人而言，我很庆幸在那样一个年纪就调整了过来。

 当然，调整了过来我目前也没有成功，只是在那之后，由于我不再去想当那个手持烟头的
 人，这个社会、那些与我无关的人、那些确实存在或者我假想出来的轻视目光，就再也，
 再也无法给我带来灼痛的感觉。
**  郁一
 有时候，你必须成为别人眼里的坏人。

 我小时候，非常听话懂事，而且内向害羞，完全不会像别的孩子一样那么会闹。大概是遗
 传的原因，毕竟我父母都很朴实，不会像某些人那样会算计。

 性格这面的善良，给我带来的最大问题就是不懂拒绝。

 举个例子。别人找我帮忙，这个事情明明他自己就可以做，我自然就觉得没有必要帮忙，
 就害羞地向他解释了原因。

 但只要他这时候摆出一副生气的表情反问我说：这点忙你都不肯帮吗？你随便弄下就好了
 呀！

 我的内心就完全招架不住，无论之前准备了多少如何拒绝的话，瞬间都无话可说了。反而
 还觉得很内疚，有点对不起他。

 为了不失去这个朋友，最后事情自然也只能替他做了，虽然这个忙可能花费了我很多时间。

 但当我有事情，实在需要他帮忙的时候，他理直气壮地我甩我一句，没时间。而且也不向
 我解释一下原因，一脸理所当然的样子。当时我就被气得发抖，又很委屈不知道说什么好。

 这个事情，真的让我陷入深深得思考，我用真心对别人，换来的难道就是这个？仔细想想
 才发现，我还几乎从来没有让他帮忙过，总是他要我帮他做这个做那个。

 如果一个人不愿意帮你忙，还总是好意思来麻烦你，那这个朋友交来要什么用？

 我知道这个后，就下定决心以后绝不和他再有联系。

 当他再求我帮忙。

 我也直接说，没时间。

 当他想道德绑架我，说我们是不是朋友啊？

 我回击，上次让你帮忙都不帮，你这种朋友交来有什么用？

 然后他就彻底闭嘴了，哈哈。

 我想他可能在心里会很恨我，觉得我这个人很坏吧。

 但这个对我来说，根本没有什么，因为我知道，和他有交情对我什么帮助都没有。哪怕他
 愿意帮我那一次，我和他之间的关系，也是他处在有利的那一方，毕竟我自己的事情喜欢
 自己做，不喜欢麻烦别人。

 大概后来，我就经常成为了别人眼里的坏人了，想拒绝就拒绝，谁想道德绑架我，直接让
 他滚蛋。

 我发现自从我这样开始对待我的人际关系，我心里再也没有那么多负担了，想做什么就做
 什么，反正我就喜欢一个人玩，把你得罪了，就得罪了，怕失去个毛。

 这不，有个很久没联系的高中同学突然和我联系，虽然隐隐约约觉得他会向我借钱，但我
 还是让他把话说完了，然后再拒绝。

 不管他会怎么评价我，我就直接这么说了。毕竟我以后肯定也不会向你借钱，那么好，不
 要浪费时间，还是直接拒绝为好。

 大家都想同事朋友对我们的评价能好一点，我也不例外。但你更要知道，不管你怎么做，
 你怎么讨好对方，有时候我们在别人的人生剧本里只能当个反面角色。

 至少知道了这一点，拒绝不再会是痛苦。
**  dopamine
 前阵子和表姐出去吃饭，她说了一段话就让我思维有了很大的转变。大致意思如下:作为平
 常人，与人相处，与人共事，都是喜欢占上风的，而后沾沾自喜。而你自己可能没有意识
 到，你所谓的占上风只是对于思想和知识与你在同一水平或者比你更低的人，对你自身并
 不算进步，更不算变优秀。真正的使你变优秀的人，并不是像这样衬托你的人，而是真正
 比你优秀，可以引导你，教给你一些比你现阶段拥有经验知识更丰富的人。这样，你才可
 以慢慢跻身于优秀之列，就算以后遇到强者，也可以泰然自若的站在他身边，而不是畏畏
 缩缩。

 谢谢大家的赞和评论，有评论说他们早就悟出了这个道理，不得不说他们真的很棒棒∽答
 主天生愚笨，最近才懂，略表惭愧。当然，有同感的我也很开心，想和你们握个爪。我发
 表的言论不可能让每个人都和我有共鸣，不喜勿喷。再次感谢大家的，阁下的心我收下啦
 ∽ ​
**  黄不会
 很多人质疑说：我忙起来应该是觉得时间变得更快而不是更慢。事实上，这是一个宏观和
 微观上的变化不同。如果你保持一成不变，那么就不会有成就感，就不会有“原来我已经
 走了这么多路”的回首与唏嘘，有的只是时间虚度的恐慌和最终接受。当你真的尝试做出
 改变，再进行回顾的时候，你才会发现你做了这么这么多当年想都不敢想的事情，时间在
 你脑海里是历历可见的细节与付出，而不是面目模糊的惊鸿一瞥和零散碎片。


 谢邀。我刚工作的时候，很多单位的同事和我说，你工作了以后就会发现时间过得很快。
 一眨眼一年就过去了，一眨眼十年就过去了。

 后来，我发现上班确实是这样。规律的工作，每天都差不多的工作量，偶尔加加班，压力
 不大不小，待遇不高不低，从周一到周五就是一眨眼就过去了。

 因此，在我工作一周年的时候，我甚至有点惊慌：一年时间就这么过去了？我怎么感觉入
 职仿佛就在上个月？事实上我工作之前也觉得一成不变的生活是很好的。平稳又安定，不
 需要多花什么心思。

 惊慌之后就是恐惧，显而易见的是，我不愿意时间就这么快地溜走，我得找出时间都去哪
 儿了。

 之后我问了几个朋友，你们觉得时间过得快吗？那些和我一样已经工作的朋友大多回答和
 我一样：是啊，时间过得实在是太快了！还没反应过来时间就走了大半。而从另外一个朋
 友那里我却得到了不一样的答案：

 我觉得时间过得太慢了，我整天在看书，每天都是精疲力尽，不知道这样的日子什么时候
 是个头。

 听到他这个话，我顿悟了。


 我们觉得时间过得很快，只是因为我们的生活一成不变而已。


 知道了这个事实之后的我，开始努力改变自己。

 我开始健身，开始学书法，开始研究摄像和摄影，开始学习排版和宣传，开始做公众号，
 开始研究新闻学和人物采访稿的写法。我给自己制定了详尽的学习计划，下一步我还准备
 花周末时间开始学习法语和吉他。

 只要是感兴趣的东西，我都愿意花费业余时间去学习，去了解。

 在工作上，我也不仅仅满足于依照原来的老经验，将工作做好。而是在完成工作的基础上，
 努力探寻自己力所能及能找到的新方法和新的思维方式。在完成工作之后，我开始追求效
 率，在效率提高后，我又在探寻新的可行方案去完成工作。

 这样的工作方式确实很累，我多做了单位并不会给我发奖金，也的确让我走了很多弯路。
 但辛苦总是值得的，比如在公司里存在着大量老旧的纸质档案，我花了近一个月的时间，
 牺牲午休和玩手机的实践，将这些档案手动输入电脑。再保存到手机里。下次再次找资料
 的时候，别人满头大汗的时候，我只需要翻翻手机就好了。

 可是数据处理本来就不是我擅长的部分，所以我最近又打算去学习个人的数据库建立和索
 引。学完了之后，就准备自己学编程，把数据彻底装进口袋里。

 所以，你问我觉得时间过得快吗？我会告诉你，一点都不。我每天都有必须要去做和处理
 的事情，等我一件件完成好的时候，已经很晚了。时间对我而言，并不是拿来消磨的消耗
 品，而是可以拿来兑换财富的宝贵筹码。

 很早以前看过一篇文章：许多人都说自己有几十年的工作经验，但其实并不是这样，他们
 只是把同一个经验用了几十年而已。上班之前尚无所感，上班之后心有戚戚。

 人在走上坡路的时候，总是吃力的。可我认为，正是因为这样的疲劳感，才是证明你一步
 步往上走的最佳证明。一帆风顺的人生就好像吃完不锻炼的肉体，迟早赘肉横生；不断学
 习的人生才会长出漂亮的腹肌。

 我在大学的时候出过报纸，为了学排版，每天跑到市区去看人排版，没人教，完全自己摸
 索。我在大学时候也喜欢写文章，一个人坐在那里憋半天改文章，去完网吧之后回来的室
 友有时候问我：你这么瞎折腾有什么用吗？

 是啊，有什么用呢？当时，我读的是工科，这辈子也碰不上宣传的事情；我以后也不可能
 会从事文职工作。这些努力让我当时看起来就和个不断在转轮里呼啦呼啦跑的仓鼠，做了
 半天都只是自己在努力。

 可是，真的是这样吗？我觉得并不是这样。很多时候，一个人额外的、微小的努力并不会
 被人注意到。一天背五个单词，一天跑步三公里，一天学一点点新知识。这些看起来微不
 足道的努力，在当时看都是无用的。可是，一天背五个单词的仁兄轻松过了四六级，过了
 雅思在准备出国；一天跑三公里的胖子变成了健身达人，励志男神；一天学习新知识的人
 变成了众人嘴里的博物馆，几乎什么都能聊一点。

 优秀的人并非生来优秀，他们只是看起来比较不会享受而已。

 然而，你还是你。

 之前看过一个人写过一篇我很喜欢的文章，叫《因为你一无所有，所以嘲笑别人不需要皱
 眉头》。

 你问我思维转变是什么？我只有两句话：永远不要放弃尝试与学习，永远不要嘲笑别人默
 默的付出与努力。​
**  林晨语
 有些人的堕落是自愿的，不是被人强迫，
 而我们眼中的堕落，是他生命的意义。

 我第一次在酒吧见到小太妹们的时候，我已经上大学了。像下面这样子的：

 虽然初中高中我身边也有同学去混社会的，有的享有极高的声誉，在一个小城市的同龄人
 中有号召力，有名气，处处是他们的传说，我初中班上也有几个女生不爱学习了，不服从
 父母管教或者是没有父母管教，流浪到社会上，跟这些人混在了一起。我那时候就喜欢打
 篮球啊，看足球比赛啊，心思虽然不在学习上，也没有被同龄人那些所谓的混得很好的
 “杂皮”裹挟和影响。我那时候看到初一跟我一起进校的女同学，初三就辍学了跟那些社
 会大哥一起混，还感到暗自窃喜，还好自己没有跟她们一样被拉下水。

 上大学后，开支陡增，为了赚钱，我就去酒吧做兼职，上班的第一天我就看到附近中学的
 “街娃”过来玩，看穿着打扮以及消费能力不是富二代，就是一般家庭的孩子。那天我有
 了一点触动，这些妹妹才十多岁怎么就出来混了呢？酒吧耍完了，第二天不上课的吗？我
 那时候开始有了点菩萨心情，为她们感到不值。

 接下来的日子里，在酒吧认识的人越来越多，听到的消息肯定也是越来越多。这些来玩的
 小太妹不是性工作者，很多都是在校学生，有很多原因让她们来到这些不应该她们那个年
 纪来的场所。有的人是厌学，找刺激；有的人是跟父母关系不好，叛逆；有的人是被朋友
 一起拉下水的，结果一发不可收拾，玩上瘾了。

 青春期的我们没有很强的自制力，虚荣心也强，学习不好，家庭不好，长相不好，你总得
 有什么东西比人家好吧？她们中的其中一些人就跟人比谁坏咯。比谁兄弟多，姐妹多，打
 架的时候比人多，自以为认了几个哥哥就耀武扬威的，那吃相很难看。

 “我抽烟，我喝酒，我泡吧，我纹身，但是我是一个好姑娘”

 这是她们某些人的QQ签名。

 小太妹是我对在社会上混的那群：12到20岁，不上学，不工作，爱打架，天天跟人混吃混
 喝的女性的一个统称。最开始在酒吧接触到这些人的时候，我是一种怜悯的心态，会想到
 他们父母的痛苦和这些人的前程被毁了，我还动过劝她们中的某些人回去上学的念头。我
 也不知道我当时怎么就那么圣母心。

 我工作的酒吧是完全禁毒的，如果被查到，一定会被封禁一段时间，旁边派出所的熟人也
 会经常来给我们提醒，叫我们不要涉毒。有一次晚上很早，才九点就来了一群人，他们要
 了一个大卡座，其中几个瘫坐在沙发上，抱着枕头睡意萌生。带头的要求我们DJ把慢摇音
 乐换成嗨爆的歌，由于是群老客户，经理就同意了他们的要求。音乐一响起，他们中的好
 几个开始摇头了，跟平时的跳舞不一样，他们忘我，尽情甩头，根据经验判断，经理说他
 们嗑药了，要我和另外一个工作人员去跟带头的确认他们是否有带药。

 我们上前把带头的拉到一边，说了我们的难处，他说他们在宾馆嗨了过来的，身上没有，
 不会给我们带来麻烦，只是找我们这个地方宣泄一下，我再三给他强调千万不能带药，他
 叫我放一百个心。我注意到他们这个卡座上的几个女孩最多只有十五六岁，我不禁唏嘘，
 感叹人生无常，好端端的学生妹就这么走入了歧途。这些妹妹是没有工资的，只要给她们
 吃，给她们住，有时候给点药吃，有时候发点零花钱，然后她发生了矛盾，你叫手下的二
 哥去帮忙处理一下，就会跟你睡。这样子的少女，我见了太多太多了，多到麻木。

 去年春节期间，我帮老家的一个酒吧招过酒托，我在网上发布招聘信息之后，高额的薪酬
 吸引来了很大一批有点质量的十五六七八岁的的妹儿。她们很多是老家职高卫校或者是其
 他中学的在校生，还有一些是辍学的少女。她们没有基础工资，每晚在酒吧充当小蜜蜂，
 不陪酒，如果有人过来在她们这桌消费，有百分之二十六的提成。很多都是一个同学拉一
 个同学来应聘，我也问过一些妹儿为什么要来做这个，她说看到宿舍的女同学周末有人来
 接，还是豪车，自从去了酒吧有了更多的零花钱，可以买很多漂亮的新衣服，高档的化妆
 品，我难免心动。反正我成绩也不好，也不指望读书这条路，反正有免费的酒喝，还有钱
 赚，还可以认识一些人，有什么不好的呢？

 没有意志力和信仰的人迟早会堕落。
 而所有的堕落几乎不是一步到位的，恶魔的种子总是在你心中慢慢发芽。

 也就是那时候开始，我对所有出来混的，被人骗的小姑娘不再抱有任何同情，也许那就是
 她们想要的快乐呢？的确我思维转变了，不再怜悯任何一个出来混的小太妹。她们发生纠
 纷，我看过很多次，一般不会用刀，拿酒瓶子啊，板凳砸啊，七八个女的围着另外一个或
 者两个女的，在酒吧外面的大马路上拳打脚踢，我也是见过的。你不觉得这些人可怜了，
 你觉得她们可恨，哪怕第一步往往是被人诱骗出来，但是谁也没有逼过她，走上这条路，
 纯粹是咎由自取。我也知道很多小女孩是一些社会人士的情人，不用情人这个词语，也可
 以直接用性奴，最开始的时候，我还会考虑到一个十多岁的小女孩被那么多人蹂躏，真是
 可怜，后来觉得她们是自作自受。


 你们可以脑补一下唐慧的女儿！她妈叫她不要卖了，她坚决要卖，连她妈都劝阻不了，我
 们可以吗？除非我们是菩萨，可是我们是凡人.

 我有一个远房堂妹，比我小两岁，从小到大没有说过五句话，只知道她的名字，过年的时
 候会在一个家族的聚会上一起吃饭。我大二的时候，回到家里，妈妈突然给我说，千万不
 要和那个堂妹联系哟，她得了艾滋病，找你借钱的话，你千万不要给钱。

 原来，我那个堂妹十四岁进去混社会，认识了一些不三不四的人，后来被一个黑老大包了，
 黑老大吸毒，海洛因，她也跟着吸，后来不知道怎么染上艾滋病了。我后来没有见过她，
 但是跟她爸妈一起参加过家族里面的人的婚礼寿宴，她父母抬不起头来，难以面对这个残
 酷的事实。她的父母是菜贩子，只是做得比较大的菜贩子，有自己固定的摊位，起早摸黑
 供她吃供她穿，女儿却走上了这样的路，怎么能让他们不心痛嘛？但是我们家族的人还算
 比较克制的，从来没有去问过他们女儿的事儿。

 我后来从其他的朋友那里倒是了解到，他跟的黑老大吸毒过多，死了，她还活着，但是不
 知道她在做什么。我害怕的是她去卖，把病毒传染给她人，希望她不要吧，为下辈子积德。

 我初中班上的女孩子，刚进初一的时候大家都差不多单纯，过了初一，大家的价值观开始
 发生了变化。有的女孩子把学习看的最重，有的更看重偶像明星，有的注重穿着打扮，而
 还有一些人崇尚社会上的暴力，觉得所谓的社会大哥能给她们明天。她们开始逃课，开始
 泡吧，开始发生性关系，甚至开始吸毒。同样的一个班出来，有的女生现在美国读博士，
 有的女生黑得不能再黑了，还有些进过鸡圈儿。不得不说，家庭教育确实太关键了。

 我没有研究过问题少女以及问题少男的问题，只是最近在场子里又看了大量的少年男女过
 来玩，玩得还很嗨，有没有聚众YL，或者嗑药，我不知道，我只知道这些小姑娘只有十四
 五岁。我想到了写下这些东西给高中生们看一看，特别是那些摇摆不定的意志不坚定的初
 中生，高中生，你们不要被拖下水了。如果你觉得跟社会大哥混很有前途，当我上面的字
 不存在吧，我不试图唤醒每一个人，如果有人恰好觉得有帮助，我会非常欣慰。

 其实作为我个人来说，越多的客户来玩我越开心，毕竟大家都不太讨厌钱这个东西，但是
 看到一些本该求学的小妹妹被人诱骗或者是裹挟着出来玩，我个人是不建议的，但是呢？
 来都来了，我就给你们好好安排吧。我不再会去劝阻任何已经黑了的人了，不过那些白着
 的青少年，快摇摇欲坠的时候，我还是愿意拉你一把的。

 青春期，我们叛逆，我们疯狂，我们渴望着新鲜，世界上的一切新鲜事物对我们太有吸引
 力了，有些人会迷恋网络游戏，有些人会迷恋酒吧，有些人会迷恋美女的翘臀，但是呢？
 最后那些大多数在社会上走上云端的人，青春期最为迷恋的东西大概就是无穷无尽的知识
 了。说句不好听点的，在大家读书的年纪你去酒吧歌舞升平，那些埋头读书，功成名就的
 同学们，未来再来酒吧挥金如土的时候，你可能是酒吧的保安，也可能是酒吧的清洁阿姨。
 我只是一个DJ！


 掩埋在阳光底下有太多的黑暗，而我可以恰好看到这些黑暗，你们无法想象有些青春期的
 女孩子堕落成了什么样子，亲自接触了，很恐怖，不是我戴有色眼镜，我奉劝各位远离，
 一旦缠上了你，你可开始倒霉了。学会辨别人吧，不要一有美女来找你喝酒搭讪，你就觉
 得是因为自己玉树临风貌似潘安的气质吸引了对方，她不过是受人摆布，来套你的钱而已。
 
 坏这个字，从来都不曾分性别。
 我们也不是佛祖，没有办法普渡他人，
 我也没有能力拯救任何一个堕落的人
 我只能拯救我自己，毕竟我要吃饭
 不再怜悯问题少女不是因为我不够善良
 只是我真的无能为力，那不是我的职责范围
 我选择视而不见，眼不见，心不烦
 老师从小那么苦口婆心教育我们不要乱来
 但是总有人会走入歧途
 劝阻是无效的，我不再劝阻，
 爱就一个字，我只说一次
 听不听是你的事.

 祝好
**  Lonely Planet
 这是一篇长文，如果你能耐心看完，相信以后对你看所有的新闻报道，都会有一个不一样
 的思考角度。


 以前学习马哲的时候，经常会嘲笑那些很傻的“经验主义”的人
 
 我们做选择题的时候会很鄙视地勾选：此人犯了典型的经验主义的错误。
 
 然而，我们正在犯的错误可能比经验主义更大
 
 我们常把一些错误的总结当作经验，并且希望复制这些经验


 一、
 热点已过，再也没有人继续讨论百雀羚刷爆朋友圈的事情了。
 当百雀羚接过凯迪拉克30秒贴片的热门传播时，我突然想到一个很悲凉的问题：
 
 每一天，营销圈正在发生的campaign少说也有成千上万，但我们只注意到了一个百雀羚，
 这意味着剩下的成千上万个创意的下场都将是落寞的。

 同样，“丧文化”的热度也正在消逝。
 
 我们记住了那个开在喜茶对面的“丧茶”，记住了“你的人生就是一杯乌龙玛奇朵”，可
 能稍带着记住网易跟饿了么这两个背后的品牌，而同期借助“有毒心灵鸡汤”的那些品牌
 都统统被遗忘了。

 创意一旦成功，便没有用了。
 这便是不具备复制性的经验，我们却一再得希望复制，结果只是为他人做了嫁衣。


 二、
 中欧国际工商管理学院教授Henry Moon(亨利 穆恩)教授，讲了一个很知名的案例：
 
 上个世纪20年代，某个公司买下了爱迪生的电灯泡专利。要知道那时候电灯还没有固定的
 市场，所以这家公司找了哈佛大学，让他们做一些研究，希望通过这些研究证明灯光是很
 重要的，这样大家就会买电灯了。

 研究者找到一个工厂，男工女工各一半分开工作的。
 研究设定也很简单：让员工干活，然后在过程中调节灯光的不同亮度。
 按照研究员的设想，灯光暗的时候，办公效率就低；灯光亮的时候，办公效率会对应提升；
 
 但是最后的曲线却是：女工的工作效果曲线不管灯光如何调节，一直在稳定上升，直到一
 个顶点后维持不变。

 当问题发生与我们预期不一样的时候，我们会找一个理论出来解释：

 于是有了第一个理论：
 
 1、在上个世纪20年代，女工的地位很低，而哈佛的大学生的观测会让她们感觉自己被选出
 来的，从而激发了他们的劳动热情；
 
 解释得通吗？
 解释得通。

 然后Henry Moon问了一个问题：如果这个理论正确，那么你可以第二天到公司，一直盯着
 你们的女下属工作，你觉得她会感觉到被尊重从而提升工作效率吗？
 
 并不会，她会觉得你有病。

 Henry Moon又接着补充了一个信息，研究员后来发现：平时员工的工资是固定工资，但是
 在实验中是计件工资。
 
 所以，有了第二个理论：
 女工为了赚取更多的奖金，所以会一直提高自己的工作效率。
 解释得通吗？
 解释得通。

 Henry Moon又接着补充了一个信息：一模一样的设置情况下，男工们的效率曲线是平的。
 这又是为什么？
 有一个理论说：
 男工相对女工而言，会让自己显得更酷，更不受环境影响；
 似乎也能解释得通。

 如果这些男工是理智的，难道他们不想多赚一些钱吗？
 
 于是又有一个理论：因为男工是要长期在工厂工作的，所以如果这次试验把效率提高了，
 他们担心以后拿固定工资的时候，老板就会要求保持这种工作效率。所以从长期博弈上来
 看，男工选择不提高效率。
 
 解释得通吗？
 解释得通。但是我已经开始怀疑，是否还有第三个参照组了。

 这个案例对我的触动很大，我们的理论都是事后的归纳总结，使得我们的理论只能是其中
 一种“可能正确”的解释方式，而不一定是其本质的真正原因。
 
 （至于女工为什么不考虑长期博弈，欢迎留言讨论）


 三、
 我们在这种事后的理论归纳上还耗费了大量的时间与精力，学术界还在尝试把这种事情复杂化。

 前不久去复旦大学参加了一场MBA的分享会，会上某教授在谈“共享经济”。
 
 他说他总结了目前的共享经济，提炼出了共享经济的几大特征，符合这个特征的才真正成
 为共享经济。
 
 比如off、mobile则不属于共享经济的范畴。

 几周后，我又听了北大某副院长关于“新零售经济”的分享。
 
 他说他总结了目前的新零售经济，提炼各种新零售经济存在的现状与优缺点，然后提出新
 零售的特征，符合这种特征的才能称为真正的新零售经济。

 我当时觉得很可悲的一点在于，我们总是对新出的事物尚未成型之时给出定义，然后教科书化。
 作为新生的事物，他们并不会根据我们的教科书来进化的。


 四、
 媒体的报道加深了这一趋势，我们所获悉的“成功／失败的原因”其实离“真相”越来越远。
 
 小米的充电宝无疑已经是充电宝市场的第一龙头。我们回顾当初关于小米的报道时候，很
 容易粗略得出结论：小米充电宝的成功，是源于对产品打造的极致、对供应链管理的极致、
 对期货应用技巧的极致；
 
 或者按照雷军的说法：“专注、极致、口碑、快”

 但是，小米真正低价的原因在于：做的电池的尾货市场。当平板电脑滞销造成电池的大量
 尾货库存，才使得小米能低价收购，生产出充电宝。
 
 之前有媒体报道过吗？并没有，直到小米已经稳坐龙头难以撼动后，刘德才出来说的。

 同样的情况，在oppo、vivo上也正在发生。
 
 oppo的副总裁说：他们一直在说我们线下渠道运营如何之好，但那只是我们做的众多事情
 里的一件。
 
 因为这一点与其它企业有明显可以描述故事的地方，所以被当做经验总结出来了。
 但这并不是oppo、vivo眼光格局长远而做的布局。
 
 oppo、vivo真正能够异军突起的原因：在于他们深耕的线下渠道刚刚好迎头赶上了三四五
 线城市的智能换机潮。

 所以，我们从媒体报道上所获取的经验真的对么？


 五、前一阵有朋友跟我说：你知道么，现在又专门卖试验数据的公司。这些公司可以根据
 你的理论要求，提供一系列的试验数据来证明你的理论正确。（我在上一篇文章中提过立
 场影响发言的事情。）

 其实，我们也往往从结果出发，去倒推原因，这跟买数据的做法其实没有什么两样。

 我们在讨论微博当初没落的时候，总结了诸多微信朋友圈的优势，说朋友圈更加干净纯粹，
 没有微博那么多的垃圾信息，也没有微博那种应该由媒体来承担的新闻属性，得出结论微
 博必将式微，朋友圈替代微博。
 
 结果当近几年微博又兴起的时候，我们又马上改口说：朋友圈是封闭的，只有微博才能实
 现真正的发声。

 同样，当微信崛起，降低了qq使用的时候，我们总结微信可以更快更直接地找到用户，效
 率更高。
 
 结果，后来90-00后大规模使用qq的时候，我们又有了新的结论。

 我们的原因，总是跟着结果来的，说明我们的原因经不起考验。

 当如今提及现在的乐视、现在的易到，似乎所有人都可以说出他们兵败如山倒的原因，并
 纷纷表示自己一直就不看好这个ppt公司。
 
 这让我想起令我一直很惭愧的几次论断：

 先是陌陌。
 
 唐岩刚刚创业的时候，便挖了我的一个朋友过去。但当时，我们都不看好，这种三观不正
 的东西怎么可能上市，怎么可能能盈利呢。
 
 再后来的故事大家都知道，先是陌陌上市，我的朋友实现了财务自由；
 再后来，陌陌接着直播的风口，通过直播实现盈利了。

 同样，当年各种打车软件刚出来的时候，我也跟朋友断言这个无法成器。
 因为当时打车软件就是用来叫出租车的，我觉得主动权根本不在打车软件手里。
 谁曾想到后来他们出了专车、快车，最后实现对这个市场的控制。

 我们很容易得到一个结论，但是忘记了得出这个节目的初始条件是否吻合。

 所以，我要问一个问题，如果乐视生态真的在构建过程中出现了类似陌陌的“直播”、滴
 滴的“快车”的产品，那么你们的断言还能成立吗？



 五、
 如果有一套的营销理论是100%成功的，那么掌握这套体系的人应该成为世界首富了吧。

 如果百雀羚的广告真的考虑了营销转化，考虑了配合产品的促销，考虑了全媒体的推广，
 考虑产品主推调性的把握，那么就一定能够成功吗？或者更简单地说：创意还能得到这样
 的关注吗？

 史玉柱作为营销的高手。
 
 他的经验经常被总结成：保持一支广告不变，集中预算集中曝光，连续打个十几年，这样
 才能不浪费广告。
 
 这样就一定对吗？
 至少不适合adidas、可口可乐这些时尚快消品。

 江南春经常提到的饱和攻击真的对吗？
 人心比流量更重要，在一段时间内集中攻击，占领产品心智。
 这样就一定对吗？
 至少不适合那些行业第三第四的品牌，因为心智就那么几个，品牌竞争对手却有那么多。

 就算那些经历过无数成功的经验被验证正确可行的，我们也要警惕它的使用条件。



 我们会给每一个事情寻求一个原因。
 这便是本能。

 事前预测很难，事后结论不一定正确。
 这便是现实。



 以上，希望对您有所帮助。
 Lonely Planet

 一个记录我和我的朋友们饭局见闻的公众号：饭局见闻
