* 焦虑 ( 想法多，无法完结，产生的紧张情绪 )
* 怎么让自己变得不懒惰与有上进心 
1、明确的目标
明确的了解自己想要什么，致力追求。
一个人没有明确的目标，就象船没有罗盘一样。
智者都有清晰思考的习惯。
意志力缘于持续的行动、自动自发、明确的目标。
诚实与努力的工作，需要明确的目标引导才能成功。
缺乏明确的目标，一生将庸庸碌碌。
坚定的目标是成功的首要原则。
2、行动
观察走在你前面的人，看看他为何领先，学习他的做法。
忙碌的人才能把事情做好，呆板的人只会投机取巧。
优柔寡断的人，即使做了决定，也不能贯彻到底。
善意需要适当的行动表达。
3、相信
相信你做得到，你一定会做到。
不断告诉自己某一件事，即使不是真的，最后也会让自己相信。
4、警觉
对于那些使狗和儿童感到畏惧的人应提高警觉。
警觉过度犹如不及，使人变得多疑。
不要羡慕邻居的篱笆更绿，或许荆棘多于青草。
对于满口“别人都说-----”的人，问他“别人”是谁，就会看到他张口结舌的窘态。
陌生人过分热心帮你做事时，当心他别有居心。
5、挑战
如果你想要更上一层楼，就为别人提供超出预期更多更好的服务。
每一次都尽力超越上次的表现，很快你就会超越周遭的人。
亨利福特悬赏 2.5 万元，征求有办法让他在每一台汽车上节省一个螺钉和螺冒的人。
你让我工厂的每个环节节省 10 分钱，我让你平步青云。
如果你一直保持现状，10 年后将会如何？
在你有把握做得更好之前，不要破坏任何东西。
6、主要目标
你的人生想要什么？你能付出什么作为回馈？
成功的人只想自己要的——而非自己不要的。
不要管过去做了什么，重要的是你将来要做什么？
如果你不知道你自己的一生要的是什么，你还想得到什么？
智者除了有所为，还能有所不为。
为自己想要的忙碌，如此即无暇担忧你不想要的。
不要怕目标定得太高，你可能需要退而求其次。
如果你不会知道自己要什么，别说你没有机会。
7、合作
请求比命令能得到更好的结果。
善于下命令的人，必定能够服从命令并且执行。
乐意合作产生支持的力量，强迫服从导致失败的结果。
告诉上司你想要什么，看他是否愿意帮助你去排除障碍。
友善的合作比煽动更得人心。
合作必须从部门领导开始，效率亦然。
狼狈为奸绝非合作。
除非你自己愿意被别人伤害，否则没有人能够伤害你。
8、勇气
勇敢的承认自己不知道的事情，才能学习并进步。
勇气只是多跨一步超越恐惧。
抱怨自己没有机会的人，多半没有勇气冒险。
9、批评
一事无成的无名小卒才能免于批评。
不要怕不公正的批评，但要知道哪些是不公正的批评。
不要批评你不了解的人，要趁机向他学习。
不要怕受人批评。当你提出新的观念，就要准备受人批评。
不要批评别人的行为，除非你知道他为何那么做。
你在同样的情况下也可能会如此。
不能忍受批评，就无法尝试新事物。
如果你经常批评别人，何不试着赞美别人？
开始批评之前，最好先略加赞美。
如果你想要更受人欢迎，尽量多赞美，少批评。
10、行为
真正伟大的人，别人会从他的善行感受出来。
一天没有臆见善行，就是白过了。
奖章和头衔不能让你上天堂，善行才能增加你的分量。
建设性的行为才能服人，言语的吹嘘无益。
不要说你想要什么，用行为表达。
善行是赞美自己最好的办法。
如果你比别人更具智慧，别人会从你的行为看出来。
善意的回应是惩罚对你不义的人最安全的方式。
对不喜欢你的人不要多费口舌。
花钱想要上天堂的人，一定后悔没有多行善。
善行比滔滔雄辩更能打动人心。
墓志铭不如善行更另人怀念。
世界不会因为所知给你勋章，而会因你的善行而给你荣耀。
善行不需要言语的粉饰。
11、正确的思考
先正确的评判自己，才有能力评断他人。
你是否欺骗别人，或是自己？想清楚再回答。
三思而后行的人，很少会做错事情。
企图说服不用大脑的人，是徒劳无功。
认为整个世界都错的人，极可能错在自己。
