#+TITLE: 离散的术语解释
#+DESCRIPTION: 一些术语的简单解释
#+TAGS: 术语
#+CATEGORIES: 术语 

* 计算机
** CGI [ Common Gateway Interface ]
   
   #+begin_verse
   外部应用程序（CGI 程序）与 WEB 服务器之间的接口标准
   就是 web 服务器如果开启了 CGI 接口，就能 执行外部的程序了,外部程序可以返回处理过的数据给服务器
   一般的 web 服务器 都支持 CGI
   动态网页就是这么来的，浏览器返回的不再是静态的 ~HTML~ 文件，而是 ~CGI~ 外部程序处理过的 ~HTML~ 内容
   还有就是处理表单，用的也很多
   #+end_verse
   

   处理步骤
   #+begin_verse
   ⑴通过 Internet 把用户请求送到 web 服务器。
   ⑵web 服务器接收用户请求并交给 CGI 程序处理。
   ⑶CGI 程序把处理结果传送给 web 服务器。
   ⑷web 服务器把结果送回到用户。
   #+end_verse

   编写语言: 任何语言都可以，一般是 ~Perl~ ，跨平台

   服务器配置:
   查看服务器的配置文档，一般 ~CGI~ 程序与网页文件放在同一目录
*** 环境变量列表编辑
    #+begin_verse
    SERVER_NAME：运行 CGI 序为机器名或 IP 地址。
    SERVER_INTERFACE：WWW 服务器的类型，如：CERN 型或 NCSA 型。
    SERVER_PROTOCOL：通信协议，应当是 HTTP/1.0。
    SERVER_PORT：TCP 端口，一般说来 web 端口是 80。
    HTTP_ACCEPT：HTTP 定义的浏览器能够接受的数据类型。
    HTTP_REFERER：发送表单的文件 URL。（并非所有的浏览器都传送这一变量）
    HTTP_USER-AGENT：发送表单的浏览的有关信息。
    GETWAY_INTERFACE：CGI 程序的版本，在 UNIX 下为 CGI/1.1。
    PATH_TRANSLATED：PATH_INFO 中包含的实际路径名。
    PATH_INFO：浏览器用 GET 方式发送数据时的附加路径。
    SCRIPT_NAME：CGI 程序的路径名。
    QUERY_STRING：表单输入的数据，URL 中问号后的内容。
    REMOTE_HOST：发送程序的主机名，不能确定该值。
    REMOTE_ADDR：发送程序的机器的 IP 地址。
    REMOTE_USER：发送程序的人名。
    CONTENT_TYPE：POST 发送，一般为 application/xwww-form-urlencoded。
    CONTENT_LENGTH：POST 方法输入的数据的字节数。
    #+end_verse
** IANA 管理的预留域名 [ 用于特定技术或政策 ]
  包括  http://example.org
   
  http://example.com
** irc /erc
   活跃频道 wikipedia-zh
   linuxba
   c_lang_cn
   emacs
   
