* 数学[[file:math.org][数学]] 
  数学包括微积分、线性代数、概率论与数理统计，计算机包括操作系统、计算机网络、数
  据结构和算法。这些知识可能在目前的工作中用不着，但是在未来的某个时候这些知识就
  可能让你灵光一闪。coolshell的创始人，业界大牛
 
  陈老师有一次给我们做分享，聊到他的一个故事。一个创业公司带宽老是不够用，请他去
  优化系统，他看了一会代码就发现某个底层网络冗余调用。他半天写了700行代码重构了
  整个架构，带宽比原来省了一半多，一年省了大几百万。创业公司CEO给他转了5w块，他
  有点不好意思，想推脱，CEO以为嫌少，又给他转了15w。半天700行代码卖20w，给跪了。
  陈老师说他看过多遍《TCP/IP详解》1-3卷。知识在某些时候一定会像金子一样闪光，是
  真的金子(捂脸。

* 计算机
** 操作系统[[file:os.org][操作系统]] 
** 计算机网络[[file:network.org][网络]] 
** 数据结构和算法[[file:algorithm.org][算法]] 
* 项目
* 饮料
** 绿豆薏仁汤　　 　　

 绿豆可以清热解毒、利尿消肿，薏仁则可以健脾止泻，轻身益气，对于经常需要熬夜工作
 者或是心烦气躁、口干舌燥、便秘、长青春痘时，除了多吃蔬菜水果与补充水份外，把绿
 豆薏仁汤当点心食用，对于消暑除烦非常有帮助。
** 绿茶

 　　绿茶是近几年来最为人所津津乐道的养生饮品，因为其中含强效的抗氧化剂儿茶酚以
 及维他命C，不但可以清除体内的自由基，还能使副肾皮质分泌出对抗紧张压力的荷尔蒙，
 当然绿茶中所含的少量咖啡因也可以刺激中枢神经，提振精神。最好在白天饮用以免影响
 睡眠。
** 枸杞茶

 　　枸杞子含有丰富的β胡萝卜素，维生素B１、维生素C、钙、铁，具有补肝、益肾、明
 目的作用，因为本身就具有甜味，不管是泡茶或是像葡萄干一样当零嘴来吃对计算机族的
 眼睛酸涩、疲劳、视力加深的问题都有很大的帮助。
** 菊花茶

 　　有明目清肝的作用，有些人就干脆菊花加上枸杞一起泡来喝，或是用蜂蜜菊花茶都于疏肝解郁都很有帮助。
** 决名子茶

 　　决名子有清热、明目、补脑髓、镇肝气、益筋骨的作用，若有便秘的人还可以在晚餐饭后饮用，对于治疗便秘很有效果。
** 杜仲茶
 　　杜仲具有补血与强壮筋骨的作用，对于经常久坐，腰虽背痛很有帮助，男女都可以喝，
 若是女性朋友还可以在生理期的末期与四物汤一起服用。

