* 经济学
经济学是不是很复杂？
读懂两个人就够了，亚当斯密 和 凯恩斯。
整个世界的经济体系都在围着他们的理念转。
这两人的理论两字总结：供、需。

赚钱两字总结：买、卖。
衡量一个项目能否做，只看两点足矣。

* 经济学
是研究人类经济活动的规律即价值的创造、转化、实现的规律——经济发展规律的理论，分为
政治经济学与科学经济学两大类型。 政治经济学根据所代表的阶级的利益为了突出某个阶
级在经济活动中的地位和作用自发从某个侧面研究价值规律或经济规律，科学经济学自觉从
整体上研究价值规律或经济规律。对称经济学就是科学经济学。经济学的核心是经济规律；
在对称经济学看来，资源的优化配置与优化再生只是经济规律的展开和具体表现，经济学的
对象应该是资源优化配置与优化再生后面的经济规律与经济本质，而不是停留在资源的优化
配置与优化再生层面。停留在资源的优化配置与优化再生层面的，是政治经济学而不是科学
的经济学。 要研究经济发展的规律就必须从整体上统一研究经济现象，宏观经济与微观经
济是统一的经济体中对称的两个方面，所以在科学的对称经济学范式框架中，有宏观经济与
微观经济之分，没有宏观经济学与微观经济学之别；而政治经济学总是把经济学分为宏观经
济学与微观经济学。

* 有什么经济学技巧可以用于日常购物？
温义飞
温义飞
​
经济学 话题的优秀回答者
编辑推荐
共 3 项收录
47,883 人赞同了该回答
今年回国期间，我陪我妈去过一趟超市，买一些零食还有国外管制的消炎药。那是一间当地的卖场，门脸熙攘，嘈杂混乱。
然而走进去没几步，我就立刻察觉到了这件超市的独特气场，
“有高手。”我凝目开始观察。

这店出入分门，右进左出。人群中大多数人惯用右手，这样的分布结构便于人们从货架上拿东西。
入口处的装修色调偏冷而悦目，会减慢人的步幅。 一旦大多数顾客下意识的开始缓步，走太快就会显得格格不入。
平均身高的水平视距摆着高利润的商品，这是零售业的基本常识。可是在儿童水平视距上摆上零食和甜品，让我不禁暗赞了一句好身手。

每一个超市都是一个猎场，你可能是猎手，也可能是猎物。你是否认为是你自己在作出购物的决定？行为经济学和心理学发展到了今天，我们早就认识到了“理性人假设”的天真。消费者在购物的时候从来都不是理性的，商家们明白这一点，而且不断在利用顾客的不理性。

我在买东西的时候总是问自己三个问题，让自己计算。

第一个问题就是“为何这样卖”。只有当你知道商家在如何影响你的判断，你才能排除这些干扰，做出有利自己的选择。我们继续用超市当例子。

超市的生活常用商品往往在店内最深处。鸡蛋，牛奶之类的产品能吸引你逛完整间店。舒缓的音乐和明亮的装修可以延长顾客的逗留时间，这往往就意味着更高的销售额。所以做生意的朋友，请别在店里放"新年好“或者其他快节奏的音乐。

大型超市的地砖从来不是统一的。在高利润的几排货架区，地砖会有让人感觉“高级”的材质和花纹。如果还有行家指点，这里的地砖会略有不平，这样当顾客推车经过时，会下意识的减慢速度。

店家的心机还远不止于此。高手会在商品价签上删掉“元”“￥”等符号和字眼，一个单纯的数字价格会减少商品和钱的逻辑关联。根据TIME杂志上的统计，使用“$"符号价签的Campbell’s罐头汤，每103个顾客才会有一个购买，而改用纯数字的价签，每14个客人就有一个购买。

当你看到“限时抢购” “每人限卖三个”之类的标志时，是不是觉得并不会影响你的决定？然而你嘴上说着不要，但是身体还是很诚实的躁动，点解？这是由于人类进化过程中产生的天性，对被限制供应的物品，特别是对有限食物的储藏是会带来生理快感的。“限时抢购”会刺激你体内的多巴胺分泌，再聪明的人也没办法控制自己的激素。

我们知道，对超市来说更高的利润，对顾客来说就是不太划算的支出。因此每次我逛超市，都会利用超市的设计，在边边角角的货架找性价比，在推车时保持速度均衡，永远不碰在收银台排队时手边的那几样商品，那是全超市利润最高的存在。
如果你很难把经济学的逻辑和对手的心机随时放在心上，最好的办法是去之前列一张购物单。

我问自己的第二个问题是“本身的价值是什么？”这是个很好理解的理论，我们在买东西的时候，支付的不光是东西本身的生产成本，还有包括广告，人工，地租等等在内的价格。所以我每次回国去药店买药，都会要求药店店员帮我推荐，然后把他们推荐的品牌全部排除。原因很简单，药品的回扣是公开的秘密，店员推荐给我的药一定是他们收回扣最多的药。如果同样的价格，一种药多支付了回扣给店员，那它的质量一定会比较差，不然就无利可图。同样的道理，那些流量很大销量很广的快消品，比如可口可乐和（此处承接广告），每一个产品中的附加成本就很低，买起来比较划算。我无法知道每样货物的生产成本，但是我大概可以猜出它的附加成本，而附加成本过高的商品往往不太划算。

为什么我在上面接广告之前要加上可口可乐？这就是在利用各位读者大老爷们的“锚定心理”。这也是跟我的第三个问题相关，即“对我的效益是什么”。不客气的说，大多数人在消费时并不清楚货物本身的价值。当年珍珠王萨尔瓦多开发出黑珍珠的时候，并没有多少顾客，因为没人知道它值多少钱。于是他们把黑珍珠放在第五大道耀眼的橱窗里，在所有提及它的广告里放上钻石和红宝石。自然，黑珍珠从此新晋成为名贵的珠宝。最常使用“锚定”手法的商家应该是家居行和电器行。很少有人真的知道一件家电的成本，但是如果把冰箱A和一个功能相似但是贵百分之三十的冰箱B放在一起，人们自然会想要买冰箱A来占便宜。

你不可能了解每一个你要买的东西，但是你可以了解你自己。在购物时建立自己的效益体系会让你受益。最简单的方法就是找一个能持之以恒带给你快乐/幸福的货物，以它的价格为标杆来衡量其他消费是否值得。比如，你最喜欢吃街角的四川火锅，每次去吃要花200块，你觉得价格合理并且心满意足。那么，每当你无法决定是否要买新东西的时候，就可以把它换算成火锅。一台PS4不再是2000块，而变成了10顿火锅，你不需要真的知道PS4的成本，但是你知道10顿火锅是至高荣耀，可能就会冷静下来不要买PS4了。这种购物理念不一定能帮助你买到客观上最物美价廉的商品，但是一定是给你个体带来极高效益的商品。同理，在追你的女神的时候你想送她一个杀很大的包包，然而这个包可能价值50顿火锅，而你认为女神带给你的快乐大约只有30顿火锅，那么，港真，你真的会。。。。孤独终生。

提到女神和包包，顺便来讲讲奢侈品。奢侈品的定义有很多种，但是我觉得它的本质是稳定的提供高质量商品的品牌，这个特征不是每一个人都需要的。要知道，商品的价格和品质不是简单的线性关系。一件普通的衬衫卖100块，一件用料稍好的衬衫200块，一件用料，设计和针脚都很好的高级衬衫卖1000块。可是第二件衬衫并没有普通的两倍好，高级衬衫更没有普通的十倍好。如果你很有钱，当然支付一千块买高级衬衫，虽然200块的衬衫里可能也有不错的，但是那需要你花时间去挑选。007整个衣柜都是tom ford,又挺又贵，但是其实有些冷门牌子也能穿出接近的效果，可你总不能指望他能空出一个下午不装逼不把妹不杀人的去逛商场吧？然而奢侈品的高价格是一种高品质的保证，不代表低价格就买不到高品质的商品。所以我不支持很闲的人买奢侈品，因为他有精力在替代品中选到品质接近而价格大幅降低的相似商品。更不要提，我们上文提及的附加成本。奢侈品牌的租金，柜员和广告费用高昂，你在购买时，必然要承担这部分对你无益的开支。当然，如果我家败家老娘们买了开心，我就觉得应该买买买，划不划算又如何？难道我还打得过她？正所谓见大利而不趋，闻祸端而不备，浅薄於争守之事，而务以仁义自饰者，可亡也。这也正是我想说的最重要的技巧，你买的开心，就是值。

总之，我们永远无法在购物时了解每一个商品的市场价值，完全理性的购物是不存在的。既然我们无法从的货物角度选择，那么，我们可以站在卖方的立场破解心理暗示，然后以生产者的立场衡量广义成本，最后回归自己内心的体验来做出购买决定。

Reference:

Martin Lindstrom. "What Your Supermarket Knows About You", The New York Times, Oct. 21, 2011.


用知乎大半年了，这是第二十个答案，感谢朋友们一直以来的关注。我看到有人说，在知乎上面免费答题是在浪费所学。但是这些我通过读书，谈话和思考总结出来的知识，本来只有我一个人在使用，放到知乎上以后，就有几千几万个人在受益。你告诉我，我到底是在浪费这些知识，还是在让它们变得更有价值？

目前我在知乎的回答，只需著明出处和作者，且非商业推广用途，可随意转载。商业用途请按稿费标准捐给希望工程，私信发送收据给我，即可获得授权。
* 非洲为什么这么穷？
非洲之所以穷，是因为长久以来没有基建、没有教育、没有走社会主义工业化道路。

别笑，后殖民时代，贫穷落后的地区，只有社会主义工业化一条路可以走。

常在世界各地走的朋友，都会发现一件事，全球化+市场经济这么多年了，生产力得到了很
大的提升，但很多地方的贫富差距似乎并没有缩小，反而越来越大了。

比如说非洲，你去非洲最穷的国家旅游，也能看见豪华的别墅，但99%的人还是住着草窝棚；
比如说印度，你要去孟买，就会看到天堂地狱并存的风景，隔着一条街，一边是堪比上海外
滩的高楼大厦，一边是垃圾遍地、污水横流的贫民窟；他们国家的精英和富人，更愿意发了
财之后立刻移民到发达国家去，而国内绝大多数人，却在贫穷的深渊中越来越穷？

举个例子，你去中国最边远的山村看一看，对比一下十年前，都会感受到惊人的变化，最起
码的，有了横穿山脉的公路铁路，甚至有了高架桥梁，通了了水、电、网，有了手机信号，
有的人盖了新房子，大家手里有了智能手机，很多人家里还添了彩电、冰箱，虽然不是最新
款的，但是他们都有，而且以这一切为纽带，开始融入现代文明。

但非洲和印度的农村不是这样的，他们现在和十年前没有区别，当年住草窝，现在还是住草
窝，当年用水桶去十几里地之外提水，现在还是如此，没有公路、铁路、自来水、输电和通
信网络。那些欧美白人“慈悲”地报道这一切，他们大学生们来施舍一些衣服食物，教两句
英语，念两句上帝，还要赞美一番“原生态”的淳朴和善良


一位派驻非洲近十年的五百强企业员工告诉我，在非洲，除了中国人是真心在搞建设，其他
的所有NGO组织，都是在表演作秀搞事情，但偏偏普通人很吃那一套。

很多去非洲、印度旅游的人们会告诉你——哎呀，他们就是懒啊，上午10点钟上班，下午两点
钟就下班，当天结了工资，第二天就消失，没饭吃了才会回来干活。

其实——这是一种不动脑子的种族主义言论，当年，西方殖民者入侵中国的时候，也是这么歧
视我们那些留着辫子的祖先的。社会达尔文主义者也是这么污名化穷人的，他们认为，穷人
之所以穷，就是又懒又笨。那么，现在的美国人不懒吗？法国人不懒吗？中国没有懒人吗？
为啥他们好歹能吃饱？

但是我认识的去非洲搞建设的华为、中兴、中石油、中建员工、联合国维和部队的士兵却告诉我——瞎扯淡呢，都是一样的人，只是没有受过教育而已，和咱们一起相处久了，耳濡目染，读书明理之后，人家会和咱们一样勤奋。

B站有一部关于中国援建肯尼亚蒙内铁路的纪录片，大家可以去看一下，我觉得看完之后，所有被种族主义蒙蔽了双眼的人们，都会放下成见，去重新看待这个世界。那些和中国工程师、工人一起工作的肯尼亚年轻人，最后在工程结束的时候，都成了这个国家铁路工程建设和工业化的中流砥柱，你最后看他们的神情，看他们整齐的制服和统一的肢体语言，你会惊奇地发现，虽然肤色不同，但他们的气质，已经很像我们那些吃苦耐劳、淳朴坚韧的中国工人了。有个肯尼亚的小伙子回忆道：来自中国的工程师成了他的师父，教他一种材料的配比的时候，由于他操作粗心，师父骂了他，最后告诉他一句话——你要好好学啊，我走了之后，你就是你们国家这个学科的奠基人了，你要知道你身上的责任。




如果援助贫困落后地区的人们，都像这位中国工程师这般无私、努力、国际主义，我相信这个世界终将会实现共产主义，会共同富裕。






蒙内铁路通车那天，肯尼亚总统激动地说：”今天，我们为新的工业化的篇章，打下了基础。“

在肯尼亚，有4万多人参与了这个项目的建设工作，其中当地员工占比超过90%。目前，有超过1500名当地人参与蒙内铁路的运营。因为蒙内铁路，他们不仅找到了好工作，而且过上了更好的生活。

蒙内铁路通车后，货物运输时间从原来10多个小时缩短至4个多小时，物流成本降低40%以上。铁路建设拉动了肯尼亚国内生产总值1.5%甚至2%的增长，更关键的是，通过铁路形成了包括港口在内的全产业链发展。

在不到一年的时间里，大约有70万人次乘坐蒙内铁路的列车。蒙内铁路货运服务也得到大幅提升，起初每月可运送22345吨货物，现在每月可运送213559吨。

蒙内铁路，是个很好的援非标本，但实际上能够做到这样的，并不多见。因为这个世界的价值观，已经被欧美资本主义主导了上百年，那些贫穷落后的地区，本就是欧美的殖民地，非洲被称作是法国的后花园，也有很多地方是美国人的势力范围。那些当地的非洲人，耳濡目染的都是白人的富裕和强大。

殖民主义遗祸万年，很多地区的土著黑人们被他们打怕了，剥削惨了，早就失去了自信和坚强，他们畏惧、依赖、甚至是谄媚西方国家。而资本主义娱乐文化的兴起，又给了他们幻觉，比如法国在非洲发掘几个足球苗子，NBA在非洲发掘几个篮球明星，这就给他们带来了希望。而这些成名、富裕的非洲人，往往急于摆脱自己的原生民族，加入到宗主国去，成为上层精英，你指望他们先富带动后富，是不可能的。

就像是印度的精英们，他们个人的知识和修养一点都不差，甚至可以成为世界顶级的软件工程师，甚至可以入主微软的这样的超级科技公司。但他们骨子里不把自己再看作是印度人了，他们也不会回到自己的国家，去帮助更多的人民。

那些贫穷的地区越来越穷，是因为殖民主义残留的社会达尔文思想还在作祟。

中国人援建扶贫的这些个方法，太慢了，太幸苦了，他们不是那么容易理解，但从基建、教育做起，才是工业化的必由之路。

办过企业、开过工厂的人都知道，你想要在一个地方办厂，总得有工业用地吧？总得有高效的基层行政体系帮你审批吧？总得有平整的道路、通电、通水、通网吧？总得有公路、铁路、港口可以运输材料和产品吧？总得有认识26个字母、阿拉伯数字、能写会算、接受过基本的技能培训的工人吧？你没有这一切，怎么办厂？怎么搞企业？没有基建和教育，工业化就是空中楼阁。

自由派经济学家只会告诉你市场决定一切，却不会告诉你，市场是个嫌贫爱富的婊子，她不会看上一无所有的国家和地区。西方殖民非洲数百年，输出了基督教，输出了普世价值，掠夺了原料和劳动力，却没有输出他们的基建、教育和工业化，以至于非洲大部分国家和地区，还是只能靠卖资源为生。

近年来，美国一直在丑化中国在非洲的建设，称之为”新殖民主义“，但明智的非洲人已经看出，中国的道路，是落后地区富强的唯一道路，加纳领导人就曾在联大会议上驳斥了美国人的谬论。

“我们必须让我们的人民接受教育和培训，这些我们正在做。我们必须解决基建赤字问题。要解决这个问题，传统方法是不行的。我们正在寻找解决问题的新方法。与非洲许多国家一样，加纳正在与中国加强关系，以帮助解决我们的部分基建赤字。”

“当年，是西方帝国主义把中国变成了半殖民地，今天，那个西方帝国主义的前受害者，正向亚洲、非洲和欧洲的国家提供数十亿美元的贷款，不仅用于建设铁路，还建设高速公路、港口、发电厂和其他基础设施以及许多商业。”

“我们，加纳，必须建设道路、桥梁、铁路、港口、学校、医院，我们必须创造就业机会，以保持年轻人的参与。对我们来说，很明显，我们已经持续了几十年的发展轨迹是行不通的。我们正在尝试另一个（发展道路）。”
在非洲，越来越多的人开始睁开双眼，重新审视这个世界，真理正在通过实践的证明，到底是谁导致了非洲的贫穷？












在我们国家，也有很多人不理解我们的基建投入，经常有人发牢骚，说国家为什么要投入那么多在边远地区修铁路、修大桥、穿隧道、修公路、建基站，甚至在群山之间架桥梁，在高原冻土上建铁路？有些没有脑子的人甚至说——那些地方穷，就让他穷下去罢了，干嘛要这么折腾啊？


这些人啊，实在是又蠢又坏，如果中国也学西方、学印度，学非洲某些国家，对落后地区不闻不问，对穷人放任不管，把贫困地区当作垃圾场，我们和当年的民国还有什么区别？我们还哪来的工业化？哪来的世界第一工业国？我们有怎么会有国家电网、中铁、华为这样了不起的企业？没有全国范围内畅通无阻的交通，没有覆盖全国的通信网络，没有广大受过基础教育的劳动力，哪来繁荣的市场经济？我们要消灭贫穷，而不是消灭穷人！


对贫困落后的地区放任不管，任其自生自灭，美其名曰保护多元文化，保护原生态，那是自私和伪善，那才是在消灭穷人。

很多人都被美国现代的”普世价值“忽悠瘸了，认为对落后地区要保护其文明，尊重文化差异，其实意思就是不管人家的未来发展，继续搞殖民地经济，把所谓的文化当作原始人标本来欣赏。然而美国自己走的却不是这一条路，他们曾经也是英国的殖民地，你们翻一翻《美国通史》，美国为什么打独立战争？要打南北战争？为什么搞西进运动？美国建国后修了多少公路、铁路？开了多少工厂？使用了多少劳动力？

基建搞好了，教育普及了，信息传播了，商品流通了，工业在当地扎根了，现代文明才会真正进入当地，形成一个良性的循环，这才是真正的扶贫。终有一天，这些脱贫的地区和国家，同样会正向反哺整个现代文明。

一个人、少数人变得富有了，超越阶层了，那不算消灭贫穷，只有大家都能有饭吃，有书读，有工作，那才是消灭贫穷。

世界大同，才是人类最崇高的奋斗目标啊。

* 面试的时候，销售经理让你把一瓶矿泉水卖 300 元，你会怎么应对？
Ye Ben
Ye Ben
​
特许金融分析师（CFA）持证人
知乎日报收录
35,357 人赞同了该回答
早年我进海航被问过类似问题，当时好像他们收了两千份简历，我们学校最后录取两个，其中一个是我，给几个思路吧

1，这个水有没有稀缺属性? 
1.1水质稀缺，比如是法国哪个小镇的天然矿泉水，比如是某活佛开光过的水

1.2 售卖环境稀缺，比如高速公路堵车几个小时，水源有限，高价得之

2，外部属性添加
2.1 比如为慈善筹款卖300，捐款人不会对定价敏感，会买
2.2放到高端会所，机场vip，顶级餐厅去卖，比如欧洲的顶级餐厅，40，50欧一瓶水，可以接受的

3，内部属性设计
问的是一瓶水，并没有说这个瓶子做多大，瓶子用什么做
能做成50升的大瓶子吗？卖300不多的，能用水晶做瓶子吗，卖300那很便宜了，其实酒里面很多这种，高端威士忌有不少

4，艺术属性添加
4.1说服某装置艺术家采纳这瓶水作为以后某艺术装置道具，300卖的便宜了

4.2继续和艺术家合作，瓶子设计成各种造型，和3不同，这里都是普通材质的东西
4.3 做成艺术作品，名字就叫一瓶水，拿到国外参个展，回来卖十万，卖给美术馆

5.上面的都不让你做，要你五分钟内马上卖，好的，要么卖不出，卖出也是坑人，那么我自己买，就一瓶么，300块，当作入职贵司的诚意表达



好多童鞋关注点在于最后是只能花300买水回家，我觉得还可以提供一点思路大家参考，比如

6.300块卖给面试官，一分钟以后以310元回购，相当于只花了10块钱就完成了任务，对于买方来说，无成本得到10块钱，边际收益还不错

7.如果6的方案有贿赂之嫌疑，还可以组织所有的面试者，我们假定15个人，大家组成攻守联盟，1号面试人300元卖给2号面试人，2号再卖给3号，最后15号面试人面试完毕后，大家一人出20元拿到这个水的资产的十五分之一，相当于每人只花了20元，算是一个低价解决所有人通过面试的整体解决方案了，也可以参考。



方法很多，其实HR考察的是你的思维过程，大家以后面试注意这一点就可以了，先做到看山不是山即可。不到万不得已，切勿一脸苦大仇深的告诉面试官：

你们这样是不对的，是欺诈，是忽悠。

如果我是HR，我对这样的童鞋有两个印象，第一，不好管理。记住你是基层员工的话，你首先要做的是执行，而不是质疑，所以任正非提到进来的新人谈战略直接让他走人；第二，思维发散性不够，创造力缺乏，也就是综合知识的积淀太少，可能可以用到社科、经济金融、人文艺术等等方面的知识来解决问题，你积淀越厚，越能用各类模型处理各类问题，这种能力，咨询公司，投资类企业尤为看重。

如果我是HR，我也会说，“这位童鞋，我说的是一瓶水，并没有说这是多少毫升装的农夫山泉，换言之，这瓶水不是标准品，价位要根据水的综合情况决定，你考虑到这些了吗？”

在实际工作或者生活过程中，很多问题的解决条件是未定的，甚至要自己动手来做工具来解决，你答题的态度决定了你是否有意愿主动的创造条件，创造模型来解决问题，记住，这是一个态度问题，甚至比能力更重要，优秀的面试官看的是态度，因为能力可以培养。

以上，渔和部分的鱼都给你们了，祝参加面试的各位童鞋好运。

编辑于 2017-09-10

* 一个精英的诞生，家庭因素有多大？
Feifeimao
Feifeimao
微博去搜：知乎肥肥猫
34,823 人赞同了该回答
很多人有个误区，他们说现在的社会“上升通道逐渐关闭”、“阶层日益固化”，是社会病了。但其实，这才是社会原本的常态。中国过去的两千年里，大部分时间都是如此。西方这种数百年稳定的社会，阶层固化更是早已天经地义。


阶层剧烈变动的年代才是历史的异态。“旧时王谢堂前燕，飞入寻常百姓家”之所以成为千古名句，恰恰就是因为这一幕不多见，不常见，很稀奇。时人异之，才产生了文学效果。一个流动性过大的社会，一定是制度不完善的，完善的制度不会容忍高流动性。


但恰好，我们这代人的祖辈和父辈生在了中国数百年来变动最剧烈的几十年里，每个大家族都有那么几个人的人生之跌宕起伏，简直可以拿来拍电影。中国在短短一百年时间里，经历了不下七八次政权变更和近乎180度的政治转向。《霸王别姬》、《大宅门》这样的影视作品之所以成为经典，就是因为成功反映了我们这一百年来的个人命运之不可预测，并引起了亿万家庭的共鸣。


这种人生经验导致我们这几代人误把这种阶层大幅波动的局面当成了世界的常态。而最近20多年看着尘埃落定，要回归历史长河的真·常态了，很多人就不适应，受不了了。


良好的家庭环境在任何年代都会极大的帮助后代晋升到社会高阶位置。将相无种只是平民阶层的幻想和安慰剂，尽管这句话是中国普通人千年来的精神支柱（甚至可以上升到民族格言），但最先喊出这句话的陈胜吴广，最后改变了他们的阶层吗？


精英阶层在历史上名头多变，无论你管他们叫什么，豪强、士族、门阀、权贵、集团、派系、二代，当他们作为一个整体出现的时候，首先是一座城堡。城堡的第一功能，是防住别人再进来。所以先进来的人，会不断地增加城墙的高度，以阻拦尚未进来的人挤来摊薄自己的特权和福利。不过他们会把砌城墙的行为包装一下，使得普通人很难分辨。


今天精英阶层的一项杀手锏，在于他们会为子女预留许多人生止损线：毕不了业可以就业，无心求职给钱创业，开拓业务刷爸妈的脸，就算一事无成，还可以当个列席者。所以精英的后代，人生是被设了下限的，差不到哪里去。


下限有限而上不封顶，这就是这群人开挂的地方。何况精英阶层还会以相互之间彼此关照对方子女的方式强化这种机制，关照了别人，也就等于关照了自己，这早已是城堡里的潜规则。与这种大招比起来，那些所谓的“增长视野”、“减少摸索”的好处都只能算毛毛雨。


现在主流意识形态开始鼓吹中产阶级的崛起。什么是中产阶级？以专业人士为代表，中产阶级的本质，是精英阶级的随从，是精英分配-酬劳体系中的一环。如果精英是躲在高高的城堡里，中产阶级就是拱卫着城堡的一圈外城。外城依附于城堡，但又优越于再外层的乡野。


中产作为城堡的外城，也有自己的城墙。中产阶级的外城墙是学历，而城堡的内城墙是血缘，这是最最核心的区别。如果你注意观察，你就会发现，越上层的人越爱用血缘来区分人，到了最顶层，几乎只认血缘，这种城墙是极高的。中产阶级的城墙比起城堡要矮许多，防御薄弱，所以时不时就有人可以翻进来。


中产与底层之间的流通也相对顺畅的多。通过几十年个人奋斗，从底层成功翻墙成为中产的人，很容易得出“个人奋斗能改变阶层”的结论，并把这个结论灌输给下一代。等到下一代想在中产的基础上继续往上爬时，才发现再上面的游戏规则和父亲当年完全不一样了。


不过，这堵城墙依然是有缝隙的。我个人的感觉是，在今天这个时代，平民其实拥有比以往更多的工具来实现阶级跃迁，但前提是你得具有以下三者中的一项：


一是“天赋”。有“天赋”的人，我们通常叫“天才”。“天赋”的本质，其实就是基因突变，按人口中的一定比例随机生成，出现地域无法控制，出现时间不可预测。这种不世出的人类天才一旦出山就光芒万丈，再保守的既得利益者也不得不考虑将这些天生异能者收编进城堡之内。有“天赋”者，万中无一，上升难度最易。


二是“才华”。我们一般也叫“能人”。而“才华”和“天赋”的区别在于，“才华”不是随机出现的，而是刻意培养的成果。这些“能人”往往是平民阶层举数代人之心力打造的“特优产品”，功能和特点都是为统治阶层精心定制的，用着绝对顺手，包您称心满意。统治阶级看到平民中居然有人这么有心，也往往心生感激，愿意接纳其成为自己一员。有“才华”者，千里挑一，上升较易。


三是“美貌”，这个就不用多解释了，占人口比例大概1%左右，可以被上层阶级拿来直接当装饰品或是改善基因用。但因为数量最多，上升的难度要比前两者高好几个数量级。


以上三大要素，占一个，就有实现阶级跨越的可能；占两个，有实现阶级跨越的较大可能。三个都不沾的，在今天这个时代，还想实现阶层跨越那就只能靠彩票了。需要注意的是，勤奋并不能使人上升到精英序列，勤奋本身只有在和天赋、才华、美貌这三要素相结合的时候才能发挥其助攻作用。单拼勤奋，只能保证你上升到底层阶级中的上层。


天赋、才华、美貌之所以得到精英阶层的承认，是因为这三样东西放在任何群体内都是稀缺资源。我注意到的一个趋势是，这类稀缺资源被优化配置的效率，在今天这个时代正在急速地上升。换言之，怀才不遇的牛人、小村小镇的美女，在未来将越来越难以被埋没，随时随地都会被挖掘出来并往城堡输送。过去因为与外界交流不多而可以娶到自己村里的大美女，这种捡漏的好事以后会越来越不再可能。


城堡内的顶层对于这种“受管控的上升通道”其实也乐见其成。毕竟，一者他们需要通过定期小规模换血的方式，来弥补自身的后代里出现废人的概率损耗；二者，城堡内也是很复杂的，城堡内的上层需要通过引入外来跃迁者这个机制，来时不时敲打一下城堡内的对手，甚至不惜打开向下掉落的通道，来警示城堡内的食物链下游。


不过，即便是天赋，才华，美貌，其门槛也一直在不断提高。比如苹果创始人之一的沃兹曾经当笑话和人说过：“我看了一下现时在苹果工作需要的经验和教育程度，我想乔布斯和我现在都很难在苹果找到一份工作了。”这就是城堡内的人加高壁垒的一个露骨的范例。


平民中的天资平庸者，尽管生活水平会随着技术进步持续上升，但相对的社会位阶却是很难再变化了。但许多人会误把生活水平绝对值的提升，当成自己在人群地位中相对地位的提升。有句鸡汤说“今天一个普通人所拥有的东西，500年前的皇帝会用半壁江山来换”，就是典型的在故意混淆绝对值和相对值的概念。


很多人的祖辈在温饱线苦苦挣扎，他们的父辈依然物质匮乏，但他今天却可以顿顿有肉、手机空调，于是就产生了“阶层上升”的错觉。但其实，今天的小白领，从全人口序列中的所处位置看，也就相当于他爷爷辈的一个普通庄稼汉或者他父辈的一个厂里的工人，看似生活水平极大改善，实际阶层位置分毫未动。这就是被精心设计出来的平民幻觉。


现在可以预见的是，在我们这代人乃至我们的下一代的有生之年，只要社会大致稳定，技术持续进步，社会财富不断增加，这套城三重系统便能完美地持续运转，目前看不到有什么可以破坏这个体系。正所谓，国安民乐，岂不美哉？
编辑于 2017-03-03
​赞同 34K​
​2,583 条评论
​分享
​收藏
​感谢
​
收起​

* 闹灾荒的时候，和珅在给灾民的米汤里撒了一把沙子， 这其中包含着什么经济学原理？
29,446 人赞同了该回答
纪晓岚看到了表象，和珅却看到了表象背后的深刻逻辑。

如果赈灾粮干干净净，和普通粮食没什么两样，用脚趾头想想都会知道，一定会出现层层截流的情况。真正吃到灾民嘴里的，恐怕就没有多少了。

更加吊诡的是，因此而饿死的灾民，没有人会为他们说话。

掺了沙子，看上去品质下降了，但原本想截流的那些人，考虑到赈灾粮的口感和挑沙子的难度也就放弃了。如此，粮食也才能够最终进入真正的灾民嘴里，虽然有沙但总比饿死要强之百倍。

前些年推广经济适用房，有经济学家建议经济适用房不应设有独立卫生间，而应采用公共卫生间。结果舆论一片哗然，骂什么的都有，说的好像这位经济学家不把穷人当人看一样。

几年后再看，时不时爆出经济适用房房主开豪车，甚至出租经济适用房赚钱。这背后的逻辑是一样的，可以安身但削减了部分功能的房子，才不会引起权力寻租。

人性使然，好的制度未必能坏人变好，但坏的制度却一定会使好人变坏。

正义感爆棚，往往因为正义是廉价的。

远的纪晓岚，近的薛之谦，他们的正义都很廉价。看上去的振臂高呼，那是因为高呼的成本和代价很低，低到他们认为自己就是正义的化身。

十九世纪法国经济学家巴斯夏有篇著名的文章《看得见的和看不见的》，说的是差的经济学家只能看到短期得失和事物表象，而好的经济学家却能够看的更加长远，也能够看到事物背后的真相。

这个论断，不光对经济学家适用，对任何一个具备思考能力的人同样适用。

* TODO 肯德基和麦当劳的优惠券意义在哪里？为何不直接降价？
朱聿欣
朱聿欣
公众号：言语炼金术
专题收录 · 果然，双十一过完，我整个人都被掏空了
共 2 项收录
24,199 人赞同了该回答
谢邀。有耐心看到最后的人一定都是人生赢家。

先说结论：利润的最大化并不等同于销售量的最大化，而是等同于消费者剩余的最小化（消费者剩余是指消费者愿意支付的最高价格与实际支付的价格之间的差额），消费者剩余越小，企业从消费者身上榨取的价值就越多，就越能实现利润的最大化。优惠券作为价格歧视策略的一种，极好地区分了愿意付出时间成本来搜索优惠信息的「穷人」（工薪或学生阶层）和不在乎优惠信息直接到门店购买的「富人」两类消费者，让他们都支付了他们愿意支付的最高价格，从而达到了消费者剩余的最小化和利润的最大化。注意，这里的「穷」与「富」，并非单纯指经济境况，而是指消费者对待同样商品时支付意愿的高低。至于单纯降价，往小了说，短期内会带动销量的上升，但不利于强化消费者的消费倾向和品牌感知，一旦重新提价，消费者的负面反应会比较大；往大了说，降价虽然是获取市场份额最简单最快捷的方式，但市场是动态波动和有机统一的，一旦你开始降价，同行业内的其他企业势必会做出应对，其结果最终导致价格进入下行通道，引发企业间的价格混战，最终不仅损害企业本身，而且恶果会波及整个行业。


为什么说使用优惠券减少了消费者盈余，从而达到了企业利润的最大化？举个例子，假设有 A、 B、 C三名消费者，他们都意欲购买一个麦辣鸡腿汉堡，但由于偏好程度以及收入状况等方面多有不同，因而，每名消费者愿意支付的最高价格也大不相同，现在假定他们三人的最高出价分别是12元、11元、10元，同时，我们还假定每个麦辣鸡腿汉堡的全部成本为5元。那么，在商家不同的价格水平下，汉堡销量将不同，商家可获利润额也不一样。此时倘若麦当劳把价格定为12元，则仅有一名消费者愿意购买，就是最高愿意出12块的A同学，此时商家可获利润为（12-5=）7元；现在麦当劳决定实施优惠，以最低价5元（即成本）销售，销量则大升至3个，A、 B、 C三人都会购买，但此时商家利润为零。以上两者情况说明单纯追求价格最高（定价12元时卖出一个汉堡利润7元）和单纯追求销量最大（定价5元时卖出3个汉堡利润0元）都带不来利润的最大。此时倘若麦当劳看形势不妙，再做调整，把价格定为10元，这样A、 B、 C三人都会购买，此时商家利润为（10X3-5x3=）15元，达到了最大化，由此可见，商家定价的最理想情况是，价格在消费者能接受的程度下最大化，并且实现在这一价格下的销量最大化。换言之，商家应该尽可能按照每名消费者愿意支付的最高价格进行销售。

问题在于，消费者不会傻逼脑残地走到柜台前，把他们愿意支付的最高价格告诉你。那怎么获取他们愿意支付的最高价格呢？一个很简单的方法就是发放一定的优惠券，由此商家就可以把具有不同支付意愿的消费者区别开来，从而对不同的消费者收取不同的价格。现在假设一个汉堡成本5元，定价10元时，100人会接受此价格。定价15元时，有60人会接受此价格，前者利润为（10-5）×100=500元，后者利润为（15-5）×60=600元。但商家不想放弃另外40个支付意愿较低的消费者，于是决定用5元优惠券来吸引他们，同时对剩下那60个对价格不敏感的消费者依然维持15元的原价销售。此时商家利润为 60×15＋40×10－5×100=800元，达到了最大化。


同时因为世界上没有免费的午餐，使用优惠券的消费者为了获取低价必须支付如下成本，一是时间成本，二是自由选择权的丧失。

时间成本的丧失：收集名目繁多的信息，下载APP，上网打印电子券，去路边索要优惠券，这些都会浪费你的时间。通常是什么样的人才愿意花费这些时间成本呢？显然是时间成本比较便宜的人——工薪或学生阶层。

自由选择权的丧失：优惠券的优惠大多限定于固定的产品组合，而较少用于单点。支付意愿高的消费者不会为了优惠而委屈自己吃一份量大便宜的套餐，他们情愿单点，随心选择自己想要吃的，即为，他们不会使用优惠券。而只要我们站在麦当劳的点餐台前仔细地观察半小时，就会发现，优惠券的使用者多半是一些「穷人」，如学生群体等。


通过优惠券，麦当劳肯德基成功地区分了顾客中的「富人」和「穷人」。对待「富人」——不持有优惠券的人，商家给他们提供的商品比较贵（没有优惠），对待「穷人」——持有优惠券的人，商家给他们提供的商品比较便宜（享有折扣）。商品一样，价格不同，这就是典型的价格歧视，这一价格歧视策略，使得商家从消费者身上榨取了更多价值，让每一个消费者都能在他们所能承受的最高价格下进行消费，从而达到了利润的最大化。


最后再大致总结和拓展一下前面几位高票答主的观点（虽然这个问题关注者寥寥），权且当个补充：

1) 优惠券能让消费者在心理上形成应激机制，每当你看到名目众多的优惠券和app时，你就会产生一种“有便宜不占白不占”的感觉，每看一次和再看一次的过程，都会无形中加强你的消费倾向和品牌感知。而单纯的降价并不能做到这一点。优惠券特别够吸引那些愿意付出时间成本搜索优惠信息、在一定程度上忌惮门店高价的经济不宽裕群体，因为这类人在心理上更容易形成类似占便宜的应激机制。

2) 优惠券能让消费者在实际支付中造成价格失敏，持续刺激消费者。优惠券的优惠策略会结合销售情况及时更新。在保证低于门面价的基础上，优惠券的价格时常在变，优惠组合也在变。比如一份麦乐鸡套餐门店18元，优惠券可能这周会把价格设为14.9元下周又设为15.9元，这周给你搭配个果汁，下周又给你赠杯可乐。如此变来变去，消费者对优惠券上的价格并不太敏感，他们所确定和坚信的一点是——使用优惠券会比门店便宜，如此一来使用优惠券能够持续刺激消费者。而门店价格作为非常formal的一种经营信号，不利于反复变动对消费者形成持久刺激，其频繁变动带来的负面影响在答案开头便已提到，在这里补充个例子——比如20世纪90年代波音公司与空客公司的那场价格混战，波音公司采取频繁降价策略，通过比街角杂货店还要低的利润率试图去建立自己在航空市场的超级霸主地位，结果不仅扰乱了整个航空市场的经营秩序，自己也股票大跌付出了惨痛代价。

最后给大家安利一本关于产品定价、价格折扣、优惠策略方面的好书，叫《让顾客自己来定价》，是沃顿商学院的营销学泰斗Jagmohan Raju教授所著，我两年前草草读过一遍，受益至今。

* 日本和韩国都属于发达国家，但是相比于欧洲国家(比如法国），感觉普通人活得很累是因为什么？
超级赛亚人
超级赛亚人
23,335 人赞同了该回答
我在东京的时候，不小心用热水把家里上网的猫浇坏了。打电话给NTT（网络运营商），两个小时不到就送来了新的。而在阿姆斯特丹的住所，无线网故障将近两个月，打电话数次依然没人维修。

再举个例子，日本早稻田大学和荷兰阿姆斯特丹大学都是各自国内相当不错的大学。然而在回复邮件的速度上，早大工作日24小时内一定会答复，阿大回邮件的速度平均是一到两周。

就我个人体验而言，在各种服务的效率上，日本几乎完爆荷兰。可从另一面来看，如此效率的背后，是各种繁杂的规矩和极其压抑的社会环境。

与悠闲而又随意的荷兰人相比，日本人十分敏感，细致，有时甚至近乎刻板的死守规矩，上下级观念深入骨髓，大多数人从众心理严重。比起肉体上的辛苦，日本社会的各种无形的条条框框会给人带来巨大的心理压力。

在荷兰，学生甚至可以对熟悉的教授直呼其名，偶尔还会互相开开玩笑。而在日本，学生见教授要考虑自己敬语是否用的正确，举止是否有失礼仪。比起荷兰人的单刀直入，日本人相对委婉。在日本，空気を読む（类似于察言观色的意思）是一项必备技能，这也导致了日本人在作出行动之前往往会三思甚至n思，这一点我们可能会在日本动漫，尤其少女漫中有所感受。日本人十分善于思考，好处是会把许多事做的极其周全。坏处是许多时候过度思考，有时能从很小的事情上思考出一大坨长篇大论。这种事无巨细的思考往往更加重了他们的心理负担。

荷兰人曾经告诉我，他们很少加班。到了下班的时刻，公司从上到下跑的快如龙卷风。在公司里，领导并不仅仅关心业务，更会关心员工是否做的开心。如果没到下班时间便完成了今日分内的工作，剩下的时间可以放松或者做点与工作无关的事情。

可在日本则全然不同。日本社会尤其鼓吹努力和奋斗，这一点我们同样能从各种日剧或者动漫里感受到。但日本人的努力，逐渐在往畸形的方向发展。许多人并不是在努力，而是做出[努力的姿态]，从而去避免他人的指责。我曾经做兼职的地方，看到有员工已经完成分内的事情，却把已经摆整齐的东西重新打乱再摆放。大家看起来都忙忙碌碌，可如果仔细观察就会发现，许多人并非真正在努力，而是为了避免别人的负面评价在已经完成的工作上磨洋工，作出努力的样子。在精神上，没有人会关注你今天是否开心。日本的社会也并不欣赏真性情的人，许多人认为，那些即使内心狂风暴雨也拼死忍耐，在他人面前伪装出朝气蓬勃阳光灿烂状态的人才是值得称赞的。

在日本，你会感受到生活的便利，服务的周到，交通的发达，基础设施的完善，但与欧洲相比，感受不到他们的幸福。在日本的社会环境下，许多人脸上挂着并非发自心底的笑容，口里说着言不由衷的敬语，这些人在内心巨大矛盾的拉扯下，一部分人逐渐麻木并习惯于现实，另一部分人则在某个风和日丽的早晨，纵身跃向铁轨。

个人感觉比起欧洲，日本的社会贫富差距依然不小。从阶级固化和人口老龄化以及资源向大城市集中的趋势来看，我国的发展趋势越来越贴近如今的日本。虽然可能要被喷，但我依然想说，我们底层人民的幸福感大概主要靠培养自己想开的能力和豁达的人生观。

想开点，比什么都好。
* 「宁愿花 11K 重新招人，也不愿意花 9K 留住老员工」的现象是否属实？为什么会出现该现象？
张宏伟
张宏伟
医学工程
19,500 人赞同了该回答
上家公司一个做内勤的女孩，要求老板加薪无果后，便把自己的朋友介绍到我们公司，她也成功被介绍到了对方的公司，工作还是原来的工作，两人交换了下老板，底薪就各涨了30%，我们都被这种操作震惊到了，于是大家纷纷效仿，以至于同行业的几家公司，老板之间斗得你死我活，底下的员工却都成了亲密的战友。
* 有什么经济学技巧可以用于日常购物？
提问：在中国买东西，少不了砍价。你去商城买东西，服务员告诉你一件衬衫50元，两件衬
衫80元，而你只想买一件，该怎么砍价？

回答：一件40元卖不卖？！

我就猜到大部分会这样答，但其实这样还不够哈哈哈～

因为！服务员在卖东西的时候，卖两件一定要比卖一件赚的多才会给你折扣，否则就永远一
件一件卖。

假设一件的成本是x，那么两件的利润是80-2x，一件的利润是50-x。

由80-2x>50-x, 得出x<30! 也就是说，一件的成本最多只有30，不然的话两件是不会给你便
宜卖的！这时你已经算出它的成本价了，就使劲往下砍吧少年！

如果你觉得蛋疼不过瘾，还可以把公式推广一下：
一件卖a元，n件卖b元，一件的成本最高是？
假设是x元吧，那么b－nx>a-x
则：x<(b-a)/(n-1) ！
比如一件100，三件250，那么一件的成本上限就是 （250-100）/ （3-1） = 75元
有了这个法则你还会怕砍价嘛！

这么出神入化的理论与实践结合，你好意思不点赞？


* 经济学原理
1 目录 
2 第一章 经济学十大原理 

 1 人们如何作出决策 
 2 原理一：人们面临交替关系 
 3 原理二：某种东西的成本是为了得到它而放弃的东西 
 4 原理三：理性人考虑边际量 
 5 原理四：人们会对激励作出反应 
 6 人们如何相互交易 
 7 原理五：贸易能使每个人状况更好 
 8 原理六：市场通常是组织经济活动的一种好方法 
 9 原理七：政府有时可以改善市场结果 
 10 整体经济如何运行 
 11 原理八：一国的生活水平取决于它生产物品与劳务的能力 
 12 原理九：当政府发行了过多货币时，物价上升 
 13 原理十：社会面临通货膨胀与失业之间的短期交替关系 
 14 结论 
 15 内容提要 

3 第二章 像经济学家一样思考 

 1 作为科学家的经济学家 
 2 科学方法：观察、理论和进一步观察 
 3 假设的作用 
 4 经济模型 
 5 微观经济学与宏观经济学 
 6 作为决策者的经济学家 
 7 实证分析与规范分析 
 8 华盛顿的经济学家 
 9 为什么经济学家意见分歧 
 10 科学判断的不同 
 11 价值观的不同 
 12 不懂装懂的人和古怪的人 
 13 感觉与现实 
 14 出发吧！ 
 15 内容提要 

4 第三章 相互依存性与贸易的好处 

 1 一个现代经济寓言 
 2 生产可能性 
 3 专业化与贸易 
 4 比较优势原理 
 5 绝对优势 
 6 机会成本和比较优势 
 7 比较优势与贸易 
 8 比较优势的应用 
 9 迈克尔·乔丹应该自己修剪草坪吗？ 
 10 美国应该与其他国家进行贸易吗？ 
 11 参考资料 
 12 结论 
 13 内容提要 

5 第四章 供给与需求的市场力量 

 1 市场与竞争 
 2 竞争市场 
 3 竞争：完全及其他 
 4 需求 
 5 个人需求的决定因素 
 6 需求表与需求曲线 
 7 其他条件相同 
 8 市场需求与个人需求 
 9 需求曲线的移动 
 10 案例研究 减少香烟需求量的两种方法 
 11 供 给 
 12 个人供给的决定因素 
 13 供给表与供给曲线 
 14 市场供给与个人供给 
 15 供给曲线的移动 
 16 供给与需求的结合 
 17 均 衡 
 18 分析均衡变动的三个步骤 
 19 结论 
 20 内容提要 

6 第五章 弹性及其应用 

 1 需求弹性 
 2 需求价格弹性及其决定因素 
 3 计算需求价格弹性 
 4 参考资料：用中点法计算弹性 
 5 需求曲线的变化 
 6 总收益与价格的需求弹性 
 7 案例研究 博物馆门票的定价 
 8 需求收入弹性 
 9 参考资料：需求曲线的弹性和总收益 
 10 新闻摘录 收费道路的弹性 
 11 供给弹性 
 12 供给价格弹性及其决定因素 
 13 计算供给价格弹性 
 14 供给曲线的变化 
 15 供给、需求和弹性的三种应用 
 16 农业的好消息能是农民的坏消息吗？ 
 17 为什么石油输出国组织不能保持石油的高价格？ 
 18 禁毒增加还是减少了与毒品相关的犯罪？ 

7 第六章 供给、需求与政府政策 

 1 价格控制 
 2 价格上限如何影响市场结果 
 3 案例研究 加油站前的长队 
 4 案例研究 短期与长期租金控制 
 5 新闻摘录 纽约市的租金控制 
 6 价格下限如何影响市场结果 
 7 案例研究 最低工资 
 8 对价格控制的评价 
 9 税 收 
 10 向买者征税如何影响市场结果 
 11 向卖者征税如何影响市场结果 
 12 案例研究 国会能分配工资税的负担吗？ 
 13 弹性与税收归宿 
 14 案例研究 谁支付奢侈品税？ 
 15 结论 
 16 内容提要 

8 第七章 消费者、生产者与市场效率 

 1 消费者剩余 
 2 支付意愿 
 3 用需求曲线衡量消费者剩余 
 4 低价格如何增加消费者剩余 
 5 生产者剩余 
 6 成本与卖者的意愿 
 7 用供给曲线衡量生产者剩余 
 8 高价格如何增加生产者剩余 
 9 市场效率 
 10 仁慈的社会计划者 
 11 参考资料：市场中看不见的手 
 12 市场均衡的评价 
 13 新闻摘录 倒卖门票 
 14 结论：市场效率与市场失灵 
 15 内容提要 

9 第八章 应用：税收的代价 

 1 税收的无谓损失 
 2 税收如何影响市场参与者 
 3 无谓损失与贸易的好处 
 4 无谓损失的决定因素 
 5 案例研究 对劳动征税的无谓损失 
 6 案例研究 亨利·乔治和土地税 
 7 无谓损失和税收收入随税收变动而变动 
 8 案例研究 拉伐曲线和供给学派经济学 
 9 新闻摘录 乌克兰应该降低税率来增加税收收入吗？ 
 10 结论 
 11 内容提要 

10 第九章 应用：国际贸易 

 1 贸易的决定因素 
 2 没有贸易时的均衡 
 3 参考资料：比较价格和比较优势 
 4 世界价格和比较忧势 
 5 贸易的赢家和输家 
 6 出口国的得失 
 7 进口国的得失 
 8 关税的影响 
 9 进口限额的影响 
 10 贸易政策的结论 
 11 各种限制贸易的观点 
 12 工作岗位论 
 13 国家安全论 
 14 幼稚产业论 
 15 新闻摘录，北美自由贸易协定和墨西哥的西红柿 
 16 不公平竞争论 
 17 作为讨价还价筹码的保护论 
 18 新闻摘录 鸡肉人侵 
 19 案例研究 关贸总协定和实现自由贸易的多边方法 
 20 结论 
 21 内容提要 

11 第十章 外部性 

 1 外部性和市场无效率 
 2 福利经济学：概述 
 3 生产中的负外部性 
 4 生产中的正外部性 
 5 案例研究 关于技术政策的争论 
 6 消费的外部性 
 7 外部性的私人解决方法 
 8 私人解决方法的类型 
 9 新闻摘录 一位愤怒的公民在呼吁 
 10 科斯定理 
 11 为什么私人解决方法并不是总有效 
 12 针对外部性的公共政策 
 13 管制 
 14 庇古税和补贴 
 15 新闻摘录 实施中的污染许可证 
 16 对污染经济分析的批评 
 17 结论 
 18 内容提要 

12 第十一章 公共物品和共有资源 

 1 不同类型的物品 
 2 公共物品 
 3 搭便车问题 
 4 一些重要的公共物品 
 5 案例研究 灯塔是公共物品吗？ 
 6 成本－收益分析是一个难题 
 7 案例研究 一条生命值多少钱？ 
 8 共有资源 
 9 共有地的悲剧 
 10 案例研究 资本主义、共产主义以及集体资源 
 11 一些重要的共有资源存 
 12 新闻摘录 新加坡解决道路拥挤的方法 
 13 新闻摘录 黄石公园应该像迪斯尼乐园一样收费吗？ 
 14 案例研究 为什么黄牛没有绝种 
 15 结论 
 16 内容提要 

13 第十二章 税制的设计 

 1 美国政府的财政概况 
 2 联邦政府 
 3 州与地方政府 
 4 税收和效率 
 5 无谓损失 
 6 案例研究 应该对收入征税，还是应该对消费征税？ 
 7 管理负担 
 8 新闻摘录 小企业和税法 
 9 边际税率与平均税率 
 10 定额税 
 11 税收与平等 
 12 受益原则 
 13 能力纳税原则 
 14 案例研究 如何分配税收负担 
 15 案例研究 横向平等与结婚税 
 16 税收归宿与税收平等 
 17 案例研究 谁支付公司所得税 
 18 案例研究 单一税率税 
 19 结论：平等与效率之间的交替 
 20 内容提要 

14 第十三章 生产成本 

 1 什么是成本 
 2 总收益、总成本和利润 
 3 作为机会成木的成本 
 4 作为一种机会成本的资本成本 
 5 经济利润与会计利润 
 6 生产与成本 
 7 生产函数 
 8 从生产函数到总成本曲线 
 9 成本的各种衡量 
 10 固定成本与可变成本 
 11 平均成本与边际成本 
 12 成本曲线及其形状 
 13 典型的成木曲线 
 14 短期与长期成本 
 15 结论 
 16 内容提要 

15 第十四章 竞争市场上的企业 

 1 什么是竞争市场？ 
 2 竞争的含义 
 3 竞争企业的收益 
 4 利润最大化与竞争企业的供给曲线 
 5 一个简单的利润最大化例子 
 6 边际成本曲线和企业的供给曲线 
 7 企业的短期停止营业决策 
 8 案例研究 生意冷清的餐馆和淡季的小型高尔夫球场 
 9 参考资料 覆水难收与沉没成本 
 10 企业进入或退出一个行业的长期决策 
 11 用我们的竞争企业图形来衡量利润 
 12 竞争市场的供给曲线 
 13 有固定数量企业的市场 
 14 有进入与退出的市场供给 
 15 参考资料 如果竞争企业获得零利润，为什么它们还在经营？ 
 16 短期与长期需求移动 
 17 为什么长期供给曲线会向右上方倾斜 
 18 结论 
 19 内容提要 

16 第十五章 垄断 

 1 为什么会产生垄断 
 2 垄断资源 
 3 案例研究 德比尔的钻石垄断 
 4 政府创造的垄断 
 5 自然垄断 
 6 垄断者如何作出生产与定价决策 
 7 垄断与竞争 
 8 垄断者的收益 
 9 利润最大化 
 10 参考资料 为什么垄断者没有供给曲线 
 11 垄断的利润 
 12 案例研究 垄断药品与无品牌药品 
 13 垄断的福利代价 
 14 无谓损失 
 15 垄断的利润：一种社会代价吗？ 
 16 对垄断的公共政策 
 17 用反托拉斯法增强竞争 
 18 管制 
 19 新闻摘录 波音的市场势力 
 20 公有制 
 21 无所作为 
 22 价格歧视 
 23 关于定价的一个寓言 
 24 这个故事的寓意 
 25 价格歧视分析 
 26 价格歧视的例子 
 27 新闻摘录 选拔最优垄断者 
 28 结论：垄断的普遍性 
 29 内容提要 

17 第十六章 寡头 

 1 在垄断和完全竞争之间 
 2 只有少数几个卖者的市场 
 3 双头的例子 
 4 竞争、垄断和卡特尔 
 5 寡头的均衡 
 6 寡头数量如何影响市场结果 
 7 案例研究 欧佩克和世界石油市场 
 8 新闻摘录 欧佩克中的争执 
 9 博弈论与合作经济学 
 10 囚犯的两难处境 
 11 作为囚犯两难处境的寡头 
 12 新闻摘录 现代海盗 
 13 囚犯两难处境的其他例子 
 14 囚犯的两难处境与社会福利 
 15 为什么人们有时能合作 
 16 案例研究 囚犯两难处境的比赛 
 17 针对寡头的公共政策 
 18 贸易限制与反托拉斯法 
 19 案例研究 一次违法的通话 
 20 关于反托拉斯政策的争论 
 21 新闻摘录 玩具反斗城是反竞争的吗？ 
 22 结论 
 23 内容提要 

18 第十七章 垄断竞争 

 1 有差别产品的竞争 
 2 短期中的垄断竞争企业 
 3 长期均衡 
 4 垄断竞争与完全竞争 
 5 垄断竞争与社会福利 
 6 参考资料：过剩生产能力是个社会问题吗？ 
 7 广告 
 8 关于广告的争论 
 9 案例研究 广告与眼镜的价格 
 10 作为质量信号的广告 
 11 品牌 
 12 案例研究 共产主义下的品牌 
 13 新闻摘录 电视网也有品牌 
 14 结论 
 15 内容提要 

19 第十八章 生产要素市场 

 1 企业的劳动需求 
 2 竞争的、利润最大化的企业 
 3 生产函数与劳动的边际产量 
 4 边际产量值和劳动需求 
 5 参考资料 投入需求与产量供给：同一枚硬币的两面 
 6 劳动市场的均衡 
 7 均衡的边际生产率 
 8 劳动供给的移动 
 9 劳动需求的移动 
 10 案例研究 生产率与工资 
 11 其他生产要素：土地和资本 
 12 土地和资本市场的均衡 
 13 参考资料 资本收入的各种形式 
 14 生产要素之间的联系 
 15 案例研究 黑死病的经济学 
 16 结论 
 17 内容提要 

20 第十九章 收入与歧视 

 1 决定均衡工资的若干因素 
 2 补偿性工资差别 
 3 人力资本 
 4 案例研究 日益增加的技能价值 
 5 能力、努力和机遇 
 6 案例研究 漂亮的收益 
 7 教育的另一种观点：信号 
 8 案例研究人力资本、天赋能力及义务教育 
 9 超级明星现象 
 10 歧视经济学 
 11 劳动市场歧视的衡量 
 12 雇主的歧视行为 
 13 案例研究 电车上的种族隔离与利润动机 
 14 顾客与政府的歧视行为 
 15 案例研究 体育运动中的歧视行为 
 16 新闻摘录男人、女人与工资 
 17 缩小中的工资差距 
 18 关于同工同酬的争论 
 19 结论 
 20 内容提要 

21 第二十章 收入分配 

 1 不平等的衡量 
 2 美国的收入不平等 
 3 案例研究 妇女运动与收入分配 
 4 案例研究 世界各国的收入不平等 
 5 贫困率 
 6 衡量不平等中的问题 
 7 新闻摘录 正确衡量了贫困率吗？ 
 8 经济流动性 
 9 收入再分配的政治哲学 
 10 功利主义 
 11 自由主义 
 12 自由意志主义 
 13 减少贫困的政策 
 14 最低工资法 
 15 福利 
 16 负所得税 
 17 新闻摘录 1996年的福利改革 
 18 实物转移支付 
 19 反贫穷计划和工作激励 
 20 新闻摘录 储蓄与福利 
 21 结论￼ 
 22 内容提要 

22 第二十一章 消费者选择理论 

 1 预算约束：消费者买得起什么 
 2 偏好：消费者想要什么 
 3 用无差异曲线代表偏好 
 4 无差异曲线的四个特征 
 5 两种极端的无差异曲线例子 
 6 参考资料 
 7 效用：表示消费者偏好的另一种方法 
 8 ￼最优化：消费者选择什么 
 9 消费者的最优选择 
 10 收入变动如何影响消费者的选择 
 11 价格变动如何影响消费者的选择 
 12 收入效应与替代效应 
 13 需求曲线的推导 
 14 四种应用 
 15 所有的需求曲线都向右下方倾斜吗？ 
 16 工资如何影响劳动供给？ 
 17 案例研究 劳动供给的收入效应： 
 18 历史趋势、彩票赢家及卡内基的猜测 
 19 利率如何影响家庭储蓄？ 
 20 穷人喜欢接受现金转移支付还是实物转移支付？ 
 21 结论：人们真的这样想吗？ 
 22 内容提要 

* 经济学原理(获得价值的方法)
** 人们如何作出决策 
*** 人们面临交替关系 天下没有白吃的午餐
    一次只能做一件事
    另一种交替关系是效率与平等之间的交替
*** 某种东西的成本是为了得到它而放弃的东西   
*** 理性人考虑边际量 
    生活中的许多决策涉及到对现有行动计划进行微小的增量调整
*** 人们会对激励作出反应 
** 人们如何相互交易  
*** 贸易能使每个人状况更好
*** 市场通常是组织经济活动的一种好方法 
*** 政府有时可以改善市场结果 
** 整体经济如何运行 
*** 一国的生活水平取决于它生产物品与劳务的能力 
*** 当政府发行了过多货币时，物价上升 
*** 社会面临通货膨胀与失业之间的短期交替关系 
* 像经济学家一样思考 
      1 作为科学家的经济学家 
      2 科学方法：观察、理论和进一步观察 
      3 假设的作用 
      4 经济模型 
      5 微观经济学与宏观经济学 
      6 作为决策者的经济学家 
      7 实证分析与规范分析 
      8 华盛顿的经济学家 
      9 为什么经济学家意见分歧 
      10 科学判断的不同 
      11 价值观的不同 
      12 不懂装懂的人和古怪的人 
      13 感觉与现实 
      14 出发吧！ 
      15 内容提要 

* 相互依存性与贸易的好处 
  节约成本
  一个现代经济寓言 牧牛人
  生产可能性 
  专业化与贸易 
  比较优势原理 
  绝对优势 
  机会成本和比较优势 
  比较优势与贸易 
  比较优势的应用 
  迈克尔·乔丹应该自己修剪草坪吗？ 
  美国应该与其他国家进行贸易吗？ 

* 供给与需求的市场力量 
市场与竞争 
竞争市场 
竞争：完全及其他 
需求 
个人需求的决定因素 
需求表与需求曲线 
其他条件相同 
市场需求与个人需求 
需求曲线的移动 
案例研究 减少香烟需求量的两种方法 
供 给 
个人供给的决定因素 
供给表与供给曲线 
市场供给与个人供给 
供给曲线的移动 
供给与需求的结合 
均 衡 
分析均衡变动的三个步骤 

* 弹性及其应用 

      1 需求弹性 
      2 需求价格弹性及其决定因素 
      3 计算需求价格弹性 
      4 参考资料：用中点法计算弹性 
      5 需求曲线的变化 
      6 总收益与价格的需求弹性 
      7 案例研究 博物馆门票的定价 
      8 需求收入弹性 
      9 参考资料：需求曲线的弹性和总收益 
      10 新闻摘录 收费道路的弹性 
      11 供给弹性 
      12 供给价格弹性及其决定因素 
      13 计算供给价格弹性 
      14 供给曲线的变化 
      15 供给、需求和弹性的三种应用 
      16 农业的好消息能是农民的坏消息吗？ 
      17 为什么石油输出国组织不能保持石油的高价格？ 
      18 禁毒增加还是减少了与毒品相关的犯罪？ 

* 供给、需求与政府政策 
价格控制 
价格上限如何影响市场结果 
案例研究 加油站前的长队 
案例研究 短期与长期租金控制 
新闻摘录 纽约市的租金控制 
价格下限如何影响市场结果 
案例研究 最低工资 
对价格控制的评价 
税 收 
 向买者征税如何影响市场结果 
 向卖者征税如何影响市场结果 
 案例研究 国会能分配工资税的负担吗？ 
 弹性与税收归宿 
 案例研究 谁支付奢侈品税？ 
 结论 
 内容提要 

* 消费者、生产者与市场效率 

消费者剩余 
支付意愿 
用需求曲线衡量消费者剩余 
低价格如何增加消费者剩余 
生产者剩余 
成本与卖者的意愿 
用供给曲线衡量生产者剩余 
高价格如何增加生产者剩余 
市场效率 
 仁慈的社会计划者 
 参考资料：市场中看不见的手 
 市场均衡的评价 
 新闻摘录 倒卖门票 
 结论：市场效率与市场失灵 
 内容提要 

* 应用：税收的代价 

收的无谓损失 
收如何影响市场参与者 
谓损失与贸易的好处 
谓损失的决定因素 
例研究 对劳动征税的无谓损失 
例研究 亨利·乔治和土地税 
谓损失和税收收入随税收变动而变动 
例研究 拉伐曲线和供给学派经济学 
闻摘录 乌克兰应该降低税率来增加税收收入吗？ 
结论 
内容提要 

* 应用：国际贸易 
易的决定因素 
有贸易时的均衡 
考资料：比较价格和比较优势 
界价格和比较忧势 
易的赢家和输家 
口国的得失 
口国的得失 
税的影响 
口限额的影响 
贸易政策的结论 
各种限制贸易的观点 
工作岗位论 
国家安全论 
幼稚产业论 
新闻摘录，北美自由贸易协定和墨西哥的西红柿 
不公平竞争论 
作为讨价还价筹码的保护论 
新闻摘录 鸡肉人侵 
案例研究 关贸总协定和实现自由贸易的多边方法 
结论 
内容提要 

* 外部性 

部性和市场无效率 
利经济学：概述 
产中的负外部性 
产中的正外部性 
例研究 关于技术政策的争论 
费的外部性 
部性的私人解决方法 
人解决方法的类型 
闻摘录 一位愤怒的公民在呼吁 
科斯定理 
为什么私人解决方法并不是总有效 
针对外部性的公共政策 
管制 
庇古税和补贴 
新闻摘录 实施中的污染许可证 
对污染经济分析的批评 
结论 
内容提要 

* 公共物品和共有资源 

同类型的物品 
共物品 
便车问题 
些重要的公共物品 
例研究 灯塔是公共物品吗？ 
本－收益分析是一个难题 
例研究 一条生命值多少钱？ 
有资源 
有地的悲剧 
案例研究 资本主义、共产主义以及集体资源 
一些重要的共有资源存 
新闻摘录 新加坡解决道路拥挤的方法 
新闻摘录 黄石公园应该像迪斯尼乐园一样收费吗？ 
案例研究 为什么黄牛没有绝种 
结论 
内容提要 

* 税制的设计 

国政府的财政概况 
邦政府 
与地方政府 
收和效率 
谓损失 
例研究 应该对收入征税，还是应该对消费征税？ 
理负担 
闻摘录 小企业和税法 
际税率与平均税率 
定额税 
税收与平等 
受益原则 
能力纳税原则 
案例研究 如何分配税收负担 
案例研究 横向平等与结婚税 
税收归宿与税收平等 
案例研究 谁支付公司所得税 
案例研究 单一税率税 
结论：平等与效率之间的交替 
内容提要 

* 生产成本 

么是成本 
收益、总成本和利润 
为机会成木的成本 
为一种机会成本的资本成本 
济利润与会计利润 
产与成本 
产函数 
生产函数到总成本曲线 
本的各种衡量 
固定成本与可变成本 
平均成本与边际成本 
成本曲线及其形状 
典型的成木曲线 
短期与长期成本 
结论 
内容提要 

* 竞争市场上的企业 
什么是竞争市场？ 
竞争的含义 
竞争企业的收益 
利润最大化与竞争企业的供给曲线 
一个简单的利润最大化例子 
边际成本曲线和企业的供给曲线 
企业的短期停止营业决策 
案例研究 生意冷清的餐馆和淡季的小型高尔夫球场 
参考资料 覆水难收与沉没成本 
 企业进入或退出一个行业的长期决策 
 用我们的竞争企业图形来衡量利润 
 竞争市场的供给曲线 
 有固定数量企业的市场 
 有进入与退出的市场供给 
 参考资料 如果竞争企业获得零利润，为什么它们还在经营？ 
 短期与长期需求移动 
 为什么长期供给曲线会向右上方倾斜 
 结论 
 内容提要 

* 垄断 

为什么会产生垄断 
垄断资源 
案例研究 德比尔的钻石垄断 
政府创造的垄断 
自然垄断 
垄断者如何作出生产与定价决策 
垄断与竞争 
垄断者的收益 
利润最大化 
 参考资料 为什么垄断者没有供给曲线 
 垄断的利润 
 案例研究 垄断药品与无品牌药品 
 垄断的福利代价 
 无谓损失 
 垄断的利润：一种社会代价吗？ 
 对垄断的公共政策 
 用反托拉斯法增强竞争 
 管制 
 新闻摘录 波音的市场势力 
 公有制 
 无所作为 
 价格歧视 
 关于定价的一个寓言 
 这个故事的寓意 
 价格歧视分析 
 价格歧视的例子 
 新闻摘录 选拔最优垄断者 
 结论：垄断的普遍性 
 内容提要 

* 寡头 

在垄断和完全竞争之间 
只有少数几个卖者的市场 
双头的例子 
竞争、垄断和卡特尔 
寡头的均衡 
寡头数量如何影响市场结果 
案例研究 欧佩克和世界石油市场 
新闻摘录 欧佩克中的争执 
博弈论与合作经济学 
 囚犯的两难处境 
 作为囚犯两难处境的寡头 
 新闻摘录 现代海盗 
 囚犯两难处境的其他例子 
 囚犯的两难处境与社会福利 
 为什么人们有时能合作 
 案例研究 囚犯两难处境的比赛 
 针对寡头的公共政策 
 贸易限制与反托拉斯法 
 案例研究 一次违法的通话 
 关于反托拉斯政策的争论 
 新闻摘录 玩具反斗城是反竞争的吗？ 
 结论 
 内容提要 

* 垄断竞争 

有差别产品的竞争 
短期中的垄断竞争企业 
长期均衡 
垄断竞争与完全竞争 
垄断竞争与社会福利 
参考资料：过剩生产能力是个社会问题吗？ 
广告 
关于广告的争论 
案例研究 广告与眼镜的价格 
 作为质量信号的广告 
 品牌 
 案例研究 共产主义下的品牌 
 新闻摘录 电视网也有品牌 
 结论 
 内容提要 

* 生产要素市场 

企业的劳动需求 
竞争的、利润最大化的企业 
生产函数与劳动的边际产量 
边际产量值和劳动需求 
参考资料 投入需求与产量供给：同一枚硬币的两面 
劳动市场的均衡 
均衡的边际生产率 
劳动供给的移动 
劳动需求的移动 
 案例研究 生产率与工资 
 其他生产要素：土地和资本 
 土地和资本市场的均衡 
 参考资料 资本收入的各种形式 
 生产要素之间的联系 
 案例研究 黑死病的经济学 
 结论 
 内容提要 

* 收入与歧视 

决定均衡工资的若干因素 
补偿性工资差别 
人力资本 
案例研究 日益增加的技能价值 
能力、努力和机遇 
案例研究 漂亮的收益 
教育的另一种观点：信号 
案例研究人力资本、天赋能力及义务教育 
超级明星现象 
 歧视经济学 
 劳动市场歧视的衡量 
 雇主的歧视行为 
 案例研究 电车上的种族隔离与利润动机 
 顾客与政府的歧视行为 
 案例研究 体育运动中的歧视行为 
 新闻摘录男人、女人与工资 
 缩小中的工资差距 
 关于同工同酬的争论 
 结论 
 内容提要 

* 收入分配 

不平等的衡量 
美国的收入不平等 
案例研究 妇女运动与收入分配 
案例研究 世界各国的收入不平等 
贫困率 
衡量不平等中的问题 
新闻摘录 正确衡量了贫困率吗？ 
经济流动性 
收入再分配的政治哲学 
 功利主义 
 自由主义 
 自由意志主义 
 减少贫困的政策 
 最低工资法 
 福利 
 负所得税 
 新闻摘录 1996年的福利改革 
 实物转移支付 
 反贫穷计划和工作激励 
 新闻摘录 储蓄与福利 
 结论￼ 
 内容提要 

* 消费者选择理论 
预算约束：消费者买得起什么 
偏好：消费者想要什么 
用无差异曲线代表偏好 
无差异曲线的四个特征 
两种极端的无差异曲线例子 
参考资料 
效用：表示消费者偏好的另一种方法 
最优化：消费者选择什么 
消费者的最优选择 
 收入变动如何影响消费者的选择 
 价格变动如何影响消费者的选择 
 收入效应与替代效应 
 需求曲线的推导 
 四种应用 
 所有的需求曲线都向右下方倾斜吗？ 
 工资如何影响劳动供给？ 
 案例研究 劳动供给的收入效应： 
 历史趋势、彩票赢家及卡内基的猜测 
 利率如何影响家庭储蓄？ 
 穷人喜欢接受现金转移支付还是实物转移支付？ 
 结论：人们真的这样想吗？ 
 内容提要 

