* 行为学 改变世界,一个时间只能做一个行为
** 主观意识行为 行为动机 增进快乐和满足感
   人类所有带有意识的行动都是为了增进他们自己的快乐和满足感
   
   研究知觉、认知、情绪、思维、人格、行为习惯、人际关系、社会关系等
*** 情绪 喜、怒、哀、惊、恐、爱
    是多种感觉、思想和行为综合产生的心理和生理状态
    
    情绪常和心情、性格、脾气、目的等因素互相作用，也受到荷尔蒙和神经递质影响。

    无论正面还是负面的情绪，都会引发人们行动的动机。尽管一些情绪引发的行为看上去没有
    经过思考，但实际上意识是产生情绪重要的一环。
**** 恐惧(认识不够) 直面恐惧本身
**** 犹豫 
**** 注意力训练  躲掉杀人的子弹
*** 人性
**** 羊群效应 从众效应
**** 明星效应
**** 专家效应
**** 权威效应
     淘宝搜“奖牌”花个 10 块钱就能定制一个逼真奖牌
**** 熟人效应
**** 男人爱财好色，女人爱美，老人健康，小孩聪明
     男人怕穷，女人怕丑，小孩怕笨，老人怕死
**** 强欲望：色，贪，懒 弱欲望：虚荣，恐惧，好奇
*** 思维
**** 思维方法
***** 系统思维(多收集资料)
***** 反馈思维(多实践)
***** 渐进思维(从简单开始)
***** 刻意思维(反向思维)
***** 生理控制思维(如自控力)

    生理控制思维，主要是希望大家对自己行为认知模式有基本的了解。这样有利于更好的自
    我观察，预测自己的行为并且改进。

    比方说，我们知道自控力是跟肌肉一样是有极限的。用多了，也会酸痛无力。我们就可以
    解释为什么有些人头两天热情十足地投入，然后就没有然后了。很大程度就是因为这些人，
    他们一开始就对自己的精力消耗太快了。后续没有能力继续去维持每天六点起床、持续 6 个
    小时的学习。

    以此为鉴，我们就知道，我们要做的是慢慢地增加自己的学习时间，让自控力肌肉有所适
    应。这样才能够持续有效。我们知道我们大脑的遗忘曲线，那么我们就可以根据大脑的生
    理运行状态进行改进，知道什么时候温故，什么时候学习新知。从而改进学习模式。
    （艾宾浩斯记忆曲线）
***** 指导性思维
*** 学习认知 
**** 快速学习  
     计划并管理你的学习时间,中途有休息时间
     
     每天想象一下你未来成功的样子
     
     如果可能的话试着去教教别人，这是学习的最好方法
     
     提高注意力和减少压力是很重要的
     
     目标学习法 
     
     第一，建立整体认识 花 5 小时，大量泛读；(豆瓣下书，评价最高 5 本)
     第二，感性了解知识点 花 3 小时，建立模型；(看目录，序言,浏览全书,归纳目录节 )
     第三，花 2 小时，请教专家；
     第四，补充“隐知识” 花 10 小时，理解复述。
**** 学习方法 
***** 系统学习(多收集资料)
***** 反馈学习(学习与实践结合)
***** 渐进学习(从简单开始)
***** 刻意学习(反向思维)
***** 抽象的东西要借助思维，反思
***** 增强欲望(行为的回报)
***** 针对困难学习要比你为了学习而学习效果要好得多
***** 立即做
      凡是 2 分钟内就可以完成的事，立刻去做不要犹豫
***** 主动分享(反馈)
    想真正掌握所学，就要不吝分享，分享是把所学化为所用最快的方法。
***** 学会做计划
     凡事预则立，学会做年度大事件计划，月度计划，周计划，最好每天早上也做个晨间计
     划，1 分钟搞定高效率的一整天。其他事情也是如是，不要迷茫，按照计划走，才有方
     向感。
***** 学会做总结
     每天晚上给自己一个独处的时间，思考自己的言行，得与失，最好做个记录，比如日记。
     完成一个大的项目或者事件时学会做总结，为下一次同样的事情打基础。
***** 利用碎片时间
     学会利用碎片时间，集腋成裘，比如阅读、思考，甚至休息。
***** 学会放松
     会娱乐会放松，才能更快乐地活着，所以学会主动放松，投入地放松。
***** 冥想
     冥想是非常值得学习的技巧，可以在冥想中仔细观察自己，体会自己，彻底放松自己，
     了解自己。
***** 把锻炼和兴趣联合起来
      比如跑步是一件很痛苦的事，我就在跑步的时候听评书，一下就觉得跑步的痛苦好像消
      失了，听书的乐趣让我慢慢坚持了下来。
**** 学习内容
***** 广而深 
***** 群众学的是君君臣臣父父子子，皇帝学的是驭人之术
** 潜意识行为 本性
** 生物本能
* 行为的意义 价值观 把意义留下
  行为得民心者得天下(都认可的行为)
** 欲望
*** 手淫有害 精气神
* 行为熟练度 能力
* 行为分工 阶级
** 劳动行为分工 
* 人类行为学理论
在人类行为中米塞斯提出了一套观念，主张人类所有带有意识的行动都是为了增进他们自己
的快乐和满足感。他谨慎的强调人类行为学并不是要统一定义快乐的目标为何，而只是要研
究那些在个人看来能够使他快乐的目标。而一个人增进快乐的方式就是排除那些使他不快乐
的来源。由于未来是无法确定的，因此所有人类行为也都是出自对于未来的预测。

“会行为的人类”被定义为是一个有能力进行逻辑思考的人，否则这个人将只不过是一只被
本性所驱动的生物而已。同样的，一个会行为的人类必定有某些让他感到不快乐的来源，同
时这个人也相信自己有能力排除这个不快的来源，否则人类根本就不会行动。

米塞斯提出的另一个结论是，人类所有的决策都是以排序方式为基础的。也因此，一个人不
可能同时进行超过一种行动，知觉的大脑在同一时间只有可能处理一个决策—即使这些决策
可以被迅速排列亦然。因此人类只会先排除掉那个最使他感到不快的来源，接着再排除排序
第二紧迫的不快来源。除此之外，米塞斯认为主观的价值是不可能以数学方式计算的，人不
可能以基数来评估他的价值衡量。举例而言，一个人可以说“我倾向于先买下一台电视机，
而不是买下一台 DVD 播放器”，但他不可能说“我倾向买下一台电视机的欲望高过买下一台
DVD 播放器的 2.5 倍。”

在一个人满足了他最紧迫的目标后，他会接着转向第二紧迫的目标，而第二紧迫目标又总是
比他的第一紧迫目标还要来的不重要。也因此，当一个人达成越来越多未来的目标时，个别
目标的满足感（或称为边际效用）也会因此减少。这个现象又可以称为边际效益递减。

因此在人类社会中，许多人类行为都是处于人与人之间的贸易，一个人将他视为较不重要的
东西与另一个人交换他视为较重要的东西，而另一个人也对贸易抱有相同的期望，希望换得
他认为较重要的东西、而牺牲他认为较不重要的东西。人类行为学对于此领域的研究又称为
交易经济学（Catallactics），这也是在经济学界较容易被接受的理论。
