* 行为学 改变世界,一个时间只能做一个行为
** 主观意识行为 行为动机 增进快乐和满足感
   人类所有带有意识的行动都是为了增进他们自己的快乐和满足感
   
   研究知觉、认知、情绪、思维、人格、行为习惯、人际关系、社会关系等
*** 情绪 喜、怒、哀、惊、恐、爱
    是多种感觉、思想和行为综合产生的心理和生理状态
    
    情绪常和心情、性格、脾气、目的等因素互相作用，也受到荷尔蒙和神经递质影响。

    无论正面还是负面的情绪，都会引发人们行动的动机。尽管一些情绪引发的行为看上去没有
    经过思考，但实际上意识是产生情绪重要的一环。
**** 恐惧(认识不够) 直面恐惧本身
**** 犹豫 
**** 注意力训练  躲掉杀人的子弹
*** 人性
**** 羊群效应 从众效应
**** 明星效应
**** 专家效应
**** 权威效应
     淘宝搜“奖牌”花个10块钱就能定制一个逼真奖牌
**** 熟人效应
**** 男人爱财好色，女人爱美，老人健康，小孩聪明
     男人怕穷，女人怕丑，小孩怕笨，老人怕死
**** 强欲望：色，贪，懒 弱欲望：虚荣，恐惧，好奇
*** 思维
**** 思维方法
***** 系统思维(多收集资料)
***** 反馈思维(多实践)
***** 渐进思维(从简单开始)
***** 刻意思维(反向思维)
***** 生理控制思维(如自控力)

    生理控制思维，主要是希望大家对自己行为认知模式有基本的了解。这样有利于更好的自
    我观察，预测自己的行为并且改进。

    比方说，我们知道自控力是跟肌肉一样是有极限的。用多了，也会酸痛无力。我们就可以
    解释为什么有些人头两天热情十足地投入，然后就没有然后了。很大程度就是因为这些人，
    他们一开始就对自己的精力消耗太快了。后续没有能力继续去维持每天六点起床、持续6个
    小时的学习。

    以此为鉴，我们就知道，我们要做的是慢慢地增加自己的学习时间，让自控力肌肉有所适
    应。这样才能够持续有效。我们知道我们大脑的遗忘曲线，那么我们就可以根据大脑的生
    理运行状态进行改进，知道什么时候温故，什么时候学习新知。从而改进学习模式。
    （艾宾浩斯记忆曲线）
***** 指导性思维
*** 学习认知 
**** 快速学习  
     计划并管理你的学习时间,中途有休息时间
     
     每天想象一下你未来成功的样子
     
     如果可能的话试着去教教别人，这是学习的最好方法
     
     提高注意力和减少压力是很重要的
     
     目标学习法 
     
     第一，建立整体认识 花5小时，大量泛读；(豆瓣下书，评价最高5本)
     第二，感性了解知识点 花3小时，建立模型；(看目录，序言,浏览全书,归纳目录节 )
     第三，花2小时，请教专家；
     第四，补充“隐知识” 花10小时，理解复述。
**** 学习方法 
***** 系统学习(多收集资料)
***** 反馈学习(学习与实践结合)
***** 渐进学习(从简单开始)
***** 刻意学习(反向思维)
***** 抽象的东西要借助思维，反思
***** 增强欲望(行为的回报)
***** 针对困难学习要比你为了学习而学习效果要好得多
***** 立即做
      凡是2分钟内就可以完成的事，立刻去做不要犹豫
***** 主动分享(反馈)
    想真正掌握所学，就要不吝分享，分享是把所学化为所用最快的方法。
***** 学会做计划
     凡事预则立，学会做年度大事件计划，月度计划，周计划，最好每天早上也做个晨间计
     划，1分钟搞定高效率的一整天。其他事情也是如是，不要迷茫，按照计划走，才有方
     向感。
***** 学会做总结
     每天晚上给自己一个独处的时间，思考自己的言行，得与失，最好做个记录，比如日记。
     完成一个大的项目或者事件时学会做总结，为下一次同样的事情打基础。
***** 利用碎片时间
     学会利用碎片时间，集腋成裘，比如阅读、思考，甚至休息。
***** 学会放松
     会娱乐会放松，才能更快乐地活着，所以学会主动放松，投入地放松。
***** 冥想
     冥想是非常值得学习的技巧，可以在冥想中仔细观察自己，体会自己，彻底放松自己，
     了解自己。
***** 把锻炼和兴趣联合起来
      比如跑步是一件很痛苦的事，我就在跑步的时候听评书，一下就觉得跑步的痛苦好像消
      失了，听书的乐趣让我慢慢坚持了下来。
**** 学习内容
***** 广而深 
***** 群众学的是君君臣臣父父子子，皇帝学的是驭人之术
*** 恋爱
**** 泡妞秘籍，一切成功的开始！
   有几个朋友再三要求我更新一些泡妞秘籍攻略，细细想来，其心可诛，这让关注我的妹子
   怎么看待我的为人…

   让我改变决定是之前的一篇文章《入侵人心，让她/他喜欢你》，其他内容大家都是只看不
   评论，唯独这类文章评论的人不少，想来需要的人不少，所以我就还是牺牲自己的幸福吧。

   入侵人心这篇文章只是讲了心锚的应用，内容比较粗浅，方便理解，但效果丝毫不差，运
   用灵活有奇效。

   一个人如果能够吸引异性，在整个人际交往中也会游刃有余，泡妞往小了说就是泡妞，放
   大视野你会发现这是包含诸多学科的一门终身必修课，归根接地是一门影响人心的学问，
   在生活工作中应用范围很广，想当初我就是抱着崇高而有远大的理想看了一些泡妞书籍，
   小有收获。

   社会现状

   2015统计数据，我国男性比女性多3376万，总人口性别比为105.06（以女性为100），出生
   人口性别比为115.88。也就是说，平均105个男人，只有100个女人，婴儿男女性别统计数
   据显示将近116个男孩，只有100个女孩。

   大数据告诉你终将有千万级的光棍诞生，这里面会不会有你？

   在农村就更明显了，女孩子一般读书毕业后眼界高了，所以很少会回原来的地方，几乎每
   个村子都有那么几个找不到媳妇的，用经济学术语来讲，这叫卖方市场，所以主掌话语权
   的女性，而稀缺性越来越严重只会加深这种话语权，为了获得繁衍的权利，你得不断的努
   力。

   文末我会提供大量社交学资料（泡妞资料）

   泡妞秘籍
   心态篇

   接下来可能会有一些粗浅的哲学，“心即理”是一种哲学理论，即身、心、意、知、物是
   浑然一体的。

   “感时花溅泪，恨别鸟惊心”是心赋予花鸟意义感情。

   “花心愁欲断，春色岂知心”花还是原来的花，只是你的心变了。

   “先生游南镇，一友人指岩中花树，问曰：‘天下无心外之物，如此花树在深山中自开自
   落，于我心亦何关？’先生回答说：‘你未看此花时，此花与汝心同归于寂；你来看此花
   时，则此花颜色一时明白起来，便知此花不在你的心外”（《王文成公全书》卷三）

   很多人见了女神会下意识的害羞和紧张，你为什么紧张，对方既不会打你，也不会骂你，
   亦不会辱你，相反有这么一个女神在身边本应该是惬意舒心的。

   其中重要的原因就是怕被拒绝，为什么怕被拒绝，因为你想上她。

   岂不知在你心里最珍贵的性，路边只要100块，运气好说不定还打个八折，所以心理关一定
   要过，你没必要为了几百块的东西而紧张。

   解决心理问题的技巧就是去经历…（我什么都没说）

   弱水三千只取一瓢饮

   关于泡妞，不同的人有不同的看法，每个人都号称自己的方法是经过检验的最正确的，然
   而你只要找一个和你气质最接近的方法即可。

   试想一下，如果你是个内向的人，但泡妞秘籍告诉你必须要外向，有幽默感会逗妹子开心，
   会说笑话，这样做对于你就会非常的困难。

   总结下来就是有两点：阴、阳

   阴：阴就是形容如同幽灵一般不受任何外界事物的影响，任何事都不能触动你或摇动你的
   情绪。阴是你不受他人影响的方式、是你在交流中不加入过度强烈情感的方式。同样地，
   无论何等强烈的情感在传递，正面或负面，都不要对其有过度的反应。

   阳：是形容像阳光般散发出风趣和正面情绪，人们会因为自己对阳光般的温暖的需求而被
   引诱。阳是你影响他人的方式，也是你不抱目的地增加价值的方式。你生活在自己的世界
   里，不会轻易地被他人改变，所以你会快乐有趣，无论此刻和谁在一起。阳是关于在实际
   上成为一个高价值的人和你好奇心与正面能量的前提。阳是双向交流中增加热情，幽默，
   好感和创造力的元素。

   阴更偏向于内向的人，可以展现不凡的气度，给人成熟稳重的感觉。阳更偏向于外向，幽
   默风趣，给人积极阳光的感觉。

   技巧篇之 话术

   最近流行“套路”这个词，其实撩妹也是有套路的，我们展现给目标的只有行为举止、言
   语这两样东西，而话术则属于言语的一种。

   反逻辑式幽默：人心的惯性作用，大脑为了加快运算能力，节约能量就会将常见的各种事
   物进行归类，一旦出其不意就会打破大脑的预期，如下我会进行举例

   A：“糟糕了，我没有公交卡，对了你有公交卡吗？”
   B：“有”
   A：“哦，那当我没说过！”
   B：“······”

   ———–分割线————-

   A：“喂，你有纸巾吗？”
   B：（摇头）
   A：“喂，有吗？”
   B：“没有啊。”
   A：“没有？没有你摇头！”
   B：“·····”

   其他话术：

   1。这个桥段用于打压完后的一段哄。例如：那个MM脸很大，打压她之后，她会显得很不高
   兴，我就会说：好吧好吧，你身材又好，又有气质，脸蛋又瘦又尖，标准的瓜子脸，而且
   还不是南瓜子，是葵花籽。
 
   面对这样与前面打压矛盾的夸赞，假的很明显。MM大多说：切。之类的话，不买账。
 
   我就会说：你看我，我都昧着良心夸你了，你咋还不高兴呢，做你男朋友必须多高端才及
   格？你给个标准，我立马考证去。
 
   然后MM就会扑哧的笑出来，然后粉拳加抱怨。

   ——————分割线—————————

   2.要到号，初期发短信的一个桥段。
   我：你叫什么名字，上次要电话忘了问你了。
   MM：我不想找男朋友，别在我这浪费时间了。
 
   我：你在短信上看见我的狐狸尾巴了？我总是夹着尾巴做人的啊。这不算是浪费时间。我
   尝试不是为了有机会，而是为了不后悔，你是我迄今唯一一个愿意冒险尝试的（无论你有
   多少个目标，做过多少次这样的事，你都要说是唯一一个，我知道这句话有贬低自己价值
   的效果，但是也让对方不会觉得你对谁都会说这样的话）我就是这种有枣没枣打三杆子的
   风格。
 
   MM：我这没枣。
   我：对不起啊，栗子树，你忙。
 
   到这里会有两种情况，A对方继续跟你聊，那就八仙过海吧。B对方不回或者只用哦，恩之
   类回复中断谈话。千万不要继续发。
 
   隔天
   我：砰砰砰。
   MM：？
   我：又是三杆子。
   MM：我晕。

   ——————分割线—————————

   姑娘：啊，打雷了
   我：恩，你怕么
   姑娘：是啊，最怕打雷了
   我：其实用不着，你非常安全。听过艾薇儿的《god is a girl》么？
   姑娘：听过，怎么了？
 
   我：上帝是个女孩儿，所以她不会对女人放电的。倒是我这样的帅哥，那才真是危险（骄
   傲风趣）
   姑娘：切，就你还帅哥（意料中）
   我：我觉得你应该保护一下我的生命安全（表情要自然，可以带点坏笑），然后就去牵手
   吧！

   ————分割线—————–

   A：昨天晚上我做了一个梦：上帝告诉我，我今生註定孤独。
   B：BLAABLAA~~（安慰之类的）
   A：但是破解的方法只有一个
   B：还有破解？
   A：把这个梦告诉十个傻子。
   B：你。。。梦嘛，你就别当真！
   A：但是我当时就哭了！
   B：为什么？
   A：因为我只认识你一个啊！天啊！我完了。
   A：但后来 我又梦到上帝了，这下子让我破涕为笑。
   B：为什么呀？
   A： 我把你的名字告诉了他，上帝说，你真会选人，那个傻子一个顶十。

   看到这里你会对话术有一定的体会，这比大多数人的对话强多了，我们模拟一段失败的对话。

   我：你好

   MM: 你好

   我：你在干嘛

   MM：没干嘛

   我：你家在哪

   MM：…

   求你放过妹纸，即便是个男的，都不想和你说话，因为你实在太无趣了。更多的话术惯例我会在后面给大家整理好，一些独门秘籍请允许我藏私。

   技巧篇之 冷读

   镜子原理：当你和对方吃饭时，如果对方用右手拿杯子喝水，你就用左手，在不经意间和她保持一致，总之就是和她照镜子一样，可以在潜意识上建立心有灵犀的感觉。

   杯子原理：当你想要测试对方对你的好感时，只需将自己的喝水的杯子“无意中”和她的杯子挨在一起，这样如果对方拿走杯子，放下后和你的杯子距离边远，那么你们心理距离还是很远的。

   同步呼吸法：沟通的关键不在于你如何去说话，而在于你如何去聆听。不要根据她说话的逻辑内容去点头，而是要配合她的呼吸节奏慢慢地深深地点头。这种同步呼吸法会在对方的潜意识建立对你的舒适感。

   两面原则：人总是期望有人能理解他被隐藏在深处的一面。如果你对一个说起与她外在特征相反的那种特征，往往会引起她的共鸣。比如说你表面看起来很活泼外向，其实有时你也有内向的时候，希望给自己一个空间让心灵平静一下。再比如，虽然有时你看上去不太爱说话，别人会误解你很冷漠。其实我看得出有时候你还是很懂得和人交流的，只不过是能够和你推心置腹的人不太好找罢了。

   方位原则：永远不要从背后接近女人，如果从正面面对女人，最好也要从侧面接近。其实还有其他一些讲究，比如最好从对方没有拿提包或行李的一侧接近，从头发分界线较窄的一边接近（即，如果头发遮住左边额头较多，露出右边额头较多，那就从右侧接近她）。如果有意把包放在你和她之间，就表明她还存在戒心，所以就要减缓进攻和交往，保持距离。

   卷入情境：人最喜欢和最关心的东西是自己，只要设法让对方说出自己的事情，她就会被卷入你所设置的情境中去了。所以说多引导她去说她自己的事情，她就会发生兴趣。要注意的是“引导”，而非盘问，你不是在审问。

   同调语言：有一种开启对方心扉的技巧是使用“同调”语言。即尽量模仿对方使用的一些关键词。比如说,你可以模仿MM经常用的口头禅,这样会让MM产生一种默契感。还有一个技巧,就是故意模仿MM的口误(但不能使用太贫,以免引起反感)

   握手大法：握手时，可以边用右手握，边用左手轻轻抓圌住对方的右胳膊。这样就会对他们的潜意识说无人能逃出我的控制。我才是掌握主导权的人。

   ……此处省略N中技巧，资料中都有，需要自己挖掘。

   技巧篇之 大数据

   一定不要看不起乞丐，很多人还不如乞丐，乞丐行乞和泡妞还是有相通之处的。

   某次我看到一手脚健全的人要钱，我当然不会给，对方1秒钟犹疑都没有，直接就走了，他或许想没必要在我这样没爱心的人身上浪费时间。

   而很多人怎么追妹子呢？

   死缠烂打

   妹纸明明已经明确表示对你没有兴趣，甚至怒言相向，你还使劲纠缠，这样的人其实连乞丐都不如，正确的做法是放弃这个妹子，立马切换目标。

   1个月找女友速成法：原谅我用这么粗浅的词，方法简单但效果不简单。

   用微信每天给附近的人打招呼，不要嫌累，100个人总有那么几个会回复你，当回复你信息的人增多时，其中必定就会有能约出来的。

   你可以构思一个精巧的打招呼话术，不断地优化，这样可以提高回复率，后期进行逐个攻破（每次最多同时聊天2~3个就可以，太多了你照顾不过来，然后找到其中能够深入沟通的那个重点突破，成功率就高多了）。

   知道为什么收到短信诈骗的消息看起来很傻，但是还是有人上当。

   其实是为了节约筛选成本。

   正如你用“你好”给妹纸打招呼时，这么无聊的信息她都会回的话，那么后期勾搭也比较容易。

   其次你要多参加一些聚会活动，一些同城群经常有举办，其中大部分是忽悠钱的，里面的妹纸都是雇的，但是也无所谓，一个好的聚会群他们会将你照顾的很好，可以适应一下和女神交流的感觉，毕竟下次举办活动还希望你能来呢。“XXX酒吧聚会，女生免费，男生100”有木有感觉很熟悉呢，如果有可能这是否可以成为一个同城赚钱项目呢？

   线下勾搭妹子的转化率其实远高于线上，我之前发了个QQ说说，估计很少人能明白其中的意思

   1，不断免费释放价值，我能免费送出去多少东西，我们就能免费得到多少有价值的东西。QQ可以免费用，也可以付费用，结果马化腾依然是富翁；
   2，在大家都做推广时，我不做，待大家都不做时，我才做。
   3，遇到实力强的同行学习他，遇到实力弱的同行建立关系，帮助他，整合他……
   4，参加聚会，遇到态度嚣张的，我忍耐，和气生财。只是不会与他合作。遇到态度诚恳，知书达理的兄台，建立友情，有钱一起赚。不装逼就不会作死，作死的根源就是不能正确认识自己，习惯性装逼……

   其中的第二条很有意思，用在泡妞上就是大家都在用微信、QQ、陌陌搞妹子，你就线下勾搭。

   如果你注册一个女号的话就会发现屌丝太多了，一个女号刷一下附近的人短时间就会有几十个人打招呼，大家都在线上勾搭，就会让妹子的选择空间增大，即便是一个负分的妹子，在网上你都不好约，但线下说不定你会被逆推。

   所以选对平台很重要。

   有没有发现上面其实应用了很多营销方面的知识，所以说万法相通。

   还有一些常用方法如：推拉、冰冻、还有更多的攻心话术我提供的压缩包都有，这些书之看过一些，剩下的其实内容大体一样，所以挑几本你喜欢的，坚持看下去并实践。。

   如果有错别字，请帮忙指正，毕竟篇幅太长，我再看写一遍就够了，再多看几遍会疯了，另外不要咨询我怎么找女朋友，我就是说说而已，想我这样正直高尚的人怎么会到处勾搭妹子呢，另外底下的资料都是别人整理的，我只是一个搬运工。如果那个妹子对我有好感，记得一定要给我说，我不嫌多。
**** 怎样勾搭大神，扩充你人脉的秘密！
   这是一篇处世的文章，难以形容它的价值。

   结识大神会少走很多弯路，然而多数时候我们都难以走进大神的朋友圈，这曾经是困扰我
   很久的问题。

   我什么都不懂…我没钱…我该怎么办…

   要记住一句话：别人并没有义务去帮助你，帮你是人情，不帮是本分。

   我曾经的困惑终于在接触社会工程学的时候解开了，这是一门包含心理、黑客、行为、艺
   术等综合学科。

   首先你要在心里去掉对方的神的光环，大神也是人、女神其实只是个女人，他们都要吃喝
   拉撒，会和你一样流鼻涕、打喷嚏、放屁、打嗝。

   1.满足对方的心理需求

   人都有被赞和认同的需要，我毫不吝啬溢美之词，会告诉对方那犹如滔滔江水般的仰慕，
   而这几乎是不用花费任何成本的，对方就会有好感，正所谓千穿万穿，马屁不穿。这里有
   一个最重要的地方，就是一定要赞美对方最擅长和自豪的地方。例如你去赞美一个富二代
   很有能力就比赞美他钱多好，赞美一个美女的气质就比赞美她的容貌好，赞美她的衣服漂
   亮就不如赞美他衣服的某个细节好。

   2.何谓惯性定律

   这个人如果帮助了你一次，那么下次帮你的概率就很高，这就是惯性定律，是经过科学统
   计得出的结论。

   我会问一些问题，其实每个问题都经过精心挑选的，既不会显得白痴又具有一定的探讨价
   值，这点我深有体会，每天问我咨询的人很多，但有一部人的问题根本没办法回答，甚至
   提问的人自己都不知道自己想问什么，这里我举几个例子。

   失败的提问 

   A:怎么在网上赚钱呢？

   B:怎样能快速增加粉丝？

   这类问题我每天都会遇到，如果你也是这样的提问，那么毫无疑问会被淹没，快速增加粉
   丝的提问居然连一个平台都没有，是微信、微博、知乎？这类问题我一般都直接忽略。

   成功的提问

   A:我最近在做贴吧营销，但是删帖比较厉害，有什么能避免删帖太多的技巧
 
   B:前几天在QQ克隆贴吧找了几个号克隆，但是我发现克隆后空间人气还是很少，是哪里出
   问题了吗？

   问题A就问的很好，至少足够精确，贴吧其实先要养号，然后连续签到，快速升级，不少平
   台可以代签到，此外手机端发帖比PC端审核松，另外就是语音广告一般不会被删，效果也
   不错，贴吧头像和签名都是可以利用的地方。

   问题B也不错，其实在百度QQ克隆贴吧找克隆的Q号效果都比较差，因为几乎都是万人骑的
   号了，每个号都被克隆了N次，效果不差才怪，方法就是在Q群里找人私聊，付费克隆，这
   样虽然效率低点，但至少是一手的。

   互惠原则

   曾经国外有一个教会募捐做出非常惊人的收益。

   志愿者拿着一朵红花先给路人，当路人错愕的瞬间思维就会进入一种奇妙的状态，我们称
   作能量最低点，当反应过来的时候花已经拿在手里。

   这时候志愿者指着募捐箱说他们在进行募捐，几乎没人会拒绝，一朵花使转化率提高了N倍。

   好笑的是那些花多半会被扔进附近的垃圾桶，这样志愿者又会把花取出来继续送给路人…

   而事情的核心其实是互惠原则，人在接受馈赠的时候会下意识的有反馈对方的想法。

   那么我们该怎么勾搭大神呢？

   方法就是：送！

   而我认为效果最好的其实并不是送红包，因为多数人都会选择送红包，这样人的神经就会
   陷入一种麻痹状态，缺少刺激感。

   最好的方法是实物。

   2007年左右，那时候黑客文化特别流行，没有人引路学任何东西都很漫长，一个简单的电
   脑远程控制我就学了很久，恰好有接触过社工，于是我将勾搭的目标设定为一个黑客。

   而我的方法就是送特产！

   对方收费培训基本都是上千块，问题是我一个穷学生根本没多余的钱，几十块钱给出去肯
   定没什么效果，但我又想认识人家，好在我还算有天赋，也看了一些杂七杂八的书，尤其
   社工相关的文章。

   先是表达仰慕之情，同时也将目前所处的情况完整的告诉了对方，虽然没钱但总要有点表
   示，所以我硬是送给对方一盒茶叶。

   自此我和大神的沟通就比较顺畅，紧接着我送了一箱苹果，也就是我们这的特产，在对方
   的再三推辞下还是被我强制送了。

   我的想法是这样的，虽然我没钱，但心意还是要表达的，这里面一半是出自真心一半是刻
   意送的。

   在我身边发生过好几个这样的事例，他们都是以勾搭的形式来获得青睐，但部分人度没把
   握好，反而给人献媚巴结的感觉，相反却不受重视。

   你应该有自己的想法和明确的目标，外圆内方，在囊中羞涩的时候而送东西是你感谢的另
   一种形式，而目的则是附带的，毕竟人和人来往也就这么回事。

 

   最没自尊的行为就是将自尊看的太重

   我时常瞧不起那些处事圆滑的人，那些动不动献媚的行为在我心里就和猫抓了一样难受，
   我以前认为是我心性刚正，然而这只是一种莫须有的自尊心罢了。

   而今那些帮助过我的人我都会给予示好，这个世界是要我们走出去，去拥抱，去改变，否
   则就如同我多年前写过的一条动态：

   我从未爱过这个世界，它对我也一样。

    对于我们来说比人脉更重要的是提升自己

   本篇文章只是在你感到迷茫，需要一个老师的时候可以用的一点小技巧，但如果沉浸在人
   脉中则未免舍本逐末。

   你若盛开，蝴蝶自来。
**** 结婚 
     创造更好生存、繁衍环境的本能
     女人说，我愿意对丈夫不离不弃一生伴他左右，但无法容忍他的冷漠、忽视。
     如果男人们能明白女性生理期的情绪不稳定源于内分泌变化，他们可能就不会觉得她任性妄为不可理喻。
     如果女人们能明白男性安静独处可以缓解压力，她们可能就不会胡思乱想自己是不是要被抛弃。
     但这一切，都只是生理行为，与我们的主观意识无关。
     放慢语速有助于降低对方的防御心理，深呼吸带来的充足氧气可以平复情绪，拥抱则会快速缓解焦虑。

     1、找对象不再看长相。五官端正身材匀称身体健康就行了。
     2、适合你的才是最好的。尝试过多次失败才知道懂事体贴的女生是世界上最好的女生。
     3、对于男人来说，事业永远是第一位，撩妹子还是放在后面吧。
** 潜意识行为 本性
** 生物本能
* 行为的意义 价值观 把意义留下
  行为得民心者得天下(都认可的行为)
** 欲望
*** 手淫有害 精气神
* 行为熟练度 能力
* 行为分工 阶级
** 劳动行为分工 
* 人类行为学理论
在人类行为中米塞斯提出了一套观念，主张人类所有带有意识的行动都是为了增进他们自己
的快乐和满足感。他谨慎的强调人类行为学并不是要统一定义快乐的目标为何，而只是要研
究那些在个人看来能够使他快乐的目标。而一个人增进快乐的方式就是排除那些使他不快乐
的来源。由于未来是无法确定的，因此所有人类行为也都是出自对于未来的预测。

“会行为的人类”被定义为是一个有能力进行逻辑思考的人，否则这个人将只不过是一只被
本性所驱动的生物而已。同样的，一个会行为的人类必定有某些让他感到不快乐的来源，同
时这个人也相信自己有能力排除这个不快的来源，否则人类根本就不会行动。

米塞斯提出的另一个结论是，人类所有的决策都是以排序方式为基础的。也因此，一个人不
可能同时进行超过一种行动，知觉的大脑在同一时间只有可能处理一个决策—即使这些决策
可以被迅速排列亦然。因此人类只会先排除掉那个最使他感到不快的来源，接着再排除排序
第二紧迫的不快来源。除此之外，米塞斯认为主观的价值是不可能以数学方式计算的，人不
可能以基数来评估他的价值衡量。举例而言，一个人可以说“我倾向于先买下一台电视机，
而不是买下一台DVD播放器”，但他不可能说“我倾向买下一台电视机的欲望高过买下一台
DVD播放器的2.5倍。”

在一个人满足了他最紧迫的目标后，他会接着转向第二紧迫的目标，而第二紧迫目标又总是
比他的第一紧迫目标还要来的不重要。也因此，当一个人达成越来越多未来的目标时，个别
目标的满足感（或称为边际效用）也会因此减少。这个现象又可以称为边际效益递减。

因此在人类社会中，许多人类行为都是处于人与人之间的贸易，一个人将他视为较不重要的
东西与另一个人交换他视为较重要的东西，而另一个人也对贸易抱有相同的期望，希望换得
他认为较重要的东西、而牺牲他认为较不重要的东西。人类行为学对于此领域的研究又称为
交易经济学（Catallactics），这也是在经济学界较容易被接受的理论。
