* 道德
道德，指衡量行为正当的观念标准。不同的对错标准是特定生产能力、生产关系和生活形态
下自然形成的。一个社会一般有社会公认的道德规范。只涉及个人、个人之间、家庭等的私
人关系的的道德，称私德；涉及社会公共部分的道德，称为社会公德。

另特此补充，道德为非正式公共机制，非正式即指无法律或权威能判定正确与否，而公共机
制指所有场合都能套用的准则。[1]

道德相对主义者认为，道德和文化有密切关系：虽然人类的道德在某些方面有共通性，但是
在不同的时代，不同的社会，往往有一些不同的道德观念；不同的文化中，所重视的道德元
素及其优先性、所持的道德标准也常常有所差异；同样一种道德，在不同文化社会背景中的
外在表现形式、风俗习惯往往也相去甚远。

语录

在一个人民的国家中还要有一种推动的枢纽，这就是美德。 —— 孟德斯鸠

人不能像走兽那样活着，应该追求知识和美德。 —— 但丁

勿以恶小而为之，勿以善小而不为。惟贤惟德，能服于人。 —— 刘备

不患位之不尊，而患德之不崇；不耻禄之不伙，而耻智之不博。 —— 张衡

土扶可城墙，积德为厚地。 —— 李白

行一件好事，心中泰然；行一件歹事，衾影抱愧。 —— 神涵光

入于污泥而不染、不受资产阶级糖衣炮弹的侵蚀，是最难能可贵的革命品质。 —— 周恩来

一个人最伤心的事情无过于良心的死灭。 —— 郭沫若

害羞是畏惧或害怕羞辱的情绪，这种情绪可以阻止人不去犯某些卑鄙的行为。 —— 斯宾诺莎

应该热心地致力于照道德行事，而不要空谈道德。 —— 德谟克利特

感情有着极大的鼓舞力量，因此，它是一切道德行为的重要前提。 —— 凯洛夫

没有伟大的品格，就没有伟大的人，甚至也没有伟大的艺术家，伟大的行动者。 —— 罗曼·罗兰

理智要比心灵为高，思想要比感情可靠。 —— 高尔基

共产主义不仅表现在田地里和汗水横流的工厂，它也表现在家庭里、饭桌旁，在亲戚之间，
在相互的关系上。 —— 马雅可夫斯基

有德行的人之所以有德行，只不过受到的诱惑不足而已；这不是因为他们生活单调刻板，就
是因为他们专心一意奔向一个目标而无暇旁顾。 —— 邓肯

人类被赋予了一种工作，那就是精神的成长。 —— 列夫·托尔斯泰

人在智慧上应当是明豁的，道德上应该是清白的，身体上应该是清洁的。 —— 契诃夫

良心是由人的知识和全部生活方式来决定的。 —— 马克思

守法和有良心的人，即使有迫切的需要也不会偷窃，可是，即使把百万金元给了盗贼，也没
法儿指望他从此不偷不盗。 —— 克雷洛夫

精神上的道德力量发挥了它的潜能，举起了它的旗帜，于是我们的爱国热情和正义感在现实
中均得施展其威力和作用。 —— 黑格尔

把“德性”教给你们的孩子：使人幸福的是德性而非金钱。这是我的经验之谈。在患难中支
持我的是道德，使我不曾自杀的，除了艺术以外也是道德。 —— 贝多芬

如果道德败坏了，趣味也必然会堕落。——狄德罗

我愿证明，凡是行为善良与高尚的人，定能因之而担当患难。 —— 贝多芬

装饰对于德行也同样是格格不入的，因为德行是灵魂的力量和生气。 —— 卢梭

我深信只有有道德的公民才能向自己的祖国致以可被接受的敬礼。 —— 卢梭

让我们把不名誉作为刑罚最重的部分吧！ —— 孟德斯鸠

对于事实问题的健全的判断是一切德行的真正基础。 —— 夸美纽斯

德行的实现是由行为，不是由文字。 —— 夸美纽斯

教育的唯一工作与全部工作可以总结在这一概念之中——道德。 —— 赫尔巴特

美德有如名香，经燃烧或压榨而其香愈烈，盖幸运最能显露恶德而厄运最能显露美德也。
—— 培根

阴谋陷害别人的人，自己会首先遭到不幸。 —— 伊索

智者宁可防病于未然，不可治病于已发；宁可勉励克服痛苦，免得为了痛苦而追求慰藉。
—— 托马斯·莫尔

有一个现象的明显程度已经让我毛骨悚然，这便是我们的人性已经远远落后我们的科学技术
了。 —— 爱因斯坦

原文:It has become appallingly obvious that our technology has exceeded our
humanity.

我们有力的道德就是通过奋斗取得物质上的成功；这种道德既适用于国家，也适用于个人。
—— 罗素

养成他们有耐劳作的体力，纯洁高尚的道德，广博自由能容纳新潮流的精神，也就是能在世
界新潮流中游泳，不被淹没的力量。 —— 鲁迅

只有在不仅消灭了阶级对立，而且在实际生活中也忘却了这种对立的社会发展阶段上，超越
阶级对立和超越这种对立的回忆的、真正人的道德才成为可能。 —— 恩格斯

我们有无产阶级道德，我们应该发展它，巩固它，并且以这种无产阶级道德教育未来的一代。
—— 加里宁

革命道德不是从天上掉下来的。它是从日常的坚持不懈的斗争和锻炼中发展和巩固起来的，
正如玉石越磨越亮，黄金越炼越纯一样。 —— 胡志明

孩子是要别人教的，毛病是要别人医的，即使自己是教员或医生。但做人处事的法子，却恐
怕要自己斟酌，许多人开来的良方，往往不过是废纸。 —— 鲁迅

不是不能见义，怕的是见义而不勇为。 —— 谢觉哉

要留心，即使当你独自一人时，也不要说坏话或做坏事，而要学得在你自己面前比在别人面
前更知耻。 —— 德谟克利特

静以修身，俭以养德。 —— 诸葛亮

君子忧道不忧贫。 —— 孔丘

贫而无谄，富而无骄。 —— 子贡

夫君子之行，静以修身，俭以养德，非淡泊无以明志，非宁静无以致远。 —— 诸葛亮

霸祖孤身取二江，子孙多以百城降。豪华尽出成功后，逸乐安知与祸双？ —— 王安石

半截粉条犹爱惜公家物件总宜珍。诸生不解余衷曲，反谓余为算细人。 —— 徐特立

让自己完全受财富支配的人是永不能合乎公正的。 —— 德谟克利特

善气迎人，亲如弟兄；恶气迎人，害于戈兵。 —— 管仲

天下有大勇者，猝然临之而不惊，不故加之而不怒。 —— 苏轼

我们应该注意自己不用言语去伤害别的同志，但是，当别人用语言来伤害自己的时候，也应
该受得起。 —— 刘少奇

讲话气势汹汹，未必就是言之有理。 —— 萨迪

不论你是一个男子还是一个女人，待人温和宽大才配得上人的名称。一个人的真正的英勇果
断，决不等于用拳头制止别人发言。 —— 萨迪

火气甚大，容易引起愤怒底烦扰，是一种恶习而使心灵向着那不正当的事情，那是一时冲动
而没有理性的行动。 —— 彼得·阿柏拉德

青年人应当不伤人，应当把个人所得的给予各人，应当避免虚伪与欺骗，应当显得恳挚悦人，
这样学着去行正直。 —— 夸美纽斯

坏事情一学就会，早年沾染的恶习，从此以后就会在所有的行为和举动中显现出来，不论是
说话或行动上的毛病，三岁至老，六十不改。 —— 克雷洛夫

一时的暴虐，岂能抗得了千古的道义？！ —— 杨云萍

持枪作盗进行侵，利笔文章诲杀淫；技艺人才培不易，植因造业孽缘深。—— 邓丰洲《专业
道德》

世界上最伟大的美德是爱祖国。——歌德
* 道德
( 做事情要有道德 ) 
* [[file:wuji.org][无道德]]
