#+TITLE: git 
#+DESCRIPTION: git 版本控制
#+TAGS[]: git
#+CATEGORIES[]: 技术
#+DATE: 2019-12-25T06:23:31+08:00

追踪文件修改历史信息。

# more   
* git 
** 初始化设置
   #+begin_src shell 
     git config [--system,--global, --list]
     git config user.name = "用户名"
     git config user.email = "邮箱"
   #+end_src
   
*** 设置远程登录 
    1. 创建 SSH Key  ssh-keygen -t rsa -C "youremail@example.com"
    2. 把公钥 rsa.pub 的内容复制到 Github "Account settings" 的 SSH Keys 中
    3. ssh-add rsa  添加私钥 
    4. 测试  ssh git@github.com  \ ssh -T git@e.coding.net
    5. coding.net 似乎是私有的，要分配权限才能 clone ?? 
** 用法
*** 初始化版本库
**** 1.git clone 
     #+begin_src sh
       git clone git://github.com/someone/some_project.git some_project
     #+end_src
**** 2.git remote
     #+begin_src sh
     git remote add origin git://github.com/someone/another_project.git
     #+end_src
*** 常用命令
**** 1、远程仓库相关命令
     查看远程仓库：$ git remote -v\\
     添加远程仓库：$ git remote add [name] [url]\\
     删除远程仓库：$ git remote rm [name]\\
     修改远程仓库：$ git remote set-url --push [name] [newUrl]\\
     拉取远程仓库：$ git pull [remoteName] [localBranchName]\\
     推送远程仓库：$ git push [remoteName] [localBranchName]

     如果想把本地的某个分支 test 提交到远程仓库，并作为远程仓库的 master 分支，或者作为另外一个名叫 test 的分支，如下：/

     $git push origin test:master // 提交本地 test 分支作为远程的 master 分支\\
     $git push origin test:test // 提交本地 test 分支作为远程的 test 分支

**** 2、分支(branch)操作相关命令
   - 查看本地分支：$ git branch
   - 查看远程分支：$ git branch -r
   - 创建本地分支：$ git branch [name] ----注意新分支创建后不会自动切换为当前分支
   - 切换分支：$ git checkout [name]
   - 创建新分支并立即切换到新分支：$ git checkout -b [name]
   - 删除分支：$ git branch -d [name] ---- -d 选项只能删除已经参与了合并的分支，对于未有合并的分支是无法删除的。如果想强制删除一个分支，可以使用-D 选项
   - 合并分支：$ git merge [name] ----将名称为[name]的分支与当前分支合并
   - 创建远程分支(本地分支 push 到远程)：$ git push origin [name]
   - 删除远程分支：$ git push origin :heads/[name] 或 $ git push origin :[name]

     /创建空的分支：(执行命令之前记得先提交你当前分支的修改，否则会被强制删干净没得后悔)/

     #+begin_src sh
     $git symbolic-ref HEAD refs/heads/[name]
     $rm .git/index
     $git clean -fdx
     #+end_src

**** 3、版本(tag)操作相关命令
   - 查看版本：$ git tag
   - 创建版本：$ git tag [name]
   - 删除版本：$ git tag -d [name]
   - 查看远程版本：$ git tag -r
   - 创建远程版本(本地版本 push 到远程)：$ git push origin [name]
   - 删除远程版本：$ git push origin :refs/tags/[name]
   - 合并远程仓库的 tag 到本地：$ git pull origin --tags
   - 上传本地 tag 到远程仓库：$ git push origin --tags
   - 创建带注释的 tag：$ git tag -a [name] -m 'yourMessage'

**** 4、子模块(submodule)相关操作命令
     添加子模块：$ git submodule add [url] [path]
     如：$git submodule add [[https://link.jianshu.com?t=git://github.com/soberh/ui-libs.git][git://github.com/soberh/ui-libs.git]] src/main/webapp/ui-libs

     初始化子模块：$ git submodule init ----只在首次检出仓库时运行一次就行
     更新子模块：$ git submodule update ----每次更新或切换分支后都需要运行一下

     删除子模块：（分 4 步走哦）
     1. $ git rm --cached [path]
     2. 编辑“.gitmodules”文件，将子模块的相关配置节点删除掉
     3. 编辑“ .git/config”文件，将子模块的相关配置节点删除掉
     4. 手动删除子模块残留的目录

**** 5、忽略一些文件、文件夹不提交
     在仓库根目录下创建名称为“.gitignore”的文件，写入不需要的文件夹名或文件，每个元素占一行即可，如
     #+begin_example
     target
     bin
     ,*.db
     #+end_example

** github
  热门  https://github.com/trending
  专题 https://github.com/topics

  搜索
  优秀项目  Awesome + 关键字  
  stars: fork
  qt in:name：表示在项目名称中搜索 qt 关键字
  qt in:readme：表示在项目 readme 中搜索 qt 关键字
  qt in:description：表示在 项目描述中搜索 qt 关键字
  qt in:USERNAME：表示在 USERNAME 中搜索 qt 关键字
  qt in:ORGNAME：表示在组织或机构名中搜索 qt 关键字
  size:>=5000 Qt ：搜索大小超过 5M 的包含 Qt 关键字项目
  language:C++ location:china 搜索国内的开发者，语言限定为 C++

  后缀
  stars:>20 extension:el language:elisp
*** 对于 depth 为1 时，要复制其他分支
    #+begin_src sh
    $ git clone --depth 1 https://github.com/dogescript...
    $ git remote set-branches origin 'remote_branch_name'
    $ git fetch --depth 1 origin remote_branch_name
    $ git checkout remote_branch_name
    #+end_src



    


    
** [[https://www.jianshu.com/p/afeeaea8c0c8][git基本操作、stash暂存、stash找回、创建分支、删除分支、git忽略文件失效、合并分支、重定向项目地址 - 简书]] :website:

 [2020-10-31 六 06:49]

*** Article

**** git 基本操作流程


   =git status= 查看本次的修改、新建、删除等信息(new file:新建文件，modified:修改文件，deleted: 删除的文件)\\
   =git pull= 拉取代码；\\
   =git add .= 添加所有即将提交的文件，\\
   =git add fileNamePath=添加某个文件\\
   =git commit -'提交的日志'= 提交到本地，\\
   =git push= 提交到git服务器；\\
   git 另一种提交方式，\\
   =git commit -a -m '提交的日志'= 添加所有即将提交的文件并提交到本地 ，\\
   =git commit -a -m= 相当于 =git add .= 和 =git commi -' '=命令的集合，当你使用 =git commit -a -m ' '=命令时，就会执行上述两个操作；

   --------------

**** git 暂存


   使用暂存的好处是，提交时不会产生类似

   #+BEGIN_QUOTE
     (Merge branch 'prd_v1.5' of http:// //././ *.**/bb_ios/bbch**** into prd_v1.5)
   #+END_QUOTE

   的日志，且安全可靠，会尽量避免将错误提交到服务器上面。

   =git stash=暂存（存储在本地，并将项目本次操作还原）\\
   =git stash pop= 使用上一次暂存，并将这个暂存删除，使用该命令后，如果有冲突，终端会显示，如果有冲突需要先解决冲突（这就避免了冲突提交服务器，将冲突留在本地，然后解决）\\
   =git stash list= 查看所有的暂存\\
   =git stash clear= 清空所有的暂存\\
   =git stash drop [-q|--quiet] []= 删除某一个暂存，在中括号里面放置需要删除的暂存ID\\
   =git stash apply= 使用某个暂存，但是不会删除这个暂存

   --------------

******* 暂存不小心清空，结果里面有需要的代码，也是有找回方法的


   =git fsck --lost-found= 命令找出刚才删除的分支里面的提交对象。\\
   然后使用 =git show= 命令查看是否正确，如果正确使用 =git merge=命令找回

   举个栗子🌰：\\
   =git fsck --lost-found=\\
   终端显示

   #+BEGIN_QUOTE
     Checking object directories: 100% (256/256), done.

     Checking objects: 100% (109977/109977), done.

     dangling commit bb01f8dfaa14ea7960d294304c61c4b401eaf2c6

     dangling commit 0203281d5dee10835022ff6cfdcda5050a372762
   #+END_QUOTE

   然后查看那个版本\\
   =git show bb01f8dfaa14ea7960d294304c61c4b401eaf2c6=\\
   结果查看图1

   记录中会描述日期和摘要，日期是你git stash的日期，摘要会记录你是在哪一条commit 上进行git stash操作的，找到后将执行 =git merge bb01f8dfaa14ea7960d294304c61c4b401eaf2c6=

   图1

**** git 创建本地分支并推送到服务器


   创建并切换到分支branchName\\
   =git checkout -b branchName=

   推送本地的 /branchName/(冒号前面的)分支到远程origin的 /branchName/(冒号后面的)分支(没有会自动创建)

   =git push origin branchName:branchName=

   在这样的命令下，如果你本地有代码，会自动切换到新的分支上，所以不必担心，你修改很多之后，从新创建分支会出现正常切换分支因为有未提交的代码而创建不成功的情况.

   */发现问题/*\\
   如果命令行提示 /git branch --set-upstream dev origin/branchName则/需在终端输入 =git push -u origin branchName=

**** 删除分支


   删除本地分支： =git branch -d [branchname]=\\
   删除远程分支： =git push origin --delete [branchname]=

**** git忽略文件


   生成git忽略文件.gitignore文件，使用终端进入到你要生成.gitignore的目录，使用命令 =touch .gitignore=,就会生成。

   下面是.gitignore的常用规则：

   - /mtk/ 过滤整个文件夹

   - *.zip过滤所有.zip文件

   - /mtk/do.c 过滤某个具体文件

   这样文件或者文件夹就被过滤了，当然本地库中还有，只是push的时候不会上传。

   .gitignore还可以指定要将哪些文件添加到版本管理中：

   - !*.zip

   - !/mtk/one.txt

   如果你将文件加入到了 /.gitignore/文件里面，但是没有说生效，为什么呢？因为之前你已经把这个文件push到过远程仓库了，请使用以下命令

   #+BEGIN_EXAMPLE
        git rm --cached `git ls-files -i --exclude-from=.gitignore`
   #+END_EXAMPLE

   经过我几次实验之后发现，上述命令在之前没有创建.gitignore文件但是已经向服务器push过代码的时候好使，但是在已经使用过这个命令后，由于其他分支并没有添加忽略文件，合并分支后，忽略文件失效，那么上述命令可能失效，那么先把本地缓存删除（改变成未track状态），然后再提交，方案如下

   #+BEGIN_EXAMPLE
        git rm -r --cached .
       git add .
       git commit -m '日志'
   #+END_EXAMPLE

   要记得，因为改变了一些东西，所以要从新pod install 然后提交代码，但是要使用 =git status=查看状态，比如已经忽略了 /Podfile.lock/，那么查看时没有 /Podfile.lock/那就是好了。

**** 合并分支


   场景如下：\\
   例如现在有分支 =master=和分支 =A=,要将分支 =A=的代码合并到 =master=\\
   第一步：切换到分支 =master=，在终端输入命令

   #+BEGIN_EXAMPLE
        git checkout master 
   #+END_EXAMPLE

   第二步：合并分支

   #+BEGIN_EXAMPLE
        git merge --no-ff -m 'version:3.0.5_buildL19011720' A
   #+END_EXAMPLE

   第三步：如果有冲突解决冲突，解决冲突后 =add .= -> =git commit -m '提交原因'=\\
   第四步：

   #+BEGIN_EXAMPLE
        git push
   #+END_EXAMPLE

   部分摘自自己的博客 [[https://www.jianshu.com/p/1d5c5ed615d3]]，新文章使用Mac down书写

**** 重定向项目地址


****** 第一种方法


   第一步： =cd=到项目目录下\\
   第二步 ：

   #+BEGIN_EXAMPLE
        git remote set-url origin 新项目地址
       //例如新项目地址是 www.jianshu.com，示例如下
       git remote set-url origin www.jianshu.com
   #+END_EXAMPLE

****** 第二种方法


   第一步： =cd=到项目目录下\\
   第二步：执行命令 =cd .git=\\
   第三步：执行命令 =open config=\\
   第四步：将新项目地址替换到图2 红条覆盖位置\\

   图2


   
** [[https://juejin.im/post/6844903812524670984][Git submodule使用指南（一）]] :website:

 [2020-11-02 一 09:55]

*** Article

**** 问题场景


  相信任何开发，都会遇到一种情况。在做不同的项目，但是又都会使用到一些常用的方法_组件_代码块等等。 作为一个追求优雅的开发人员，肯定不能接受一段代码到处复制粘贴的操作。而且一旦这段代码日后需要更新，到处粘贴的话就需要全局搜索然后含泪修改了。 那么有没有一种办法，能够作为一些公共代码的“栖息地”，可以做到一处编写，到处使用呢？

  *答案是有的。*

  --------------

**** 寻找工具


  经过在知名404网站上一番搜寻，找到了Git内置的一个功能：submodule。

***** 什么是submodule


  #+BEGIN_QUOTE
    有种情况我们经常会遇到：某个工作中的项目需要包含并使用另一个项目。 也许是第三方库，或者你独立开发的，用于多个父项目的库。 现在问题来了：你想要把它们当做两个独立的项目，同时又想在一个项目中使用另一个。

    Git 通过子模块来解决这个问题。 子模块允许你将一个 Git 仓库作为另一个 Git 仓库的子目录。 它能让你将另一个仓库克隆到自己的项目中，同时还保持提交的独立。
  #+END_QUOTE

  --------------

**** 如何使用
***** 添加子模块


  #+BEGIN_EXAMPLE
       # 直接clone，会在当前目录生成一个someSubmodule目录存放仓库内容
      git submodule add https://github.com/chaconinc/someSubmodule

      # 指定文件目录
      git submodule add https://github.com/chaconinc/someSubmodule  src/submodulePath
       复制代码
  #+END_EXAMPLE

  新增成功之后，运行 =git status=会在父仓库发现增加了2个变化

  1. new file: .gitmodules
  2. new file: someSubmodule（实际上并不是一个file）

  展开说说：

  1. 什么是.submodules .submodules是记录当前项目的子模块配置的文件，里面保存了项目 URL 与已经拉取的本地目录之间的映射。

  2. 子模块目录 在新增完子模块之后，执行 =git status=之后，会看到类似下面的信息

  #+BEGIN_EXAMPLE
       $ git diff --cached someSubmodule
      diff --git a/someSubmodule b/someSubmodule
       # 重点是下面这行的 160000
      new file mode 160000
      index 0000000..c3f01dc
      --- /dev/null
      +++ b/DbConnector
      @@ -0,0 +1 @@
      +Subproject commit c3f01dc8862123d317dd46284b05b6892c7b29bc
       复制代码
  #+END_EXAMPLE

  虽然someSubmodule是父仓库里面的一个目录，但是Git并不会列出里面所有的变化，而是会当做一个特殊的提交。 PS：160000模式。 这是 Git 中的一种特殊模式，它本质上意味着你是将一次提交记作一项目录记录的，而非将它记录成一个子目录或者一个文件。

***** clone已经包含子模块的项目


  正常clone包含子模块的函数之后，由于.submodule文件的存在someSubmodule已经自动生成。但是里面是空的。还需要执行2个命令。

  #+BEGIN_EXAMPLE
        # 用来初始化本地配置文件
      git submodule init
       # 从该项目中抓取所有数据并检出父项目中列出的合适的提交(指定的提交)。
      git submodule update
      ------------------更好的方式---------------------
       # clone 父仓库的时候加上 --recursive，会自动初始化并更新仓库中的每一个子模块
      git  clone --recursive https://github.com/chaconinc/MainProject
       复制代码
  #+END_EXAMPLE

***** git submodule 工作流

  当一个项目里面包含子模块的时候，不仅仅需要对父仓库进行版本管理，子模块目录下也是存在版本的。那在不同的父仓库下面如何进行子模块的版本管理也成为新的问题。

  最简单的办法，就是主项目只专注使用子模块的master分支上的版本，而不使用子模块内部的任何分支版本。

  操作如下：

  #+BEGIN_EXAMPLE
       cd submodulePath
      git fetch
      git merge origin/master
       复制代码
  #+END_EXAMPLE

  此时在主项目就能看到submodule目录已经更新了。 当然这也操作有点不方便，下面是更简便的方法：

  #+BEGIN_EXAMPLE
       # Git 将会进入子模块然后抓取并更新，默认更新master分支
      git submodule update --remote
       复制代码
  #+END_EXAMPLE

  如果需要更新其他分支的话，需要另外配置。

  #+BEGIN_EXAMPLE
        # 将git submodule update --remote 的分支设置为stable分支
      git config  -f .gitmodules submodule.DbConnector.branch stable
       复制代码
  #+END_EXAMPLE


** git配置过程中fatal:拒绝合并无关的历史
首先将远程仓库和本地仓库关联起来：

git branch --set-upstream-to=origin/master master

然后使用git pull整合远程仓库和本地仓库，

git pull --allow-unrelated-histories    (忽略版本不同造成的影响)

* faq
** 在Git存储库中查找并还原已删除的文件
   查找影响给定路径的最后一次提交。由于文件不在head commit中，所以此commit必须已将其删除。
   git rev-list -n 1 HEAD -- <file_path>
 
 然后在提交之前签出版本，使用插入符号(^符号：
 git checkout <deleting_commit>^ -- <file_path>
 
 或者在一个命令中，如果$file是有问题的文件。
 git checkout $(git rev-list -n 1 HEAD --"$file")^ --"$file"
 
 如果您使用的是zsh并启用了扩展的_glob选项，插入符号将无法工作。你可以用~1代替。
 git checkout $(git rev-list -n 1 HEAD --"$file")~1 --"$file"

 - 2
 使用git log --diff-filter=D --summary获取所有删除文件的承诺和删除文件的承诺；
使用git checkout $commit~1 path/to/file.ext恢复删除的文件。
其中，$commit是您在步骤1中发现的承诺值，例如e4cf499627。
