#+TITLE: gimp 小难题
#+DESCRIPTION: 照片处理
#+TAGS[]: gimp 
#+CATEGORIES[]: 技术
#+DATE: 2020-01-25T06:56:22+08:00
#+draft: true

gimp 用于解决平面设计中的问题。

# more

** 基础
*** 概念 
**** 色
     我们肉眼看到的发光物或反光物的一种视觉现象，瞎子看不到色。
   
     #+begin_quote
     人们对色的喜爱不一样，有人喜欢白色，有人喜欢红色。
     #+end_quote
**** 像素与矢量
     矢量是包含了它们从一个端点到另一个端点的路径信息的线。他们没有关于在 GIMP 的图像窗口中创建像素的信息。

像素是一个点，有红色、绿色、蓝色和透明度等级。大多数 GIMP 工具是基于光栅的，这意味着它们操作像素。
**** 分辨率
     分辨率是单位面积的色点，单位为 PPI（Pixels Per Inch），5PPI 表示每平方英寸有 5*5 个像素，分辨率越高像素图越清晰度。
    
**** 色的合成
     自然界中的颜色亿亿万，但在计算机上，由于科技的限制，只能表示色的一部分，有如下几种合成方式。 
   
     - 色相、饱和度和明度系统 (HSB) [ 基于人眼的直接感官，就像我们常说的深蓝呀，品红啊，就是 HSB 模式  ]
     - 红绿蓝三原色(RGB) [ 发光体，显示器用来合成颜色的模式，红绿合成黄，稍微红稍微绿合成稍微黄，这样表示的颜色范围就多啦 ] [ 加色模式，发光原理，越变越亮 ]
     - RGBA [ 图像软件使用的，alpha 通道用来作为选区的 ]
     - 青、洋紅、黄、黑四元色 (CMYK) [ 用在印刷里面调色用的 ] [ 减色模式，反射原理 ，越变越黑 ]

       #+begin_quote
       异色，不同颜色模式下，不能表示的颜色
       #+end_quote
*** 工具箱
**** 工具 
     说明：大多数工具是基于光栅的
***** 选择工具 (创建可编辑的选区)
***** 路径工具 (创建或编辑路径)
***** 缩放工具(调整视图)
***** 采色器
***** 测量工具 (测量角度和距离)
***** 移动工具 (可移动图层，选区，文本，蒙板)
***** 校准工具 (对齐图层)
***** 裁剪工具 (裁剪图层)
***** 转换工具 (可旋转图层，选区，路径)
***** 缩放、剪切工具 (进行图像缩放，平行四边形变换)
***** 透视、翻转工具 (进行边缘拉伸，或水平，垂直翻转)
***** 文字工具 
***** 填充工具 (填充纯色或图案)
***** 渐变工具 (平滑渐变)
***** 绘图工具 (画线条) [ 铅笔，画笔，喷枪]
***** 橡皮擦 (擦除像素，背景图层用背景色擦)
***** 墨水工具
 是专门为像 Wacom 这样的绘图板设计的。它可以对压力和平板电脑的倾斜特性做出反应。
***** 克隆工具 (克隆像素，按 CTRL 并单击鼠标(必须在同一图层))
***** 模糊/锐化,减淡/加深
***** 污迹 (想象你用手指在画布上划过未干的油漆)
**** 工具选项
     每个工具有自己的附加属性可供设置
*** 图像窗口
    每个图像都有一个窗口，用于编辑图像，单窗口模式下用标签显示
*** 首选项
*** 图层和模式
    层就像是一层层叠加的透明纸张,我们把颜色放在纸张上面。
    
    图层可以使用蒙版来隐藏图层的某些部分
**** 绘图模式 
     三组通道的合成方式，相当于用某种画笔作画 
    
     - 正常 绘制工具添加的新像素的颜色替换层中现有像素的颜色
     - Dissolve(溶解) 笔画中加入了随机的空白区域。这类似于用画笔的笔尖在画布上轻涂颜料
     - Behind 在具有透明度的图层中，这种模式只绘制透明区域
     - 颜色擦除 类似于橡皮擦工具
     - addition 减淡、加深
     - Overlay 叠加(黑色加深，亮色变浅)
     - soft light 柔和 (另一种叠加)
     - hard light (强光)
     - hue 色调
     - color 色彩模式
**** 图层模式
图层模式与绘图模式差不多，就是图层之间混合
**** 使用图层模式为图像着色
**** 使用图层蒙版为图像着色
*** 色彩模式
    当处理图像时，GIMP 使用三种颜色模式之一: RGB、灰度或索引
*** 路径 (选区到路径)  -> 矢量绘图 (路径描边)
** 摄影师 (光栅处理)
*** 柔光(使照片模糊) 
   一般会复制两个图层，进行高斯模糊等，然后翻转颜色，然后进行色相饱和调节，最后进行图层的柔光。
   
但对于眼睛，嘴巴等需要清晰的地方，需要添加蒙板，然后用喷枪，软边的毛刷，给眼睛嘴巴刷刷
*** 照片素描 (草图)
    三个图层
**** 简单草图层 (以此为原图，复制两个新层) 
    去掉饱和(变灰)，然后滤镜(边缘检测->索贝尔)，差不多就素描了。然后加强白色(颜色->色阶，白色拉到左边点) ，然后翻转颜色，变成白底黑线，
    
    还可以试下别的边缘检测
**** 添加深度
在此层中，添加高斯模糊，设置图层模式为 加深，使背景黑色加深，
在上面一层，再添加高斯模糊，半径大点，图层模式为强光。 
**** 最后的润色
** 网络平面设计
*** 凝胶按钮 (现在用的不多了，都是 CSS 了)
**** 基础层 
     拉四条矩形辅助线，然后画个矩形，设置圆角，移除辅助线
**** 颜色层
    选一个颜色，拖到选区里面，收缩边缘，保存到通道
    返回图层，清除选区 （C-S-a)
** 广告设计和特效
** 特效
** 有用的软件包
***  GIMP Paint Shop
    http://code.google.com/p/gps-gimp-paint-studio/
*** 更多扩展
    http://registry.gimp.org/
** 默认的画布大小为 640 × 400 像素
** 图像基础
*** 图层
    图层就是透明的纸，修改照片时，可以把图层覆盖在照片上，在图层上操作，就不会破坏原图了。 
*** 灰度
    灰度就相当于带了一副墨镜看照片一样，颜色变得灰蒙蒙。
*** 通道
    图像合成中，不同色的量， 在 *RGB*   合成模式中，有 3 个通道，而 *CMYK* 图像则默认有四个通道

