* 视觉效果
** 正片负冲
** LOMO 色彩风格
** 杂志上模特皮肤柔和的中间影调
* 用PS创作而不是学会使用
许多令人怦然心动的大片，并不需要多么高深的 Photoshop 技巧，“通道”可以算是最高
难度的动作。用好 Photoshop，需要的是能够建立创作思路，并且可以驾驭工具的大脑和双
手。

问自己：在你尝试“成片负冲”的效果之前，你是否真的尝试过胶片摄影，是否在数天的等
待之后，用双眼和记忆，去体会天气、光线、135 画幅的景深、光圈、正片、负冲、胶片感
光度、冲洗工艺等各种因素所带来的色彩夸大？在你疯狂比较各种 LOMO 风格制作教程的差
异之前，是否了解为什么 LOMO 相机会带来不同的色彩风格，如何在 Photoshop 这个空前
强大的数字暗房里面，用大自然所建立起来的色彩规则，去还原这个渲染的机理？

这夸张了吗？完全没有。我所知的 Photoshop 大师们，他们并不是还没学会 Lab 通道是怎
么回事就成了“光影魔术手”，但他们从未因为对“精通工具”的追求，而忽视了创作本身。
更不会因为对数字技术的追求，而忘记了艺术本身的模样。

所以，在学习 Photoshop 这件事情上，我认为，不要抱有“精通”这样的目标。学多少，
用多少，多用，用熟了，再进阶。一口吃成个胖子不是正经事。

关于 Photoshop 的教材，我认为，http://Adobe.com 和 http://Lynda.com 是两个巨大的
宝藏，上面有许许多多的入门教材可看。我非常反对看国内的 Photoshop 教程，毁了不知
道多少人。
* 教程
基础之后，还是要看怎么用，比如摄影后期：

后期推荐一：李涛，PS高手之路

地址：网易云课堂直接搜索


很经典的教程，不完全算后期，但可以当成学完工具之后的过渡。

后期推荐二：李涛，数码摄影后期高手之路

地址：高高手 - 艺·术 在线教育


这套教程是是收费的，但是内容很好，我也还在看，可以一起交流~

如果你和我一样喜欢李涛老师的课，但有不想花钱，高高手网站上有也有免费的课程：大众
数字摄影课堂，直接搜索就行。


后期推荐三：橄榄图摄影课堂

地址：橄榄图摄影课堂


橄榄图也是我很喜欢看的一个教程网站，里面有付费也有免费的内容，免费的通常是一些照片处理的小技巧，很有意思，可以看看。



橄榄图有一套教程十分推荐：循序渐进学摄影，如果你是刚开始学摄影，这个非常适合，而且免费。不仅讲了相机的基础知识，还有很多提高技巧、审美内容。


除了后期以外，PS也经常被用来合成海报、作图等。


—————————————————————————————————


平面推荐一：李文全Photoshop视频教程

地址：淘宝搜索


李文全是锤子科技的设计师，记得当时也是看了他的教程之后才知道了Matte Painting，慢慢练起了合成，不过需要花钱购买了。




平面推荐二：Jenny Le的教程

地址：How-To Tutorials & Free Online Courses by Envato Tuts+


Jenny是一位来自越南的大神，也是我很喜欢的一位国外设计师，作品充满想象、色调丰富，而且她还会定期更新教程在tusplus上，跟着做你也能合成大片。


基本上Jenny的每个教程我都会练习。



除了Photoshop之外，tutsplus上还有很多计算机相关的教程，比如：illustrator、HTML、CSS等，都是英文，但阅读难度并不大。


跟着教程，你也可以容易做出这些：







tutsplus不需要翻墙也能上。


平面推荐二：Home - Photoshop Tutorials

地址：Home - Photoshop Tutorials


photoshoptutorials也是国外一个专门的PS教程网站，无需翻墙。教程也是英文，但很详细，而且最后都会给出素材和源文件，可以看看大师们的PSD是什么样的。


比如这个：



平面推荐三：阿门教你PS

地址：微信公众号搜索


阿门的小号，每天都会推送PS的实例教程，都很棒看到喜欢的可以多练练。


这些都是我自己学习看过的教程，还算不错，推荐给大伙儿，希望有帮助。当然你也可以买PS相关的书籍来看，书籍偏概念，视频偏操作，各有优点。


—————————————————————————————————


然后是我自己一些常去的PS素材站点，希望有帮助。


1、优设网：优设-UISDC: 优秀网页设计联盟-SDC-网页设计师交流平台


优设网每个月都会有设计资源包，有时候相当不错，值得收藏。



2、站酷：站酷 (ZCOOL)


站酷也是常去的网站，看看国内大神们的作品，顺便下载素材。


3、昵图网：昵图网_原创素材共享平台www.nipic.com


昵图网也可以下载很多PS素材，样式、样机等，不过需要共享分，可以淘宝购买。平时最新的电影海报都能下载到PSD。



4、千图网：千图网_专注免费设计素材下载的网站


千图网上素材质量也不错，不过不是VIP会限制下载。



千图网还有专门的样机板块。




5、图鱼网：图鱼 - 好用的网页PS设计底纹背景图片纹理素材网站


图鱼网类似国外的subtlepatterns，也是非常不错的纹理背景网站，ppt和PS都可以用。



6、笔刷网站：Free Photoshop Brushes at Brusheezy!


brusheezy是国外一个笔刷素材下载网站，不需要翻墙，资源很丰富，雪花、雷电、雨水这些笔刷资源很多。




7、图片素材：Textures for 3D, graphic design and Photoshop!


texture也是一个图片和纹理下载网站，火焰PNG、枫叶这些素材很多，很方便。



8、SDC设计师网址导航：SDC设计师网址导航


优设网整理的素材导航网站，有时候其他网站没找到合适的素材，可以来这里翻翻。
* ps教程
** 图像
*** 数字图像 
**** 位图（像素) 墨水点，颜色点, 分辨率的概念
     像素 长×宽 个点 360*480
     分辨率 PPI 像素/英寸的值
     屏幕 72PPI 喷墨打印 150PPI 印刷 300PPI
**** 矢量图
*** 纸张图像
** 保存文件格式
*** 信息多 
    pds
*** 没图层信息
    jpg , gif , png, bmp
** 图像，画布操作(方形) 
   改变大小
   旋转图像
   裁剪
** 选区 调整色彩区域
   基本几何规格形状(方形，圆形)
   色彩差异法 魔棒
   快速蒙板 
   细化选区 调整边缘
   钢笔工具
   通道选择
   
   选区运算  
   羽化选区(图像有过渡边缘)

   
   
