* ranger
  ?  查看帮助
** 浏览:
   H   后退
   L   前进
   gg  跳到顶端
   G   跳到底端
   gh  go home
   gn  新建标签
   f   查找
   /   搜素
   g   快速进入目录
** 编辑
   space   选择
   uv      取消选择
   yy      复制
   dd      剪切
   pp      粘贴
   delete  删除
   cw      重命名
   A       在当前名称基础上重命名
   I       类似 A, 但是光标会跳到起始位置
   Ctrl-f  向下翻页
   Ctrl-b  向上翻页
** 书签
   m       新建书签
   `       打开书签
   um      删除书签
   
** 标签
   gn / C-n        新建标签
   TAB / S-TAB     切换标签
   A-Right, A-Left 切换标签
   gc / C-w        关闭标签
** 排序
   on/ob   根据文件名进行排序(natural/basename)
   oc      根据改变时间进行排序 (Change Time 文件的权限组别和文件自身数据被修改的时间)
   os      根据文件大小进行排序(Size)
   ot      根据后缀名进行排序 (Type)

   oa      根据访问时间进行排序 (Access Time 访问文件自身数据的时间)
   om      根据修改进行排序 (Modify time 文件自身内容被修改的时间)
** 其他
   zh      显示隐藏文件
   zp      打开/关闭文件预览功能
   zP      打开目录预览功能
** 链接(Link)
   pl      粘贴绝对路径的链接
   pL      粘贴相对路径的链接
   phl     硬链接
** 批量改名
   批量选择文件后, 键入命令:bulkname, 会打开编辑器, 其中的文件名编辑后保存退出, 再
   次打开操作确认编辑, 然后就批量改名了, 如果想取消批量改名, 在确认时把文件内容删除
   即可.
** 任务管理
   在执行某些操作(比如复制一个大文件)时不能立即完成, 这在 ranger 中就是一个任务. 你
   可以停止, 启动某个任务, 也可以对某个任务设置优先级.

   w: 打开/关闭任务视图. 在 w 打开的任务视图中:
   dd: 终止一个任务
   J: 降低当前任务的优先级
   K: 提升当前任务的优先级
** 其他
   zf      过滤器(如过滤 pdf 文件, zf+pdf,回车)
   S       在当前目录打开终端
   z(*)    改变设置, *表示在弹出选项中的选择
   o(*)    改变排序方式
   ! / s   使用 shell 命令(！shell -w ls -hl %s,%s 代表当前被选中的文件)
   :       使用 ranger 命令(3? 查看可用命令)
   :set colorscheme snow 设置颜色模式
** 快速预览
   安装以下程序可以实现快速预览:
   elinks, html
   highlight,text/code
   img2txt,image
   atool,压缩包
   pdf2text,pdf
   medinfo,audio/video
* vim
  - % 跳转到相配对的括号
  - gD 跳转到局部变量的定义处
  - '' 跳转到光标上次停靠的地方, 是两个', 而不是一个"
  - mx 设置书签,x 只能是 a-z 的 26 个字母
  - `x 跳转到书签处("`"是 1 左边的键)
  - > 增加缩进,"x>"表示增加以下 x 行的缩进
  - < 减少缩进,"x<"表示减少以下 x 行的缩进
  - { 跳到上一段的开头
  - } 跳到下一段的的开头
  - ( 移到这个句子的开头
  - ) 移到下一个句子的开头
  - [[跳转至上一个函数(要求代码块中'{'必须单独占一行)
  - ]] 跳转至下一个函数(要求代码块中'{'必须单独占一行)
  - C-] 跳转至函数或变量定义处
  - C-O 返回跳转前位置 
  - C-T 同上 
  - nC-T 返回跳转 n 次
  - 0 数字 0,跳转至行首 
  - ^ 跳转至行第一个非空字符 
* chrome 
** vimium 
   
   - o 打开书签或 URL
   - b 打开书签
   - << TAB 左移
   - ALT + f  多 URL 打开
   - X：恢复刚刚关闭的页面
   - gs：查看页面源代码。
   - yy：拷贝当前页面的 URL 到剪贴板。
   - yf：拷贝某一个 URL 到剪贴板
   - 

* tmux
- Control + a before any command
- Control + a then ? to bring up list of keyboard shortcuts
- Control + a then " to split window
- Control + a then <Space> to change pane arrangement
- Control + a then o to rotate panes
- Control + a then h, j, k, l to move left, down, up, right. Respectively. (vim hjkl)
- Control + a then ; to go to last panel
- Control + a then c to create a new window
- Control + a then n to next window
- Control + a then p to previous window
- Control + a then [0-9] move to window number
- Control + a then & to kill window
- Custom:
- Control + a then m to switch to main-horizontal layout with the main window at 2/3 height..
- Control + a then M to switch to main-vertical layout with the main window at half width.

  
bind-key    -T prefix       C-a               last-window                              
bind-key    -T prefix       C-b               send-prefix                              
bind-key    -T prefix       C-o               rotate-window                            
bind-key    -T prefix       C-z               suspend-client                           
bind-key    -T prefix       Space             next-layout                              
bind-key    -T prefix       !                 break-pane                               
bind-key    -T prefix       "                 split-window -v -c "#{pane_current_path}"
bind-key    -T prefix       #                 list-buffers                             
bind-key    -T prefix       $                 command-prompt -I "#S" "rename-session '% %'"
bind-key    -T prefix       %                 split-window -h -c "#{pane_current_path}"
bind-key    -T prefix       &                 confirm-before -p "kill-window #W? (y/n)" kill-window
bind-key    -T prefix       '                 command-prompt -p index "select-window -t ':%%'"
bind-key    -T prefix       (                 switch-client -p
bind-key    -T prefix       )                 switch-client -n
bind-key    -T prefix       ,                 command-prompt -I "#W" "rename-window '%% '"
bind-key    -T prefix       -                 delete-buffer
bind-key    -T prefix       .                 command-prompt "move-window -t '%%'"
bind-key    -T prefix       0                 select-window -t :=0
bind-key    -T prefix       1                 select-window -t :=1
bind-key    -T prefix       2                 select-window -t :=2
bind-key    -T prefix       3                 select-window -t :=3
bind-key    -T prefix       4                 select-window -t :=4
bind-key    -T prefix       5                 select-window -t :=5
bind-key    -T prefix       6                 select-window -t :=6
bind-key    -T prefix       7                 select-window -t :=7
bind-key    -T prefix       8                 select-window -t :=8
bind-key    -T prefix       9                 select-window -t :=9
bind-key    -T prefix       :                 command-prompt
bind-key    -T prefix       ;                 last-pane
bind-key    -T prefix       =                 choose-buffer
bind-key    -T prefix       ?                 list-keys
bind-key    -T prefix       C                 command-prompt -p "Name of new window: " "new-window -n '%%'"
bind-key    -T prefix       D                 choose-client
bind-key    -T prefix       L                 switch-client -l
* visual studio code 
** General
   Ctrl+Shift+P, F1 Show Command Palette
   Ctrl+P Quick Open, Go to File...
   Ctrl+Shift+N New window/instance
   Ctrl+W Close window/instance
   Ctrl+, User Settings
   Ctrl+K Ctrl+S Keyboard Shortcuts
** Basic editing
   Ctrl+X Cut line (empty selection)
   Ctrl+C Copy line (empty selection)
   Alt+ ↓ / ↑ Move line down/up
   Ctrl+Shift+K Delete line
   Ctrl+Enter /
   Ctrl+Shift+Enter
** Insert line below/ above
   Ctrl+Shift+\ Jump to matching bracket
   Ctrl+] / Ctrl+[ Indent/Outdent line
   Home / End Go to beginning/end of line
   Ctrl+ Home / End Go to beginning/end of file
   Ctrl+ ↑ / ↓ Scroll line up/down
   Alt+ PgUp / PgDn Scroll page up/down
   Ctrl+Shift+ [ / ] Fold/unfold region
   Ctrl+K Ctrl+ [ / ] Fold/unfold all subregions
   Ctrl+K Ctrl+0 /
   Ctrl+K Ctrl+J
** Fold/Unfold all regions
   Ctrl+K Ctrl+C Add line comment
   Ctrl+K Ctrl+U Remove line comment
   Ctrl+/ Toggle line comment
   Ctrl+Shift+A Toggle block comment
   Alt+Z Toggle word wrap
** Rich languages editing
   Ctrl+Space Trigger suggestion
   Ctrl+Shift+Space Trigger parameter hints
   Ctrl+Shift+I Format document
   Ctrl+K Ctrl+F Format selection
   F12 Go to Definition
   Ctrl+Shift+F10 Peek Definition
   Ctrl+K F12 Open Definition to the side
   Ctrl+. Quick Fix
   Shift+F12 Show References
   F2 Rename Symbol
   Ctrl+K Ctrl+X Trim trailing whitespace
   Ctrl+K M Change file language
   Multi-cursor and selection
   Alt+Click Insert cursor*
   Shift+Alt+ ↑ / ↓ Insert cursor above/below
   Ctrl+U Undo last cursor operation
   Shift+Alt+I Insert cursor at end of each line selected
   Ctrl+L Select current line
   Ctrl+Shift+L Select all occurrences of current selection
   Ctrl+F2 Select all occurrences of current word
   Shift+Alt + → Expand selection
   Shift+Alt + ← Shrink selection
   Shift+Alt + drag mouse Column (box) selection
** Display
   F11 Toggle full screen
   Shift+Alt+0 Toggle editor layout (horizontal/vertical)
   Ctrl+ = / - Zoom in/out
   Ctrl+B Toggle Sidebar visibility
   Ctrl+Shift+E Show Explorer / Toggle focus
   Ctrl+Shift+F Show Search
   Ctrl+Shift+G Show Source Control
   Ctrl+Shift+D Show Debug
   Ctrl+Shift+X Show Extensions
   Ctrl+Shift+H Replace in files
   Ctrl+Shift+J Toggle Search details
   Ctrl+Shift+C Open new command prompt/terminal
   Ctrl+K Ctrl+H Show Output panel
   Ctrl+Shift+V Open Markdown preview
   Ctrl+K V Open Markdown preview to the side
   Ctrl+K Z Zen Mode (Esc Esc to exit)
** Search and replace
   Ctrl+F Find
   Ctrl+H Replace
   F3 / Shift+F3 Find next/previous
   Alt+Enter Select all occurrences of Find match
   Ctrl+D Add selection to next Find match
   Ctrl+K Ctrl+D Move last selection to next Find match
** Navigation
   Ctrl+T Show all Symbols
   Ctrl+G Go to Line...
   Ctrl+P Go to File...
   Ctrl+Shift+O Go to Symbol...
   Ctrl+Shift+M Show Problems panel
   F8 Go to next error or warning
   Shift+F8 Go to previous error or warning
   Ctrl+Shift+Tab Navigate editor group history
   Ctrl+Alt+- Go back
   Ctrl+Shift+- Go forward
   Ctrl+M Toggle Tab moves focus
** Editor management
   Ctrl+W Close editor
   Ctrl+K F Close folder
   Ctrl+\ Split editor
   Ctrl+ 1 / 2 / 3 Focus into 1
   st, 2nd, 3rd editor group
   Ctrl+K Ctrl + ← Focus into previous editor group
   Ctrl+K Ctrl + → Focus into next editor group
   Ctrl+Shift+PgUp Move editor left
   Ctrl+Shift+PgDn Move editor right
   Ctrl+K ← Move active editor group left/up
   Ctrl+K → Move active editor group right/down
** File management
   Ctrl+N New File
   Ctrl+O Open File...
   Ctrl+S Save
   Ctrl+Shift+S Save As...
   Ctrl+W Close
   Ctrl+K Ctrl+W Close All
   Ctrl+Shift+T Reopen closed editor
   Ctrl+K Enter Keep preview mode editor open
   Ctrl+Tab Open next
   Ctrl+Shift+Tab Open previous
   Ctrl+K P Copy path of active file
   Ctrl+K R Reveal active file in Explorer
   Ctrl+K O Show active file in new window/instance
** Debug
   F9 Toggle breakpoint
   F5 Start / Continue
   F11 / Shift+F11 Step into/out
   F10 Step over
   Shift+F5 Stop
   Ctrl+K Ctrl+I Show hover
** Integrated terminal
 Ctrl+` Show integrated terminal
 Ctrl+Shift+` Create new terminal
 Ctrl+Shift+C Copy selection
 Ctrl+Shift+V Paste into active terminal
 Ctrl+Shift+ ↑ / ↓ Scroll up/down
 Shift+ PgUp / PgDn Scroll page up/down
 Shift+ Home / End Scroll to top/bottom 
