#+TITLE: 编程语言小问题
#+DESCRIPTION: 编程语言简介
#+TAGS[]: 编程语言
#+CATEGORIES[]: 技术
#+DATE: 2019-12-07T19:41:03+08:00

什么是自然语言？

就是沟通的双方都能理解的一种符号或语音或视频，用来表达想法或现象的。
#+begin_quote
就是给沟通对象传达自己意图的某种行为，比如，盲人的比比划划，对外国人的指指画画等动作
#+end_quote

什么是编程语言？

就是给计算机看的，用在计算机上的一种符号，指导计算机行为的东西
#+begin_quote
计算机还没有人那么智能，以后发展的话，计算机也能通过其它介质来传递想法(如语音描述什么的)
#+end_quote

#+begin_quote
因为计算机现在还不太智能，解析语言的解析器只能理解文本，所以，编程语言必须是某种 *规则化* 的文本
#+end_quote
# more 
** 语言分类
   为什么还要给编程语言分类呢？ 什么 A 语言，B语言，C语言 ...

   因为能够理解某种语言的是某种语言对应的解析器，每种解析器能够理解的语法规格的数量都不同，所以给语言为低级语言和高级语言。
  
   #+begin_quote
   就像我们一个小学 1 年级的学生和大学 1 年级的学生，学习的汉语语法结构不一样多，词汇量也不一样多，所以用某种表达对低年级学生来说不理解。所以编程语言是向着高级语言发展的。
   #+end_quote

   根据用途不同，也会选择相应的编程语言，比如追求效率的，一般选用比较低级的语言，能对机器更直接的操作。
** 语法规范
  所有语言，都有一套基本的语法规范，比如怎么定义名词(描述某样东西)，动词和名词的位置，转折句放在哪里等等，编程语言也差不多，但非常简洁。 
*** 数据和数据结构
    解析器有专门的东西去分析文本里面的数据(名词)，并为他分类(数组，列表，文件。。)。
    
    比如，我很喜欢唱歌，跳舞，吃饭。那 "唱歌，跳舞，吃饭" 就会被划分成一个数组。
*** 指令及流程控制
    流程，在语言中用来表示转折，条件限制什么的。
    
    比如，我很不喜欢唱歌，"不" 就表示转折。还有，我到 18 岁才喜欢唱歌，就是要满足条件"18"岁。
*** 语法糖
    编程语言中还有许多语法糖，用来增强语言的表达能力。

    但总的来说，编程语言没有自然语言好理解，因为有好多计算的部分，可以给自己一个心理暗示：计算机，你要跟我说什么？在读一些代码的时候。
