#+TITLE: 人生意义
#+TAGS[]:  人生
#+CATEGORIES[]: 生活
#+DATE: 2019-11-22T06:55:56+08:00
#+PUBLISHDATE: 2019-11-22T06:55:56+08:00
#+DRAFT: nil
#+WEIGHT: 1

关于人生的意义，一百个人有一百个人的想法。这里仅说自己的狭隘理解。
# more

* 什么是人 
  人是一个智能体，就是能智能的改变外部世界的动物。
 
** 人的结构
   人的形状就像中文汉字“大”差不多的形状

** 人体运转方向
根据各器官的功能，大略分为感知部件，分析部件，处理部件，这三个部件实行一个闭环，人生就在这三个部件之间运转。
   
#+begin_quote
提供运转的动力系统是人的新陈代谢系统（呼吸系统和心脏系统和排泄系统等）
#+end_quote

有时候，我们可能不大使用分析部件，凭直觉做事，那是因为形成了一种肌肉记忆，或者说习惯,那么可以说人生也可能在这两个部件中运转，这是另一种情况。  

有时人还什么都不做呢，就趴在床上看视频

还有时什么都不做，在情绪中，发呆中，在睡眠中

人生的几种运行状态：
1. 感知世界 - 分析世界 - 改造世界
2. 感知世界 - 改造世界
3. 感知世界
4. 情绪，休息，睡眠 

** 大脑 (分析系统，情绪，记忆的主体)
  我们用大脑，用神经系统来处理信息，处理的信息带有主观性，是避免不了的，只能尽可能完备。
   
*** 思维
    - 思维是我们对感受到的东西进行 *行为加工* 的现象
    - 要想加工好，需要专注东西
    - 反复加工
    - 进行测试
 
      思维方法 
    - 沉浸式思维
*** 情绪(喜怒哀乐)
    情绪是我们对东西的感受，与人对东西的往期经历有关，对未知的东西，我们会像灵长类动物一样产生好奇，然后打开潘多拉魔盒。
    
    #+begin_quote
    这里的潘多拉仅仅指人有好奇心
    #+end_quote
   
*** 想象
    想象是对不同的东西进行行为加工
** 补充能量
*** 吃 
*** 运动
    人在固定的动作后(睡眠，长时间某种动作)，会疲劳，就要改变某种状态。
*** 休息
    人在改变世界，或长时间某种动作后，会疲劳，就要休息    

* 人生意义
每个人想法不一样，我的想法是对自己满意，比昨天有进步，就是幸福。要做到比昨天进步，就要给自己一点小压力，给自己设置几个完成的任务，稍微有点难度的，或自己没完成的。  

#+begin_quote
解决自己的生活中遇到的小难题，就是人生的意义，就是幸福的人生
#+end_quote

完成以后给自己以自信的微笑，我今天活的是有意义的。

下面是人基本的任务
** 寿命
   人命很短，人很脆弱，所以人活着只能做自己想到的很少一部分的事情，要做就抓紧了。
     
** 关系
   对人最重要的关系是  
   - 父母   
   - 妻女   
   - 朋友
** 事业   
   - 人生规划
** 健康
   - 既然小肚子变大了，为什么不做仰卧起坐
   - 既然坐姿不好，含胸驼背，为什么不昂首挺胸
   - 既然眼睛不好，为什么不少看手机
** 知识
   - 知识的整理比知识的阅览更重要
   - 泛泛浏览信息有害

     
