* 代理
  google-chrome --proxy-server="socks5://localhost:7077"
  HTTP(S)代理服务器：127.0.0.1:42428
  SOCKS 代理服务器：127.0.0.1:40695

* 调试页面
** 移动端缩放 ( shift+鼠标左键上下移动进行放大缩小 )
** ceshi 
   当选择响应（Responsive）作为设备类型时，可以更改仿真屏幕的尺寸
触摸启用仿真
将鼠标移到设备上可查看圆形“触摸”光标。这将对基于触摸的 JavaScript 事件（如 touchstart，touchmove 和 touchend）做出反应。鼠标特定的事件和 CSS 效果不会做出反应。

按住 Shift 键，然后单击并移动鼠标以模拟双指缩放操作。

移动仿真器设备工具栏
值得花一点时间来让自己熟悉移动仿真器上方的工具栏和菜单：
默认设置有：

设备类型（或简称响应（Responsive））
当前分辨率
缩放（屏幕可以放大或缩小以更好得适合仿真器面板）
竖屏/横屏切换按钮（假设选择了响应（Responsive）之外的设备）
三点菜单允许你显示或隐藏其他设置：

设备边框（如果可用，手机或平板电脑的外观图形）
媒体查询
像素标尺
设备像素比（例如 2.0 用于仿真的视网膜屏幕）
设备类型（类别如“mobile”或“tablet”）
网络限制（一种在较慢的连接上限制带宽和测试性能的方法）
捕获包括设备边框（如果显示）的屏幕截图。
最后一个选项允许你重置以上这些设置到默认状态。
移动手机仿真器设备工具栏选项

CSS 媒体查询工具栏

工具栏下方的栏显示一系列典型的手机，平板电脑和设备尺寸。当选择响应（Responsive）
作为设备的宽度设置时，可以单击此选项。

从三点菜单中选择显示媒体查询（Show media queries），以查看在 CSS 中设置的所有媒
体查询的图形颜色编码表示。

Chrome 移动设备仿真器媒体查询

蓝色——以最大宽度的查询
绿色——以一个范围内宽度的查询
橘色——以最小宽度为目标的查询
可以单击任何颜色的条形栏以将仿真器屏幕设置为该宽度。
** 带宽限制模拟
限制（Throttling）下拉菜单允许你模拟移动连接或不可靠的酒店和机场 WiFi 经常遇到的
慢网络速度！你可以使用它来确保你的网站或应用程序快速加载，并在所有环境中保持响应。

网络（Network）标签和 Chrome 的设备工具栏（启用时）可以使用限制下拉菜单。你可以
通过选择限制下拉菜单底部的编辑（Edit…）或从开发者工具菜单（F1）中选择设置
（Settings）并选择限制（Throttling）选项卡来设置自己的带宽配置：

Chrome 移动设备仿真器带宽

单击添加自定义配置文件（Add custom profile），然后输入：

配置文件名称
下载速度（千比特每秒）
上传速度（千比特每秒）
以毫秒为单位的延迟（在进行网络请求时的典型延迟）
仿真移动传感器
智能手机和平板电脑通常具有传感器，例如在台式设备中不存在的 GPS，陀螺仪和加速度计。这些可以在 Chrome 中通过选择更多工具（More tools），然后从开发工具主三点菜单中选择传感器（Sensors）：

Chrome 移动设备仿真器带宽

将出现一个新面板，你可以定义：

当前的纬度和经度，或从下拉列表中选择一个主要城市。你也可以选择禁用位置，用来模拟当设备无法获取 GPS 信号时应用程序的反应。
方向。有几个可用的预设方向，或者可以通过单击和拖动来移动设备图像来改变方向。
远程真实设备调试
最后，Chrome 允许你通过 USB 连接真实的 Android 设备进行远程设备调试。从开发者工具主三点菜单中选择更多工具（More tools），然后选择远程设备（Remote devices）。确保勾选 Discover USB debices，然后连接手机或平板电脑，并按照说明进行操作。

Chrome 允许你设置端口转发，以便导航到设备上本地服务器上的网址。 Chrome 的预览面
板显示设备屏幕的同步视图，你可以使用设备或 Chrome 本身进行交互。

全方位的开发者工具包括应用程序（Application）选项卡，可用于在离线模式下测试
Progressive Web Apps。请注意，不同于需要 HTTPS 的真实应用程序，Chrome 允许 PWA
通过 HTTP 连接从本地主机运行。

* 浏览器 [ html 展示成元素文档树,css 中查找元素的样式(现在是从右往左找选择子) ]
** 高效匹配样式 [ 从右往左的特点]
   例子 ：
   #+begin_src css
     #home a {color: blue;}

     .home-anchor {color: blue;}
   #+end_src
用下面的，不用上面的
* chrome 插件
** Vimium 
*** Navigating the page	
    j, <c-e>		Scroll down	
    k, <c-y> Scroll up	
    gg		Scroll to the top of the page	
    G		Scroll to the bottom of the page	
    d		Scroll a half page down	
    u		Scroll a half page up	
    h		Scroll left	
    l		Scroll right	
    zH		Scroll all the way to the left	
    zL		Scroll all the way to the right	
    r		Reload the page	
    yy		Copy the current URL to the clipboard	
    p		Open the clipboard's URL in the current tab	
    P		Open the clipboard's URL in a new tab	
    gu		Go up the URL hierarchy	
    gU		Go to root of current URL hierarchy	
    i		Enter insert mode	
    v		Enter visual mode	
    V		Enter visual line mode	
    gi		Focus the first text input on the page	
    f		Open a link in the current tab
	  F		Open a link in a new tab	
    <a-f>		Open multiple links in a new tab	
    yf		Copy a link URL to the clipboard
    [[		Follow the link labeled previous or <	
    ]]		Follow the link labeled next or >	
    gf		Select the next frame on the page	
    gF		Select the page's main/top frame	
    m		Create a new mark	
    `		Go to a mark		
*** Using the vomnibar	
    o		Open URL, bookmark or history entry	
    O		Open URL, bookmark or history entry in a new tab	
    b		Open a bookmark	
    B		Open a bookmark in a new tab	
    T		Search through your open tabs	
    ge		Edit the current URL	
    gE		Edit the current URL and open in a new tab			
*** Using find	
    /		Enter find mode	
    n		Cycle forward to the next find match	
    N		Cycle backward to the previous find match			
*** Navigating history	
    H		Go back in history	
    L		Go forward in history			
*** Manipulating tabs	
    t		Create new tab	
    J, gT		Go one tab left	
    K, gt		Go one tab right	
    ^		Go to previously-visited tab	
    g0		Go to the first tab	
    g$		Go to the last tab	
    yt		Duplicate current tab	
    <a-p>		Pin or unpin current tab	
    <a-m>		Mute or unmute current tab	
    x		Close current tab	
    X		Restore closed tab	
    W		Move tab to new window	
    <<		Move tab to the left	
    >>		Move tab to the right			
*** Miscellaneous(多方面）	
    ?		Show help	
    gs		View page source

** 眼睛护航
   切换颜色模式开关，用 ~C-q~
   还要勾选下是否禁用
