* gimp
帮助 F1 帮助
Shift F1 上下文帮助

工具箱
工具
R 矩形选择
E 椭圆形选择
F 自由选择
Z 模糊选取
Shift O 按颜色选取
I 剪刀 
B 路径
O 颜色拾取器
M 移动
Shift C Crop and Resize
Shift R 旋转
Shift T 缩放
Shift S 剪切
Shift P 透视
Shift F 翻转
T 文本
Shift B Bucket Fill
L 混合
N 铅笔
P 刷子
Shift E 橡皮
A 喷枪
K 墨水
C 克隆
Shift U 模糊/锐化
S 污点
Shift D 减淡/加深

双击工具按钮打开工具选项对话框。
内容
X 交换颜色
D 默认颜色

点击改变至该种颜色
文件
Ctrl N 新图像
Ctrl O 打开图像
Ctrl Alt O 作为新图层打开图像
Ctrl D 复制图像
Ctrl 1 打开最近图像 01
Ctrl 2 打开最近图像 02
Ctrl 3 打开最近图像 03
Ctrl 4 打开最近图像 04
Ctrl 5 打开最近图像 05
Ctrl 6 打开最近图像 06
Ctrl 7 打开最近图像 07
Ctrl 8 打开最近图像 08
Ctrl 9 打开最近图像 09
Ctrl 0 打开最近图像 10
Ctrl S 保存图像
Shift Ctrl S 另存为
Ctrl E Export to
Shift Ctrl E Export ...
Ctrl Q 退出

对话

Ctrl L 图层
Shift Ctrl B 刷子
Shift Ctrl P 仿照
Ctrl G 渐变
Shift Ctrl T 工具选项
Ctrl P 调色板
Shift Ctrl I 信息窗口
Shift Ctrl N 浏览窗口
如果相应对话框未打开则会将其打开,否则相应对话框将获得输入焦点。

编辑
撤销/ 重做 
Ctrl Z 撤销 
Ctrl Y 重做

剪贴板
Ctrl C 复制选择部分
这将使一个副本被复制到 GIMP 剪贴板。
Ctrl X 剪切选中部分
 Ctrl K 清除选择
Shift Ctrl C Named copy selection
Shift Ctrl X Named cut selection
Shift Ctrl V Named paste clipboard

填充
Ctrl D 用前景色填充
Ctrl D 用背景色填充
Ctrl D Fill with Pattern

图层
PgUp , Ctrl Tab 选中上一层
PgDn Shift , Ctrl Tab 选中下一层
Home 选中第一层
End 选中最后一层
Ctrl M 合并可见图层
Ctrl H Anchor layer
* ranger
?  查看帮助
** 浏览:
   H   后退
   L   前进
   gg  跳到顶端
   G   跳到底端
   gh  go home
   gn  新建标签
   f   查找
   /   搜素
   g   快速进入目录
** 编辑
   space   选择
   uv      取消选择
   yy      复制
   dd      剪切
   pp      粘贴
   delete  删除
   cw      重命名
   A       在当前名称基础上重命名
   I       类似 A, 但是光标会跳到起始位置
   Ctrl-f  向下翻页
   Ctrl-b  向上翻页
** 书签
   m       新建书签
   `       打开书签
   um      删除书签
   
** 标签
   gn / C-n        新建标签
   TAB / S-TAB     切换标签
   A-Right, A-Left 切换标签
   gc / C-w        关闭标签
** 排序
   on/ob   根据文件名进行排序(natural/basename)
   oc      根据改变时间进行排序 (Change Time 文件的权限组别和文件自身数据被修改的时间)
   os      根据文件大小进行排序(Size)
   ot      根据后缀名进行排序 (Type)

   oa      根据访问时间进行排序 (Access Time 访问文件自身数据的时间)
   om      根据修改进行排序 (Modify time 文件自身内容被修改的时间)
** 其他
   zh      显示隐藏文件
   zp      打开/关闭文件预览功能
   zP      打开目录预览功能
** 链接(Link)
   pl      粘贴绝对路径的链接
   pL      粘贴相对路径的链接
   phl     硬链接
** 批量改名
   批量选择文件后, 键入命令:bulkname, 会打开编辑器, 其中的文件名编辑后保存退出, 再
   次打开操作确认编辑, 然后就批量改名了, 如果想取消批量改名, 在确认时把文件内容删除
   即可.
** 任务管理
   在执行某些操作(比如复制一个大文件)时不能立即完成, 这在 ranger 中就是一个任务. 你
   可以停止, 启动某个任务, 也可以对某个任务设置优先级.

   w: 打开/关闭任务视图. 在 w 打开的任务视图中:
   dd: 终止一个任务
   J: 降低当前任务的优先级
   K: 提升当前任务的优先级
** 其他
   zf      过滤器(如过滤 pdf 文件, zf+pdf,回车)
   S       在当前目录打开终端
   z(*)    改变设置, *表示在弹出选项中的选择
   o(*)    改变排序方式
   ! / s   使用 shell 命令(！shell -w ls -hl %s,%s 代表当前被选中的文件)
   :       使用 ranger 命令(3? 查看可用命令)
:set colorscheme snow 设置颜色模式
** 快速预览
安装一下程序可以实现快速预览:
elinks, html
highlight,text/code
img2txt,image
atool,压缩包
pdf2text,pdf
medinfo,audio/video
* vim
  % 跳转到相配对的括号
  gD 跳转到局部变量的定义处
  '' 跳转到光标上次停靠的地方, 是两个', 而不是一个"
  mx 设置书签,x 只能是 a-z 的 26 个字母
  `x 跳转到书签处("`"是 1 左边的键)
  > 增加缩进,"x>"表示增加以下 x 行的缩进
  < 减少缩进,"x<"表示减少以下 x 行的缩进
  { 跳到上一段的开头
  } 跳到下一段的的开头
  ( 移到这个句子的开头
  ) 移到下一个句子的开头
[[ 跳转至上一个函数(要求代码块中'{'必须单独占一行)
  ]] 跳转至下一个函数(要求代码块中'{'必须单独占一行)
  C-] 跳转至函数或变量定义处
  C-O 返回跳转前位置 
  C-T 同上 
  nC-T 返回跳转 n 次
  0 数字 0,跳转至行首 
  ^ 跳转至行第一个非空字符 
