bootstrap 建立了一个响应式的12列格网布局系统，它引入了fixed(固定) and fluid-with(浮动)的两种布局方式. 
我们从全局样式(global style),格网系统（grid system），流式格网（fluid grid system）,自定义（customing）,
布局（layouts）,响应式设计（responsive design ）这 六个方面讲解 scaffolding
* global style
bootstrip 要求 html5 的文件类型，so <!DOCTYPE html>
同时，它通过bootstrap.less 文件来设置 全局排版和链接显示风格，其中去掉了 body的margin,使用
@baseFontFamily,@baseFontSize,@linkColor 等变量来控制基本排版
* 栅格系统（grid system）
默认的bootstrap格网系统提供了一个宽达940像素的12列的格网。这意味着你页面的默认宽度是940px
最小的单元要素宽度是940/12px.
bootstrap 内置了一套响应式、移动设备优先的流式栅格系统。随着屏幕设备或视口（viewport）尺寸的增加，系统会自动分为最多12列
就是通过一系列的行（row）与列（column）的组合创建页面布局，然后你的内容就可以放入到你创建好的布局当中。
行（row）必须包含在.container中，以便为其赋予合适的排列(alignment)和内补(padding).
使用行（row）在水平方向创建一组列(column).
你的内容应当放置于列（column）内，而且,只有列（column)可以作为行（row）的直接子元素。
类似Predefined grid classes like .row and .col-xs-4 这些预订义的栅格class可以用来快速创建 栅格布局。
bootstrap 源码中定义的mixin也可以用来创建语义化的布局。
通过设置padding 从而创建列(column)之间的间隔（gutter)。然后通过为第一和最后一列设置负值的margin从而抵消掉padding的影响。
栅格系统中的列是通过指定1到12的值来表示其跨越的范围。例如，三个等宽的列可以使用三个.col-xs-4来创建。
sm md lg xl 和默认
offset push pull 设定偏移
** 栅格选项
|           | 手机（<768px) | 平板(>768px) | 桌面（>992px) |          |
| class前缀 | .col-xs-      | .col-sm-     | .col-md-      | .col-lg- |
| 列数      | 12            |              |               |          |
* 流式系统 (fluid grid system)
* 自定义(customing)
* 布局(layouts)
* 响应式设计(responsive design)
abc璇
abc璇
abc璇

璇
璇
璇
璇
jjjk璇
璇
璇
璇
璇
abc璇
abc璇
abc璇
abc璇
璇
* bootstrap css
** 移动设备优先
适应设备<meta name="viewport" content="width=device-width,initial-scale=1.0">
禁用缩放 user-scalable=no  maximum-scale=1.0




