* 快捷键
智能提示：ctrl + J
方法参数提示：ctrl + shift +空格
智能标记（如：提示using、实现接口、抽象类等）：ctrl + .

执行测试：ctrl + R,T(当前上下文)，ctrl + R,A（所有）,ctrl + R,Y（所有受影响）
重新生成：ctrl+shift+B
执行化全文：ctrl+K,D
循环粘贴：ctrl+shift+V
快速切换到上一页/下一页：ctrl+F6/ctrl+shift+F6
#region快捷键：选中要注释的内容，按ctrl+K,S，选择#region

 

1.快速using（这个的快捷键是ctrl+.）



2.快速回到之前编辑的代码页面
现在的项目动不动就几十个代码页面，经常需要在几个页面之间跳来跳去，这时就需要这两个快捷键：
CTRL + - 向后定位，回到上一个编辑的光标点
CTRL + TAB 回到上一个文档窗口，CTRL按住不放再按TAB可以选择要切换的文档窗口。这个功能和WINDOWS的ALT+TAB类似

3.转到定义、查找引用
比如上边的例子，想知道变量arrayList在哪定义的，就点击arrayList按F12光标就会跳至ArrayList arrayList = new ArrayList();
想知道有多少个地方使用这个变量arrayList就右击arrayList按A。
F12 转到定义 或者 右击[对象]按G
查找引用 右击按A

4.列出成员、查看参数说明（CTRL + J）（Ctrl+Shift+空格键）
当输入arrayList.之后就会弹出对应的成员列表：



如果你的鼠标点了别的页面再回来时发现这个成员列表已经消失了，这时你将光标移到arrayList.后面，按CTRL + J 就可以再显示成员列表。

查看参数说明，光标移到参数，按Ctrl+Shift+空格键 显示参数说明：



 
5.其它的常用快捷键：
VS的快捷键太多了，没那功夫记那么多快捷键，记几个常用的就够了

CTRL + SHIFT + B 生成解决方案
F4 显示属性窗口
F5 运行调试
F10 跨过程序执行
F11 单步逐句执行
F7: 查看代码
Shift+F7: 查看窗体设计器
Ctrl+F: 查找
F3: 查找下一个
Ctrl+H: 替换  

 

Shift+Alt+F10
Ctrl+K+M
Ctrl+E+D

Ctrl+F5: 开始执行(不调试)
F9: 切换断点
Ctrl+Shift+F9: 删除全部断点
Ctrl+Shift+F: 在文件中查找
Ctrl+K,S: 插入外侧代码

 

选中一行或多行代码进行注释：ctrl+E,C
选中一行或多行代码取消注释：ctrl+E,U

对代码进行格式缩进处理：ctrl+K,D

Ctrl+k,Ctrl+f 整理缩进格式

  
1，Visual Studio 2008自带的1000多个 Windows 系统使用的各种图标、光标和动画文件
在Visual Studio 2008的安装目录下，
\Microsoft Visual Studio 9.0\Common7\VS2008ImageLibrary\2052文件夹下面，有一个VS2008ImageLibrary.zip，这个文件里面将常用的Windows系统图标、光标和动画文件集中到了一起。包括Office、Win9x、WinVista和WinXP等系统使用的，可以免费使用哦。  

2，删除多余的using指令，并且排序
当我们新一个类的时候，Visual Studio 会将常用的命名空间using在类的头部。但是在我们写完一个类的时候，有些using是多余的，删除多余的using，再排一下序，可以使代码看起来更清晰。Visual Studio 2008 已经为我们做好了这一切。在代码编辑区点击右键，可以看到"组织 using"菜单，这就是我们需要的了。

3，复制或删除一行代码时，不用先选择它
如果你想复制一行代码，你只需要简单的按CTRL+c拷贝，然后按CTRL+v粘贴这行就可以了，而不需要选择整行的代码。如果你想删除一行代码，只需按CTRL+x就可以了。

4，取代其他编辑器里Ctrl+F的方便的增量查找
用过ultraedit会对那两个上下搜索按钮印象深刻，Visual studio里有更厉害的。
操作方法：  
1）.按Ctrl+I键；  
2）.键入你要搜索的文本。注意：这时你会看到光标跳至第一个匹配的地方，匹配的文本高亮显示；  
3）.再次按下Ctrl+I键，光标将跳至下一个匹配的文本；  
4）.按Ctrl+Shift+I可向后搜索；  
5）.要停止搜索，按ESC键；  

5，如何在编辑器中进行框式选择
操作方法：  
你是否知道VS提供了两种不同的选择模型：流式和框式吗？  
大家应该都熟悉流式选择模型了，只要使用Shift+方向键即可（或者使用鼠标进行选择）。  
框式选择则允许你同时对航和列进行选择。只要同时按下Shift+Alt+方向键，你就了解它的不同之处了。剪切，拷贝，粘贴，这些功能都能使用，只是需要记住从哪里开始选择的。啊，让我想起了那段做测试时的时光。  
备注：也可以使用鼠标+Alt键完成该操作。前两天我还遇到该提示的一个有意思的用法。有时候我们拷贝网上的文章中的代码时会将行号一起拷进来，使用框式选择可以只选择行号部分，将其删除。

6，如何使用快捷键在当前代码行的上面或下面插入一行（推荐，很实用）
按下Ctrl+Enter会在上面插入一个空行，Ctrl+Shift+Enter则会在下面插入一个空行。光标会移至新行的开始处。  
备注：这是我非常喜欢的一个快捷键，如果不用这个，则需要使用Home或End，然后使用方向键，再使用回车才能达到上面的效果。

7，安装之后，将您的IDE设置恢复到默认设置
如果IDE的设置在任何先前发布的版本中做了更改，它们都应该被恢复到默认设置。可以在Visual Studio 2008中点击菜单 Tools > Import and Export Settings... > Reset all settings，此外还有一些Import和Export的选项可用。

8，通过按"tab"两次插入代码块
操作步骤：
在编辑的中输入代码片段，比如"for"

在这个状态下，按两次"tab"键，将会插入代码块，如下图所示

此时你可以把第一"i"改成"j"，然后按Tab键，则所有的变量都变成了"j"。
备注：这样既快又不容易语法出错。

9，使用Ctrl+Tab打开IDE的导航，获得鸟瞰视图
同时在Visual Studio中导航到所有打开的文件和工具窗体
按"Ctrl+Tab"键，打开IDE导航窗口，按住Ctrl键，同时用方向键或鼠标选中一个文件或工具窗体来激活。

备注：这时最好不要松开"Ctrl+Tab"，按方向键看鸟瞰图，全部松开后就定位到需要的文件或工具窗体，说实在的，这窗口挺酷的。

10，查找匹配的标记
某些标识总是成对出现。例如，"{"标识必须用对应的"}"标识关闭。虽然你点击一个{ 和它匹配的}就会高亮显示，但是如果代码过长的话就不好找了，同样，编译器指示符"#region"必须有对应的"#endregion"指示符。当导航你的代码时，你有时需要查找对应的标识。通过按Ctrl-]你可以这样做。这个快捷键只有当光标在这些标识符的任何一个的下面时才起作用，它会立即跳转到对应的标识符而不管它是开的或闭的标识。
如果你想显亮两个匹配的标识之间的所有代码时，按Ctrl-Shift-]显亮整个块，并移动光标到开的标识处。这个快捷键只有当光标在任意的标识的下面时才起作用（如光标在区域内它就不会起作用了）
11.如果你想临时想禁用一段代码，你可以把这段代码注释掉，方法是：先选择这段代码，然后CTRL+k+c（按住CTRL键不放，然后，按一下k键，再按一下c键），见（图5）（图6）。使用CTRL+k+u可以取消注释
12 - 使用CTRL+n或CTRL+SHIFT+a创建新项
13 使用CTRL+空格进行自动完成

 

Shift+Alt+Enter: 切换全屏编辑

Ctrl+m+Crtr+o折叠所有大纲

Ctrl+M+Crtr+P: 停止大纲显示

Ctrl+K+Crtr+C: 注释选定内容

Ctrl+K+Crtr+U: 取消选定注释内容

Ctrl+J : 列出成员 智能感知

Ctrl+B,T / Ctrl+K,K: 切换书签开关

Ctrl+B,N / Ctrl+K,N: 移动到下一书签

Ctrl+B,P: 移动到上一书签

Ctrl+B,C: 清除全部标签
Ctrl+I: 渐进式搜索

Ctrl+Shift+I: 反向渐进式搜索

Ctrl+F: 查找

Ctrl+Shift+F: 在文件中查找

F3: 查找下一个

Shift+F3: 查找上一个

Ctrl+H: 替换

Ctrl+Shift+H: 在文件中替换

Alt+F12: 查找符号(列出所有查找结果)

Ctrl+Shift+V: 剪贴板循环

Ctrl+左右箭头键: 一次可以移动一个单词

Ctrl+上下箭头键: 滚动代码屏幕，但不移动光标位置。

Ctrl+Shift+L: 删除当前行

Ctrl+M,M: 隐藏或展开当前嵌套的折叠状态

Ctrl+M,L: 将所有过程设置为相同的隐藏或展开状态

Ctrl+E,S: 查看空白

Ctrl+E,W: 自动换行

Ctrl+G: 转到指定行

Shift+Alt+箭头键: 选择矩形文本

Alt+鼠标左按钮: 选择矩形文本

Ctrl+Shift+U: 全部变为大写

Ctrl+U: 全部变为小写代码快捷键

Ctrl+Shift+空格键 / Ctrl+K,P: 参数信息

Ctrl+K,I: 快速信息

Ctrl+E,U / Ctrl+K,U: 取消选定注释内容

Ctrl+K,M: 生成方法存根

Ctrl+K,X: 插入代码段

Ctrl+K,S: 插入外侧代码

F12: 转到所调用过程或变量的定义窗口快捷键

Ctrl+W,W: 浏览器窗口

Ctrl+W,S: 解决方案管理器

Ctrl+W,C: 类视图

Ctrl+W,E: 错误列表

Ctrl+W,O: 输出视图

trl+W,P: 属性窗口

Ctrl+W,T: 任务列表

Ctrl+W,X: 工具箱

Ctrl+W,B: 书签窗口

Ctrl+W,U: 文档大纲

Ctrl+D,B: 断点窗口

Ctrl+D,I: 即时窗口

Ctrl+Tab: 活动窗体切换

Ctrl+Shift+N: 新建项目

Ctrl+Shift+O: 打开项目

Ctrl+Shift+S: 全部保存

Shift+Alt+C: 新建类

Ctrl+Shift+A: 新建项

Shift+Alt+Enter: 切换全屏编辑

Ctrl+B,T / Ctrl+K,K: 切换书签开关

Ctrl+B,N / Ctrl+K,N: 移动到下一书签

Ctrl+B,P: 移动到上一书签

Ctrl+B,C: 清除全部标签

Ctrl+I: 渐进式搜索

Ctrl+Shift+I: 反向渐进式搜索

Ctrl+F: 查找

Ctrl+Shift+F: 在文件中查找

F3: 查找下一个

Shift+F3: 查找上一个

Ctrl+H: 替换

Ctrl+Shift+H: 在文件中替换

Alt+F12: 查找符号(列出所有查找结果)

Ctrl+Shift+V: 剪贴板循环

Ctrl+左右箭头键: 一次可以移动一个单词

Ctrl+上下箭头键: 滚动代码屏幕，但不移动光标位置。

Ctrl+Shift+L: 删除当前行

Ctrl+M,M: 隐藏或展开当前嵌套的折叠状态

Ctrl+M,L: 将所有过程设置为相同的隐藏或展开状态

Ctrl+M,P: 停止大纲显示

Ctrl+E,S: 查看空白

Ctrl+E,W: 自动换行

Ctrl+G: 转到指定行

Shift+Alt+箭头键: 选择矩形文本

Alt+鼠标左按钮: 选择矩形文本

Ctrl+Shift+U: 全部变为大写

Ctrl+U: 全部变为小写
