** 【好莱坞电影系列】

 汉斯·季默（Hans Zimmer）：最喜欢的好莱坞配乐大师，作品气势恢宏充满戏剧性。
 《勇闯夺命岛》（The Rock）
 《角斗士》（Gladiator）
 《加勒比海盗》三部曲（Pirates of the Caribbean）
 《雨人》（Rain Man）
 《达芬奇密码》（The Da Vinci Code）
 詹姆斯．霍纳（James Horner）：作品叙事性、抒情性很强，充满历史沧桑感。
 《泰坦尼克号》（Titanic）
 《勇敢的心》（Brave Heart）
 《秋日传奇》(The Legend of Fall)
 丹尼·叶夫曼（Danny Elfman）：作品充满童话般梦幻色彩，独树一帜。
 《剪刀手爱德华》（Edward Scissorhands）
 《僵尸新娘》（Corpse Bride）
 《查理和巧克力工厂》（Charlie and the Chocolate Factory）
 《爱丽丝梦游仙境》（Alice in Wonderland）
**  【日本动漫电影系列】

 泽野弘之 (Hiroyuki Sawano)：作品极富戏剧性，以电子乐见长。
 《医龙》
 《魔王》
 《机动战士高达UC 独角兽》（機動戦士ガンダムUC(ユニコーン) ）
 吉田洁（Kiyoshi Yoshida）：作品以日式传统和风为主。
 《穿越时空的少女》（时をかける少女）
 《死狂/剑豪生死斗》（シグルイ）
 天门：作品清新隽永，多与新海诚搭档。
 《云之彼端 约定的地方》（云のむこう、约束の场所）
 《秒速5CM》（秒速5センチメートル オリジナルサウンドトラック）
 平沢 进(Susumu hirasawa)：电子合成乐为主，风格极其迷幻，多与今敏搭档。
 《千年女优》（千年女優）
 《红辣椒》（Paprika）
 岩崎琢（Iwasaki Taku）：爵士风为主，但最广为人知的还是伤感沧桑的几部配乐。
 《浪客剑心追忆篇》（るろうに剣心-明治剣客浪漫譚- 追憶編）
 《浪客剑心星霜篇》（るろうに剣心-明治剣客浪漫譚- 星霜編）
 《此时此刻的我》（今、そこにいる僕）
 久石让（Joe Hisaishi）：作品兼具通话的幻想色彩与史诗气质，无需过多介绍了吧。
 《天空之城》（天空の城ラピュタ）
 《风之谷》（风の谷のナウシカ）
 《幽灵公主》（もののけ姫）
 《菊次郎之夏》（菊次郎の夏）
 《太阳照常升起》
 川井宪次（Kenji Kawai）：作品以复古史诗风格居多，多用唱诗班人声。
 《Fate/Stay Night》
 《精灵守护者》（精霊の守り人）
 《攻壳机动队》（Ghost in the Shell）
 《机动战士高达00》（机动戦士ガンダム00）
