* 安装 
  qemu-system-x86_64 -hda archlinux.vmdk -boot d -cdrom /home/wuming/soft/tar/archlinux-2017.03.01-dual.iso -m 512
** 方法/步骤
*** 首先 创建虚拟机, 加载镜像并开机
*** 安装 os
    操作系统从光盘镜像引导启动, 需要把系统装在硬盘中
**** 分区 
     fdisk /dev/sda
     设定分区大小, 用 +1G 命令
     要使分区结果生效，需要用 w 命令
     
     BIOS(fdisk、cfdisk 和 sfdisk）
     UEFI （工具使用 gdisk、cgdisk 和 sgdisk)
**** 如果您创建了交换分区（例如 /dev/sda3），使用 mkswap 将其初始化：
     # mkswap /dev/sda3
     # swapon /dev/sda3
**** 格式化分区
     输入 mkfs.ext4 /dev/sda1
**** 挂载分区
     mount /dev/sda1 /mnt
**** 修改镜像源。因为安装 arch 还需要下载，所以必须保证虚拟机处于联网状态。可以采用 NAT 模式。当然也可以根据你的需要，自行选择其他模式。
     vi /etc/pacman.d/mirrorlist
     建议将 163 的复制到最前面
**** 安装系统
     输入 pacstrap /mnt base
**** 生成 fstab
     fstab 文件用于在系统启动的时候自动挂载所需分区。我们可以自动生成 fstab。
     genfstab -U -p /mnt >> /mnt/etc/fstab
**** 初始化 pacman 密匙环
     开始安装前，需要设置 pacman 密匙。

     # pacman-key --init
     # pacman-key --populate archlinux
**** 进入新系统
     arch-chroot /mnt /bin/bash
**** 配置 root 密码
     使用不带用户名的 passwd 来配置密码。
**** 创建新用户
     useradd wuming -m -g wheel -G audio,video,storage
**** 修改用户的密码 
     passwd wuming
**** 如果用户创建错了，用 userdel 删除用户并重新创建。
     userdel wuming --remove
**** 安装 grub
     grub 是一个广泛使用的引导工具，安装也非常方便。
     pacman -S grub
     
     安装好 grub 之后还需要将其安装到系统中 ，并生成配置文件。注意设备名这里不需要
     在后面添加数字。

     grub-install --recheck /dev/sda
     grub-mkconfig -o /boot/grub/grub.cfg
**** 配置网络
     虚拟机一般都使用 NAT 方式连接，在虚拟机内部会认为自己直连了网络，所以只需要启
     动 DHCP 服务即可。

     systemctl enable dhcpcd
**** 安装桌面
     虚拟机性能一般不会太好（除非你 32G 内存并将虚拟机装到了 SSD 中），所以桌面最好
     使用轻量的 xfce4。

     pacman -S xfce4 xfce4-goodies
     
     为了能够开机自动启动图形界面，我们还需要安装显示管理器。其实 xfce4 自带了一个显示
     管理器 xfwm，不过这个家伙没有自带 service 文件，无法通过 systemctl 作为服务启动。所以
     还是安装一个独立的显示管理器更好。我一直安装的是 SDDM，用起来不错。

     pacman -S sddm
     systemctl enable sddm
     
     安装好之后，如果希望开机的时候自动打开数字锁定键，可以编辑配置文件/etc/sddm.conf，
     打开数字锁定键。

     Numlock=on
     
     然后重新启动虚拟机，这样应该就可以看到一个具有图形界面的 Linux 系统。
**** 配置虚拟机高级功能
     下面就是这篇文章主要内容了，配置虚拟机高级功能。
**** 安装附加工具包
     
     首先需要安装支持虚拟机高级功能的附加工具包。假如不是在图形界面中使用这些功能，需
     要安装 virtualbox-guest-utils-nox，不过我们这里用不到这个。

sudo pacman -S virtualbox-guest-utils

安装的时候会出现一个选项询问使用哪个客户端模块。对于标准 linux 内核，也就是我们现
在默认安装的这种情况，使用 virtualbox-guest-modules-arch，也就是选 2（这是我现在的
顺序，不排除将来 ArchLinux 修改选项顺序）。如果是自定义内核的话，使用带 dkms 的那个。

加载 VirtualBox 内核模块
为了让 VirtualBox 内核模块自动加载，启动 vboxservice 服务。

systemctl enable vboxservice.service
如果需要手动启动的话，用下面的命令。不过一般情况我们用不到。

# modprobe -a vboxguest vboxsf vboxvideo

这样一来，ArchLinux 的虚拟机高级功能应该就算配置好了。重启虚拟机就可以使用这些功
能了。我觉得最实用的还是分辨率自适应和共享剪贴板了。
*** 更多设置
    设置 时区：

    # ln -sf /usr/share/zoneinfo/Region/City /etc/localtime
    例如：

    # ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
    运行 hwclock(8) 以生成 /etc/adjtime：

    # hwclock --systohc
    这个命令假定硬件时间已经被设置为 UTC 时间。详细信息请查看 System time#Time standard。

    本地化
    本地化的程序与库若要本地化文本，都依赖 Locale，后者明确规定地域、货币、时区日期的格式、字符排列方式和其他本地化标准等等。在下面两个文件设置：locale.gen 与 locale.conf。

    /etc/locale.gen 是一个仅包含注释文档的文本文件。指定您需要的本地化类型，只需移除对应行前面的注释符号（＃）即可，建议选择带 UTF-8 的项：

    # nano /etc/locale.gen
    en_US.UTF-8 UTF-8
    zh_CN.UTF-8 UTF-8
    zh_TW.UTF-8 UTF-8
    接着执行 locale-gen 以生成 locale 讯息：

    # locale-gen
    /etc/locale.gen 会生成指定的本地化文件。

    创建 locale.conf 并编辑 LANG 这一 变量，比如：

    Tip: 将系统 locale 设置为 en_US.UTF-8，系统的 Log 就会用英文显示，这样更容易问题的判断和处理。用户可以设置自己的 locale，详情参阅 Locale 或 Locale_(简体中文)#设置 locale。
    /etc/locale.conf
    LANG=en_US.UTF-8
    警告: 不推荐在此设置任何中文 locale，会导致 TTY 乱码。
    另外，如果你需要修改 #键盘布局，并想让这个设置持续生效，编辑 vconsole.conf(5)，例如：

    /etc/vconsole.conf
    KEYMAP=de-latin1
    主机名
    要设置 hostname，将其 添加 到 /etc/hostname，myhostname 是需要的主机名：

    /etc/hostname
    myhostname
    并且添加 对应的信息 到 hosts(5)：

    /etc/hosts
    127.0.0.1	localhost
    ::1		localhost
    127.0.1.1	myhostname.localdomain	myhostname
    如果机器有一个永久的 IP 地址，请使用这个 IP 而不是 127.0.1.1。

    网络配置
    对新安装的系统，需要再次设置网络。具体请参考 Network configuration (简体中文)。

    对于 无线网络配置，安装 软件包 iw、wpa_supplicant、dialog 以及需要的 固件软件包。

    Initramfs
    你通常不需要创建 initramfs，因为在你执行 pacstrap 时已经安装 linux，这时 mkinitcpio 会被自动运行。

    如果修改了 mkinitcpio.conf，用以下命令创建一个 Initramfs：

    # mkinitcpio -p linux
    Root 密码
    设置 Root 密码：

    
