#+TITLE: linux 系统简介
#+DESCRIPTION: linux 系统简介
#+TAGS: linux,os
#+CATEGORIES: 软件使用
#+DATE: <2019-06-07 07:29:28>

* linux
** 简介 
   LINUX，是托瓦兹创造的 类 ~UNIX~ 的操作系统(电脑操作管家)。
   我决定用 ~搭积木~ 的方式来讲解这篇文章的功能。
   #+HTML: <!-- more -->

** 进程管理和调度
   #+begin_verse
   我现在什么都不是，但作为一个管家，要做的事情其实很多，所以我先解决以后要面对的处理多个任务的问题，这是一个操作管家首先要解决的。
   我决定定义一个进程的概念，一个进程指定一个程序的实例，我可以在内存中加载好几个进程，然后每过一定时间切换一下，因为速度像火影里的分身一样，因为速度非常快，以为有好几个人存在。
   #+end_verse
   
   #+begin_quote
   那么，用积木搭建一个循环的东西，每过一定时间就加载进程执行程序,就可以'同时'做好几件事啦。
   #+end_quote
 
*** 进程表示
*** 进程优先级 
    像有些程序，什么文字处理程序，用户动一下它才动一下的交互程序，就没必要占用时间了吧，就把优先级设置低一点。进程就要有一个优先级的属性。
    
*** 进程间通信和同步
**** 信号 [signals,SIGxxxx,整数]
     shell 中   
     中断信号 Control-C
     发送信号 kill

**** pipes 
**** sockets
**** file locking
**** message queues
**** semaphores
**** shared memory
** 内存管理
   进程要用到内存，资源也要用到内存，如何处理?硬件提供了分段分页的支持。
** 设备驱动程序
*** 字符设备  
    /dev/zero
    /dev/random  随机数,慢，精确
    /dev/urandom 系统随机，块，随机少

** 模块
** 虚拟文件系统
** Ext 文件系统族
   本机设备都放在 /dev/ 这个目录下
   磁盘设备放在 /dev/sd* 文件名下
   分区类型，分为 msdos(MBR) 和 GPT 两种
   MBR 是为了兼容 windows,它把开机程序和，分区信息都放在第一个扇区。
   如果是扩展分区类型的分区，在在目的分区的第一扇区划出多个扩展分区子分区。
   扩展分区最多一个。

  
   GUID partition table(  GPT 磁盘分区表 ), 把扇区定义为逻辑区块地址（Logical Block Address, LBA）
   GPT 使用了 34 个 LBA 区块来纪录分区信息,并且磁盘最后的 34 个 LBA 用来作备份。
   LBA0 （MBR 相容区块）
   LBA1 （GPT 表头纪录）
   LBA2-33 （实际纪录分区信息处）
  

   开机的检测程序分为 BIOS 和 UEFI
   BIOS 会调用操作系统设置的 MBR/GPT(LBA0) 的启动程序,跟操作系统有关。
  
   linux 会多一个 boot loader 来选择多个系统中的一个。
  
   UEFI（Unified Extensible Firmware Interface）,相当于一个小操作系统，可以进行配置，所以如果要安装 linux,就要关闭 安全启动（secure boot )这一选项.  
** 无持久存储的文件系统
** 扩展属性和访问控制表
** 网络
** 系统调用 
** 时间管理 
*** Real time(1970,1,1,UTC) 
*** Process time(CPU 时间)
** 数据同步
* 启动过程
** 引导程序载入内核
   引导扇区的 Grub 读入 /boot 目录下的内核文件
** init process  (初始化)
   调用配置： /etc/inittab, /etc/init/*.conf
** 系统初始化
   在 init 的配置文件中有这么一行：si::sysinit:/etc/rc.d/rc.sysinit　它调用执行
   了/etc/rc.d/rc.sysinit l5:5:wait:/etc/rc.d/rc 5 这一行表示以 5 为参数运行
   /etc/rc.d/rc，/etc/rc.d/rc 是一个 Shell 脚本，它接受 5 作为参数，去执行
   /etc/rc.d/rc5.d/目录下的所有的 rc 启动脚本，/etc/rc.d/rc5.d/目录中的这些启动
   脚本实际上都是一些连接文件，而不是真正的 rc 启动脚本，真正的 rc 启动脚本实际
   上都是放在/etc/rc.d/init.d/目录下。
** 建立终端 
   1:2345:respawn:/sbin/mingetty tty1
   2:2345:respawn:/sbin/mingetty tty2
   3:2345:respawn:/sbin/mingetty tty3
   4:2345:respawn:/sbin/mingetty tty4
   5:2345:respawn:/sbin/mingetty tty5
   6:2345:respawn:/sbin/mingetty tty6
** 用户登录系统
   （1）命令行登录
   （2）ssh 登录
   （3）图形界面登录
** 图形模式与文字模式切换
   Ctrl + Alt + F1 ~ F6
** 关机
   正确的关机流程为：sync > shutdown > reboot > halt
   关机指令为：shutdown -h +10 10 分钟后
