#+TITLE: spacemacs 简介
#+DESCRIPTION: spacemacs 简介
#+TAGS[]: spacemacs
#+CATEGORIES[]: 技术
#+DRAFT: true
#+DATE: 2020-02-24T12:46:44+08:00

*spacemacs* 是对 *emacs* 编辑器的一套配置，特点是快捷键方便记忆，一般用 空格键 （SPACE KEY）作为命令前导，所以取名 spacemacs。
# more

** 安装和使用
   #+begin_src sh
     # 安装
     $ git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
     # 更新
     $ git pull origin master
   #+end_src
   
** 配置 layers
   spacemacs 的功能包含在 layers 里面，你要哪一个功能，就选定哪一层就好了。默认帮你配好了很多层了，足够用了。
   
** 配置 Dotfile (最重要的配置文件)
   *~/.spacemacs*   文件是 *spacemacs* 总的配置文件，你可以在里面配置需要安装的层和其他选项。
*** Dotfile 的 同步 
    当修改完 ~.spacemacs~ 文件后，可以执行  *sync-configuration-layers* 命令同步配置，就不用重启 *spacemacs* 了。
    
*** 层中排除 package (not) 
    #+BEGIN_SRC emacs-lisp
      (defun dotspacemacs/layers ()
        ;; List of configuration layers to load.
        (setq-default dotspacemacs-configuration-layers
                      '(auto-completion
                        (spacemacs-ui-visual :packages (not treemacs fancy-battery))))
    #+END_SRC
** 环境变量
   *spacemacs* 有自己的环境变量， 通过 =spacemacs/edit-env= 编辑
** 设置文件默认的主模式
   #+begin_src lisp
     (add-to-list 'auto-mode-alist '("\\.js\\'" . react-mode))
   #+end_src
   
** 键绑定 
   按键方式一般会设置成 *前导键* 式的绑定样式
   #+begin_src lisp
     (spacemacs/declare-prefix "o" "custom")
     (spacemacs/set-leader-keys "oc" 'my-custom-command)
   #+end_src
   
** 界面 
*** 主题 
    设置默认主题组
    #+begin_src lisp
      (setq-default dotspacemacs-themes '(spacemacs-light leuven zenburn))
    #+end_src
*** 字体设置
    #+BEGIN_SRC emacs-lisp
      (setq-default dotspacemacs-default-font '("Source Code Pro"
                                                :size 10.0
                                                :weight normal
                                                :width normal))
    #+END_SRC

** 布局和工作空间
*** 布局 
    相当于一种历史状态，可以保存，以备下次使用。
    
    | ~L~ | load layouts from file                                     |
    | ~o~ | open a custom layout                                       |
    | ~r~ | remove current buffer from layout                          |
    | ~R~ | rename current layout                                      |
    | ~s~ | save layouts                                               |
    | ~t~ | display a buffer without adding it to the current layout   |
    | ~w~ | workspaces transient state (needs eyebrowse layer enabled) |
*** 工作空间
    布局还能划分工作空间
** 缓冲区操作命令(以 b 开头)
** 文件操作命令(以 f 开头) 
** 帧操作命令(以 F 开头)
** 导航
*** 光标   
    光标移动用 *vim* 样式的快捷键就好了，如果选择 *Vim* 编辑样式的话。
*** 快速跳转 avy    
    | ~SPC j b~   | 可以返回到跳转的地方，挺好用 |
    | ~SPC j j~   | initiate avy jump char                             |
    | ~SPC j w~   | initiate avy jump word                             |
    | ~SPC j l~   | initiate avy jump line                             |
*** 快速跳转到链接 ace-link
    默认只有 =help-mode= and =info-mode= 开着的。
*** 窗口跳转
    #+begin_quote
    通过窗口编号跳转，移动窗口
    #+end_quote
    | ~SPC 1~     | go to window number 1 |
    | ~SPC 2~     | go to window number 2 |
*** Buffers 管理
*** 书签
    打开书签  ~SPC f b~
    | ~C-d~       | delete the selected bookmark                 |
    | ~C-e~       | edit the selected bookmark                   |
    | ~C-f~       | toggle filename location                     |
    | ~C-o~       | open the selected bookmark in another window |

** 搜索    
*** 关闭高亮 
    ~SPC s c~
*** 正则查找
    以 ~SPC x r~ 开头
** 编辑 
*** 文本修改
    以 ~SPC x~ 开头，排序，比较什么的。
*** 文本插入
    以 ~SPC i~ 开头
*** 缩放片段
    narrow
*** 替换 
    iedit 模式   ~SPC s e~ ，对于用 ~SPC /~ 搜索的多文件，可以用 ~C-c C-e~ 编辑修改 
*** 批量重命名
    wdired
*** 编辑 lisp 代码
   以 ~SPC k~  开始
*** 访问寄存器
   ~SPC r~  开头
** 比较
   比较 *buffer* 的不同 ，以 ~SPC D~ 开头
** 缩放
   ~SPC z~ 
** 服务
*** 保证服务不关闭
    #+BEGIN_SRC emacs-lisp
      (setq-default dotspacemacs-persistent-server t)
    #+END_SRC
*** 退出 emacs
   退出服务 ~SPC q q~ 
*** 禁止服务
    #+BEGIN_SRC emacs-lisp
      (setq-default dotspacemacs-enable-server nil)
    #+END_SRC
** 调试
*** 加载有错误
    emacs --debug-init
*** 更新包后有错，要重新编译安装包
    spacemacs/recompile-elpa
*** 打开调试开关 
    toggle-debug-on-error

    
