* 首先,我想引用一下别人说过的一句话:除非在过去的十年你一直生活在山洞里,否则你一定听说过linux. 
是的,现在听说过linux, 会一点linux基本操作的人多如牛毛,然而真正能用linux做一点事情的确少之又少,这就造成了现在的状况:各大 linux论坛十分热闹,但我国linux瞬娜椿故分紧?到底是什么原因造成了这样的状况? 纠其原因,只有两个字:浮燥! 
如果在论坛里来一次 调查投票,看一下在论坛里的人到底有多少人手头有一本以上的正规linux教材.我想这个数字不会超过30%. 如果再问一下,有多少人完整的读过各发行版自带的入门文档,系统定制文档,系统管理文档和系统安全文档,恐怕这个数字不到10%. 如果进一步再调查一下究竟有多少人静下心来学习过操作系统和计算机网络等和linux学习十分密切的专业课程,那么恐怕只有3%的数字都不到了. 
这让我想到了98年前后IT泡沫时代的中关村.在中关村的大街小巷,到处是一个个意气分发牛哄哄的IT精英.他们戴着默镜,剔着小平头,张口闭口都是网络, 安全,信息,黑客,代码,产业.T恤背后写着三个字:别惹我! 然而最后IT泡沫一过,只有那些真正肯安安心心静心学习的人在IT界存活了下来. 
现在国人学习linux的状况也是这样,学linux的人个个都意气分发,以为学习linux会用linux是多么了不起.学了一点皮毛就认为很牛了.但是那些企业用人单位却很难找到真正适合的linux人材.因此,我想就目前的状况发表一下我的看法. 
首先,这篇文章是写给那些想成为linux高手,并真正想用linux做些事情的人.如果你只想做一个菜鸟,没事的时候在你双系统启动的电脑上偶尔选一次 linux,然后没事进去偷着乐,那就请你自便.另外,我想说明,和真正的牛人比起来,我自己还处于一个比较低的水平.我没有读过内核源代码,不知道 linux工作原理等等,但是通过摸索,至少我已经找到了通往高手的道路的方向.因此还是想说两句. 
1：linux不是玩具   
如果你想系统的学习linux,你必需清楚的认识到这一点.现在有很多人,号称是linux爱好者,但是他们大部分的事情还是用windows 做,而linux只是作为一个随便玩玩的系统.他们懂得一些linux的基本操作,知道有linux这个玩艺,也因为经常听人家说linux好就咬定了 linux就是好.只要有人说linux比windows差,那么他们就奋起反驳,他们也看不起用windows的人,认为用windows的人水平低. 但是自己用电脑的大部分时间还是用windows并且把重要的文件都放在了windows分区,因为他们骨子里只把linux当做玩具,没有真正领悟 linux的精髓所在.如果你真正想系统的学习linux,想用linux有所作为,那么请忘记windows的思维方式,慢慢感受和习惯linux 的操作方式,总有一天你会真正体验到他的奥妙所在,从而从自己内心深处喜欢他,使用他,而不是为了赶时髦或向人炫耀而使用他. 
2：手头有一本好的入门教材吗   
"如果你还没有好好的读完过一本linux安装及入门教材就不要到初学者论坛来问题!因为你连问问题的资格都没有! " 这是我的一个比较偏激的观点. 

如果你现在开始下决心学习linux了,那么第一件你要做的事情是到书店去挑一本好书.而不是到论坛社区去问该用什么版本,该如何学习 linux.一本好的入门教材可以让你快速领悟linux的操作方式,系统的基本使用等等.而且都是前人总结经验写出来的,他可以帮你搭起一个学习 linux的框架,对linux有一个总体的认识.就好比建一撞大楼前先打好地基,搭好混凝土框架.以后就可以慢慢往这个框架里添砖加瓦,最后建起大楼. 而那些想急于学习的,不想看书,只想靠混论坛来学习linux知识的人,就好比建一撞大楼,今天建好第一层,然后第一层就要全部粉刷好,装修好,家具买好 住进去,然后第二天再开始建第二层.

这样没有整体规划的学习是学不好linux的,最后的结果是浪费自己的时间,也浪费别人的时间. 如果你不信, 可以让实事去告诉你,以一年为限,你和你的一个朋友同时从0开始学linux,计算机基础差不多.你去买几本好书自己慢慢看边看边做实验,让你的朋友整天 到各大论坛瞎混零散的学些linux知识.也许一开始,你的朋友会比你懂得多,但是一年以后你的水平肯定在你的朋友之上. 在初学阶段,不要随便在论坛上发问,多看书是根本,即使真的非问不可的问题,也要先自己动手察资料解决.实在不行再来问,高手不会鄙视菜鸟,因为每一个高 手都是从菜鸟过来的,他们都知道菜鸟的苦衷.但是高手会看不起那些自己不愿动手动脑不会学习解决问题而只想得到现成答案的人.那样的人会被高手在心里暗骂 成不配用linux的蠢货. 

你需要以下几种书: 
一本好的入门教材
一本linux指令参考手册
linux系统管理手册
讲解linux系统原理的书

一开始,你只需要入门教材就可以了.并且严格安教材的讲解去学习,不要一天到晚想着去装显卡驱动啦,装游戏啦,装软件啦,这些都没有必要.你就当你自己的电 脑不能上网,只能通过看书学习.慢慢看书,稳抓稳打.慢慢地就融会贯通了.这时候你再到linux初学者论坛去看看,你在那里早已经是高手了. 

 

另外,一开始你要选定一本入门教材,但是不能只看一本,因为有些书上讲的,可能是另外的书上没有的.因此,重点选一本教材看完.然后再看两三本入门教材浏览 一下.作为对第一本书的知识的扩充和巩固. 在看书过程中,如果你有什么不懂的,不要急于上论坛问,自己认真看几次,实在不懂没有关系,把问题放在那里.不要钻牛角尖不懂不肯放手,这种精神是好的, 但是方法是错误的.你尽管学下去,也许你看完书本以后的内容,就对前面不懂的内容豁然开朗了.这是在学习linux中常有的情况. 

 

另外,现在很多入门书籍是针对非技术型用户的.(我把那些对linux本身不感兴趣,只想用他来上网,听音乐和打字的人称为非技术型用户,而把对linux本身感兴趣的人称为技术用户) 这 些针对非技术型用户的入门书籍几乎通篇都是插图,讲解的内容都是如何在图形界面下操作.这些书籍并不能帮你成为一个高手.反而会让你养成倚赖鼠标和图形界 面操作的习惯以后很难改掉.因此不能看这些书,一定要买那些一开始就从系统基本机构基本命令开始讲解的书籍.我看过的第一本linux入门书籍共有十多 章,但是他从第十一章开始才大致的讲解了一下图形界面的知识.我很感谢这本书,让我一开始就脱离了windows的思维方式,给我以后的进一步学习带来了很大帮助. 

 

完成以上的内容,你就完成了建大楼打地基建混凝土框架的过程了.可以接下来进一步学习了. 

 

 

 

3：你看完系统自带的文档了吗?   

 

 

当你完成入门的过程后,就可以开始读其他的文档,然后到论坛的精华区看看,向你建起来的大楼框架中添砖头了.当然 ,首先要读的,还是系统自带的文档. 

 

绝大多数linux发行版都自带非常详细的文档.比如我一直在用的redhat,他有从系统安装到系统安全,针对不同层次的人的详尽文档.静下心来,把这些 文档读完,比看任何论坛的精华区都有用.书籍和文档就好比是你每天都离不开的一日三餐,论坛区的精华文档就好比是点心和水果.你可以不吃点心和水果,但是 决不能不吃正餐. 

 

当然,不能为看文档而看文档,你一定要边看边安文档中说的做试验验证.这样才印象深刻,否则看过就忘记了等于没有看. 

 

另外,如果真心想学习linux就不要吝啬,也不要害怕丢失数据而不敢做实验.我建议你去买一个小的二手硬盘,然后放开手干.不要怕丢失数据而不敢做,如果你没有学会技能,将来做了linux系统管理员或者网络管理员到那时因为不会而丢了数据就是大事情了.

 

 

 

4：学习linux不是逛自由市场  

 

 

 

经常看到有人问用什么版本的linux好,其实只要你认真学习无论什么版本都挺好的.要知道,开发linux发行版的人都是通读过linux内核代码,对 linux原理极其精通的人,而且每一个开发团队都对他的发行版做过测试后放出的.那些国际知名的大品牌更是如此. 因此,讨论什么版本好并无意义,关键是你是不是真心想学.不过,为了避免曲高和寡,最好选用的人多的版本,比如redhat manrake suse 等等. 国内有一两个 linux版本做的也不错,但是国内的linux都是面向非技术型用户开发的,因此,如果你想成为高手,建议不要用国内的版本. 

 

学 习linux不是逛自由市场,选定版本就要静下心来学习.不要今天换版本明天要升级.这样对你没有好处.我见过一些人号称用过十几种甚至几十种 linux,向人谈论起来头头是到,好像懂的很多,但是如果你让他去用linux搭建一个web服务器,做一个linux网关,他就什么都不会了.他们把 时间都浪费在了版本的转换上了. 

 

 

 

 

5：你能看懂英文文档吗?   

 

 

 

谈论这个问题,我有点低气不足,因为我自己的英语很差.但是,至少我可以无障碍的读完一般的计算机文档.计算机英语很简单,只要熟悉了计算机专业英语,高中 毕业的水平就可以轻松的阅读计算机文档了.如果你的英语实在太差了,连最简单的计算机英语文档都看不懂,那么在学习linux的同时,请赶紧学习英语.也 许你说,你可以看翻译的文档,当我还是一个菜菜鸟的时候,也是这样认为的.但是,后来才发现,如果你想深入学习linux,看不懂因为文档实在是太难了. 

 

写的最好的,最全面的文档都是英语写的,最先发布的技术信息也都是用英语写的.即便是非英语国家的人发布技术文档,也都首先翻译成英语在国际学术杂志和网 络上发表.你去看看各大软硬件生产商的官方网站,有哪一个不是用英语作为其主站的? 长期用windows的人会很不习惯这一点,装个软件还要看半天文档,应为windows用起来实在太简单了.但是如果你想学习linux就必需学会看各 种文档,而大部分的文档都是用英语写的.我发现很多人甚至连man文档都不会看,有什么命令不会用了就跑到论坛上来问,还装出一副可怜相,乞讨一个命令的 用法.有这些时间还不如自己看看man文档,即使你一个一个单词的翻译成中文再自己看都比问别人强,因为别人的回答再怎么详尽都比不上man文档详尽.安 装一个新的软件时先看README,再看INSTALL然后看FAQ,最后才动手安装,这样遇到问题就知道为什么.否则,说明文档都不看,结果出了问题再 来找答案反而浪费时间! 古人说欲速则不达就是这个道理! 

 

 

 

6：忘记windows的思维方式     

 

 

 

思想性的转变比暂时性的技术提高更有用,因为他能帮助你加快学习速度.现在很多人用linux.但是,他们用linux的方式完全是 windows的那一套方式.骨子里都是windows的思想.这样是不能领悟linux的精髓体验不到他的优越性的.我前几天看到一个朋友要把刚装了不 到2天的mandrake 10 删除掉,我问他为什么,他说太慢了,受不了,还是用windows快.然后我留意了一下他用linux的方式,他的所有操作都带着windows的影子. 

 

他连最基本的删除,移动文件这样的操作都要用鼠标,这样当然慢了!最后我只好说,你删除吧,你不适合用linux, linux不是这样用的.各位可以去看看那些linux高级用户,他们是怎样操作的.通常他们都是在X上开一个xterm或者rxvt终端,80%以上的 操作都在这个终端下用命令完成,因为 linux的命令行十分强大,速度也十分快,简单的几个命令的组合就能完成非常复杂的操作.举一个例子:linux 的常用命令find,去看看man文档,初学者一定会觉得太复杂而不原意用,但是你一旦学会了就对他爱不释手.他的功能实在太强了,在配合exec参数或 者通过管道重定向到xargs命令和 grep命令,那么他能完成非常复杂的操作,如果同样的操作你用图形界面的工具来完成,恐怕要多花十几倍的时间.

 

因此linux高手经常会说:如果没有 find和grep我们还怎么活.但是现在大部分的linux初级用户受到windows影响都喜欢用图形界面的工具来完成一些基本的操作,我并不是说图 形界面不好.只是由于linux和windows设计思想的不同他们的操作方式也有很大不同.在windows下用图形界面操作会比敲命令快,但是 linux是一个命令行组成的操作系统,他的精髓在命令行! 无论图形界面发展到什么水平这个原理是不会变的! 

 

 

 

7：入门以后多学命令   

 

 

 

当你看完了一两本入门书籍后就应该扩充自己的知识,多学习linux命令,但是不要在初学阶段就系统的学习linux命令,初学阶段只要学会书上提到过的命令就可以了.单靠学习各种命令而成为高手是不可能的,但不会命令而成为高手也是不可能的.这就好比学英语,什么语法都不懂,只捧着单词手册背单词是学不会英语的,但是没有单词词汇量英语水平也提不高的. 

 

在linux中学习命令的最好办法是学习bash脚本编程.bash脚本比起其他语言来学习简 单,但是功能却十分强大.通过学习bash编程,能让你掌握大量的linux命令.另外,买一本命令参考手册是必要的,遇到不知道怎么用的命令可以随时查 询,这要比察man文档快.特别适合英语不好,看不懂man文档的人. 

 

 

在linux中,命令可分为系统基本命令和应用程序命令.系统基 本命令是所有的unix类系统都支持的命令,走到哪都不变,只要是unix类系统上就肯定有.比如ls,rm,rmdir,cp,cd,mv,cat等 等.这样的基本命令大约有200个,这些命令是一定要掌握的,我买了一本指令参考手册>这本书非常好,他根据命令的常用指数分类,标明3颗星的为最 常用命令,一定要掌握,两颗星的其次,1颗星的只要知道一下就可以了虽然现在都已经FC3了,但是经典的UNIX基本命令几十年来都没有变过!另外有些命 令是linux特有的或者是某一个应用程序的可执行文件比如xmms播放器.这些只要知道就可以了,不知道也无所谓.有些命令比较少用,因此通常都记不住 他的用法,对于这些命令至少要知道有这个命令,脑子里有印象,需要用的时候察一下手册就可以了,但是决不能不知道这个命令的存在! 

 

 

 

8：学会管理系统   

 

 

 

等到有了基本知识,也掌握了一定量的命令用法后,就可以进一步学习管理系统.这些内容入门书上会有,但是不会很深入.要深入的学习系统管理,就要去买一本类似之类的书.认真的看书并做实验,可以让你很快的进步.学习配置各种网络服务器,用linux搭建网络,这些都是学习linux系统管理和网络管理的好方法. 到了这个阶段就可以经常上网察察资料,看发布软件的官方网站文档和FAQ,看看论坛精华区文章.但是不能本末倒置,多看书还是根本.书籍和官方文档可以让你系统的学习,但是论坛可以让你学到一些小知识,小技巧.我本人也经常到论坛上来看看,因为即便是一个新手,也可能会发现一些你所不知道的小技巧,看论坛 可以学到这些小技巧.但是我看文档和看论坛的时间比不会小于4:1 . 可以把平时积累的问题一次在论坛上发问. 但是初学的时候不要频繁上论坛,因为你要问的问题都在书上写着,耐心一点,你很快就能看到了. 

 

 

 

 

9：深入了解系统结构     
 
 
 

等你有了一定的系统管理知识,知道了/etc下那些配置文件有什么用,知道了一般的网络服务器如何配置后,就可以去了解系统结构了. 了解系统结构不是要你去看什么文件夹放什么内容,而是要学习一些原理性的东西.比如系统是如何引导的,引导后启动了那些东西.系统中哪些是最基本的库文 件,有什么用等等.学习系统结构的最好方法是自己做一个linux系统,再也没有什么能比自己做一个linux系统更能学习系统结构了.LFS (linux from strach)可以教你从源代码自己编译一个系统.通过自己编译一个系统,你就可以了结linux系统结构,知道哪些文件是干什么用的,以及他们如何协调 工作.当然,在你达到LFS水平之前还有很多事情要做,比如学会如何编译安装源代码发布的软件和编译新的内核等等.到了LFS水平,那么在大多数 linux论坛上你就可以被人称作"高手"了!到了这个地步,就相当于一撞大楼已经基本建好,但是还需要粉刷和装修,真正的细活还在后面! 

 

 

永远记住天外有天,人外有人的道理.即便有了LFS水平,在那些搞linux系统开发,通读过linux内核代码的人看来你还是一个菜鸟.因此, 请时刻保持虚心的态度.即便是在论坛上只有一颗星级别的人,也有可能是一个潜在的,真正的高手! 大多数真正的高手平时都在搞研发工作,哪里有时间上论坛啊! 倒是有很多大学还没毕业的学生,整天混在论坛上. 

 

 

 

10：学习专业课程     
 
 
 

如果你不是计算机专业的,而想把linux学好,就一定要学习专业课程.学习微机原理,操作系统,计算机网络等等专业课程是必需的.为什么同时开始学习 linux,有些人学的非常快,不到半年就成了高手,有些人玩来玩去还玩不出名堂,玩了一两年还是菜鸟? 因为那些学得快的人有基础,他们都学过专业课程.同样一篇文档,没有基础的人可能看了三遍还不明白,基础扎实的眼睛扫两下就懂了! 这就是专业和非专业的差别! 因此,要想达到更高的境界就一定要学习基础的专业课程. 

 

 

 

 

11：保持虚心学习的态度   
 
 
 
 

我想再重复一遍天外有天,人外有人的道理! 保持虚心的学习态度不仅能让你学到更多知识,而且会让你受人尊重. 

 

在linux的世界里,如果你想靠混论坛,发水贴,换几颗星星增加一下级别,然后再面对菜鸟说几句牛哄哄的话来赢得别人的尊重是不可能的.即便是一个刚入门 的菜鸟,也能分辨你回答问题的质量,从而知道你到底有多少水平. 另外,当你成了"高手"的时候,你也能从"菜鸟"那里学到很多知识.因为有很多问题是你从来没有想过的,认为自己肯定会的,但是实际遇到的时候会有困难. 而"菜鸟"们往往更善于发现这类问题.这就是中国人常说的"教学相长"! 

 

在linux的世界里,越是水平高的人越谦虚,因为他们知道自己还有很多不知道的,而那些半瓶水就想晃荡的人反而自以为是,因为他们还不知道自己还有很多不知道的! 去看看linuxdiyf、OSCHINA嵌入式开发和UNIX的牛人,他们很多都是有过好几年linux方面的工作经验,精通linux和unix的好手,但是每个人都保持着非常谦逊的态度,这些人是值得尊敬的。

* Location: https://www.zhihu.com/question/27751139                                                                                      
学习学习方法
学习学不进去的时候怎么办?
不管学霸还是学渣都有学不进去习的时候这时候你们都是怎么逼自己的还是干脆就不学了

1392 人赞同
我来给个方法论回答
我试过无数方法，解决学不下去的问题。
先整理几个失败的方法：
1，学不下去就不学：喝茶，喝咖啡，静坐，冥想，听音乐，网上看各种励志鸡汤，制定学习计划。通通无效。冥想半天睡着了，喝着咖啡就开始吃零食
了；听听音乐就顺便看了个电影，看着励志鸡汤就顺路看上了知乎。。。结果是一天一天又一天，继续荒废。

2，能占用的时间都占用，剩下的学习。就是所谓的逆序时间管理。把玩的时间都安排好，剩下可怜的几个小时学习。可玩的事情太多啊！玩着玩着心就
野了，更没法低头学习。

3，什么都不干：关手机，断网线，坐在桌前先呆5分钟。结果要不是百无聊赖不知不觉又玩上了，要不就是睡着了，或者一个人静默的胡思乱想。

4，先干点安静的事情：书法，画画，写日记。看窗外。我只能说，呵呵。人在拖延的时候，所有无聊的事情都拥有巨大的吸引力。我曾经静心练书法，
然后练着练着，觉得笔不好，然后就上网shopping 买笔去了。。。看看窗外，看到一只猫，就出去抓猫去了。还顺路拎回家只小猫，于是接下来的N天都
忙着养猫了。

我是长期抗争，屡败屡战。把吃不到奶的劲都使出来了，浑身上下能用的不能用的全都动员了一圈，才培养了一个脆弱的支持体系，维护我少得可怜的意
志力。

我有一个思想轨道论。人每一次的思想支配行为，都是在强化一条轨道。时间长了，要脱离轨道很难。天天在外头跑来跑去，就觉得家里呆不住。天天宅
在家里，就懒得去外面。早起的人恒早起，都是这个原理。人的精神状态，学习状态，懒惰程度，全有自己的轨道。玩三消/扫雷/纸牌类简单游戏的时候
，明明没啥瘾，甚至觉得有点无聊，可还是一局一局的玩下去，在那种时刻可以明显感受到”心流“ 在固定的轨道上涌动。”学不下去“的时候，就要给自
己打破现有的懒散轨道，铺一条”学习“轨道。

怎么”打破“现有轨道呢？分为环境和身体。环境包括：改变居住环境；改变学习环境；参加学习小组/课程；找学习伙伴，等等。身体包括：开始早起，
开始运动，规律作息和三餐。尤其我想强调一下运动对激发精神活力的作用。跑吧，小伙伴们。效果立竿见影。我自己有强烈的感觉，当成天宅在家里的
时候，身体的状态是懒散的，内敛的，肢体不会大舒大展，精神也是懒散的，专注细节的。跑起来之后，肢体舒展，环境改变，精神也被激活。瑜伽，跳
操，仰卧起坐之类固定在某地的运动都不行。

现有懒散的轨道打破之后，就要给自己铺设一条学习的轨道。这个过程挺难的。如果思想是河流，它已经在我们惰性的河床上流了太久。现在我们把它带
到学习的平原上，刚开始只能徒劳的浅浅划下痕迹，很容易散漫，很容易惯性的又回到原来。这时候就要用意志力给自己设限，约束河流往学习的方向走
。我用的是纸笔。字很烂，就是给大家一个参考：

[9ad6612662ec6285450f4048635bedca_b][whitedot]
高亮区是我对时间的记录。几点几分，接下来的时间我打算干什么。几点几分结束。用了多少时间。这可以约束自己的思想，也可以激发思维的主动性：
接下来5分钟我要做某某事。我用这个方法一直监督自己的思想，防止出轨。

还有一种学不下去的情况，就是思路卡住了，接下来遇到困难。通常的建议是暂停，干点别的事，再回来。可惜我要是干上别的事就回不来了。所以没办
法，只能死磕：

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

我就是坐在那里，各种吐槽，各种画小人诅咒，各种抱怨。做大量的无用功。但是都用纸笔记下来--要是光用脑子想，很快就控制不住想玩了。我就是写
写写，全是和学习有关的事情，然后在某一个点，突然灵光毕现，豁然开朗。

所以总结一下，学不下去的时候怎么办？早起，好好吃饭。收拾屋子，重新摆放家具位置，拿书到图书馆去。图书馆学不下去的，换个位置。换到咖啡店
去。换到教室去。下午出去跑圈。找个秒表，整个本，一分一秒的趴桌子上死磕。那种大学图书馆常见到的，拿张小桌布，抱个小水壶，听着音乐再啃个
水果，真的不是学习啊同学。

453 赞同反对
【看完不点赞小朋友真是太不可爱了】
补充几点：
1:我所说的“学不下去就逼着自己学”并不是说要死磕到底，而是在休息之后觉得状态恢复了一些时继续投入学习。
举个栗子，晚上八点钟的时候，你写数学题时脑袋发胀，不会写，写不下去了。这时候出去休息你有了两个选择：1，玩二十分钟之后，觉得放松了继续
回去写。2，玩个三四个小时继续回去写。
我的话我选选择一，玩个三四个小时之后十一二点钟了吧，这个时候就应该犯困了，多数人应该更写不下去了。还有整个学习计划就被彻底打乱了。
2:该困告的时候就应该果断立刻马上的去困告告，身体上革命的本钱，熬夜伤身啊少年。
=================以上2月1日早9:30更新=============
(*◑∇◑)☞【重要的事说三遍！】鸡汤喝多了会中毒！鸡汤喝多了会中毒！鸡汤喝多了会中毒！☜(◐∇◐*)
曾经有一段时间疯狂的迷恋各种正能量文字，看完之后真的挺振奋的，那种酸爽简直无法和深夜写作业比！但是那些喷鸡汤的真的想对他们说，暂时的振
奋就暂时的振奋，能让我埋头学习就是好鸡汤，好东西。那段时间，恩，怎么说，我成绩掉的比较严重的时候，让我重新回到前几名的、让我熬过那段时
间一直逼着我学习的就是那一些鸡汤。
然后现在。。。我看那些鸡汤再也没有感觉了，那段正能量文字满天飞的日子也过去了，我现在基本能知道的都是我以前看过的，还有什么刘同卢思浩那
些我从最开始看就觉得没什么感觉，刘同可以当做故事看或者人生感悟看，至于卢思浩。。你们愿意看你们开心就好。
所以！这次告诉你们两个东西！
1:鸡汤喝多了会中毒！给你那些正能量的东西总有一天会用完，接下来的路就要靠自己坚持下去！
2:在低谷的时候正能量文字是真的可以陪你挺过去！但是它是不能用多久而且可以第二次没用。☜(=σωσ=☜)

重要的事说三遍！点赞（上面说过一遍）点赞！
曾经在知乎里看到一句话：如果你不想学、学不进去了那就不学了，那你什么时候学？看到问题里有一个话题：熬夜。( ･ิϖ･ิ)っ这里想说起一些关于自己
的经历和感受。我家在城乡结合部，一个略老旧的社区里，社区里年轻人大多已经搬走，剩下的大部分是退休的老人和在孙女孙子的大妈（这段是废话，
可不看），自然而然广场舞的骚扰肯定少不了。←_←也不知道你们对于那种一整个晚上都在循环听大喇叭放：终于你做了别人的小三～的感觉是什么样子
。
后来我为了逃避这种精神污染，开始插耳机，可是呢，我发现一个问题——终于你做了别人的小三这十个字还是无法被音乐掩盖。【黑喂狗跟我唱终于你做
了别人的小三～】
放暑假了，我妈就开始放养我了。在最后几天刷作业的时候，我发现白天我根本无法放下手机安心写作业，无奈只好认命半夜刷作业。好家伙，半夜刷作
业跟打了鸡血似的，又精神又没有口水歌。（上课期间，不推荐半夜刷作业，因为这样貌似越刷越困。）从此之后半夜刷作业的日子一发不可收拾。
(๑òωó๑) 可是你知道后果是什么吗？恩？这个人脸色不好，脾气暴躁，这特么还胖了，胖了就算了，痘痘爆发，白天看什么都看不进。
好了，上面一段其实可以都不看，看这一句就好：上学期间千万不要熬夜写作业，早起补作业都好一点。熬夜之后你第二天晚上写作业更没精神更学不进
去，很烦躁脑子一片混沌啊有木有？？？！如果习惯熬夜的话，那就星期五晚点睡，不要写作业了，该玩就玩，第二天睡个懒觉，下午乖乖写作业。
2，学不进去的时候要逼着自己学。
如果不是精力的原因，那你要训练一下自己的毅力了？是不是觉得一到写作业的时候就发现指甲要剪了？这本小说居然挺好看的？好像我微博上有人评论
？我去看看热门微博？
乖乖，那我问你，那你准备什么时候学？玩够了再学？按照你这样说，当你打开热门微博的时候就会一条条看，再看看评论，好不容易翻完了你有手贱去
刷新关注去了，然后顺着顺着你就玩到了半夜。哦，半夜了啊，要写作业了啊？然后你就熬夜，熬夜写作业之后第二天继续学不进去，学不进去了我就玩
玩吧，之后你又点开了热门微博。。。。
很负责任的说，玩不够的。
再送你一句话：当你决定出发的时候，最困难的地方就已经度过了，所以，何不执行下去？
泡完脚，闭眼！困高！
如果明天题主看到了这个答案，拜托提醒我一下我明天起床洗头发，谢谢。

410 赞同反对
[da8e974dc_] 知乎用户我是机器鼓励师
“操，不可能不行啊，再看一遍！”
“既然这个世界上有别人能搞得定，我也一定可以搞定的，再来！”
“尼玛！终于明白了！操！我果然是天才”

最近在备考，一共六本厚厚的专业书可真是挑战。开始的时候是真的看不进去，毕竟放假了看专业书籍对我来说太残忍了，很烦躁，效率很低。在微博上
看到了清华陈吉宁校长的毕业典礼讲话，里面举了《Outliers》中的例子：无论是小提琴还是钢琴专业的学生，他们… 显示全部
最近在备考，一共六本厚厚的专业书可真是挑战。开始的时候是真的看不进去，毕竟放假了看专业书籍对我来说太残忍了，很烦躁，效率很低。
在微博上看到了清华陈吉宁校长的毕业典礼讲话，里面举了《Outliers》中的例子：无论是小提琴还是钢琴专业的学生，他们从5岁左右开始学琴，到20
岁时，那些具有成为世界级独奏家潜质的学生都至少练习了10000小时，那些被认为比较优秀的学生都至少练习了8000小时，而那些被认为将来只能成为
一名音乐辅导老师的学生只练习了4000小时。这就是所谓的“10000小时法则”。
之前也听过什么一件事只要做满多少多少小时，你就可以精通这件事，这次临近考试，我就打算实践一下，给自己的学习时间计个时。我使用手机秒表计
的时，当我按“开始”的一刹那，就感觉战斗开始了！过一会会看一下手机，啊呀，看了45分钟了，再过一小会就一个小时了！哈哈真开心。~然后不知不
觉地多看了30分钟，休息的时候停止计时，等调整好再计时开始，以此类推。看到秒表上的数字不断累积，秒位数字飞快地闪着，然后从秒到分最后累积
到小时，感觉是对自己刚才的精力集中做了一个很直观的量化，虽然离前面提到的4000小时还有很长的距离，但是方向却很明朗，而且也有一个结果在那
里放着，就算最后不是最好，但也绝对不会是最差。如果累计到了会不会真的发生奇迹呢，打心眼里期待这次实验的结果啊。
一天下来，我累计学习了6：56：47，这七个小时度过地都很高效，这种事在假期发生，这对我来说简直是奇迹啊。。。。太惭愧了。更让人开心的是，
明天我会继续在这个时间上累计计时，正在向着4000撒欢狂奔~

我觉得很多时候不能专心做事的原因，是因为较短的时间内很看到这件事给自己带来的有形的收益，随之而来的浮躁情绪，伴着懒惰的天性，便总会感觉
自己徘徊在原地。就算你进步了，你在学习过程中的不专心也会让你产生一种愧疚，会让你怀疑自己，否定自己的进步。数字上的量化会很直观地告诉你
，你前进了多少，离4000小时还有多远。

喜欢做各种方面的实验，就是因为好奇看到的说法到底是真的假的~哈哈哈！

时间久了，有了完整做一件事情的习惯再回头看这个答案，还是觉得这样的开始挺可爱的~


 青禾学医的小白，即将去医院实习~


我在二戰考研的時候，一邊工作，一邊學習。經常有學不下去的時候，忙了一天擠著公交吃完飯后居然還得刻苦學習，總覺得特別心酸。我總問自己，憑
什麼妳就得折騰，就不能在一個地方安心工作，別人都過得挺好，妳為什麼要拼命過得不好。
因為不甘心啊。因為沒有經歷過，不曾看到過，未能努力過，那些痛苦總會在我荒廢了一天后深夜折磨我，夜不能寐。
所以我得學習，哪怕多看了一張紙，多記住一句話，也比昨天的我要多前進一步。我並沒有卓越的天賦可以過目不忘，也沒有優越的家境供我衣食無憂，
我只能靠自己。努力，是最簡單也是最難的事。對於未來，我能做的也只有拼盡全力而已。
每當我學不進去的時候，我都會這樣想想，然後繼續翻書。
希望二戰順利。


没有不学这个选项，ABCD都是学。


如果是感觉浮躁，心神不定，告诉自己再坚持5分钟，如果5分钟后还不进入状态，建议休息一会。如果是觉得大脑迟钝，集中不了注意力，这时候需要换
换脑子，站起来动一动，吃点东西，喝点水，再学。这时候可以换一样科目。有时候觉得东西多，压力大，怎么学也… 显示全部
如果是感觉浮躁，心神不定，告诉自己再坚持5分钟，如果5分钟后还不进入状态，建议休息一会。
如果是觉得大脑迟钝，集中不了注意力，这时候需要换换脑子，站起来动一动，吃点东西，喝点水，再学。这时候可以换一样科目。
有时候觉得东西多，压力大，怎么学也学不完干脆不学时。制定计划，定下最重要的几个目标，目标越少越好，帮助自己朝一个方向努力。
随时想到要做的事（和学习无关），找张纸或本子随后记下来，一会儿再办。
把手机关机，放到别的房间。想想自己是为了什么在学习，努力必然是痛苦的，但现在的短期的痛苦是为了避免以后更大的痛苦。
骚年，加油，我也常常要克服这种情况= =。。


 征途是星辰与大海大学开始运动。越运动越努力

逼自己学，逼着逼着就适应了。
逼自己跑，跑着跑着就能跑了。
逼自己变，变着变着就成功了。


排名第一的回答提到，关键是心思要在学习上。那么如何集中心思到学习上？关键是引起学习的兴趣。这方面我的一个方法，就是提问题。把学习内容变
成一个个问题提出来，然后学习的过程，就是去钻研解决这些问题的方法。这样做的好处是因为，问题容易引起大脑… 显示全部
排名第一的回答提到，关键是心思要在学习上。那么如何集中心思到学习上？
关键是引起学习的兴趣。
这方面我的一个方法，就是提问题。把学习内容变成一个个问题提出来，然后学习的过程，就是去钻研解决这些问题的方法。这样做的好处是因为，问题
容易引起大脑的兴趣，大脑的一个特点是想把未完成的问题解决掉，没有解决的时候就会一直去想，甚至吃饭想，睡觉想，这个时候其他的诱惑都弱爆了
，就是钻研这个问题才是最有意思的事。
这个方法尤其适合对于感兴趣的内容钻研性的学习，而且往往能体会到钻研的乐趣和进步的感觉。

