** 心理活动(大脑活动而不是心)
*** 感觉
感觉器官（5官+皮肤）接收外在刺激把刺激传给大脑的过程 。这个过程是潜意识下的我们是意识不到的
**** 视觉
**** 听觉
**** 其他
***** 嗅觉
***** 味觉
***** 触觉 动觉
***** 肤觉
*** 知觉
而知觉是潜意识把这些刺激通过我们的大脑神经加工过以后把信息送入我们的意识里
*** 心理,意识
**** 睡眠与梦
**** 其他状态
***** 清醒梦境
***** 催眠
***** 冥想
***** 幻觉
***** 宗教狂热
*** 智力
*** 动机
*** 人格
*** 心理障碍
**** 恐惧
一自己有信心、二找到陪同治疗的人、三找到好医生
*** 心理治疗

*** 社会影响
*** 社会心理学

** 行为活动
*** 学习    
*** 记忆
*** 目标
感觉，这种最虚无缥缈的东西，才是一个人活下来的动力。由此，要找到人生的目标，
一定要先从回忆你最美好的感觉开始。是和家人在一起的时光，还是在户外呼吸到新鲜的空气，
是团队协作攻克一个个难题，还是通过自己的研究得出一个有价值的结论。在这一过程中，
切记抛弃道德观念的束缚，喜欢慵懒的躺在沙发上与喜欢成为沙场点兵的商业巨子之间，没有好坏没有优劣

*** 人的发展
五岁时，妈妈告诉我，人生的关键在于快乐。上学后，人们问我长大了要做什么，我写下“快乐”。
他们告诉我，我理解错了题目，我告诉他们，他们理解错了人生。——约翰·列侬

** 心灵鸡汤
*** 心小,任何小事都是障碍
*** 天下只有三种事：我的事，他的事，老天的事。抱怨自己的人，应该试着学习接纳自己；抱怨他人的人，应该试着把抱怨转成请求；抱怨老天的人，请试着用祈祷的方式来诉求你的愿望。
*** 一本书，一只手环，改变爱抱怨的你，成就不抱怨的世界。
*** 养成能力的四个阶段是：
　　1.无意识的无能：
　　2.有意识的无能；
　　3.有意识的有能；
　　4.无意识的有能 。
*** 永远不要找别人要安全感
*** 信心
信心不仅来源于自身的实力，也来源于自身的气质，更来源于自身的锻炼，展示自身信心的方法首先要从外在做起，当你在众人面前的时候，你要学会微笑，你地言谈举止特别重要，不是要你一副盛气凌人的样子，而是学会不卑。关键在于你地内心，你如果内心里面充满了自信，你就会自然而然的流露出来。积极地自我暗示也非常重要。你要告诉自己，你不要和别人比，你就和昨天的自己比，今天你是否比昨天更懂得微笑，更加信心满满，更加的开朗活泼，更加自信幽默。
每天都要进行自我暗示，努力告诉自己，你要比别人做的更好，让别人去佩服你，更不是去嫉妒你。
** 前进方向
 目标
独立思维
实践测试成长 交互的是自己
技术 操控的是机器
交流 交互的是人
家庭 父母
思考
思考 具体
思考 要什么 不要什么
工作: 服务行业; 服务工具; 工具完美 
网页完美
视觉/操控/功能
我这样思考之后的结果是：1.发现自己需要一个稳定的家庭，我还喜欢小孩子 2. 我很想证明自己 3. 我不喜欢做别人做滥了的事，我喜欢创新，我总有新点子 4. 我擅长并热衷揣测别人的心思，我观察非常仔细 5.我不喜欢单兵作战，我喜欢和兄弟们一起打拼。如果你仔细思考了，你应该和我一样，得到几条你想要的感觉。

之后，以你的感觉为目标，建立自己的坐标系，落实到自己的生活和工作中去。曾经我觉得只要自己努力，什么工作都能做好，但实际做的时候，总觉得不称心，不如意。但我建立自己的坐标之后，我就开始找一份可以集合以上345点的工作，它就是marketing，而我可以为他付出120%的精力。

如果明天我将死去！
（现在是晚上，好像有点可悲，没关系，惊天地泣鬼神的事情发生在暗夜是不错的选择）
你需要近一步确定自己的方向。先告诉我你现在感觉累吗？记住，不要在身体觉得累的时候进行人生的思考，觉得自己一事无成的时候就先滚上床睡觉去吧。睡一觉充电去，明天四点我在知乎等你。如果你现在正在感到自己将进行脱胎换骨的兴奋，再也没有比现在更好哦的了。那我们就继续
接下来要做的是，把浪费你时间的东西或人从生活中剔除。
比如qq上闲聊的人
比如天天找你吃喝的朋友（如果这是你的人生目标或快乐的事，那就……）
比如镜子
比如游戏
首先学会克制自己，很小的事情就可以。例如
今天不吃晚饭
今天不吃肉
想说的一句话忍住不说
想要夹得菜不去夹它
嘘嘘到一半憋住
装一个生鸡蛋一天不让它碎了
这都是小事，但慢慢锻炼过后，你会在大事上也会有良好的控制力。
然后学会坚持。
每天给心爱的人准时发一条短信
每天扎马步两分钟
每天喝八杯水
每天对三个陌生人微笑
每天写一句话
每天上知乎^ ^
接下来回顾以上
1.确定目标
2.制定计划
3.实施计划
这是件令人激动的事情，但最重要的是勇敢的去实施。有对梦想负责的勇气。你要告诉自己，不论结果成功失败，我都不在乎，我不是为了做这件事而去做。在实现的过程中，一边制定新计划，一边进行修改。这样你可以会保持兴奋，反复循环，乐此不彼。我不知道你的目标是什么，但是我奉劝你活着不能眼里只有目标。比如你要挣五百万，然后就像个骡子一样的早出晚归只是为了挣钱而挣钱。人不是野兽。要时而慢下来，接触大自然，看看自己走歪了没有。不要着急成功，完成目标。我相信，你的人生还很长，如果早早的得到万人赞赏，你会变得傲慢忘记了最单纯的目标，这种目标对于人生的意义没什么意义。如果你不去炫耀的过去，将会不迷失在自己的世界。
改变思想比学习技术更重要。
-------------尼采 
