* 物质世界
** 变化 (灵魂,变化不同决定了是什么物质)
*** 相对(规律,逻辑)
*** 绝对
** 联系  蝴蝶效应
** 时间 (未解之谜) 有没快慢一说
盛年不重来，一日难再晨，及时当勉励，岁月不待人。
*** 时间管理方法
**** GTD 
收集
删选
计划
执行
回顾
**** 四象限法
**** 番茄工作法
: 人们在潜意识的时间多一些，有时不知道目的在哪里
** 意识 表面与深入
对「快速」的期望是「放松」的天敌。
心里一发慌，当然更睡不着。越追求，越得不到，这根本就是一个恶性循环。
创造(输出)
吸收(输入) 

* Need do
1.系统化的学习
2.抓住垃圾时间
3.调整心态(宽容)
4.本质而不是表象
5.认真看书
6.多思考
7.把空闲的时间用在编程上,当看不下文档的时候
* Not do
1.东瞧西看
2.浪费时间
3.心态不正
4.少看论坛多看源码
5.别看太快
6.别囫囵吞枣
7.编程了,就没有时间瞎抱怨了,或者改写文档
* math
** 自然数
** 复数
** 集合
** 算术
** 数论
*** 素数
*** 同余
** 代数
*** 微积分
** 几何(空间)
*** 拓扑
* 提神
首先保证晚上的睡眠，具体多长时间因人而异。
然后重点来了：吃完午饭火速找个安静的地方完全放松地打个盹，10~20分钟，哪怕半小时后天塌了也要完全放松。醒过来就又是一条好汉了。 
* 学不下去时，我用类比法自救
* 哈佛幸福课
** 积极的环境能改变人
** 过犹不及
** 幸福与幽默
** 收获交流
** 完美主义
** 自尊与自我实现
** 爱情与自尊
** 享受过程
** 写日记
** 睡眠
** 感激
** 环境的力量
** 逆境还是机遇
** 乐观主义
** 积极情绪
** 运动与冥想
** 如何去改变
** 养成良好习惯
** 面对压力
* 经济学
	人/物/时间
	趋势是发展,并且是客观的(需求发展)
	收入与付出(对生活有很大的影响)
	需求判断与真实需求 (经济问题)
	欲望
	竞争
	口红效应->没大钱只能买小钱
	纳什均衡
* 学习方法
学习学不进去的时候怎么办?
不管学霸还是学渣都有学不进去习的时候这时候你们都是怎么逼自己的还是干脆就不学了

1392 人赞同
我来给个方法论回答
我试过无数方法，解决学不下去的问题。
先整理几个失败的方法：
1，学不下去就不学：喝茶，喝咖啡，静坐，冥想，听音乐，网上看各种励志鸡汤，制定学习计划。通通无效。冥想半天睡着了，喝着咖啡就开始吃零食
了；听听音乐就顺便看了个电影，看着励志鸡汤就顺路看上了知乎。。。结果是一天一天又一天，继续荒废。

2，能占用的时间都占用，剩下的学习。就是所谓的逆序时间管理。把玩的时间都安排好，剩下可怜的几个小时学习。可玩的事情太多啊！玩着玩着心就
野了，更没法低头学习。

3，什么都不干：关手机，断网线，坐在桌前先呆5分钟。结果要不是百无聊赖不知不觉又玩上了，要不就是睡着了，或者一个人静默的胡思乱想。

4，先干点安静的事情：书法，画画，写日记。看窗外。我只能说，呵呵。人在拖延的时候，所有无聊的事情都拥有巨大的吸引力。我曾经静心练书法，
然后练着练着，觉得笔不好，然后就上网shopping 买笔去了。。。看看窗外，看到一只猫，就出去抓猫去了。还顺路拎回家只小猫，于是接下来的N天都
忙着养猫了。

我是长期抗争，屡败屡战。把吃不到奶的劲都使出来了，浑身上下能用的不能用的全都动员了一圈，才培养了一个脆弱的支持体系，维护我少得可怜的意
志力。

我有一个思想轨道论。人每一次的思想支配行为，都是在强化一条轨道。时间长了，要脱离轨道很难。天天在外头跑来跑去，就觉得家里呆不住。天天宅
在家里，就懒得去外面。早起的人恒早起，都是这个原理。人的精神状态，学习状态，懒惰程度，全有自己的轨道。玩三消/扫雷/纸牌类简单游戏的时候
，明明没啥瘾，甚至觉得有点无聊，可还是一局一局的玩下去，在那种时刻可以明显感受到”心流“ 在固定的轨道上涌动。”学不下去“的时候，就要给自
己打破现有的懒散轨道，铺一条”学习“轨道。

怎么”打破“现有轨道呢？分为环境和身体。环境包括：改变居住环境；改变学习环境；参加学习小组/课程；找学习伙伴，等等。身体包括：开始早起，
开始运动，规律作息和三餐。尤其我想强调一下运动对激发精神活力的作用。跑吧，小伙伴们。效果立竿见影。我自己有强烈的感觉，当成天宅在家里的
时候，身体的状态是懒散的，内敛的，肢体不会大舒大展，精神也是懒散的，专注细节的。跑起来之后，肢体舒展，环境改变，精神也被激活。瑜伽，跳
操，仰卧起坐之类固定在某地的运动都不行。

现有懒散的轨道打破之后，就要给自己铺设一条学习的轨道。这个过程挺难的。如果思想是河流，它已经在我们惰性的河床上流了太久。现在我们把它带
到学习的平原上，刚开始只能徒劳的浅浅划下痕迹，很容易散漫，很容易惯性的又回到原来。这时候就要用意志力给自己设限，约束河流往学习的方向走
。我用的是纸笔。字很烂，就是给大家一个参考：

高亮区是我对时间的记录。几点几分，接下来的时间我打算干什么。几点几分结束。用了多少时间。这可以约束自己的思想，也可以激发思维的主动性：
接下来5分钟我要做某某事。我用这个方法一直监督自己的思想，防止出轨。

还有一种学不下去的情况，就是思路卡住了，接下来遇到困难。通常的建议是暂停，干点别的事，再回来。可惜我要是干上别的事就回不来了。所以没办
法，只能死磕：

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

我就是坐在那里，各种吐槽，各种画小人诅咒，各种抱怨。做大量的无用功。但是都用纸笔记下来--要是光用脑子想，很快就控制不住想玩了。我就是写
写写，全是和学习有关的事情，然后在某一个点，突然灵光毕现，豁然开朗。

所以总结一下，学不下去的时候怎么办？早起，好好吃饭。收拾屋子，重新摆放家具位置，拿书到图书馆去。图书馆学不下去的，换个位置。换到咖啡店
去。换到教室去。下午出去跑圈。找个秒表，整个本，一分一秒的趴桌子上死磕。那种大学图书馆常见到的，拿张小桌布，抱个小水壶，听着音乐再啃个
水果，真的不是学习啊同学。

453 赞同反对
【看完不点赞小朋友真是太不可爱了】
补充几点：
1:我所说的“学不下去就逼着自己学”并不是说要死磕到底，而是在休息之后觉得状态恢复了一些时继续投入学习。
举个栗子，晚上八点钟的时候，你写数学题时脑袋发胀，不会写，写不下去了。这时候出去休息你有了两个选择：1，玩二十分钟之后，觉得放松了继续
回去写。2，玩个三四个小时继续回去写。
我的话我选选择一，玩个三四个小时之后十一二点钟了吧，这个时候就应该犯困了，多数人应该更写不下去了。还有整个学习计划就被彻底打乱了。
2:该困告的时候就应该果断立刻马上的去困告告，身体上革命的本钱，熬夜伤身啊少年。
=================以上2月1日早9:30更新=============
(*◑∇◑)☞【重要的事说三遍！】鸡汤喝多了会中毒！鸡汤喝多了会中毒！鸡汤喝多了会中毒！☜(◐∇◐*)
曾经有一段时间疯狂的迷恋各种正能量文字，看完之后真的挺振奋的，那种酸爽简直无法和深夜写作业比！但是那些喷鸡汤的真的想对他们说，暂时的振
奋就暂时的振奋，能让我埋头学习就是好鸡汤，好东西。那段时间，恩，怎么说，我成绩掉的比较严重的时候，让我重新回到前几名的、让我熬过那段时
间一直逼着我学习的就是那一些鸡汤。
然后现在。。。我看那些鸡汤再也没有感觉了，那段正能量文字满天飞的日子也过去了，我现在基本能知道的都是我以前看过的，还有什么刘同卢思浩那
些我从最开始看就觉得没什么感觉，刘同可以当做故事看或者人生感悟看，至于卢思浩。。你们愿意看你们开心就好。
所以！这次告诉你们两个东西！
1:鸡汤喝多了会中毒！给你那些正能量的东西总有一天会用完，接下来的路就要靠自己坚持下去！
2:在低谷的时候正能量文字是真的可以陪你挺过去！但是它是不能用多久而且可以第二次没用。☜(=σωσ=☜)

重要的事说三遍！点赞（上面说过一遍）点赞！
曾经在知乎里看到一句话：如果你不想学、学不进去了那就不学了，那你什么时候学？看到问题里有一个话题：熬夜。( ･ิϖ･ิ)っ这里想说起一些关于自己
的经历和感受。我家在城乡结合部，一个略老旧的社区里，社区里年轻人大多已经搬走，剩下的大部分是退休的老人和在孙女孙子的大妈（这段是废话，
可不看），自然而然广场舞的骚扰肯定少不了。←_←也不知道你们对于那种一整个晚上都在循环听大喇叭放：终于你做了别人的小三～的感觉是什么样子
。
后来我为了逃避这种精神污染，开始插耳机，可是呢，我发现一个问题——终于你做了别人的小三这十个字还是无法被音乐掩盖。【黑喂狗跟我唱终于你做
了别人的小三～】
放暑假了，我妈就开始放养我了。在最后几天刷作业的时候，我发现白天我根本无法放下手机安心写作业，无奈只好认命半夜刷作业。好家伙，半夜刷作
业跟打了鸡血似的，又精神又没有口水歌。（上课期间，不推荐半夜刷作业，因为这样貌似越刷越困。）从此之后半夜刷作业的日子一发不可收拾。
(๑òωó๑) 可是你知道后果是什么吗？恩？这个人脸色不好，脾气暴躁，这特么还胖了，胖了就算了，痘痘爆发，白天看什么都看不进。
好了，上面一段其实可以都不看，看这一句就好：上学期间千万不要熬夜写作业，早起补作业都好一点。熬夜之后你第二天晚上写作业更没精神更学不进
去，很烦躁脑子一片混沌啊有木有？？？！如果习惯熬夜的话，那就星期五晚点睡，不要写作业了，该玩就玩，第二天睡个懒觉，下午乖乖写作业。
2，学不进去的时候要逼着自己学。
如果不是精力的原因，那你要训练一下自己的毅力了？是不是觉得一到写作业的时候就发现指甲要剪了？这本小说居然挺好看的？好像我微博上有人评论
？我去看看热门微博？
乖乖，那我问你，那你准备什么时候学？玩够了再学？按照你这样说，当你打开热门微博的时候就会一条条看，再看看评论，好不容易翻完了你有手贱去
刷新关注去了，然后顺着顺着你就玩到了半夜。哦，半夜了啊，要写作业了啊？然后你就熬夜，熬夜写作业之后第二天继续学不进去，学不进去了我就玩
玩吧，之后你又点开了热门微博。。。。
很负责任的说，玩不够的。
再送你一句话：当你决定出发的时候，最困难的地方就已经度过了，所以，何不执行下去？
泡完脚，闭眼！困高！
如果明天题主看到了这个答案，拜托提醒我一下我明天起床洗头发，谢谢。

410 赞同反对
[da8e974dc_] 知乎用户我是机器鼓励师
“操，不可能不行啊，再看一遍！”
“既然这个世界上有别人能搞得定，我也一定可以搞定的，再来！”
“尼玛！终于明白了！操！我果然是天才”

最近在备考，一共六本厚厚的专业书可真是挑战。开始的时候是真的看不进去，毕竟放假了看专业书籍对我来说太残忍了，很烦躁，效率很低。在微博上
看到了清华陈吉宁校长的毕业典礼讲话，里面举了《Outliers》中的例子：无论是小提琴还是钢琴专业的学生，他们… 显示全部
最近在备考，一共六本厚厚的专业书可真是挑战。开始的时候是真的看不进去，毕竟放假了看专业书籍对我来说太残忍了，很烦躁，效率很低。
在微博上看到了清华陈吉宁校长的毕业典礼讲话，里面举了《Outliers》中的例子：无论是小提琴还是钢琴专业的学生，他们从5岁左右开始学琴，到20
岁时，那些具有成为世界级独奏家潜质的学生都至少练习了10000小时，那些被认为比较优秀的学生都至少练习了8000小时，而那些被认为将来只能成为
一名音乐辅导老师的学生只练习了4000小时。这就是所谓的“10000小时法则”。
之前也听过什么一件事只要做满多少多少小时，你就可以精通这件事，这次临近考试，我就打算实践一下，给自己的学习时间计个时。我使用手机秒表计
的时，当我按“开始”的一刹那，就感觉战斗开始了！过一会会看一下手机，啊呀，看了45分钟了，再过一小会就一个小时了！哈哈真开心。~然后不知不
觉地多看了30分钟，休息的时候停止计时，等调整好再计时开始，以此类推。看到秒表上的数字不断累积，秒位数字飞快地闪着，然后从秒到分最后累积
到小时，感觉是对自己刚才的精力集中做了一个很直观的量化，虽然离前面提到的4000小时还有很长的距离，但是方向却很明朗，而且也有一个结果在那
里放着，就算最后不是最好，但也绝对不会是最差。如果累计到了会不会真的发生奇迹呢，打心眼里期待这次实验的结果啊。
一天下来，我累计学习了6：56：47，这七个小时度过地都很高效，这种事在假期发生，这对我来说简直是奇迹啊。。。。太惭愧了。更让人开心的是，
明天我会继续在这个时间上累计计时，正在向着4000撒欢狂奔~

我觉得很多时候不能专心做事的原因，是因为较短的时间内很看到这件事给自己带来的有形的收益，随之而来的浮躁情绪，伴着懒惰的天性，便总会感觉
自己徘徊在原地。就算你进步了，你在学习过程中的不专心也会让你产生一种愧疚，会让你怀疑自己，否定自己的进步。数字上的量化会很直观地告诉你
，你前进了多少，离4000小时还有多远。

喜欢做各种方面的实验，就是因为好奇看到的说法到底是真的假的~哈哈哈！

时间久了，有了完整做一件事情的习惯再回头看这个答案，还是觉得这样的开始挺可爱的~


 青禾学医的小白，即将去医院实习~


我在二戰考研的時候，一邊工作，一邊學習。經常有學不下去的時候，忙了一天擠著公交吃完飯后居然還得刻苦學習，總覺得特別心酸。我總問自己，憑
什麼妳就得折騰，就不能在一個地方安心工作，別人都過得挺好，妳為什麼要拼命過得不好。
因為不甘心啊。因為沒有經歷過，不曾看到過，未能努力過，那些痛苦總會在我荒廢了一天后深夜折磨我，夜不能寐。
所以我得學習，哪怕多看了一張紙，多記住一句話，也比昨天的我要多前進一步。我並沒有卓越的天賦可以過目不忘，也沒有優越的家境供我衣食無憂，
我只能靠自己。努力，是最簡單也是最難的事。對於未來，我能做的也只有拼盡全力而已。
每當我學不進去的時候，我都會這樣想想，然後繼續翻書。
希望二戰順利。


没有不学这个选项，ABCD都是学。


如果是感觉浮躁，心神不定，告诉自己再坚持5分钟，如果5分钟后还不进入状态，建议休息一会。如果是觉得大脑迟钝，集中不了注意力，这时候需要换
换脑子，站起来动一动，吃点东西，喝点水，再学。这时候可以换一样科目。有时候觉得东西多，压力大，怎么学也… 显示全部
如果是感觉浮躁，心神不定，告诉自己再坚持5分钟，如果5分钟后还不进入状态，建议休息一会。
如果是觉得大脑迟钝，集中不了注意力，这时候需要换换脑子，站起来动一动，吃点东西，喝点水，再学。这时候可以换一样科目。
有时候觉得东西多，压力大，怎么学也学不完干脆不学时。制定计划，定下最重要的几个目标，目标越少越好，帮助自己朝一个方向努力。
随时想到要做的事（和学习无关），找张纸或本子随后记下来，一会儿再办。
把手机关机，放到别的房间。想想自己是为了什么在学习，努力必然是痛苦的，但现在的短期的痛苦是为了避免以后更大的痛苦。
骚年，加油，我也常常要克服这种情况= =。。


 征途是星辰与大海大学开始运动。越运动越努力

逼自己学，逼着逼着就适应了。
逼自己跑，跑着跑着就能跑了。
逼自己变，变着变着就成功了。


排名第一的回答提到，关键是心思要在学习上。那么如何集中心思到学习上？关键是引起学习的兴趣。这方面我的一个方法，就是提问题。把学习内容变
成一个个问题提出来，然后学习的过程，就是去钻研解决这些问题的方法。这样做的好处是因为，问题容易引起大脑… 显示全部
排名第一的回答提到，关键是心思要在学习上。那么如何集中心思到学习上？
关键是引起学习的兴趣。
这方面我的一个方法，就是提问题。把学习内容变成一个个问题提出来，然后学习的过程，就是去钻研解决这些问题的方法。这样做的好处是因为，问题
容易引起大脑的兴趣，大脑的一个特点是想把未完成的问题解决掉，没有解决的时候就会一直去想，甚至吃饭想，睡觉想，这个时候其他的诱惑都弱爆了
，就是钻研这个问题才是最有意思的事。
这个方法尤其适合对于感兴趣的内容钻研性的学习，而且往往能体会到钻研的乐趣和进步的感觉。
