* svn
** svn 重新验证证书 ->会在用户名和密码错误的情况下重新验证 
   Error:  “Server certificate verification failed: issuer is not trusted”
   
   使用终端执行如下命令：svn list https://your.repository.url 接下来选择对应的
   （临时）/（永久）即可。
** 功能
   查看修改的文件记录
   svn cat -- 显示特定版本的某文件内容。
   svn list -- 显示一个目录或某一版本存在的文件列表。
   svn log -- 显示 svn 的版本 log，含作者、日期、路径等。
   svn diff -- 显示特定修改的行级详细信息。

   list 示例：

   svn list http://svn.test.com/svn     #查看目录中的文件。
   svn list -v http://svn.test.com/svn  #查看详细的目录的信息(修订人,版本号,文件大小等)。
   svn list [-v]                        #查看当前当前工作拷贝的版本库 URL。
   cat 示例：

   svn cat -r 4 test.c     #查看版本 4 中的文件 test.c 的内容,不进行比较。
   diff 示例：

   svn diff               #什么都不加，会坚持本地代码和缓存在本地.svn 目录下的信息的不同;信息太多，没啥用处。
   svn diff -r 3          #比较你的本地代码和版本号为 3 的所有文件的不同。
   svn diff -r 3 text.c   #比较你的本地代码和版本号为 3 的 text.c 文件的不同。
   svn diff -r 5:6        #比较版本 5 和版本 6 之间所有文件的不同。
   svn diff -r 5:6 text.c #比较版本 5 和版本 6 之间的 text.c 文件的变化。
   svn diff -c 6 test.c    #比较版本 5 和版本 6 之间的 text.c 文件的变化。
   log 示例：

   svn log         #什么都不加会显示所有版本 commit 的日志信息:版本、作者、日期、comment。
   svn log -r 4:20 #只看版本 4 到版本 20 的日志信息，顺序显示。
   svn log -r 20:5 #显示版本 20 到 4 之间的日志信息，逆序显示。
   svn log test.c  #查看文件 test.c 的日志修改信息。
   svn log -r 8 -v #显示版本 8 的详细修改日志，包括修改的所有文件列表信息。
   svn log -r 8 -v -q   #显示版本 8 的详细提交日志，不包括 comment。
   svn log -v -r 88:866 #显示从版本 88 到版本 866 之间，当前代码目录下所有变更的详细信息 。
   svn log -v dir  #查看目录的日志修改信息,需要加 v。
   svn log http://foo.com/svn/trunk/code/  #显示代码目录的日志信息。
   常用命令

   svn add file|dir -- 添加文件或整个目录
   svn checkout -- 获取 svn 代码
   svn commit  -- 提交本地修改代码
   svn status    -- 查看本地修改代码情况：修改的或本地独有的文件详细信息
   svn merge   -- 合并 svn 和本地代码
   svn revert   -- 撤销本地修改代码
   svn resolve -- 合并冲突代码

   svn help [command] -- 查看 svn 帮助，或特定命令帮助
   svn diff 个性化定制
   svn 配置文件: ~/.subversion/config

   修改~/.subversion/config，找到如下配置行：

   # diff-cmd = diff_program (diff, gdiff, etc.)
   将上面那个脚本的路径添加进去就行，修改为

   diff-cmd = /usr/local/bin/diffwrap.sh  #绝对路径
   这样 svn diff 命令就会默认使用 vimdiff 比较文件。

   diffwrap.sh 文件
   #! /bin/bash

   # for svn diff: 修改~/.subversion/config，找到如下配置行：
   # diff-cmd = diff_program (diff, gdiff, etc.)
   # diff-cmd = ~/bin/diffwrap.sh

   # 参数大于 5 时，去掉前 5 个参数；参数小于 5，失败，什么也不做
   shift 5

   # 使用 vimdiff 比较
   vimdiff "$@"
