#+TITLE: 计算机网络简介
#+DESCRIPTION: 计算机网络简介
#+TAGS[]: network
#+CATEGORIES[]: 技术
#+DATE: 2020-02-13T13:08:49+08:00

一个人，你再强，你最多也只能掌握两个人的知识，干两个人的活，比方啊。但是你有些事情不会做，或者人手不够怎么办，那就多找几个人不就完了吗。

计算机也是一样，你把计算机连成一个团体，那么所有在团体中的计算机就都能受益了，可以互相帮助。

# more
  
** 网络结构
   计算机连接一般是用电线(现在是光纤)  ，连接到一个中间节点，中间节点连到另一个中间节点，然后连接到另外一台计算机，这种结构叫做星型结构。
   #+begin_quote
   不是在你的电脑上插上所有要联系的人的线，而是连上一个中心点。
  #+begin_export type
  #+end_export 
   这样的结构，造成了你的信息要经过人家传递，所以加密挺重要的，但不能完全避免
   #+end_quote
  
*** 网络编号
    在网络中的计算机怎么扮演自己的角色，就像在人群中，你怎么扮演自己的角色。计算机在
    这里不如人，没有脚，不能到处跑。但它们可以用它们专有的交流方式（电线或无线电）来
    沟通，我们用话通过空气传播来沟通。为了指明给谁沟通，自己需要一个代号(IP 编号)，就
    像人需要一个名字一样（不能重名）。
 
    #+begin_quote
    现在是 *IPV6* 了，但还没普及，普及的化连海里的沙子都有名字了。
    #+end_quote
    
*** 大小网络
    根据交流范围，网络分为小网络（局域网，内网）和大网络（广域网，公网，Internet）
**** 内网 IP (保留地址) 
     - 10.x.x.x
     - 172.16.x.x 至 172.31.x.x
     - 192.168.x.x

**** 公网 IP 
     除内网 IP 及本地地址
     
** 网络协议  
   网络结构有了，但你不能随便把电(信号电)传给人家吧，人家又不知到你传的电是什么意思，所以要有一个电的标准，这样就制造了一个标准（协议） 

*** 国际标准 ( OSI 协议 )
    这个标准是一个模型，没有用在网络上，用在了理论上。
    
    - 应用层（Application Layer）应用软件直接能看得懂的信息
    - 表达层（Presentation Layer）适合传输的信息
    - 会话层（Session Layer） 把信息加了是否在会话的内容
    - 传输层（Transport Layer）把信息加了传输协议
    - 网络层（Network Layer）信息传给谁，加了双方 IP 内容 (网络名字)
    - 数据链路层（Data Link Layer） 不知道 (MAC 名字)
    - 物理层  决定信息的传递方式，是坐飞机还是汽车

*** 实际标准( TCP/IP )
    - 应用层 
    - 传输层
    - 网络层 
    - 数据链路层
    - 物理层 
** 网络性能
   速率，带宽，时延啊什么的
** 路由
   那些中间节点有好几条线可以传出信息，决定从那条线传输，就这是它们的路由功能，就叫它们路由节点。
   
   路由节点（路由器）按照设定的通讯地址（路由表）决定走哪条路。

   #+begin_quote
   路由器带的系统会进行一系列 *网络性能* 测试来生成可靠的路由表(网络是动态的，路由也是动态的)。
   #+end_quote
