#+TITLE: 编程语言简介
#+DESCRIPTION: 编程语言简介
#+TAGS[]: 编程语言
#+CATEGORIES[]: 技术
#+DATE: 2019-12-07T19:41:03+08:00

前文我们讲过，世界是由 *东西* 组成的，东西分为两种，一种是会动的东西，另一种是静止的东西。
会动的东西影响不动的东西，或会动的东西相互影响，构成了我们运动的世界。

  # more 

#+begin_quote
这里你可以转下头，看下窗外或身边的东西，想想是不是有的东西能动的，有的东西不在动。追溯到物理学，什么东西都在动，这里不深究这个。
#+end_quote
我们人类呢，是群居动物，彼此之间需要沟通，然后就创造了一种符号，来指代外部的东西，这种符号叫做语言文字。

语言文字的外形结构分好几种，有跟东西的外形差不多的象形文字，还有是基本字母组合而成的楔形文字(楔形文字是由象形文字改造而来)。

  #+begin_quote
  动物也有语言，就是我们不懂，可能词汇量比我们人类少吧
  
  编程语言呢，就是一种结构好看(清晰)的的语言文字，用来给人或者编译器沟通的符号(告诉机器做什么)。
  
  人人人，重要的是给人看，自己先要看懂，人看不懂，机器更笨了吧，会报错的。
  #+end_quote

** 例子

  |--------------------------------+------------------------|
  | 自然语言                       | 编程语言               |
  |--------------------------------+------------------------|
  | 今有一只 10 斤的小猪           | smallpig = 10          |
  | 好久没开荤了，我想吃一斤的猪肉 | smallpig = smallpig -1 |
  | 小猪哭晕在厕所                 | 什么都不做 ( do nothing )  |

- 编程语言分低级语言和高级语言。   
- 低级语言比较 *啰嗦* ,要面对不同的 *零部件* ，语法结构也较 *简陋* ,不好理解，而且不同类型机器的语言不一样，不能沟通。
- 高级语言的语法结构就像 *人类语言* 的 *主谓宾* 结构一样，较好理解，抹平了一些 *零部件* 的差异。
  
** 静物
*** 预定义
    一般编程语言都会提供给你一些简单的东西给你使用，比如数字，字符串。
    数字可以用来做简单数学运算。
    字符串一般用来给屏幕作显示文字用的。
*** 自定义
    预定义的东西提供的对象较为简单，但我们可以用这些简单的对象拼接成较为复杂的对
    象，在编程语言中一般叫定义类，或定义结构。
** 动物
   编程语言除了提供一些数学函数，和显示函数，还提供很多的库函数。
*** 自定义
    定义动物，编程语言有自己的语法格式。
*** 轮子
    东西越多，就越不需要造轮子，但你要安装人家造好的轮子来。
** 条件判断
   动物都不傻，不会反复做不能实现的事情，所以作为符号表达，也要表示这种状态哦。😏 
** 循环结构
   反复做多次的东西，用一个语法表达不香吗，哈哈。
   
